backend/package-lock.json, backend/package.json, backend/src/ee/services/audit-log/audit-log-types.ts, backend/src/server/routes/index.ts, backend/src/server/routes/v1/integration-router.ts, backend/src/services/integration-auth/integration-delete-secret.ts, backend/src/services/integration/integration-service.ts, backend/src/services/integration/integration-types.ts, frontend/src/components/v2/DeleteActionModal/DeleteActionModal.tsx, frontend/src/hooks/api/integrations/queries.tsx, frontend/src/views/IntegrationsPage/IntegrationsPage.tsx, frontend/src/views/IntegrationsPage/components/IntegrationsSection/IntegrationsSection.tsx
- This PR will allow users to optionally delete secrets in the destination (for now, only Github) upon deletion of integration 
```sh
```
---
=> feat: added secrets deletion feature on integration removal

backend/src/@types/fastify.d.ts, backend/src/db/migrations/20240806113425_remove-creation-limit-rate-limit.ts, backend/src/db/schemas/rate-limit.ts, backend/src/ee/routes/v1/rate-limit-router.ts, backend/src/ee/services/license/licence-fns.ts, backend/src/ee/services/license/license-types.ts, backend/src/ee/services/rate-limit/rate-limit-service.ts, backend/src/ee/services/rate-limit/rate-limit-types.ts, backend/src/server/config/rateLimiter.ts, backend/src/server/plugins/inject-rate-limits.ts, backend/src/server/routes/index.ts, backend/src/server/routes/v1/identity-router.ts, backend/src/server/routes/v2/organization-router.ts, backend/src/server/routes/v2/project-router.ts, frontend/src/hooks/api/rateLimit/types.ts, frontend/src/views/admin/DashboardPage/RateLimitPanel.tsx
This PR will enable users in shared cloud to have different rate limits based on their organization's license plan
License Server PR:
https://github.com/Infisical/license-server/pull/21
```sh
```
---
=> misc: moved to license-plan-based rate limits

backend/src/ee/services/secret-replication/secret-replication-service.ts
This PR resolves secrets not getting deleted on new kms architecture secret replication
```sh
```
---
=> fix: resolved replication secret not getting deleted

docs/integrations/platforms/kubernetes.mdx
Kubernetes Operators Integration Document Fix #2262
- [ ✅] Documentation
=> kubernetes operators integration doc fix

backend/scripts/create-backend-file.ts
added logging and a while loop to ask prompt again for backend/scripts/create-backend-file.ts .
=> better logging and while loop for ask propmt again

backend/src/services/integration-auth/integration-sync-secret.ts
@maidul98 knows this
```sh
```
---
=> feat: switched to ssm update as overwrite with tag as seperate operation

backend/src/ee/services/secret-approval-request/secret-approval-request-secret-dal.ts
=> fix: resolved secret approval broken due to tag name removal

backend/src/services/integration-auth/integration-sync-secret.ts
=> feat: added more endpoints for delete

frontend/src/pages/integrations/aws-parameter-store/create.tsx
This PR resolves. the toggling to a controlled state change for switch in parameter store integration
```sh
```
---
=> feat(ui): resolved a race condition in ui

backend/src/services/integration-auth/integration-sync-secret.ts, backend/src/services/secret-v2-bridge/secret-v2-bridge-service.ts, backend/src/services/secret/secret-queue.ts
This PR adds log point on aws ssm tag creation failing. And delete kms secret based will check before hand
```sh
```
---
=> feat: added log point for aws tag and check for delete secret in bridge

backend/src/ee/routes/v1/dynamic-secret-lease-router.ts, docs/api-reference/endpoints/dynamic-secrets/create-lease.mdx, docs/api-reference/endpoints/dynamic-secrets/create.mdx, docs/api-reference/endpoints/dynamic-secrets/delete-lease.mdx, docs/api-reference/endpoints/dynamic-secrets/delete.mdx, docs/api-reference/endpoints/dynamic-secrets/get-lease.mdx, docs/api-reference/endpoints/dynamic-secrets/get.mdx, docs/api-reference/endpoints/dynamic-secrets/list-leases.mdx, docs/api-reference/endpoints/dynamic-secrets/list.mdx, docs/api-reference/endpoints/dynamic-secrets/renew-lease.mdx, docs/api-reference/endpoints/dynamic-secrets/update.mdx, docs/mint.json
- This PR adds dynamic secrets and dynamic secret leases to the API references documentation
```sh
```
---
=> doc: add dynamic secrets to api references

docs/documentation/guides/local-development.mdx
The word "secret" was missing from a sentence.
=> fix: added missing word

backend/src/ee/services/secret-approval-policy/secret-approval-policy-service.ts, backend/src/ee/services/secret-approval-request/secret-approval-request-service.ts, backend/src/server/routes/index.ts
Ensure the api level of secret approval policy and request management does license check
```sh
```
---
=> feat: license check in secret approval api level

frontend/src/layouts/AppLayout/AppLayout.tsx, frontend/src/pages/org/[id]/overview/index.tsx
This PR resolves failing add members to project operation when there are pending users in an org.
Closes #2288 
```sh
```
---
=> fix: resolved add all members to project failing when there is pending users in organization

company/handbook/talking-to-customers.mdx, company/mint.json
=> added talking-to-customers.mdx to handbook

docs/sdks/languages/csharp.mdx, docs/sdks/languages/java.mdx, docs/sdks/languages/node.mdx, docs/sdks/languages/python.mdx
Added include imports & expand secret references documentation to SDK's.
```sh
```
---
=> Fix: Include imports SDK docs

frontend/src/context/ProjectPermissionContext/types.ts, frontend/src/views/Project/RolePage/components/RolePermissionsSection/RolePermissionSecretsRow.tsx, frontend/src/views/SecretOverviewPage/SecretOverviewPage.tsx, frontend/src/views/SecretOverviewPage/components/CreateSecretForm/CreateSecretForm.tsx
PR to address some minor ui issues caused when custom roles are applied and secret permission are removed from some environments and paths etc.
```sh
```
---
=> feat: resolved ui issues related to permission based hiding

backend/package-lock.json, backend/src/keystore/keystore.ts, backend/src/lib/dates/index.ts, backend/src/queue/queue-service.ts, backend/src/server/routes/index.ts, backend/src/services/access-token-queue/access-token-queue.ts, backend/src/services/identity-access-token/identity-access-token-service.ts, backend/src/services/service-token/service-token-service.ts
This PR improves infisical performance by reduction in SQL write for identity and service token lastUsed at. It achieves this debounce technique by using redis and our queue. 
Its first written to redis and then a queue job is pushed. Given its a same job id, duplicate queue pushed won't be considered. There will only be first one pushed and its delayed. After the delay its written towards postgres.
```sh
```
---
=> feat: added identity and service token postgres update debounced

frontend/src/views/Project/MembersPage/components/ServiceTokenTab/ServiceTokenTab.tsx
Until we simplify the experence of machine identity, we will keep service tokens.
=> Remove service token depreciation notice

backend/src/ee/services/dynamic-secret/dynamic-secret-service.ts, backend/src/ee/services/license/licence-fns.ts, backend/src/server/routes/v1/integration-auth-router.ts, backend/src/services/integration-auth/integration-app-list.ts, backend/src/services/integration-auth/integration-auth-service.ts, backend/src/services/integration-auth/integration-auth-types.ts, backend/src/services/integration-auth/integration-list.ts, backend/src/services/integration-auth/integration-sync-secret.ts, frontend/public/data/frequentConstants.ts, frontend/src/hooks/api/integrationAuth/queries.tsx, frontend/src/pages/integrations/azure-devops/authorize.tsx, frontend/src/pages/integrations/azure-devops/create.tsx, frontend/src/views/IntegrationsPage/IntegrationPage.utils.tsx
This PR introduces a new Azure DevOps integration. This work is heavily based on @meetcshah19's work.
A few key changes:
1. Changed referencing from "Azure DevOps org ID" to "org name". There's a difference between organization ID's and organization names in Azure. We are actually using the Azure org name, not the org ID as it is referred to in Meet's PR.
2. Added unique parameter for azure devops org name (previously the teamId parameter was being reused)
3. Minor rephrasing in the create integration step.
4. Smaller overall improvements. 
---
=> Feat: Azure DevOps Integration

backend/src/ee/services/secret-approval-policy/secret-approval-policy-dal.ts, backend/src/ee/services/secret-approval-request/secret-approval-request-fns.ts, backend/src/ee/services/secret-approval-request/secret-approval-request-service.ts, backend/src/server/routes/index.ts, backend/src/services/project/project-dal.ts, backend/src/services/smtp/smtp-service.ts, backend/src/services/smtp/templates/secretApprovalRequestNeedsReview.handlebars, frontend/src/hooks/api/secretApproval/mutation.tsx, frontend/src/views/SecretApprovalPage/components/ApprovalPolicyList/components/AccessPolicyModal.tsx, frontend/src/views/SecretApprovalPage/components/SecretApprovalRequest/SecretApprovalRequest.tsx
This PR aims to add support for email notifications for secret change requests. Whenever a new secret change request is created, the reviewers will be notified via. email that their attention is needed.
The email will include a direct link to the change request.
Additionally: This PR also resolves an issue with creation secret change policies.
---
=> Feat: Email notification on secret change requests

backend/src/ee/routes/v1/scim-router.ts, backend/src/ee/services/scim/scim-fns.ts, backend/src/ee/services/scim/scim-service.ts, backend/src/ee/services/scim/scim-types.ts
Updated request validation for scim update group endpoint.
```sh
```
---
=> fix: resolved scim group update failing

backend/src/server/routes/est/certificate-est-router.ts
- This PR ensures that unclosed EST-related connections will be cleaned up 
```sh
```
---
=> misc: added timeout for est connection

backend/src/server/routes/index.ts
In the past the health check did not account for DB and redis being ready. This would result in a brief hiccup between deployments. This should resolve it
=> Update health check

frontend/src/views/Org/MembersPage/components/OrgIdentityTab/components/IdentitySection/IdentityKubernetesAuthForm.tsx
This will reduce confusion for users when configuring k8s auth.
=> Add tool tip for k8s auth

backend/package-lock.json, backend/package.json, backend/src/ee/routes/v1/scim-router.ts, backend/src/ee/services/scim/scim-fns.ts, backend/src/ee/services/scim/scim-service.ts, backend/src/ee/services/scim/scim-types.ts, backend/src/lib/knex/scim.ts, backend/src/server/app.ts, backend/src/services/org/org-dal.ts
This PR address our failing scim operations due to missing various corner cases in scim operation. This adds all the proper scim conventions as needed
```sh
```
---
=> Resolved scim failing due to missing rfc cases

frontend/src/pages/login/index.tsx, frontend/src/views/Login/components/InitialStep/InitialStep.tsx
Fixed the issue where the logo on the login page appeared misaligned, sitting too close to the top of the container. This bug affected the overall visual presentation of the page, making the layout look uneven.
FIXES : #2361
```sh
```
https://github.com/user-attachments/assets/78f0dd18-e1dc-4c39-af31-1c1cda94295c
---
=> FIX : padding-and-alignment-login-page

frontend/src/pages/login/index.tsx, frontend/src/views/Login/components/InitialStep/InitialStep.tsx
Reverts Infisical/infisical#2362
=> Revert "FIX : padding-and-alignment-login-page"

docs/documentation/platform/dynamic-secrets/elastic-search.mdx
=> Elasticsearch is one word

backend/src/services/integration-auth/integration-app-list.ts, backend/src/services/integration-auth/integration-auth-types.ts, backend/src/services/integration-auth/integration-sync-secret.ts, frontend/src/pages/integrations/aws-parameter-store/authorize.tsx, frontend/src/pages/integrations/circleci/create.tsx, frontend/src/views/IntegrationsPage/components/IntegrationsSection/ConfiguredIntegrationItem.tsx
The Circle CI integration seemingly never worked in the first place _(or broke because Circle CI pushed a breaking change)_ due to in-proper project slugs. This PR resolves it by refactoring the fetching of apps, and the secret syncing step.
---
=> fix(integrations/circle-ci): Refactored Circle CI integration

docs/integrations/cicd/githubactions.mdx, docs/self-hosting/configuration/envars.mdx, docs/self-hosting/deployment-options/kubernetes-helm.mdx, docs/self-hosting/deployment-options/standalone-infisical.mdx
The SITE_URL is required or Infisical will fail with a error message.
details: https://questions.infisical.com/2J28261
---
=> docs: add mention of SITE_URL as being required

backend/src/server/app.ts
Small typo I noticed while skimming the code.
---
=> fix: small typo (`fasitfy` -> `fastify`)

backend/src/services/certificate-authority/certificate-authority-validators.ts
This PR will enable users to create certificates whose SAN value is a wildcard domain 
This PR resolves the following issue:
https://github.com/Infisical/infisical/issues/2212
```sh
```
---
=> misc: allow wildcard SAN domain value for certificates

backend/src/services/secret-v2-bridge/secret-v2-bridge-fns.ts
PR to resolve secret reference skipping if the value is not found
```sh
```
---
=> Secret reference skip if not found

docs/documentation/platform/sso/azure.mdx
This PR corrects the stated Azure SAML documentation attribute mappings to be inline with the screenshot.
---
=> Fix Stated Map for Azure SAML Attributes

frontend/src/components/signup/EnterEmailStep.tsx
Fixes email capitalisation issue where we send a lowercase email from frontend on login but not on signup.
Now we send lowercase emails on signup also.
=> Send lower case emails to backend

backend/src/ee/routes/v1/saml-router.ts, standalone-entrypoint.sh
1. Added debug log for entra scim debugging
2. Enabled source map for standalone script too
```sh
```
---
=> feat: debug added log points for entra failing saml

backend/src/ee/routes/v1/saml-router.ts
This PR resolves entra saml failing
```sh
```
---
=> fix: resolved entra failing

backend/src/services/integration-auth/integration-sync-secret.ts
Add logs to debug missing secret in GCP secret sync. Context : [ISSUE](https://linear.app/infisical/issue/ENG-1476/gcp-sm-syncing-issue)
=> chore: add log on empty value being pushed to gcp

frontend/src/components/v2/Select/Select.tsx, frontend/src/views/Project/MembersPage/components/GroupsTab/components/GroupsSection/GroupModal.tsx
=> fixed inactive cancel button

backend/src/ee/routes/v1/project-role-router.ts
Fixed request schema to accept a role description. This is a prerequisite for fixing the Terraform provider's project role resource. 
---
=> fix: updating role description

frontend/src/context/WorkspaceContext/WorkspaceContext.tsx
- This PR handles "no project access" case upon redirect from email or slack notification
```sh
```
---
=> misc: added handling of no project access for redirects

backend/src/services/identity-oidc-auth/identity-oidc-auth-service.ts
This PR finalizes the error codes being thrown during oidc login failure. Before this, login errors were being sent as error 500s which was misleading
```sh
```
---
=> misc: finalized error codes for oidc login

backend/src/ee/services/permission/org-permission.ts, backend/src/ee/services/permission/permission-dal.ts, backend/src/ee/services/permission/permission-service.ts, backend/src/ee/services/permission/permission-types.ts, backend/src/services/org/org-role-service.ts
This PR fixes couple of issues with permission system due to collision with groups and additional privileges. This also fixes issue with org group permission not considered. 
The query to pull permission for group, additional privileges and user permission are optimized into one single query.
```sh
```
---
=> User group permission fixes

backend/src/services/org/org-service.ts
Fixes a small bug in project invite  where the org invite specific checks needs to be moved inside when org invite is needed for a project invite. 
```sh
```
---
=> feat: moved check for org invite specifc operation inside the creation if

frontend/src/views/SecretOverviewPage/components/SecretV2MigrationSection/SecretV2MigrationSection.tsx
This PR revises the forced project upgrade banner to improve legibility and avoid confusing terminology.
```sh
```
---
=> Improvement: Project Upgrade Banner Revisions

frontend/src/views/SecretApprovalPage/components/ApprovalPolicyList/ApprovalPolicyList.tsx, frontend/src/views/SecretApprovalPage/components/ApprovalPolicyList/components/AccessPolicyModal.tsx
Fetch groups using project id instead of slug
---
=> fix: group fetch using project id

frontend/src/views/Org/AuditLogsPage/AuditLogsPage.tsx, frontend/src/views/Org/AuditLogsPage/components/LogsFilter.tsx, frontend/src/views/Org/AuditLogsPage/components/LogsSection.tsx
- This PR adds a maintenance notice to the audit log page 
- This PR also auto-selects the first workspace by default 
```sh
```
---
=> misc: added maintenance notice to audit log page

backend/src/ee/routes/v1/group-router.ts, backend/src/lib/api-docs/constants.ts, docs/api-reference/endpoints/groups/add-group-user.mdx, docs/api-reference/endpoints/groups/create.mdx, docs/api-reference/endpoints/groups/delete.mdx, docs/api-reference/endpoints/groups/get-by-id.mdx, docs/api-reference/endpoints/groups/get.mdx, docs/api-reference/endpoints/groups/list-group-users.mdx, docs/api-reference/endpoints/groups/remove-group-user.mdx, docs/api-reference/endpoints/groups/update.mdx, docs/api-reference/endpoints/project-groups/create.mdx, docs/api-reference/endpoints/project-groups/delete.mdx, docs/api-reference/endpoints/project-groups/get-by-id.mdx, docs/api-reference/endpoints/project-groups/list.mdx, docs/api-reference/endpoints/project-groups/update.mdx, docs/mint.json
- This PR adds all the groups-related endpoints to the API reference
```sh
```
---
=> doc: add groups endpoints to api reference documentation

backend/src/server/routes/v3/dashboard-router.ts, frontend/src/views/SecretOverviewPage/SecretOverviewPage.tsx
Fix for dashboard and overview not able to access when root folder access not provided
```sh
```
---
=> fix: dashboard not showing when root accessn not provided

frontend/src/views/Org/AuditLogsPage/AuditLogsPage.tsx
While we work on fixing audit logs, we will disable the filters.
=> hide audit log filter in prod

backend/src/server/routes/v1/organization-router.ts
PR to make audit log disable for Infisical cloud due to maintenance mode
```sh
```
---
=> feat: disabled audit log for cloud due to maintainence mode

backend/src/ee/routes/v1/access-approval-policy-router.ts, backend/src/ee/routes/v1/secret-approval-policy-router.ts, backend/src/ee/services/access-approval-policy/access-approval-policy-dal.ts, backend/src/ee/services/access-approval-policy/access-approval-policy-service.ts, backend/src/ee/services/access-approval-policy/access-approval-policy-types.ts, backend/src/ee/services/secret-approval-policy/secret-approval-policy-dal.ts, backend/src/ee/services/secret-approval-policy/secret-approval-policy-service.ts, backend/src/ee/services/secret-approval-policy/secret-approval-policy-types.ts, backend/src/server/routes/index.ts
- This PR creates the necessary secret approval policy and access approval policy API updates in order to support secret approval policy and access approval policy TF resources
Terrform PR:
https://github.com/Infisical/terraform-provider-infisical/pull/55
```sh
```
---
=> misc: approval policy modifications for TF resource

backend/src/server/routes/v1/dashboard-router.ts, backend/src/server/routes/v1/index.ts, backend/src/server/routes/v3/index.ts, frontend/src/components/v2/Dropdown/Dropdown.tsx, frontend/src/hooks/api/dashboard/queries.tsx, frontend/src/pages/integrations/aws-parameter-store/create.tsx, frontend/src/pages/integrations/aws-secret-manager/create.tsx, frontend/src/views/SecretOverviewPage/components/SecretOverviewTableRow/SecretOverviewTableRow.tsx, frontend/src/views/SecretOverviewPage/components/SecretTableResourceCount/SecretTableResourceCount.tsx, frontend/src/views/Settings/OrgSettingsPage/components/OrgEncryptionTab/AwsKmsForm.tsx
This PR adds AWS region slugs to all integration dropdowns, fixes dropdown overflow, adds explanatory tooltips to the secrets table resource counter, moves the dashboard router to v1, and improves handling of querystring boolean values for dashboard endpoints.
```sh
```
---
=> Fix: Various UI Improvements, Fixes and Backend Refactoring

backend/src/services/secret/secret-queue.ts
This PR fixes integration sync retries on failure.
```sh
```
---
=> Fix: Integration Sync Retry on Error Patch

frontend/src/components/navigation/RegionSelect.tsx, frontend/src/components/signup/InitialSignupStep.tsx, frontend/src/pages/_app.tsx, frontend/src/views/Login/components/InitialStep/InitialStep.tsx
This PR adds a region select dropdown to login and signup for cloud users to select their preferential data region.
```sh
```
---
=> Feature: Add Data Region Select

frontend/src/components/v2/Select/Select.tsx, frontend/src/views/Org/MembersPage/components/OrgGroupsTab/components/OrgGroupsSection/OrgGroupsTable.tsx, frontend/src/views/Org/MembersPage/components/OrgIdentityTab/components/IdentitySection/IdentityTable.tsx, frontend/src/views/Org/MembersPage/components/OrgMembersTab/components/OrgMembersSection/OrgMembersTable.tsx, frontend/src/views/Org/MembersPage/components/OrgRoleTabSection/OrgRoleTable.tsx
1. Increased width for all the select in org access control
2. Added text overflow changes for select 
3. Fixed org role page overflow
```sh
```
---
=> feat: increase select width in org access control page and added overflow bounding for select

frontend/src/hooks/api/identities/queries.tsx, frontend/src/views/Org/MembersPage/components/OrgIdentityTab/components/IdentitySection/IdentityAuthMethodModal.tsx, frontend/src/views/Org/MembersPage/components/OrgIdentityTab/components/IdentitySection/IdentityAwsAuthForm.tsx, frontend/src/views/Org/MembersPage/components/OrgIdentityTab/components/IdentitySection/IdentityAzureAuthForm.tsx, frontend/src/views/Org/MembersPage/components/OrgIdentityTab/components/IdentitySection/IdentityGcpAuthForm.tsx, frontend/src/views/Org/MembersPage/components/OrgIdentityTab/components/IdentitySection/IdentityKubernetesAuthForm.tsx, frontend/src/views/Org/MembersPage/components/OrgIdentityTab/components/IdentitySection/IdentityOidcAuthForm.tsx, frontend/src/views/Org/MembersPage/components/OrgIdentityTab/components/IdentitySection/IdentityTokenAuthForm.tsx, frontend/src/views/Org/MembersPage/components/OrgIdentityTab/components/IdentitySection/IdentityUniversalAuthForm.tsx
Allow users to replace / overwrite auth methods for identities.
---
=> feat: allow users to replace auth methods

backend/src/services/identity-kubernetes-auth/identity-kubernetes-auth-service.ts
This PR introduces better error logs for the K8 native auth
---
=> fix(k8-auth): better errors

backend/src/lib/casl/index.ts, frontend/src/views/Org/MembersPage/components/OrgIdentityTab/components/IdentitySection/IdentityModal.tsx
This fixes a bug in create identity not submitting in initial try but works when the metadata table is added and removed. 
Added a default value. This seems to be some kinda of zod bug
```sh
```
---
=> feat: added a default empty array for create-identity

backend/src/services/integration/integration-service.ts
Added error for integration not found. This is necessary for our terraform integration resources.
---
=> fix(api): integration not found error

backend/src/@types/ldif.d.ts, backend/src/ee/services/dynamic-secret/providers/ldap.ts
Fix action breaking due to `import {} from commonjs-module`
```sh
```
---
=> fix: change mustache import

backend/src/ee/services/dynamic-secret/providers/ldap.ts
=> fix handlebars import

frontend/src/views/Project/KmsPage/components/CmekTable.tsx
This PR corrects the KMS Docs link on the KMS table.
```sh
```
---
=> Fix: Correct KMS Doc Link

.github/pull_request_template.md, backend/src/ee/services/audit-log/audit-log-types.ts, backend/src/lib/api-docs/constants.ts, backend/src/server/routes/v1/project-env-router.ts, backend/src/server/routes/v1/secret-folder-router.ts, backend/src/server/routes/v1/secret-import-router.ts, backend/src/services/project-env/project-env-service.ts, backend/src/services/project-env/project-env-types.ts, backend/src/services/secret-folder/secret-folder-service.ts, backend/src/services/secret-import/secret-import-dal.ts, backend/src/services/secret-import/secret-import-service.ts, backend/src/services/secret-import/secret-import-types.ts
This PR is a prerequisite for supporting Terraform Imports. It allows us to fetch secret imports purely by ID, and it exposes more information about secret folders, which is necessary for Terraform.
I also added a new type to our Pull request template called Improvement, which should be used when making improvements/adjustments to existing code, as suggested by @scott-ray-wilson.
---
=> feat: terraform imports prerequisite / api improvements

backend/src/services/identity/identity-org-dal.ts
This PR fixes identity pagination in org level. Some identities were not shown while shown in searching.
```sh
```
---
=> feat: corrected identity pagination in org level

backend/src/server/routes/v1/identity-aws-iam-auth-router.ts, backend/src/server/routes/v1/identity-azure-auth-router.ts, backend/src/server/routes/v1/identity-gcp-auth-router.ts, docs/cli/commands/export.mdx, docs/cli/commands/run.mdx, docs/cli/commands/secrets.mdx, docs/cli/usage.mdx, docs/documentation/platform/token.mdx, docs/integrations/cicd/jenkins.mdx, docs/integrations/cloud/aws-amplify.mdx, docs/integrations/platforms/docker-compose.mdx, docs/integrations/platforms/docker.mdx, docs/integrations/platforms/kubernetes.mdx, docs/internals/service-tokens.mdx, frontend/src/context/WorkspaceContext/WorkspaceContext.tsx
We are postponing service tokens and therefore we need to remove previous notice. This PR does just that.
=> Remove service token notice

docs/documentation/platform/identities/oidc-auth/circleci.mdx, docs/mint.json
This PR adds documentation for how to configure CircleCI OIDC auth. It also includes sample usage which demonstrates using CircleCI OIDC token to authenticate with Infisical terraform provider
```sh
```
---
=> doc: circle ci oidc auth

backend/src/ee/services/license/license-fns.ts, backend/src/services/org/org-dal.ts, frontend/package-lock.json, frontend/package.json, frontend/src/components/v2/MultiSelect/MultiSelect.tsx, frontend/src/components/v2/MultiSelect/index.tsx, frontend/src/components/v2/index.tsx, frontend/src/views/Project/MembersPage/components/MembersTab/components/AddMemberModal.tsx
This PR adds a new multi-select component and uses it to improve adding users to a project.
https://github.com/user-attachments/assets/0a28e58a-621c-426b-a0af-428a5ee8946f
```sh
```
---
=> Feature: Multi-Select Component and Improve Adding Users to Project

backend/src/services/integration-auth/integration-sync-secret.ts
This PR resolves ssm integration failing in 1-1 mapping when string value is empty
```sh
```
---
=> fix: resolved ssm failing for empty secret in 1-1 mapping

helm-charts/infisical-standalone-postgres/Chart.yaml, helm-charts/infisical-standalone-postgres/templates/infisical.yaml, helm-charts/infisical-standalone-postgres/templates/jobs-rbac.yaml, helm-charts/infisical-standalone-postgres/templates/schema-migration-job.yaml, helm-charts/infisical-standalone-postgres/values.yaml
- Allows users to specify service accounts of their own for migration job 
- Allows users to pass in existing secret that contains PG connection string
```sh
```
---
=> Make helm chart more dynamic 

backend/src/lib/knex/scim.ts, backend/src/server/plugins/add-errors-to-response-schemas.ts, backend/src/server/plugins/error-handler.ts
1. Resolved scim failing for mismatch in error response. Removed that just for scim
2. Resolved knexjs dynamic generation for and,or not condition 
```sh
```
---
=> Resolved response schema mismatch for scim

backend/src/server/routes/v1/organization-router.ts
- This PR will allow the audit logs endpoints to be invoked using machine identities
```sh
```
---
=> misc: made audit log endpoint mi accessible

docs/mint.json
Adding footer to the documentation
```sh
mintlify dev
```
- Check the footer at the bottom of the documentation page
---
=> Add footer to docs

backend/src/services/external-migration/external-migration-fns.ts
This PR fixes an issue with the EnvKey migration raised by @maidul98, that causes the migration to fail for large uploads (above 10MB). The issue was occurring because we weren't batching secrets when getting secrets by key. Resulting in the DB failing to read.
---
=> fix: envkey migration failing due to not using batches

backend/src/services/secret-v2-bridge/secret-v2-bridge-service.ts, backend/src/services/secret/secret-service.ts
1. Update all the secret operation to execute snapshotting and syncing only when its shared secret. Snapshot and integration sync is not needed when its personal secret. Its more for dev purpose.
```sh
```
---
=> feat: only do sync secret and snapshot if its shared secret change

docs/cli/commands/token.mdx, docs/integrations/platforms/docker-compose.mdx, docs/integrations/platforms/docker.mdx
1. Fixed misinformation in the doc for machine identity with docker compose
2. Added how to use token generation with docekr starting script
```sh
```
---
=> chore: updated documentation for docker compose and docker for machine identity

backend/src/services/secret-v2-bridge/secret-v2-bridge-fns.ts, backend/src/services/secret/secret-fns.ts, cli/packages/cmd/login.go, cli/packages/cmd/root.go, cli/packages/cmd/user.go, cli/packages/util/constants.go, cli/packages/util/init.go
This PR adds support for the EU region. Previously the user would need to select "Self hosted" and then enter "https://eu.infisical.com". Now it's an option in the dropdown. This should help relieve any possible confusion.
---
=> feat: cloud EU region support

backend/src/ee/services/permission/project-permission.ts
=> feat: added filter folder to remove read only in migration

backend/src/ee/services/permission/project-permission.ts
Reverts Infisical/infisical#2605
=> Revert "feat: added filter folder to remove read only in migration"

Dockerfile.standalone-infisical, backend/src/ee/routes/v1/secret-scanning-router.ts, backend/src/ee/services/secret-scanning/secret-scanning-queue/secret-scanning-queue.ts, backend/src/ee/services/secret-scanning/secret-scanning-service.ts, backend/src/lib/config/env.ts, backend/src/server/routes/index.ts, frontend/src/layouts/AppLayout/AppLayout.tsx, frontend/src/pages/org/[id]/secret-scanning/index.tsx
- This PR will allow us to enable secret scanning feature for a select few orgs in Infisical cloud
```sh
```
---
=> misc: added secret scanning whitelist configuration

cli/test/.snapshots/test-TestUniversalAuth_SecretsGetWrongEnvironment
Updated CLI snapshot error message to reflect the new error messages thrown from the API.
---
=> fix: cli snapshot test error message change

frontend/src/hooks/api/secrets/queries.tsx, frontend/src/views/Org/MembersPage/components/OrgGroupsTab/components/OrgGroupsSection/OrgGroupsTable.tsx, frontend/src/views/Org/MembersPage/components/OrgMembersTab/components/OrgMembersSection/OrgMembersTable.tsx, frontend/src/views/SecretOverviewPage/SecretOverviewPage.tsx
This PR fixes secrets incorrectly displaying their value as overridden on the Overview table. Also minor UI improvements to Org Users/Groups Tables 
```sh
```
---
=> Fix: Correct Secret Value Override Display on Overview Table

docs/sdks/languages/go.mdx
Update for our Go SDK docs to properly reflect the new automatic token refreshing logic.
---
=> docs: go SDK refreshing docs

frontend/src/views/SecretApprovalPage/components/SecretApprovalRequest/components/SecretApprovalRequestAction.tsx
- This PR will allow approvers to bypass secret change requests
```sh
```
---
=> feat: allow approvers to bypass secret change requests

backend/src/services/identity-access-token/identity-access-token-dal.ts, backend/src/services/identity-ua/identity-ua-client-secret-dal.ts
This PR aims to resolve an issue with the daily cleanup job. Our daily cleanup job has been erroring due to high TTL values. We are fixing this by using `LEAST()`, which will ensure that the TTL cannot go above a set value during computation.
---
=> fix: `timestamp out of range` error during daily cleanup

docs/integrations/cicd/githubactions.mdx
- add missing repo permission scope for Github app sync integration self-hosted setup
```sh
```
---
=> doc: added missing github app permission scope

backend/src/services/secret-v2-bridge/secret-v2-bridge-fns.ts
This PR fixes an issue in recursive logic in which it fetches from the top order rather than just from bottom order. 
```sh
```
---
=> fix: resolved recursive secret logic pulling secret from top

backend/src/services/external-migration/external-migration-fns.ts, backend/src/services/external-migration/external-migration-queue.ts, backend/src/services/external-migration/external-migration-types.ts
This PR fixes the EnvKey data import.
Previously, the EnvKey import didn't factor in:
1. Blocks
2. Block branches
3. Custom base environments
4. Normal environment branches
5. Secret inheritance
All this has now been resolved and works as expected.  
@maidul98 has been sent details on how to test this, as the test suite requires login credentials.
---
=> feat: envkey import refactor

backend/package-lock.json, backend/src/lib/api-docs/constants.ts, backend/src/server/routes/v3/secret-router.ts, backend/src/services/secret-v2-bridge/secret-v2-bridge-fns.ts, backend/src/services/secret-v2-bridge/secret-v2-bridge-service.ts, backend/src/services/secret-v2-bridge/secret-v2-bridge-types.ts, backend/src/services/secret/secret-queue.ts, backend/src/services/secret/secret-service.ts, frontend/package-lock.json, frontend/package.json, frontend/src/hooks/api/secrets/index.ts, frontend/src/hooks/api/secrets/queries.tsx, frontend/src/hooks/api/secrets/types.ts, frontend/src/styles/globals.css, frontend/src/views/SecretMainPage/components/SecretListView/SecretDetailSidebar.tsx, frontend/src/views/SecretMainPage/components/SecretListView/SecretItem.tsx, frontend/src/views/SecretMainPage/components/SecretListView/SecretListView.tsx, frontend/src/views/SecretMainPage/components/SecretListView/SecretListView.utils.ts, frontend/src/views/SecretMainPage/components/SecretReferenceDetails/SecretReferenceDetails.module.css, frontend/src/views/SecretMainPage/components/SecretReferenceDetails/SecretReferenceDetails.tsx, frontend/src/views/SecretMainPage/components/SecretReferenceDetails/index.tsx, frontend/src/views/SecretOverviewPage/components/SecretOverviewTableRow/SecretEditRow.tsx
Reverts Infisical/infisical#2649
=> feat: secret reference graph for understanding how its pulled

frontend/src/views/ShareSecretPublicPage/components/ShareSecretForm.tsx, frontend/src/views/ViewSecretPublicPage/components/PasswordContainer.tsx, frontend/src/views/ViewSecretPublicPage/components/SecretContainer.tsx
This PR fixes copying shared secrets to clipboard on generation. Also minor text casing adjustments.
```sh
```
---
=> Fix: Copy Shared Secret Link to Clipboard on Generate

backend/src/server/routes/v1/cmek-router.ts
This PR corrects the param doc references for the KMS decrypt endpoint.
```sh
```
---
=> Docs: Correct KMS API Docs for Decrypt Endpoint

helm-charts/secrets-operator/Chart.yaml, helm-charts/secrets-operator/templates/infisicalsecret-crd.yaml, helm-charts/secrets-operator/values.yaml, k8-operator/kubectl-install/install-secrets-operator.yaml
- updated kubernetes operator version in helm
- add new properties to helm for secret operator
```sh
```
---
=> misc: added helm related configs for operator

docs/documentation/platform/identities/machine-identities.mdx
=> fix link in docs

backend/src/ee/services/permission/project-permission.ts
=> feat: fixed missing secret folder and import permission in service token

backend/src/ee/services/dynamic-secret/dynamic-secret-service.ts, backend/src/ee/services/dynamic-secret/dynamic-secret-types.ts, backend/src/lib/types/index.ts, backend/src/server/routes/v1/dashboard-router.ts, backend/src/services/cmek/cmek-service.ts, backend/src/services/external-group-org-role-mapping/external-group-org-role-mapping-service.ts, backend/src/services/secret-folder/secret-folder-dal.ts, backend/src/services/secret-folder/secret-folder-service.ts, backend/src/services/secret-folder/secret-folder-types.ts, backend/src/services/secret-v2-bridge/secret-v2-bridge-dal.ts, backend/src/services/secret-v2-bridge/secret-v2-bridge-service.ts, backend/src/services/secret-v2-bridge/secret-v2-bridge-types.ts, backend/src/services/secret/secret-service.ts, frontend/src/components/v2/Checkbox/Checkbox.tsx, frontend/src/helpers/reverseTruncate.ts, frontend/src/hooks/api/dashboard/index.ts, frontend/src/hooks/api/dashboard/queries.tsx, frontend/src/hooks/api/dashboard/types.ts, frontend/src/hooks/api/secrets/queries.tsx, frontend/src/hooks/api/secrets/types.ts, frontend/src/views/SecretMainPage/SecretMainPage.tsx, frontend/src/views/SecretMainPage/components/ActionBar/ActionBar.tsx, frontend/src/views/SecretOverviewPage/SecretOverviewPage.tsx, frontend/src/views/SecretOverviewPage/components/SecretSearchInput/SecretSearchInput.tsx, frontend/src/views/SecretOverviewPage/components/SecretSearchInput/components/QuickSearchDynamicSecretItem.tsx, frontend/src/views/SecretOverviewPage/components/SecretSearchInput/components/QuickSearchFolderItem.tsx, frontend/src/views/SecretOverviewPage/components/SecretSearchInput/components/QuickSearchModal.tsx, frontend/src/views/SecretOverviewPage/components/SecretSearchInput/components/QuickSearchSecretItem.tsx, frontend/src/views/SecretOverviewPage/components/SecretSearchInput/components/index.tsx, frontend/src/views/SecretOverviewPage/components/SecretSearchInput/index.tsx
This PR adds quick/deep search functionality to the secrets dashboard to allow users to quickly navigate across projects/environments, search nested folders and access secret values.
https://github.com/user-attachments/assets/25e12cd4-8f01-4a6e-8cf4-8ebcad73024d
```sh
```
---
=> Feature: Secrets Dashboard Quick/Deep Search

docs/documentation/platform/kms/kubernetes-encryption.mdx, docs/documentation/platform/kms/overview.mdx, docs/mint.json, frontend/src/views/Project/KmsPage/components/CmekTable.tsx
- This PR adds the Key ID column so that it can be extracted easily for use in API or in kubernetes KMS plugin (design inspo from aws KMS)
Before:
After:
This PR also adds kubernetes encryption to the docs
```sh
```
---
=> feat: added key id column

backend/src/server/routes/v1/admin-router.ts, backend/src/services/org/org-service.ts, backend/src/services/super-admin/super-admin-dal.ts, backend/src/services/super-admin/super-admin-service.ts, frontend/src/hooks/api/admin/types.ts, frontend/src/hooks/api/users/types.ts, frontend/src/views/Login/components/InitialStep/InitialStep.tsx, frontend/src/views/admin/DashboardPage/DashboardPage.tsx
This PR adds support for using the server admin configured default org for OIDC login and also only displays OIDC/SAML login when enforced for the default org.
```sh
```
---
=> Feature: OIDC Default Org

backend/src/server/plugins/swagger.ts
This PR updates our OpenAPI Spec to reflect separate servers for EU and US.
```sh
```
---
=> Docs: Update OpenAPI Spec Servers 

docs/documentation/platform/admin-panel/server-admin.mdx, docs/documentation/platform/sso/auth0-oidc.mdx, docs/documentation/platform/sso/azure.mdx, docs/documentation/platform/sso/general-oidc.mdx, docs/documentation/platform/sso/google-saml.mdx, docs/documentation/platform/sso/jumpcloud.mdx, docs/documentation/platform/sso/keycloak-oidc.mdx, docs/documentation/platform/sso/keycloak-saml.mdx, docs/documentation/platform/sso/okta.mdx
This PR updates the docs to include OIDC in the server admin console default org description, adds a new tip for default org config to each SAML/OIDC provider, and improves the info box for each as well.
```sh
```
---
=> Docs: OIDC Default Org Support and OIDC/SAML Tip/Info Improvements

backend/src/services/secret-sharing/secret-sharing-service.ts
Fix minor typo
Discuss with Tony
=> fix: minor typo

docs/documentation/guides/organization-structure.mdx, docs/mint.json
=> added blueprint for org structure

backend/src/ee/services/secret-approval-request/secret-approval-request-service.ts, frontend/src/views/SecretApprovalPage/components/SecretApprovalRequest/components/SecretApprovalRequestChangeItem.tsx
This PR fixes couple of minor bugs
1. Present secret tag not shown in approval details page
2. Update not working for secret approval
Another small fix is manual secret rotation not triggering. This is because of bullmq immediately with repeat generate same key. We added remove on case to avoid this issue.  
```sh
```
---
=> fix: resolved tag update not happening via approval

helm-charts/infisical-standalone-postgres/CHANGELOG.md, helm-charts/infisical-standalone-postgres/Chart.yaml, helm-charts/infisical-standalone-postgres/README.md, helm-charts/infisical-standalone-postgres/templates/_helpers.tpl, helm-charts/infisical-standalone-postgres/templates/infisical.yaml, helm-charts/infisical-standalone-postgres/templates/jobs-rbac.yaml, helm-charts/infisical-standalone-postgres/templates/schema-migration-job.yaml, helm-charts/infisical-standalone-postgres/values.yaml
This PR adds support for auto creating service accounts for infisical helm chart. It also includes docs for the chart.
=> Add support for auto creating SA for job and deployment

frontend/src/hooks/api/secrets/mutations.tsx, frontend/src/hooks/api/secrets/types.ts, frontend/src/views/SecretMainPage/SecretMainPage.tsx, frontend/src/views/SecretMainPage/components/CreateSecretForm/CreateSecretForm.tsx, frontend/src/views/SecretOverviewPage/SecretOverviewPage.tsx, frontend/src/views/SecretOverviewPage/components/CreateSecretForm/CreateSecretForm.tsx
This PR adds support for adding tags in create secret form both in overview and main page
```sh
```
---
=> feat: added tag support on create secret

frontend/src/pages/integrations/aws-secret-manager/create.tsx
- This PR updates the AWS secret manager integration page to use react-hook-form which consequently resolves multiple validation issues
```sh
```
---
=> misc: moved aws secret manager integration to react hook form

backend/src/lib/validator/index.ts, backend/src/lib/validator/validate-folder-name.ts, backend/src/server/routes/v1/secret-folder-router.ts, backend/src/services/secret-folder/secret-folder-dal.ts, backend/src/services/secret-v2-bridge/secret-v2-bridge-fns.ts, frontend/src/components/v2/SecretInput/SecretInput.tsx
=> feat: random patches

npm/package-lock.json, npm/package.json
Fixed NPM CLI symlink issue.
---
=> fix: npm cli symlink

docs/documentation/platform/identities/oidc-auth/gitlab.mdx, docs/mint.json
This PR adds documentation for how to use OIDC auth for Gitlab pipelines
```sh
```
---
=> doc: add docs for gitlab oidc auth

npm/src/index.cjs
This PR fixes the NPM CLI installer for Windows. There was a smaller issue with the symlink creation, causing the `infisical` command to not be accessible across the system.
The primary issue was npm couldn't find a file called `infisical` to create the symlink for, because Windows downloads 3 files with `.exe`, `.ps1`, and `.cmd` extensions. The solution for this was to create an empty file that matches the unix binary file (`infisical`). See comment in code for further details
```sh
```
---
=> fix: NPM-based CLI windows symlink

backend/src/services/identity-azure-auth/identity-azure-auth-service.ts
Minor change to give users a better insight in which service principal is not allowed.
---
=> chore(azure-auth): better error on service principal not allowed

backend/src/services/identity-aws-auth/identity-aws-auth-service.ts, backend/src/services/identity-azure-auth/identity-azure-auth-service.ts, backend/src/services/identity-gcp-auth/identity-gcp-auth-service.ts, backend/src/services/identity-kubernetes-auth/identity-kubernetes-auth-service.ts, backend/src/services/identity-oidc-auth/identity-oidc-auth-service.ts
This PR aims to add access token removal when an auth method is removed.
---
=> fix(identity): remove access tokens when auth method is removed

docs/api-reference/endpoints/secrets/create-many.mdx, docs/api-reference/endpoints/secrets/create.mdx, docs/api-reference/endpoints/secrets/delete-many.mdx, docs/api-reference/endpoints/secrets/delete.mdx, docs/api-reference/endpoints/secrets/list.mdx, docs/api-reference/endpoints/secrets/read.mdx, docs/api-reference/endpoints/secrets/update-many.mdx, docs/api-reference/endpoints/secrets/update.mdx
=> update docs note

backend/src/server/routes/v1/integration-router.ts, backend/src/services/integration/integration-service.ts, frontend/src/hooks/api/integrations/types.ts, frontend/src/views/IntegrationsPage/IntegrationDetailsPage/components/IntegrationSettingsSection.tsx
This PR Adds additional metadata (AWS Region & IAM Role) to AWS Secrets Manager settings page
Closes ENG-1753 and ENG-1850
Manually tested by setting up AWS integration and verifying data is displayed correctly.
---
=> feat(integrations): Add AWS Secrets Manager IAM Role + Region

backend/src/server/routes/v3/signup-router.ts, backend/src/services/auth/auth-signup-service.ts
This PR resolves signup failing via SAML when you sign up disabled. Now we allow signup via saml and it only affects normal email
```sh
```
---
=> feat: resolved saml failing when signup is disabled

frontend/next.config.js, frontend/src/layouts/AppLayout/AppLayout.tsx, frontend/src/views/SecretOverviewPage/SecretOverviewPage.tsx
The PR fixes couple of bugs in infisical
1. When there is no environment a project overview page keeps on infisical logo loading indicator forever
2. When two projects has uneven environments count, and they switch between using the sidebar project switcher it causes a react query undefined error thrown with react throwing another error on hook order invalid. This seems to an issue on how we structure in overview page. For now i have swtich to browser router from nextjs router to trigger a refresh. On dashboard revamp will fix this in depth as structure need to change a lot
3. Frontend failing to talk with CLI on trying to login due to connect src issue, Added the localhost ip as black list in script
```sh
```
---
=> Random patches

frontend/src/hooks/api/organization/types.ts, frontend/src/views/Settings/BillingSettingsPage/components/BillingDetailsTab/PmtMethodsTable.tsx
This PR fixes payment methods not being able to be removed. In addition a confirmation to remove the card and success/error notification have been added.
https://github.com/user-attachments/assets/0ad77735-40d1-48b8-9490-c7ec40360a9e
```sh
```
---
=> Fix: Resolve Remove Payment Method Error

frontend/package-lock.json, frontend/package.json, frontend/src/components/v2/CreatableSelect/CreatableSelect.tsx, frontend/src/components/v2/CreatableSelect/index.tsx, frontend/src/components/v2/FilterableSelect/FilterableSelect.tsx, frontend/src/components/v2/Select/components/index.tsx, frontend/src/views/SecretMainPage/components/CreateSecretForm/CreateSecretForm.tsx, frontend/src/views/SecretOverviewPage/components/CreateSecretForm/CreateSecretForm.tsx
You can now create a new tag when adding a new secret to a project
This PR adds in a new `<CreatableSelect />` component which will be replaced once codebase refactor to `react-select` is complete
manually tested
---
=> feat: Add new tag when creating secret

frontend/src/components/v2/FilterableSelect/FilterableSelect.tsx, frontend/src/views/Org/MembersPage/components/OrgMembersTab/components/OrgMembersSection/AddOrgMemberModal.tsx
This PR Updates the Invite User optional project select to use a filterable multi-select component.
```sh
```
---
=> Improvement: Filterable Multi-Select Project Input on Invite Users

frontend/src/components/v2/DatePicker/DatePicker.tsx, frontend/src/components/v2/FilterableSelect/FilterableSelect.tsx, frontend/src/views/Org/AuditLogsPage/components/LogsFilter.tsx, frontend/src/views/Org/AuditLogsPage/components/LogsSection.tsx, frontend/src/views/Org/AuditLogsPage/components/types.tsx
This PR updates the project select to be filterable on audit logs. Also includes minor UI adjustments
```sh
```
---
=> Improvement:  Filterable Project Select for Audit Logs

frontend/src/hooks/usePagination.tsx, frontend/src/pages/org/[id]/overview/index.tsx
This PR adds client-side pagination to the project overview page with other minor UI adjustments
(default page size is not 12, just for screenshot)
```sh
```
---
=> Improvement: Add Pagination to the Project Overview Page

backend/src/services/identity-kubernetes-auth/identity-kubernetes-auth-service.ts
- This PR will allow kubernetes native auth with custom audience value
Relevant docs:
https://kubernetes.io/docs/reference/kubernetes-api/authentication-resources/token-review-v1/
Before this PR:
```sh
```
---
=> fix: address custom audience issue

backend/e2e-test/routes/v3/secret-recursive.spec.ts, backend/e2e-test/testUtils/secrets.ts, backend/src/services/secret-v2-bridge/secret-v2-bridge-fns.ts
This PR adds E2E testing for secret recursive operation. 
```sh
```
---
=> Added testing for secret recursive operation

cli/packages/cmd/dynamic_secrets.go
This PR fixes cli broken at the moment because of another PR changing and the present one test were shown passed not the latest. 
```sh
```
---
=> fix: dynamic secret broken due to merge of another issue

frontend/src/views/SecretApprovalPage/components/ApprovalPolicyList/components/AccessPolicyModal.tsx
The main objective of this PR is to make it more clear that glob patterns are supported for policies. Additionally, I've touched up on other parts of the UI, such as the approvals section and enforcement level field.
**Before after pictures:**
**Before:**
**After:**
---
=> improvement(ui): approval policy modal

docs/integrations/platforms/kubernetes-csi.mdx, docs/mint.json
- this PR adds documentation for the Infisical CSI provider
```sh
```
---
=> doc: added docs for infisical csi provider

cli/test/helper.go, cli/test/secrets_test.go
Disable test failing. This test has been disabled forever, and enabling it is causing issues? I assume there was a reason this was disabled in the first place.
---
=> fix(cli): tests failing

frontend/src/components/v2/FilterableSelect/FilterableSelect.tsx, frontend/src/components/v2/Pagination/Pagination.tsx, frontend/src/pages/org/[id]/overview/index.tsx, frontend/src/views/SecretMainPage/components/ActionBar/CreateSecretImportForm.tsx, frontend/src/views/SecretMainPage/components/SecretDropzone/CopySecretsFromBoard.tsx
This PR updates various environment selects to be filterable and also updates the copy secrets from env modal to use multi-select over checkboxes. Also Adjusts pagination alignment for project overview grid view.
Copy Secrets Modal:
Add Import Modal:
```sh
```
---
=> Improvement: Copy Secrets Modal & Environment Selects Improvements

backend/src/ee/services/license/license-fns.ts, frontend/src/helpers/roles.ts, frontend/src/views/Org/MembersPage/components/OrgGroupsTab/components/OrgGroupsSection/OrgGroupModal.tsx, frontend/src/views/Org/MembersPage/components/OrgIdentityTab/components/IdentitySection/IdentityModal.tsx, frontend/src/views/Org/MembersPage/components/OrgMembersTab/components/OrgMembersSection/AddOrgMemberModal.tsx, frontend/src/views/Org/UserPage/UserPage.tsx, frontend/src/views/Org/UserPage/components/UserDetailsSection.tsx, frontend/src/views/Org/UserPage/components/UserOrgMembershipModal.tsx, frontend/src/views/Org/UserPage/components/UserProjectsSection/UserGroupsTable.tsx, frontend/src/views/Project/MembersPage/components/GroupsTab/components/GroupsSection/GroupModal.tsx, frontend/src/views/Project/MembersPage/components/MembersTab/components/AddMemberModal.tsx, frontend/src/views/Settings/ProjectSettingsPage/components/SecretTagsSection/SecretTagsSection.tsx, frontend/src/views/Settings/ProjectSettingsPage/components/SecretTagsSection/SecretTagsTable.tsx
This PR updates add/edit modals pertaining to users, identities and groups to use filterable selects over drop downs (project and org level). Minor refactoring/revisions. 
Add Group to Project (All fields):
Add Users to Project (Role selection):
Invite Users to Org (Role selection):
Create/Update Identity (Role selection):
Edit User (Role Selection):
Create/Update Group (Role selection):
Secret Tags Table:
User Page Groups:
```sh
```
---
=> Improvement: User/Group/Identity Modals Dropdown to Filterable Select Refactor + User Groups and Secret Tags Table Pagination

backend/src/ee/services/license/license-fns.ts, frontend/src/components/v2/FilterableSelect/FilterableSelect.tsx, frontend/src/helpers/members.ts, frontend/src/views/SecretApprovalPage/components/ApprovalPolicyList/ApprovalPolicyList.tsx, frontend/src/views/SecretApprovalPage/components/ApprovalPolicyList/components/AccessPolicyModal.tsx, frontend/src/views/SecretApprovalPage/components/ApprovalPolicyList/components/ApprovalPolicyRow.tsx, frontend/src/views/SecretOverviewPage/SecretOverviewPage.tsx
This PR refactors the secret approval policy modal to use filterable selects and include minor. UI revisions. Also includes re-ordering of secret overview page filters dropdown items.
```sh
```
---
=> Improvement: Secret Approval Form Filterable Selects

frontend/src/layouts/AppLayout/components/ProjectSelect/ProjectSelect.tsx, frontend/src/views/SecretOverviewPage/SecretOverviewPage.tsx, frontend/src/views/SecretOverviewPage/components/CreateSecretForm/CreateSecretForm.tsx
This PR updates the Create Secret modal to use a multi-select component instead of checkboxes for environment selection.
```sh
```
---
=> Improvement: Multi-select for Environment Selection on Create Secret

backend/e2e-test/mocks/queue.ts, backend/e2e-test/vitest-environment-knex.ts, backend/package-lock.json, backend/package.json, backend/src/ee/services/audit-log/audit-log-queue.ts, backend/src/lib/config/env.ts, backend/src/main.ts, backend/src/queue/queue-service.ts, backend/src/server/routes/index.ts
This PR adds support for using [pg-boss](https://timgit.github.io/pg-boss/#) as a queue for processing audit logs. For now, it would have to be manually toggled using the `USE_PG_QUEUE` env flag
```sh
```
---
=> misc: pg-queue for audit logs 

backend/e2e-test/vitest-environment-knex.ts, backend/src/@types/fastify.d.ts, backend/src/ee/routes/v1/oidc-router.ts, backend/src/main.ts, backend/src/server/app.ts, backend/src/server/routes/v1/sso-router.ts, backend/src/services/smtp/templates/organizationInvitation.handlebars, backend/src/services/smtp/templates/workspaceInvitation.handlebars
1. Fixed csrf issue in oauth. Copied our oidc implmentation for it as state cannot be used for cli port anymore because state has a random id generated for oauth security. For more info refer [oauth0 csrf](https://auth0.com/docs/secure/attack-protection/state-parameters). Used passport out of the box solution. Other passport like saml already has it implemented under the hood.
2. Rephrased our template for invite to avoid social engineering attack to an extend
```sh
```
---
=> feat: resolved csrf for oauth2 using state parameter

backend/src/ee/services/audit-log/audit-log-queue.ts, backend/src/lib/config/env.ts, backend/src/queue/queue-service.ts
-This will hide the initialization of pg-queue behind an ENV feature flag 
```sh
```
---
=> misc: added pg queue init flag

backend/src/@types/fastify-request-context.d.ts, backend/src/lib/logger/logger.ts, backend/src/server/app.ts, backend/src/server/plugins/error-handler.ts, backend/src/server/routes/sanitizedSchemas.ts, frontend/src/hooks/api/types.ts, frontend/src/reactQuery.tsx
This PR consolidates the `requestId` into `reqId` to fix multiple fields related to request ID's in our internal logging.
---
=> fix: consolidate reqId and requestId fields

README.md
The documentation no longer contains information about deploying on AWS EC2 or DigitalOcean in the self-hosting section.
N/A
---
=> doc: remove invalid links

frontend/src/hooks/api/kms/types.ts
This hotfix adds in a missing import that was not picked up during testing or code review.
ran build locally
---
- [X} I have read the [contributing guide](https://infisical.com/docs/contributing/getting-started/overview), agreed and acknowledged the [code of conduct](https://infisical.com/docs/contributing/getting-started/code-of-conduct). 📝
=> hotfix: add missing package import

backend/e2e-test/vitest-environment-knex.ts, backend/src/main.ts, backend/src/queue/queue-service.ts
- this PR adds ssl options to pg-boss initialization
```sh
```
---
=> misc: add ssl setting for pg boss

backend/src/ee/routes/v1/group-router.ts, backend/src/ee/services/group/group-dal.ts, backend/src/ee/services/group/group-service.ts, backend/src/ee/services/group/group-types.ts, backend/src/lib/api-docs/constants.ts, frontend/src/hooks/api/groups/index.tsx, frontend/src/hooks/api/groups/mutations.tsx, frontend/src/hooks/api/groups/queries.tsx, frontend/src/hooks/api/groups/types.ts, frontend/src/pages/org/[id]/groups/[groupId]/index.tsx, frontend/src/views/Org/GroupPage/GroupPage.tsx, frontend/src/views/Org/GroupPage/components/AddGroupMemberModal.tsx, frontend/src/views/Org/GroupPage/components/GroupCreateUpdateModal.tsx, frontend/src/views/Org/GroupPage/components/GroupDetailsSection.tsx, frontend/src/views/Org/GroupPage/components/GroupMembersSection/GroupMembersSection.tsx, frontend/src/views/Org/GroupPage/components/GroupMembersSection/GroupMembersTable.tsx, frontend/src/views/Org/GroupPage/components/GroupMembersSection/GroupMembershipRow.tsx, frontend/src/views/Org/GroupPage/components/GroupMembersSection/index.tsx, frontend/src/views/Org/GroupPage/components/index.tsx, frontend/src/views/Org/GroupPage/index.tsx, frontend/src/views/Org/MembersPage/components/OrgGroupsTab/components/OrgGroupsSection/OrgGroupsSection.tsx, frontend/src/views/Org/MembersPage/components/OrgGroupsTab/components/OrgGroupsSection/OrgGroupsTable.tsx
This PR adds a new way to manage group users.
Each group has its own page with more group details, and dedicated tables to manage users
tested manually
Groups:
create, update delete from both overview page and details page
add + remove members from details page
---
=> improvement: Better group member management

backend/src/server/routes/v1/integration-auth-router.ts
This PR moves integration auth to params
```sh
```
---
=> misc: moved integration auth to params

backend/package-lock.json, backend/package.json, backend/src/lib/config/env.ts, backend/src/server/routes/index.ts, backend/src/server/routes/v1/user-engagement-router.ts, backend/src/services/user-engagement/user-engagement-service.ts
This PR removes Plain and implements programmatically creating Pylon issues. This will be great for centralizing our inbound issues / requests in one place.
**New environment variables**:
- `PYLON_API_KEY`: The Pylon API key. Without this, the wish feature will stop working.
---
=> feat: remove plain and move to pylon

backend/src/db/migrations/20241213122350_project-split-to-products.ts
=> feat: changed multi insert into batch insert

backend/src/server/routes/v1/organization-router.ts, backend/src/server/routes/v2/user-router.ts, backend/src/services/org/org-schema.ts
Description 📣
This PR sanitizes the response of two endpoints that were previously returning more data than needed (encryped org data key)
```sh
```
---
=> misc: remove encrypted data key from org response

frontend/src/components/navigation/NavHeader.tsx
This PR fixes broken breadcrumbs in secret manager due to project split
```sh
```
---
=> feat: resolved broken breakcrumb in secret manager

Dockerfile.fips.standalone-infisical, Dockerfile.standalone-infisical
This PR adds OpenSSH dependency to the standalone Dockerfiles
---
=> Add OpenSSH dependency to standalone Dockerfiles

backend/src/ee/routes/v1/org-role-router.ts, backend/src/ee/routes/v1/project-role-router.ts, backend/src/ee/routes/v2/project-role-router.ts, backend/src/ee/services/ssh-certificate-template/ssh-certificate-template-service.ts, frontend/src/hooks/api/roles/types.ts, frontend/src/views/Org/RolePage/components/OrgRoleModifySection.utils.ts, frontend/src/views/Project/RolePage/components/RolePermissionsSection/ProjectRoleModifySection.utils.tsx
This PR addresses unhandled null values in schemas for org and project roles.
```sh
```
---
=> Fix: Correct Role Description Schema to Accept Null

docs/mint.json
This PR temporarily removes the documentation for App Connections.
```sh
```
---
=> Docs: Temporarily Remove App Connections

docs/mint.json
=> Remove intercom from docs

frontend/src/layouts/OrganizationLayout/OrganizationLayout.tsx
PR fixes the typo in Org layout
```sh
```
---
=> fix: resolved typo in layout

frontend/src/pages/secret-manager/integrations/AwsSecretManagerConfigurePage/AwsSecretManagerConfigurePage.tsx, frontend/src/pages/secret-manager/integrations/AzureAppConfigurationConfigurePage/AzureAppConfigurationConfigurePage.tsx, frontend/src/pages/secret-manager/integrations/CircleCIConfigurePage/CircleCIConfigurePage.tsx
This ensures that only the folders in the selected environment gets displayed and suggested in the secret path input field
```sh
```
---
=> misc: made secret path input show correct folders

frontend/src/const/routes.ts, frontend/src/pages/secret-manager/IntegrationsListPage/IntegrationsListPage.utils.tsx, frontend/src/pages/secret-manager/integrations/AzureKeyVaultAuthorizePage/AzureKeyVaultAuthorizePage.tsx, frontend/src/pages/secret-manager/integrations/AzureKeyVaultAuthorizePage/route.tsx, frontend/src/routeTree.gen.ts, frontend/src/routes.ts
This change was overriden by the migration to react barebones PR. 
Original PR here:
https://github.com/Infisical/infisical/pull/2922
```sh
```
---
=> feat: target specific azure key vault tenant

docs/documentation/platform/pr-workflows.mdx
Add note Approval Workflows as paid feature
---
=> docs: add note Approval Workflows as paid feature

docs/documentation/platform/dynamic-secrets/overview.mdx
Add note for dynamic secrets as paid feature
---
=> docs: add note for dynamic secrets as paid feature

backend/src/ee/routes/v1/saml-router.ts
PR improves saml message clarity when the email or first name is not retrievable.
```sh
```
---
=> Updated saml error message

frontend/src/pages/organization/AccessManagementPage/components/OrgGroupsTab/components/OrgGroupsSection/OrgGroupsSection.tsx, frontend/src/pages/project/AccessControlPage/components/GroupsTab/components/GroupsSection/GroupsSection.tsx
This PR improves the User Groups upgrade modal text to specify enterprise license requirement.
```sh
```
---
=> Improvement: Clarify Enterprise Plan for User Group Feature Upgrade Modal

backend/src/server/plugins/serve-ui.ts, frontend/src/pages/secret-manager/integrations/GitlabAuthorizePage/GitlabAuthorizePage.tsx, frontend/src/pages/secret-manager/integrations/GitlabConfigurePage/GitlabConfigurePage.tsx
- Resolved broken gitlab image
- Removed standalone endpoints from api doc
```sh
```
---
=> Fixed broke image

backend/src/ee/services/license/license-service.ts
This PR changes the org plan fetch from checking billing permission to just checking the user is part of organization. Any user part of organization should be able to fetch the plan. Then only we can hide the UI as needed and show notifications for license requirements
```sh
```
---
=> feat: resolved app not loading on org no access

frontend/src/pages/auth/LoginPage/components/InitialStep/InitialStep.tsx, frontend/src/pages/organization/AppConnections/GithubOauthCallbackPage/route.tsx, frontend/src/pages/project/AccessControlPage/components/ProjectRoleListTab/components/ProjectRoleList/ProjectRoleList.tsx, frontend/src/pages/secret-manager/integrations/AzureAppConfigurationOauthCallbackPage/route.tsx, frontend/src/pages/secret-manager/integrations/AzureKeyVaultOauthCallbackPage/route.tsx, frontend/src/pages/secret-manager/integrations/BitbucketOauthCallbackPage/route.tsx, frontend/src/pages/secret-manager/integrations/GcpSecretManagerOauthCallbackPage/route.tsx, frontend/src/pages/secret-manager/integrations/GithubOauthCallbackPage/route.tsx, frontend/src/pages/secret-manager/integrations/GitlabOauthCallbackPage/route.tsx, frontend/src/pages/secret-manager/integrations/HerokuOauthCallbackPage/route.tsx, frontend/src/pages/secret-manager/integrations/NetlifyOauthCallbackPage/route.tsx, frontend/src/pages/secret-manager/integrations/VercelOauthCallbackPage/route.tsx
This PR fixes login SSO redirect and project role creation
```sh
```
---
=> fix: address sso redirect and project role creation

docs/changelog/overview.mdx
First try at updating the Changelog from these past months.
Let me know if you think of anything I might have forgotten.
- [ x] Documentation
---
- [x ] I have read the [contributing guide](https://infisical.com/docs/contributing/getting-started/overview), agreed and acknowledged the [code of conduct](https://infisical.com/docs/contributing/getting-started/code-of-conduct). 📝
=> Doc: Update Nov & Dec Changelogs

backend/src/services/integration-auth/integration-sync-secret.ts, frontend/src/pages/secret-manager/integrations/GitlabConfigurePage/GitlabConfigurePage.tsx
This PR will add support for configuring initial sync behavior for GitLab secret sync integration. This PR also addresses issue where creating GitLab integration does not succeed when `protected` flag is not set
```sh
```
---
=> feat: add initial sync behavior for gitlab

backend/src/server/routes/v3/secret-router.ts, frontend/src/pages/secret-manager/OverviewPage/OverviewPage.tsx
=> feat: added validation for secret name to disallow spaces and overview page 

cli/packages/cmd/run.go
This PR ensures that the CLI run command with the `--watch` flag does not hang indefinitely when API errors occur
```sh
```
---
=> fix: address infinite hang when infisical run watch fails

backend/src/services/integration-auth/integration-team.ts
This ensures that all the groups are fetched for configuring GitLab integration
```sh
```
---
=> misc: add pagination handling for gitlab groups fetch

backend/src/ee/services/dynamic-secret/providers/sql-database.ts, backend/src/ee/services/secret-rotation/secret-rotation-queue/secret-rotation-queue.ts
This PR fixes mssql secret rotation and dynamic secret failing because of self signed cert failing
```sh
```
---
=> Resolve self signed error for mssql

backend/src/services/integration-auth/integration-sync-secret.ts, backend/src/services/secret/secret-queue.ts
This PR adds secret key indicator for AWS secret manager integration errors
```sh
```
---
=> misc: add secret key indicator for failed AWS integration syncs

backend/src/server/routes/v1/integration-router.ts
- This ensures that `isActive` can be left omitted if the intention is to make no changes
Relevant API changes:
https://github.com/Infisical/infisical/pull/2957
```sh
```
---
=> misc: made is active optional for integration patch

docs/integrations/platforms/kubernetes/infisical-dynamic-secret-crd.mdx, docs/integrations/platforms/kubernetes/infisical-push-secret-crd.mdx, docs/integrations/platforms/kubernetes/infisical-secret-crd.mdx
This PR adds smaller improvements to the existing K8s documentation
---
=> docs: small k8s docs improvements

backend/src/ee/services/external-kms/external-kms-service.ts
This PR ensures that errors thrown by AWS is properly propagated to the frontend for improved user feedback
```sh
```
---
=> misc: added error propagation for aws kms

backend/src/services/integration-auth/integration-sync-secret.ts, frontend/src/pages/secret-manager/integrations/CloudflarePagesConfigurePage/CloudflarePagesConfigurePage.tsx
This PR ensures that error 304s for the redeploy process will be treated as a successful sync attempt. This also ensures that the auto redeploy option only applies for production syncs as per the documentation [here](https://developers.cloudflare.com/api/resources/pages/subresources/projects/subresources/deployments/methods/create/)
```sh
```
---
=> fix: addressed cloudflare pages error 304

backend/src/server/routes/index.ts, backend/src/services/super-admin/super-admin-service.ts
This will fix instance allowed login settings for when user only has SAML/OIDC
```sh
```
---
=> misc: add oidc saml handling for login SA check

backend/src/server/routes/v1/invite-org-router.ts, backend/src/services/org/org-service.ts, backend/src/services/org/org-types.ts, frontend/src/hooks/api/users/mutation.tsx, frontend/src/pages/organization/AccessManagementPage/components/OrgMembersTab/components/OrgMembersSection/OrgMembersTable.tsx, frontend/src/pages/organization/UserDetailsByIDPage/components/UserDetailsSection.tsx
This PR fixes the org invite resend feature.
```sh
```
---
=> fix: address org invite resend issues

backend/src/services/integration-auth/integration-sync-secret.ts
This PR appends the secret key name to the error message when an AWS Parameter Store Integration fails to update/create a secret on sync.
```sh
```
---
=> Improvement: Add Secret Key to AWS Parameter Store Integreation Sync Error

frontend/src/pages/secret-manager/OverviewPage/components/SecretOverviewTableRow/SecretOverviewTableRow.tsx
This PR fixes the secret overview expanded secret overflow handling to accommodate the nav restructure.
```sh
```
---
=> Fix: Adjust Secret Overview Expanded Secret View

backend/src/db/migrations/20250116092245_add-enforce-capitalization-project-flag.ts, backend/src/db/schemas/projects.ts, backend/src/ee/services/secret-approval-request/secret-approval-request-service.ts, backend/src/services/project/project-service.ts, backend/src/services/secret/secret-service.ts, frontend/public/locales/en/translations.json, frontend/public/locales/es/translations.json, frontend/public/locales/pt-BR/translations.json, frontend/src/pages/secret-manager/OverviewPage/components/CreateSecretForm/CreateSecretForm.tsx, frontend/src/pages/secret-manager/SecretDashboardPage/components/CreateSecretForm/CreateSecretForm.tsx, frontend/src/pages/secret-manager/SettingsPage/components/AutoCapitalizationSection/AutoCapitalizationSection.tsx
This PR modifies the concept of project `auto-capitalization` to be `enforce capitalization`. This PR ensures that capitalization enforcement is `false` by default and is "opt-in"
```sh
```
---
=> misc: added handling of secret case enforcement

backend/src/ee/services/audit-log-stream/audit-log-stream-service.ts, frontend/src/pages/organization/SettingsPage/components/AuditLogStreamTab/AuditLogStreamForm.tsx
This PR updates the failure message on audit log stream setup to display in the UI correctly
```sh
```
---
=> Improvement: Propagate Upstream Error on Audit Log Stream Setup Fail

backend/src/ee/services/ldap-config/ldap-config-service.ts, backend/src/ee/services/saml-config/saml-config-service.ts
This PR removes Enterprise Member and Identity Limits for SAML/LDAP Login
---
=> Remove Enterprise Member and Identity Limits for SAML/LDAP Login

frontend/src/layouts/OrganizationLayout/OrganizationLayout.tsx
This PR corrects the check of when to display the org sidebar
```sh
```
---
=> Fix: Correct Display Org Sidebar Check

frontend/src/components/v2/FormControl/FormControl.tsx, frontend/src/pages/secret-manager/integrations/VercelConfigurePage/VercelConfigurePage.tsx
This PR adds helper text to the Vercel integration form to help point users to their access permissions for Infisical if they don't see the Vercel project they are looking for.
```sh
```
---
=> Improvement: Vercel Integration Project Permission Helper Text

frontend/src/layouts/OrganizationLayout/components/MinimizedOrgSidebar/MinimizedOrgSidebar.tsx
This PR fixes `Pro trail` button overflow issue in sidebar
```sh
```
---
=> fix: resolved pro trial button issue in sidebar

frontend/src/pages/organization/SecretManagerOverviewPage/SecretManagerOverviewPage.tsx
This PR fixes project list/grid view pagination which was not updating page size or page when changed.
```sh
```
---
=> Fix: Project List/Grid Pagination Behavior

docs/documentation/guides/python.mdx, docs/documentation/platform/sso/azure.mdx
I've updated the Python guide to use the latest native Python SDK. This should help reduce confusion between the different SDK's.
**Minor**
I also fixed a typo in the Entra ID SSO documentation.
---
=> docs(guides): updated python guide

docs/documentation/platform/access-controls/role-based-access-controls.mdx
Removed the word 'male,' which was a typo, and replaced it with 'make.'
Fixes #3037 
```sh
```
---
=> Fixed the typo in the Role-based Access Controls docs.

helm-charts/secrets-operator/Chart.yaml, helm-charts/secrets-operator/values.yaml, k8-operator/controllers/infisicalsecret/conditions.go
This PR adds better error status's to help users better understand the origin of errors.
---
=> feat(k8-operator): better error status

docs/mint.json, docs/self-hosting/reference-architectures/on-prem-k8s-ha.mdx
A complete guide to k8s HA reference docs
=> K8s HA reference docs

docs/mint.json, frontend/src/pages/secret-manager/integrations/AzureDevopsAuthorizePage/AzureDevopsAuthorizePage.tsx, frontend/src/pages/secret-manager/integrations/AzureDevopsConfigurePage/AzureDevopsConfigurePage.tsx, frontend/src/pages/secret-manager/integrations/AzureKeyVaultAuthorizePage/AzureKeyVaultAuthorizePage.tsx
This PR changes the order of the integration docs navigation bar to list app connections and secret syncs beneath infrastructure integrations. In addition, azure integrations with incorrect logo image references have been corrected.
```sh
```
---
=> Improvements: Integration Docs Nav Bar Reorder & Azure Integration Logo fix

docs/integrations/secret-syncs/aws-parameter-store.mdx, docs/integrations/secret-syncs/gcp-secret-manager.mdx, frontend/src/components/secret-syncs/SecretSyncImportSecretsModal.tsx, frontend/src/helpers/secretSyncs.ts, frontend/src/pages/secret-manager/IntegrationsListPage/components/FrameworkIntegrationTab/FrameworkIntegrationTab.tsx, frontend/src/pages/secret-manager/IntegrationsListPage/components/InfrastructureIntegrationTab/InfrastructureIntegrationTab.tsx
This PR contains textual improvements to clarify secret sync import behavior and minor integration layout improvements.
```sh
```
---
=> improvements: Import Behavior Doc/UI Clarification and Minor Integration Layout Adjustments

cli/packages/cmd/secrets.go
This PR fixes the plain output in list mode in cli
```sh
```
---
=> Resolved list secret plain to have key as well

docs/cli/overview.mdx
=> Fix grammar on overview.mdx

helm-charts/secrets-operator/Chart.yaml, helm-charts/secrets-operator/templates/infisicalsecret-crd.yaml
- This PR undos the removal of a helm installation flag in the secret CRD template
```sh
```
---
=> misc: readded operator installation flag for secret CRD

docs/documentation/platform/sso/keycloak-oidc/overview.mdx
This PR removes relative paths for OIDC overview docs to fix broken images
```sh
```
---
=> Fix: Remove Relative Paths for ODIC Overview Docs

backend/src/server/routes/sanitizedSchemas.ts
This PR removes unused and outdated metadata field in secrets
```sh
```
---
=> misc: removed outdated metadata field

backend/src/db/migrations/20250205045509_increase-gcp-auth-limit.ts, backend/src/db/schemas/identity-gcp-auths.ts, backend/src/ee/services/audit-log/audit-log-types.ts
This PR increases identity gcp auth text limits for gcp configuration inputs
```sh
```
---
=> feat: increased identity gcp auth cred limit from 255 to respective limits

backend/src/ee/services/audit-log/audit-log-types.ts, backend/src/server/routes/v3/secret-router.ts, backend/src/services/secret-v2-bridge/secret-v2-bridge-service.ts, backend/src/services/secret/secret-service.ts, frontend/src/hooks/api/auditLogs/constants.tsx, frontend/src/hooks/api/auditLogs/enums.tsx
This PR adds secret metadata to audit logs for the following events:
- get secret
- create secret (if present in payload)
- update secret (if present in payload)
- batch create secrets (if present in payload)
- batch update secrets (if present in payload)
Also adds missing batch secret update/create audit log label and fixes batch update secret error message.
```sh
```
---
=> Improvement: Include Secret Metadata in Audit Logs

backend/package.json
Reverts Infisical/infisical#3102
=> Revert "Feat/enc migration"

backend/package.json
Reverts Infisical/infisical#3103
=> Revert "Revert "Feat/enc migration""

frontend/src/pages/secret-manager/IntegrationsDetailsByIDPage/IntegrationsDetailsByIDPage.tsx
This PR adds support for deleting secrets from within the integrations details page. We already had a button for this, but it had no functionality. This PR simply adds functionality to the existing button.
---
=> fix(native-integrations): delete integrations from details page

docs/self-hosting/configuration/requirements.mdx
Updated hardware for infisical to highlight compute per instance/container
=> Update hardware for infisical

docs/documentation/setup/networking.mdx, docs/mint.json
This PR adds a section in our docs for documenting egress IPs of Infisical Cloud
```sh
```
---
=> doc: added section for egress ips

backend/package-lock.json, backend/package.json
Reverts Infisical/infisical#3244
=> Revert "Address SAML CVE"

backend/src/db/migrations/20250212191958_create-gateway.ts
PR to fix correction in gateway migration table check
```sh
```
---
=> fix: corrected table name check in migration

.gitignore, cli/packages/api/model.go, cli/packages/cmd/run.go, cli/packages/util/secrets.go, cli/test/secrets_test.go, flake.nix
Reverts Infisical/infisical#3238
=> Revert "feat: confirm environment exists when running `run` command"

backend/src/ee/services/license/license-service.ts
=> feat: added log and updated license ttl to 5min

backend/src/services/identity-kubernetes-auth/identity-kubernetes-auth-service.ts
=> feat: added k8s abort

backend/src/lib/config/env.ts, backend/src/queue/queue-service.ts
=> misc: add flag for disabling workers

backend/src/server/plugins/secret-scanner.ts, backend/src/server/plugins/serve-ui.ts, backend/src/services/identity-ua/identity-ua-service.ts
=> feat: return fastify res and making it async

frontend/src/main.tsx
=> feat: removed refresh

frontend/vite.config.ts
Reverts Infisical/infisical#3306
=> Revert "Added vite base path option"

backend/src/services/org-admin/org-admin-service.ts
=> added check for org in project id

.github/workflows/release_build_infisical_cli.yml
=> feat: updated ruby action

backend/src/db/migrations/20250402000941_add-type-to-kms-keys.ts, backend/src/services/kms/kms-service.ts
Improvement to the recent KMS key migration for adding a new keyUsage column. It now properly checks if the table is present on down migrate, and properly checks for the correct field.
---
=> fix: improve kms key migration

docs/mint.json, docs/sdks/languages/csharp.mdx, docs/sdks/languages/ruby.mdx
Removed documentation for legacy SDK's.
---
=> fix: removed legacy sdk's

docs/integrations/platforms/kubernetes/infisical-push-secret-crd.mdx
Improved the existing documentation for the new k8's generator support we recently introduced. This is mostly layout changes to make the documentation more inline with existing docs.
---
=> docs(k8s/generators): improve documentation

backend/src/db/migrations/20250429232917_store-cert-secret-key-and-chain.ts
=> small migration fix

backend/package-lock.json, backend/package.json, backend/src/server/plugins/fastify-zod.ts, docs/mint.json
Support openapi titles for zod description
=> feat(docs): Support OpenAPI titles for Zod descriptions

frontend/src/pages/organization/SettingsPage/components/OrgDeleteSection/OrgDeleteSection.tsx
- This PR brings user to the login screen upon deletion of organization
```sh
```
---
=> misc: updated org delete flow to clear session

backend/src/server/plugins/serve-ui.ts
A cache fix for ui bundle deployment skew
```sh
```
---
=> feat: added new cache control for index html

frontend/src/hooks/api/roles/types.ts, frontend/src/pages/project/RoleDetailsBySlugPage/components/ProjectRoleModifySection.utils.tsx, frontend/src/pages/project/RoleDetailsBySlugPage/components/RoleModal.tsx
Fixed project roles not being editable in some cases
=> Fixed project roles not being editable in some cases

docs/mint.json, docs/self-hosting/deployment-options/linux-upgrade.mdx
=> add linux upgrade docs

backend/src/ee/services/permission/default-roles.ts, frontend/src/pages/organization/AccessManagementPage/components/OrgRoleTabSection/OrgRoleTable.tsx, frontend/src/pages/organization/RoleByIDPage/RoleByIDPage.tsx, frontend/src/pages/organization/RoleByIDPage/components/DuplicateOrgRoleModal.tsx, frontend/src/pages/organization/RoleByIDPage/components/RoleModal.tsx, frontend/src/pages/project/AccessControlPage/components/ProjectRoleListTab/components/ProjectRoleList/ProjectRoleList.tsx, frontend/src/pages/project/RoleDetailsBySlugPage/RoleDetailsBySlugPage.tsx, frontend/src/pages/project/RoleDetailsBySlugPage/components/DuplicateProjectRoleModal.tsx, frontend/src/pages/project/RoleDetailsBySlugPage/components/DuplicateRoleModal.tsx, frontend/src/pages/project/RoleDetailsBySlugPage/components/RoleModal.tsx
This PR adds the ability to duplicate organization and project roles.
This PR also removes deprecated read permission from default project roles
```sh
```
---
=> feature(project/org-roles): Add ability to duplicate org and project roles

docs/documentation/platform/sso/general-oidc/group-membership-mapping.mdx, docs/documentation/platform/sso/general-oidc/overview.mdx, docs/mint.json
This PR adds general OIDC group membership mapping documentation
```sh
```
---
=> docs(oidc-group-membership-mapping): Add general OIDC group membership mapping documentation

backend/src/services/identity-oci-auth/identity-oci-auth-service.ts
=> fix oci machine identity

backend/src/server/routes/v1/project-router.ts
- add support for identities to update project audit log retention
```sh
```
---
=> misc: add identity support for audit log retention

docs/integrations/secret-syncs/overview.mdx
=> feat(docs): Key Schema Tweaks

backend/src/db/migrations/20250516021501_toggle-secret-sharing-on-project.ts, backend/src/db/schemas/projects.ts, backend/src/lib/api-docs/constants.ts, backend/src/server/routes/sanitizedSchemas.ts, backend/src/server/routes/v1/project-router.ts, backend/src/services/project/project-service.ts, backend/src/services/project/project-types.ts, frontend/src/hooks/api/workspace/queries.tsx, frontend/src/hooks/api/workspace/types.ts, frontend/src/pages/secret-manager/SecretDashboardPage/components/SecretListView/SecretDetailSidebar.tsx, frontend/src/pages/secret-manager/SecretDashboardPage/components/SecretListView/SecretItem.tsx, frontend/src/pages/secret-manager/SettingsPage/components/ProjectGeneralTab/ProjectGeneralTab.tsx, frontend/src/pages/secret-manager/SettingsPage/components/SecretSharingSection/SecretSharingSection.tsx, frontend/src/pages/secret-manager/SettingsPage/components/SecretSharingSection/index.tsx
Enable / Disable Secret Sharing UI at the project level
=> feat(project): Enable / Disable Secret Sharing

frontend/src/pages/organization/SettingsPage/components/OrgProductSelectSection/OrgProductSelectSection.tsx
=> Org Products Padding Fix

backend/src/server/routes/v1/certificate-router.ts, backend/src/services/certificate/certificate-fns.ts, backend/src/services/certificate/certificate-service.ts, frontend/src/hooks/api/certificates/queries.tsx, frontend/src/pages/cert-manager/CertificatesPage/components/CertificateCertModal.tsx, frontend/src/pages/organization/SettingsPage/components/OrgProductSelectSection/OrgProductSelectSection.tsx, frontend/src/pages/secret-manager/SettingsPage/components/ProjectGeneralTab/ProjectGeneralTab.tsx, frontend/src/pages/secret-manager/SettingsPage/components/SecretSharingSection/SecretSharingSection.tsx
Fix bundle endpoint for old certs by making private key nullable. Also updates the built CA chain function.
=> fix bundle endpoint for old certs

frontend/src/pages/secret-manager/SecretDashboardPage/components/SecretListView/SecretDetailSidebar.tsx
fix secret rollback not tainting form
=> fix secret rollback not tainting form

backend/src/server/routes/v1/identity-kubernetes-auth-router.ts, backend/src/services/project/project-service.ts
We created breaking change by not allowing hyphens which were once allowed. Adding it back
=> Allow Hyphens in k8s 

docs/integrations/platforms/kubernetes-csi.mdx, docs/integrations/platforms/kubernetes-injector.mdx, docs/mint.json
Documentation for the new k8s agent injector. The full repository can be found [here](https://github.com/Infisical/infisical-agent-injector)
---
=> docs: k8s agent injector

backend/src/ee/services/license/license-fns.ts, backend/src/ee/services/license/license-service.ts, backend/src/services/org/org-dal.ts, frontend/src/pages/organization/BillingPage/components/BillingCloudTab/CurrentPlanSection.tsx
Fixes in Infisical cloud due to bugs and license server changes
1. None of the on prem endpoints are modified in here
2. Fixed invalid redirect from stripe
3. Made billing more clear
```sh
```
---
=> Feat: license server changes

backend/src/ee/services/access-approval-policy/access-approval-policy-service.ts, backend/src/ee/services/permission/default-roles.ts, backend/src/ee/services/permission/project-permission.ts, backend/src/ee/services/secret-approval-policy/secret-approval-policy-service.ts, backend/src/ee/services/secret-approval-request/secret-approval-request-service.ts, backend/src/services/certificate/certificate-service.ts, docs/internals/permissions/project-permissions.mdx, frontend/src/context/ProjectPermissionContext/index.tsx, frontend/src/context/ProjectPermissionContext/types.ts, frontend/src/context/index.tsx, frontend/src/pages/project/RoleDetailsBySlugPage/components/ProjectRoleModifySection.utils.tsx, frontend/src/pages/secret-manager/SecretApprovalsPage/components/ApprovalPolicyList/ApprovalPolicyList.tsx, frontend/src/pages/secret-manager/SecretApprovalsPage/components/ApprovalPolicyList/components/AccessPolicyModal.tsx, frontend/src/pages/secret-manager/SecretApprovalsPage/components/ApprovalPolicyList/components/ApprovalPolicyRow.tsx, frontend/src/pages/secret-manager/SecretApprovalsPage/components/SecretApprovalRequest/components/SecretApprovalRequestAction.tsx
Specific permission for bypassing policy + small policy modal UI change
=> feat(policies): Specific permission for bypassing policy

frontend/src/pages/auth/SelectOrgPage/SelectOrgSection.tsx
This PR adds proper error messages for login bypass failures
```sh
```
---
=> misc: add proper error message for bypass failure

backend/src/@types/fastify.d.ts, backend/src/lib/logger/logger.ts, backend/src/server/plugins/auth/inject-identity.ts
Add org id to requests
```sh
```
---
=> feat: org id logger

backend/src/ee/services/license/license-service.ts
Resolved cloud missing member used and identity used in getPlan
```sh
```
---
=> feat: added missing memberused, identityused in getplan for cloud

docs/cli/usage.mdx
=> Fix CLI custom headers doc tip

backend/src/ee/services/license/license-fns.ts, backend/src/ee/services/license/license-service.ts, backend/src/lib/config/env.ts
Implemented env and license server configuration to have cloud region internal environment variable
```sh
```
---
=> feat: added region flag

backend/src/ee/services/oidc/oidc-config-service.ts
Added helpful logs to debug what the struct of oidc claim is for user
=> add oidc logs

backend/src/services/secret-sync/aws-secrets-manager/aws-secrets-manager-sync-fns.ts
This PR updates the secret manager sync functions to handle constrained IAM policies
```sh
```
---
=> Fix: Update aws secret manager sync to handle constrained iam policies

backend/src/lib/config/env.ts, backend/src/services/folder-commit/folder-commit-service.ts
=> PIT: fix checkpoint creation to do it in batches to avoid insert fails

backend/src/lib/config/env.ts, backend/src/services/folder-commit/folder-commit-service.ts
Reverts Infisical/infisical#3671
=> Revert "PIT: fix checkpoint creation to do it in batches to avoid insert fails"

backend/src/services/certificate-authority/certificate-authority-service.ts, backend/src/services/certificate-authority/internal/internal-certificate-authority-schemas.ts, backend/src/services/pki-subscriber/pki-subscriber-service.ts, frontend/src/hooks/api/ca/mutations.tsx, frontend/src/pages/cert-manager/CertificateAuthoritiesPage/components/CaModal.tsx
=> misc: general improvements

backend/src/ee/services/license/license-service.ts, backend/src/ee/services/permission/org-permission.ts, docs/internals/permissions/organization-permissions.mdx, frontend/src/context/OrgPermissionContext/index.tsx, frontend/src/context/OrgPermissionContext/types.ts, frontend/src/context/index.tsx, frontend/src/pages/organization/BillingPage/BillingPage.tsx, frontend/src/pages/organization/BillingPage/components/BillingCloudTab/PreviewSection.tsx, frontend/src/pages/organization/BillingPage/components/BillingDetailsTab/CompanyNameSection.tsx, frontend/src/pages/organization/BillingPage/components/BillingDetailsTab/InvoiceEmailSection.tsx, frontend/src/pages/organization/BillingPage/components/BillingDetailsTab/PmtMethodsSection.tsx, frontend/src/pages/organization/BillingPage/components/BillingDetailsTab/PmtMethodsTable.tsx, frontend/src/pages/organization/BillingPage/components/BillingDetailsTab/TaxIDSection.tsx, frontend/src/pages/organization/BillingPage/components/BillingDetailsTab/TaxIDTable.tsx, frontend/src/pages/organization/BillingPage/components/BillingTabGroup/BillingTabGroup.tsx, frontend/src/pages/organization/RoleByIDPage/components/OrgRoleModifySection.utils.ts, frontend/src/pages/organization/RoleByIDPage/components/RolePermissionsSection/OrgPermissionBillingRow.tsx, frontend/src/pages/organization/RoleByIDPage/components/RolePermissionsSection/RolePermissionRow.tsx, frontend/src/pages/organization/RoleByIDPage/components/RolePermissionsSection/RolePermissionsSection.tsx
Removed the old crud permissions and replaced with read + managed (read already exists). Manage will allow you to update, delete and create relevant resources.
=> add manage permission for billing

frontend/src/pages/secret-manager/SecretApprovalsPage/components/ApprovalPolicyList/components/AccessPolicyModal.tsx
=> New policy warning UI

docs/documentation/platform/kms/hsm-integration.mdx
Removed the FIPS section from the HSM documentation for the time being
---
=> docs: remove fips section

backend/src/services/identity-project/identity-project-dal.ts, backend/src/services/project-membership/project-membership-dal.ts
PR to make the role list in detail view of identity and user membership detail 
```sh
```
---
=> feat: added sort for roles in both user and identity details view

frontend/src/hooks/api/reactQuery.tsx, frontend/src/pages/secret-manager/SecretDashboardPage/components/ActionBar/CreateDynamicSecretForm/CassandraInputForm.tsx, frontend/src/pages/secret-manager/SecretDashboardPage/components/ActionBar/CreateDynamicSecretForm/ElasticSearchInputForm.tsx, frontend/src/pages/secret-manager/SecretDashboardPage/components/ActionBar/CreateDynamicSecretForm/KubernetesInputForm.tsx, frontend/src/pages/secret-manager/SecretDashboardPage/components/ActionBar/CreateDynamicSecretForm/LdapInputForm.tsx, frontend/src/pages/secret-manager/SecretDashboardPage/components/ActionBar/CreateDynamicSecretForm/MongoAtlasInputForm.tsx, frontend/src/pages/secret-manager/SecretDashboardPage/components/ActionBar/CreateDynamicSecretForm/MongoDBInputForm.tsx, frontend/src/pages/secret-manager/SecretDashboardPage/components/ActionBar/CreateDynamicSecretForm/RabbitMqInputForm.tsx, frontend/src/pages/secret-manager/SecretDashboardPage/components/ActionBar/CreateDynamicSecretForm/RedisInputForm.tsx, frontend/src/pages/secret-manager/SecretDashboardPage/components/ActionBar/CreateDynamicSecretForm/SapAseInputForm.tsx, frontend/src/pages/secret-manager/SecretDashboardPage/components/ActionBar/CreateDynamicSecretForm/SapHanaInputForm.tsx, frontend/src/pages/secret-manager/SecretDashboardPage/components/ActionBar/CreateDynamicSecretForm/SnowflakeInputForm.tsx, frontend/src/pages/secret-manager/SecretDashboardPage/components/ActionBar/CreateDynamicSecretForm/SqlDatabaseInputForm.tsx, frontend/src/pages/secret-manager/SecretDashboardPage/components/ActionBar/CreateDynamicSecretForm/TotpInputForm.tsx, frontend/src/pages/secret-manager/SecretDashboardPage/components/DynamicSecretListView/EditDynamicSecretForm/EditDynamicSecretAwsElastiCacheProviderForm.tsx, frontend/src/pages/secret-manager/SecretDashboardPage/components/DynamicSecretListView/EditDynamicSecretForm/EditDynamicSecretAwsIamForm.tsx, frontend/src/pages/secret-manager/SecretDashboardPage/components/DynamicSecretListView/EditDynamicSecretForm/EditDynamicSecretAzureEntraIdForm.tsx, frontend/src/pages/secret-manager/SecretDashboardPage/components/DynamicSecretListView/EditDynamicSecretForm/EditDynamicSecretCassandraForm.tsx, frontend/src/pages/secret-manager/SecretDashboardPage/components/DynamicSecretListView/EditDynamicSecretForm/EditDynamicSecretElasticSearchForm.tsx, frontend/src/pages/secret-manager/SecretDashboardPage/components/DynamicSecretListView/EditDynamicSecretForm/EditDynamicSecretKubernetesForm.tsx, frontend/src/pages/secret-manager/SecretDashboardPage/components/DynamicSecretListView/EditDynamicSecretForm/EditDynamicSecretLdapForm.tsx, frontend/src/pages/secret-manager/SecretDashboardPage/components/DynamicSecretListView/EditDynamicSecretForm/EditDynamicSecretMongoAtlasForm.tsx, frontend/src/pages/secret-manager/SecretDashboardPage/components/DynamicSecretListView/EditDynamicSecretForm/EditDynamicSecretMongoDBForm.tsx, frontend/src/pages/secret-manager/SecretDashboardPage/components/DynamicSecretListView/EditDynamicSecretForm/EditDynamicSecretRabbitMqForm.tsx, frontend/src/pages/secret-manager/SecretDashboardPage/components/DynamicSecretListView/EditDynamicSecretForm/EditDynamicSecretRedisProviderForm.tsx, frontend/src/pages/secret-manager/SecretDashboardPage/components/DynamicSecretListView/EditDynamicSecretForm/EditDynamicSecretSapAseForm.tsx, frontend/src/pages/secret-manager/SecretDashboardPage/components/DynamicSecretListView/EditDynamicSecretForm/EditDynamicSecretSapHanaForm.tsx, frontend/src/pages/secret-manager/SecretDashboardPage/components/DynamicSecretListView/EditDynamicSecretForm/EditDynamicSecretSnowflakeForm.tsx, frontend/src/pages/secret-manager/SecretDashboardPage/components/DynamicSecretListView/EditDynamicSecretForm/EditDynamicSecretSqlProviderForm.tsx, frontend/src/pages/secret-manager/SecretDashboardPage/components/DynamicSecretListView/EditDynamicSecretForm/EditDynamicSecretTotpForm.tsx
This PR updates the handling of validation errors for dynamic secrets so that it shows the validation details right away in unhandled cases. This PR also properly adds the form validation rules for the dynamic secret name. 
```sh
```
---
=> misc: update dynamic secret validation error handling

frontend/src/pages/organization/SecretSharingSettingsPage/components/OrgSecretShareLimitSection/OrgSecretShareLimitSection.tsx, frontend/src/pages/public/ShareSecretPage/components/ShareSecretForm.tsx
This PR enables free max view limit number entry instead of only supporting 1 or unlimited
```sh
```
---
=> Improvement(secret-sharing): Allow free number entry for max views in secret sharing

docs/documentation/platform/identities/oidc-auth/spire.mdx, docs/mint.json
This PR adds setup docs for SPIFFE/SPIRE integration with OIDC auth
```sh
```
---
=> doc: add oidc auth doc for spire

frontend/src/pages/organization/AccessManagementPage/components/OrgMembersTab/components/OrgMembersSection/OrgMembersTable.tsx
This PR adds client-side filtering by role to the org users table 
```sh
```
---
=> improvement(org-users-table): Add filter by roles to org users table

frontend/src/lib/fn/string.ts, frontend/src/pages/secret-manager/SecretApprovalsPage/components/SecretApprovalRequest/SecretApprovalRequest.tsx, frontend/src/pages/secret-manager/SecretApprovalsPage/components/SecretApprovalRequest/components/SecretApprovalRequestChangeItem.tsx, frontend/src/pages/secret-manager/SecretApprovalsPage/components/SecretApprovalRequest/components/SecretApprovalRequestChanges.tsx
Improve messaging in secret change when approval request is created via replicated import 
```sh
```
---
=> feat: updated ui for replication approval

backend/src/server/routes/v1/invite-org-router.ts, backend/src/server/routes/v1/password-router.ts, backend/src/server/routes/v2/user-router.ts, backend/src/server/routes/v3/signup-router.ts
This PR improves smtp rate limits by trimming and substringing their key to dampen redis load and defaults to realIp if parameter is not present in pre-validation
```sh
```
---
=> improvement(smtp-rate-limit): trim and substring keys and default to realIp

backend/src/keystore/keystore.ts, backend/src/services/project/project-service.ts
This PR adds a lock to project create to check plan
```sh
```
---
=> feat: added lock for project create

backend/src/services/org/org-service.ts, backend/src/services/user/user-dal.ts
=> Fix for inviteUserToOrganization for usernames with no email formats

backend/src/services/user/user-service.ts
This PR re-adds the merge user logic which was removed in the following PR 
https://github.com/Infisical/infisical/pull/3518
```sh
```
---
=> fix: re-added merge user logic

backend/src/ee/services/audit-log/audit-log-types.ts, backend/src/services/secret/secret-queue.ts, backend/src/services/webhook/webhook-fns.ts, docs/documentation/platform/audit-log-streams/audit-log-streams.mdx, docs/documentation/platform/webhooks.mdx, frontend/src/hooks/api/auditLogs/constants.tsx, frontend/src/hooks/api/auditLogs/enums.tsx, frontend/src/hooks/api/auditLogs/types.tsx, frontend/src/pages/secret-manager/SettingsPage/components/WebhooksTab/WebhooksTab.tsx
This PR adds webhook trigger audit logs to keep a record of webhook events. Small doc typo fix included.
```sh
```
---
=> improvement(project-webhooks): Add webhook triggered audit log

backend/src/services/folder-commit-changes/folder-commit-changes-dal.ts
=> feat(pit): improve commit changes condition as some old versions can be zero

backend/src/ee/services/secret-approval-request/secret-approval-request-service.ts
=> feat(secret-request): hide secret value on missing secret read permission

backend/src/ee/services/secret-rotation-v2/azure-client-secret/azure-client-secret-rotation-fns.ts
Fix Azure Client Secrets to check if the client secret has been manually deleted to avoid blocking the process
```sh
```
---
=> feat(secret-rotation): Azure Client Secrets manually deleted client secrets check

docs/integrations/frameworks/packer.mdx, docs/mint.json
Added docs for the new Packer Plugin and re-organized the integrations to be alphabetical.
=> feat(docs): Packer Plugin Docs

docs/documentation/platform/sso/auth0-saml.mdx
Small tip to avoid blockers due to incorrect mappings on Auth0 SAML
```sh
```
---
=> fix(docs): add a tip on Auth0 SAML doc tip

frontend/public/locales/en/translations.json
Update wording for service tokens
=> Update wording for service tokens

docs/documentation/platform/sso/auth0-saml.mdx
=> fix(docs): replace tip to warning on Auth0 Auth

backend/src/services/identity/identity-org-dal.ts
=> Add left join

frontend/src/components/secret-syncs/forms/SecretSyncDestinationFields/VercelSyncFields.tsx
Allow users to input custom branch names as Vercel only send a max of 100 with no pagination available
```sh
```
---
=> fix(secret-sync): allow users to input custom branch names on Vercel

backend/src/services/project/project-service.ts
Add a condition to only limit the number of projects to SecretManager and allow users to try out the other products like KMS/PKI/SSH.
```sh
```
---
=> Add a condition to only limit the number of projects to SecretManager

backend/src/db/migrations/20250613153957_add-machine-identity-delete-protection.ts, backend/src/db/schemas/identities.ts, backend/src/ee/services/audit-log/audit-log-types.ts, backend/src/lib/api-docs/constants.ts, backend/src/server/routes/v1/identity-router.ts, backend/src/services/identity-project/identity-project-dal.ts, backend/src/services/identity/identity-org-dal.ts, backend/src/services/identity/identity-service.ts, backend/src/services/identity/identity-types.ts, backend/src/services/telemetry/telemetry-types.ts, frontend/src/hooks/api/auditLogs/types.tsx, frontend/src/hooks/api/identities/mutations.tsx, frontend/src/hooks/api/identities/types.ts, frontend/src/pages/organization/AccessManagementPage/components/OrgIdentityTab/components/IdentitySection/IdentityModal.tsx, frontend/src/pages/organization/AccessManagementPage/components/OrgIdentityTab/components/IdentitySection/IdentityTable.tsx, frontend/src/pages/organization/IdentityDetailsByIDPage/components/IdentityDetailsSection.tsx, frontend/src/pages/organization/IdentityDetailsByIDPage/components/ViewIdentityAuthModal/ViewIdentityContentWrapper.tsx
Delete protection for machine identities
=> feat(machine-identities): Delete protection

docs/self-hosting/guides/production-hardening.mdx
This PR adds documentation for production hardening
```sh
```
---
=> doc: production hardening

frontend/src/pages/project/AccessControlPage/components/ProjectRoleListTab/components/ProjectRoleList/ProjectRoleList.tsx
This PR adds pagination, search and column sorting to the project roles table. In addition the project role row dropdown has been improved to include icons, a larger button and better menu alignment.
```sh
```
---
=> improvement(project-roles): Add pagination, search and column sorting to Project Roles table

frontend/src/components/permissions/AccessTree/components/AccessTreeContext.tsx, frontend/src/components/permissions/AccessTree/components/PermissionSimulation.tsx, frontend/src/components/permissions/AccessTree/hooks/index.ts, frontend/src/components/permissions/AccessTree/nodes/FolderNode/components/FolderNodeTooltipContent.tsx, frontend/src/components/permissions/AccessTree/nodes/RoleNode.tsx, frontend/src/components/permissions/AccessTree/utils/createFolderNode.ts, frontend/src/components/v2/SecretPathInput/SecretPathInput.tsx, frontend/src/context/ProjectPermissionContext/types.ts
This PR updates the access tree display to properly display dynamic secret conditions.
```sh
```
---
=> improvement(access-tree): dynamic secret conditional display

backend/src/lib/config/env.ts, backend/src/server/plugins/auth/inject-identity.ts, backend/src/server/routes/v3/login-router.ts, cli/packages/api/model.go, cli/packages/cmd/dynamic_secrets.go, cli/packages/cmd/export.go, cli/packages/cmd/init.go, cli/packages/cmd/login.go, cli/packages/cmd/secrets.go, cli/packages/cmd/ssh.go, cli/packages/cmd/tokens.go, cli/packages/cmd/user.go, cli/packages/models/cli.go, cli/packages/util/credentials.go, cli/packages/util/folders.go, cli/packages/util/secrets.go, frontend/src/components/utilities/attemptCliLogin.ts, frontend/src/components/utilities/attemptCliLoginMfa.ts, frontend/src/hooks/api/auth/queries.tsx, frontend/src/pages/auth/LoginPage/components/PasswordStep/PasswordStep.tsx, frontend/src/pages/auth/SelectOrgPage/SelectOrgSection.tsx
Lower token lifetime to 1 day (refresh 14 days) and fix CLI refresh token functionality.
Also includes some spelling corrections.
=> feat: Lower token lifetime to 1 day (refresh 14 days) and fix CLI refresh token functionality

frontend/src/hooks/api/accessApproval/types.ts, frontend/src/pages/secret-manager/SecretApprovalsPage/components/AccessApprovalRequest/components/ReviewAccessModal.tsx, frontend/src/pages/secret-manager/SecretApprovalsPage/components/ApprovalPolicyList/ApprovalPolicyList.tsx, frontend/src/pages/secret-manager/SecretApprovalsPage/components/ApprovalPolicyList/components/AccessPolicyModal.tsx, frontend/src/pages/secret-manager/SecretApprovalsPage/components/ApprovalPolicyList/components/ApprovalPolicyRow.tsx
This PR fixes UI bugs that was happening due to sequence approval flow.
1. Resolved secret approval sequence incorrect
2. Patched up approval required incorrect numbering
```sh
```
---
=> feat: patched up approval sequence ui bugs

docs/documentation/guides/nextjs-vercel.mdx
=> Docs links fix

backend/src/db/instance.ts
This adds min to knexjs pool. Avoids stale connection issue and resumability
```sh
```
---
=> feat: added min 0 for knexjs pool

backend/src/server/routes/v1/invite-org-router.ts, backend/src/server/routes/v1/password-router.ts, backend/src/server/routes/v2/user-router.ts, backend/src/server/routes/v3/signup-router.ts
This PR adds more aggressive rate limiting to verify endpoints
```sh
```
---
=> improvement(verify-endpoints): add more aggressive rate limiting to verify endpoints

backend/src/server/routes/v3/secret-router.ts, backend/src/services/project/project-service.ts, backend/src/services/secret/secret-service.ts, backend/src/services/secret/secret-types.ts
=> Add projectSlug parameter on secrets v3 endpoints

backend/src/ee/services/audit-log-stream/audit-log-stream-fns.ts, backend/src/ee/services/audit-log-stream/audit-log-stream-service.ts, backend/src/ee/services/audit-log/audit-log-queue.ts
improve audit log streams: add backend logs + DataDog source
=> improve audit log streams: add backend logs + DD source

frontend/src/layouts/OrganizationLayout/components/MinimizedOrgSidebar/MinimizedOrgSidebar.tsx
This PR gives users ability to copy their user session token so that they can quickly use to fetch a secret using there workflow.
```sh
```
---
=> feat: added copy token button

frontend/src/components/secret-syncs/CreateSecretSyncModal.tsx, frontend/src/components/secret-syncs/SecretSyncSelect.tsx, frontend/src/pages/organization/AppConnections/AppConnectionsPage/components/AppConnectionList.tsx
This PR adds search and pagination to the secret sync and app connection select modals
```sh
```
---
=> improvement(secret-sync/app-connection): Add search/pagination to secret sync and app connection selection modals

backend/src/ee/services/secret-scanning/secret-scanning-queue/secret-scanning-queue.ts, backend/src/ee/services/secret-scanning/secret-scanning-service.ts, backend/src/server/routes/index.ts, backend/src/server/routes/v1/secret-sync-routers/cloudflare-pages-sync-router.ts, backend/src/services/app-connection/cloudflare/cloudflare-connection-schema.ts
This PR removes secret scanning v1 queue and webhook
```sh
```
---
=> chore(secret-scanning-v1): remove secret scanning v1 queue and webhook endpoint

docs/integrations/secret-syncs/aws-parameter-store.mdx, frontend/src/components/secret-syncs/forms/SecretSyncDestinationFields/AwsParameterStoreSyncFields.tsx
docs
Clarify relationship between path and key schema for AWS parameter store
=> Clarify relationship between path and key schema for AWS parameter store

frontend/src/components/v2/PasswordGenerator/PasswordGenerator.tsx, frontend/src/pages/cert-manager/CertificatesPage/components/CertificateModal.tsx, frontend/src/pages/cert-manager/CertificatesPage/components/CertificateTemplateModal.tsx, frontend/src/pages/cert-manager/PkiSubscribersPage/components/PkiSubscriberModal.tsx, frontend/src/pages/cert-manager/PkiTemplateListPage/components/PkiTemplateForm.tsx, frontend/src/pages/kms/KmipPage/components/KmipClientModal.tsx, frontend/src/pages/project/AccessControlPage/components/ServiceTokenTab/components/ServiceTokenSection/AddServiceTokenModal.tsx, frontend/src/pages/secret-manager/SecretDashboardPage/components/ActionBar/ReplicateFolderFromBoard/SecretTreeView.tsx, frontend/src/pages/secret-manager/SettingsPage/components/AutoCapitalizationSection/AutoCapitalizationSection.tsx, frontend/src/pages/secret-manager/SettingsPage/components/DeleteProjectProtection/DeleteProjectProtection.tsx, frontend/src/pages/secret-manager/SettingsPage/components/SecretSharingSection/SecretSharingSection.tsx, frontend/src/pages/secret-manager/SettingsPage/components/SecretSnapshotsLegacySection/SecretSnapshotsLegacySection.tsx
This PR removes manual css overrides of checked state styling on checkboxes
```sh
```
---
=> fix(checkbox): Remove manual css overrides of checkbox checked state

backend/src/services/identity-access-token/identity-access-token-dal.ts
Pause cert auth roll out to reduce DB load
=> Remove cert auth left join

backend/src/ee/services/audit-log/audit-log-queue.ts
Remove debug logs for DataDog stream
=> Remove debug logs for DataDog stream

frontend/src/components/v2/GenericFieldLabel/GenericFieldLabel.tsx, frontend/src/pages/secret-manager/SecretApprovalsPage/components/AccessApprovalRequest/AccessApprovalRequest.tsx, frontend/src/pages/secret-manager/SecretApprovalsPage/components/AccessApprovalRequest/components/ReviewAccessModal.tsx, frontend/src/pages/secret-manager/SecretApprovalsPage/components/ApprovalPolicyList/components/ApprovalPolicyRow.tsx
This PR updates the UI for sequence approval display in the policy table and improves the access request modal UI
```sh
```
---
=> improvement(access-policies): Revamp approval sequence table display and access request modal

company/handbook/spending-money.mdx
=> update spend policy

backend/src/services/identity/identity-org-dal.ts, backend/src/services/identity/identity-types.ts, frontend/src/components/v2/Pagination/Pagination.tsx, frontend/src/hooks/api/identities/queries.tsx, frontend/src/hooks/api/organization/types.ts, frontend/src/pages/organization/AccessManagementPage/components/OrgGroupsTab/components/OrgGroupsSection/OrgGroupsSection.tsx, frontend/src/pages/organization/AccessManagementPage/components/OrgGroupsTab/components/OrgGroupsSection/OrgGroupsTable.tsx, frontend/src/pages/organization/AccessManagementPage/components/OrgIdentityTab/components/IdentitySection/IdentitySection.tsx, frontend/src/pages/organization/AccessManagementPage/components/OrgIdentityTab/components/IdentitySection/IdentityTable.tsx, frontend/src/pages/organization/AccessManagementPage/components/OrgMembersTab/components/OrgMembersSection/OrgMembersSection.tsx, frontend/src/pages/organization/AccessManagementPage/components/OrgMembersTab/components/OrgMembersSection/OrgMembersTable.tsx, frontend/src/pages/organization/AccessManagementPage/components/OrgRoleTabSection/OrgRoleTabSection.tsx, frontend/src/pages/organization/AccessManagementPage/components/OrgRoleTabSection/OrgRoleTable.tsx, frontend/src/pages/project/AccessControlPage/components/MembersTab/components/MembersTable.tsx, frontend/src/pages/project/AccessControlPage/components/ProjectRoleListTab/components/ProjectRoleList/ProjectRoleList.tsx, frontend/src/pages/project/RoleDetailsBySlugPage/components/GeneralPermissionPolicies.tsx
This PR standardizes the UI/functionality across org access control tabs and improves general UI
```sh
```
---
=> improvement(org-access-control): Standardize and improve org access control UI

backend/src/ee/services/access-approval-request/access-approval-request-service.ts, frontend/src/pages/secret-manager/SecretApprovalsPage/components/AccessApprovalRequest/components/ReviewAccessModal.tsx
Fix bypassing approval policies
They were broken after the sequence approval updates since self-approvals may now not work due to the need for additional approval steps.
=> Fix bypassing approval policies

backend/src/db/migrations/20250630170849_add-index-for-access-token.ts
This PR will address issue with very long identity deletions due to a sequential scan over ALL identity access rows during CASCADE
```sh
```
---
=> misc: add indices for referencing columns in identity access token

frontend/src/layouts/AdminLayout/Sidebar.tsx, frontend/src/pages/admin/EnvironmentPage/EnvironmentPage.tsx, frontend/src/pages/admin/EnvironmentPage/components/EnvironmentPageForm.tsx
=> misc: updated sidebar name

frontend/src/layouts/AdminLayout/Sidebar.tsx, frontend/src/pages/admin/EnvironmentPage/EnvironmentPage.tsx, frontend/src/pages/admin/EnvironmentPage/components/EnvironmentPageForm.tsx
Reverts Infisical/infisical#3896
=> Revert "misc: updated sidebar name"

.github/workflows/release_build_infisical_cli.yml
=> misc: updated CLI releaser spec

frontend/src/components/secret-syncs/forms/SecretSyncOptionsFields/SecretSyncOptionsFields.tsx
=> misc: update tooltip for overwrite sync

backend/src/ee/services/secret-scanning-v2/secret-scanning-v2-queue.ts
This PR scales down the number of workers for secret scanning to account for HA deployments
```sh
```
---
=> misc: downsize worker count for secret scanning jobs

frontend/src/components/notifications/Notifications.tsx, frontend/src/pages/secret-manager/OverviewPage/components/SelectionPanel/SelectionPanel.tsx
=> Improve multi-env error message to show full env name instead of slug

helm-charts/infisical-standalone-postgres/CHANGELOG.md, helm-charts/infisical-standalone-postgres/templates/infisical.yaml, helm-charts/infisical-standalone-postgres/values.yaml
Reverts Infisical/infisical#3914
=> Revert "feat(helm-charts/infiscal-core): topologySpreadConstraints support"

.github/workflows/helm-release-infisical-core.yml, helm-charts/infisical-standalone-postgres/CHANGELOG.md, helm-charts/infisical-standalone-postgres/Chart.yaml, helm-charts/infisical-standalone-postgres/templates/infisical.yaml, helm-charts/infisical-standalone-postgres/values.yaml
Reverts Infisical/infisical#3915
=> Revert "Revert "feat(helm-charts/infiscal-core): topologySpreadConstraints support""

backend/src/services/identity-project/identity-project-service.ts, backend/src/services/identity/identity-service.ts
=> misc: allow users with create permission to add identities with no access

cli/detect/cmd/scm/scm.go, cli/detect/git.go, cli/detect/utils.go, cli/packages/cmd/scan.go
Add BitBucket platform to secret scanning
=> Add BitBucket platform to secret scanning

backend/src/ee/routes/v1/ldap-router.ts, backend/src/ee/routes/v1/oidc-router.ts, backend/src/ee/routes/v1/saml-router.ts, backend/src/ee/services/oidc/oidc-config-service.ts, backend/src/ee/services/oidc/oidc-config-types.ts, backend/src/ee/services/saml-config/saml-config-service.ts, backend/src/ee/services/saml-config/saml-config-types.ts, backend/src/lib/api-docs/constants.ts, docs/api-reference/endpoints/organizations/ldap-sso/create-ldap-config.mdx, docs/api-reference/endpoints/organizations/ldap-sso/get-ldap-config.mdx, docs/api-reference/endpoints/organizations/ldap-sso/update-ldap-config.mdx, docs/api-reference/endpoints/organizations/oidc-sso/create-oidc-config.mdx, docs/api-reference/endpoints/organizations/oidc-sso/get-oidc-config.mdx, docs/api-reference/endpoints/organizations/oidc-sso/update-oidc-config.mdx, docs/api-reference/endpoints/organizations/saml-sso/create-saml-config.mdx, docs/api-reference/endpoints/organizations/saml-sso/get-saml-config.mdx, docs/api-reference/endpoints/organizations/saml-sso/update-saml-config.mdx, docs/docs.json, frontend/src/hooks/api/oidcConfig/mutations.tsx, frontend/src/hooks/api/oidcConfig/queries.tsx, frontend/src/pages/organization/SsoPage/components/OrgSsoTab/OIDCModal.tsx, frontend/src/pages/organization/SsoPage/components/OrgSsoTab/OrgOIDCSection.tsx, frontend/src/pages/organization/SsoPage/components/OrgSsoTab/OrgSsoTab.tsx
This PR adds documentation for all our LDAP/SAML/OIDC organization configuration endpoints.
---
=> docs(api-reference/organizations): document SSO configuration endpoints

backend/src/db/migrations/20250602155451_fix-secret-versions.ts, backend/src/services/org-membership/org-membership-dal.ts, backend/src/services/org/org-service.ts
Add jitter and increase window to 12 m
For testing, follow instructions in this PR: https://github.com/Infisical/infisical/pull/3974
=> Add jitter and increase window to 12 m

backend/src/db/migrations/20250710022434_add-index-for-access-token.ts
=> misc: remove concurrently for index creations

backend/src/ee/services/secret-scanning-v2/secret-scanning-v2-queue.ts, backend/src/ee/services/secret-scanning-v2/secret-scanning-v2-types.ts
This PR properly assigns secret scanning leaks to the committing author instead of Jim.
```sh
```
---
=> fix(secret-scanning-v2): Remove Jim as sole author of all secret leaks

docs/Dockerfile, docs/docs.json
Allow docs to run fully offline
=> Allow docs to run fully offline

backend/src/ee/services/ldap-config/ldap-config-service.ts, backend/src/ee/services/license/licence-enums.ts, backend/src/ee/services/license/license-service.ts, backend/src/ee/services/saml-config/saml-config-service.ts, backend/src/services/org/org-service.ts, frontend/src/hooks/api/identities/mutations.tsx, frontend/src/hooks/api/users/queries.tsx, frontend/src/pages/organization/AccessManagementPage/components/OrgMembersTab/components/OrgMembersSection/OrgMembersSection.tsx
Minor fix to only compute `identityLimit` and no longer consider `memberLimit` on identities check, removed the Members limit field from the billing table and small improvements on invalidating the subscription query on users/machine events
```sh
```
---
=> fix(billing): fix feature flags to only use identityLimit

frontend/src/pages/secret-manager/SecretApprovalsPage/components/ApprovalPolicyList/components/AccessPolicyModal.tsx
This PR replaces the secret path field input with the secret path input for autocomplete
```sh
```
---
=> improvement(frontend): use secret path input for create policy modal

docs/Dockerfile
Use non root user for docs Dockerfile
=> Use non root user for docs Dockerfile

docs/changelog/overview.mdx
=> updated changelog

docs/docs.json, docs/sdks/languages/cpp.mdx, docs/sdks/overview.mdx
Added our C++ SDK to our on-site documentation.
---
=> docs: cpp sdk

backend/src/services/secret-sync/azure-devops/azure-devops-sync-schemas.ts, frontend/src/components/secret-syncs/forms/SecretSyncReviewFields/AzureDevOpsSyncReviewFields.tsx, frontend/src/components/secret-syncs/forms/schemas/azure-devops-sync-destination-schema.ts, frontend/src/hooks/api/secretSyncs/types/azure-devops-sync.ts, frontend/src/pages/secret-manager/IntegrationsListPage/components/SecretSyncsTab/SecretSyncTable/helpers/index.ts, frontend/src/pages/secret-manager/SecretSyncDetailsByIDPage/components/SecretSyncDestinationSection/AzureDevOpsSyncDestinationSection.tsx
Make Azure DevOps sync not require project name
=> Make Azure DevOps sync not require project name

cli/packages/util/check-for-update.go
This PR updates the CLI latest version check to query the new CLI repository for releases
```sh
```
---
=> misc: update CLI latest version check

docs/integrations/app-connections/postgres.mdx
=> Add missing setting for postgres app connection

backend/src/ee/services/saml-config/saml-config-service.ts
Small fix to properly verify emails for SSO accounts. Previously, verification was skipped since only the isAccepted field was checked, which caused a verification email to be sent on every login.
```sh
```
---
=> Add isEmailVerified to isUserCompleted flag on samlLogin

company/documentation/engineering/how-to-write-design-doc.mdx
This PR adds a section to our design document guide about getting explicit sales team approval if necessary.
```sh
```
---
=> doc: added section about sales approval

backend/src/ee/services/license/license-fns.ts, frontend/src/hooks/api/subscriptions/types.ts, frontend/src/hooks/usePathAccessPolicies.tsx, frontend/src/pages/project/AccessControlPage/components/MembersTab/components/MemberRoleForm/SpecificPrivilegeSection.tsx, frontend/src/pages/secret-manager/SecretApprovalsPage/components/AccessApprovalRequest/components/RequestAccessModal.tsx, frontend/src/pages/secret-manager/SecretDashboardPage/SecretDashboardPage.tsx, frontend/src/pages/secret-manager/SecretDashboardPage/components/ActionBar/ActionBar.tsx, frontend/src/pages/secret-manager/SecretDashboardPage/components/SecretDropzone/SecretDropzone.tsx
This PR integrates access requests into single env views when a policy is in place at the current path. Also includes general UI improvements
```sh
```
---
=> improvement(access-requests): add access requests to single env view + general UI improvements

backend/src/services/certificate-authority/certificate-authority-dal.ts, backend/src/services/certificate-authority/internal/internal-certificate-authority-service.ts
=> On importCertToCa use serialNumber instead of dn to get the parentCa

backend/src/server/lib/cookie.ts, backend/src/server/routes/v1/auth-router.ts, backend/src/services/app-connection/github-radar/github-radar-connection-fns.ts, backend/src/services/app-connection/github/github-connection-fns.ts
-  Fix Github radar app connection errors
-  Clear `aod` cookie on signout
---
=> fix: github radar app connection errors and clear `aod` cookie on signout

backend/src/ee/services/license/license-service.ts, backend/src/server/routes/index.ts, backend/src/services/project/project-service.ts
PR to remove cloud plan cache from this side as we are caching it now on the license api
```sh
```
---
=> Removed cloud plan cache as it is handled on the license api

backend/src/lib/crypto/cryptography/crypto.ts
Added a check for dev mode, and if running in dev mode it will allow FIPS to work without a license.
---
=> fix(fips): allow fips in dev mode without license

backend/src/ee/routes/v2/secret-rotation-v2-routers/secret-rotation-v2-endpoints.ts
=> Fix secret rotation defaults

backend/src/ee/services/secret-rotation-v2/secret-rotation-v2-queue.ts, backend/src/ee/services/secret-scanning-v2/secret-scanning-v2-queue.ts, backend/src/services/microsoft-teams/microsoft-teams-fns.ts, backend/src/services/project/project-service.ts, backend/src/services/secret-sync/secret-sync-queue.ts, backend/src/services/secret/secret-queue.ts, backend/src/services/service-token/service-token-service.ts
Resolved broken url due to layout change made sometime back 
```sh
```
---
=> feat: updated invalid url

backend/src/services/reminder/reminder-queue.ts, backend/src/services/reminder/reminder-service.ts, backend/src/services/secret-v2-bridge/secret-v2-bridge-dal.ts
=> Fix secret reminders migration job

backend/src/db/migrations/20250725144940_fix-secret-reminders-migration.ts, backend/src/services/reminder/reminder-queue.ts
=> Add manual migration to secret imports rework

frontend/src/components/permissions/OrgPermissionCan.tsx, frontend/src/components/permissions/PermissionDeniedBanner.tsx, frontend/src/components/permissions/ProjectPermissionCan.tsx, frontend/src/components/v2/AccessRestrictedBanner/AccessRestrictedBanner.tsx, frontend/src/components/v2/AccessRestrictedBanner/index.ts, frontend/src/components/v2/index.tsx, frontend/src/hoc/withPermission/withPermission.tsx, frontend/src/hoc/withProjectPermission/withProjectPermission.tsx, frontend/src/pages/kms/KmipPage/KmipPage.tsx, frontend/src/pages/kms/OverviewPage/OverviewPage.tsx, frontend/src/pages/secret-manager/SecretDashboardPage/SecretDashboardPage.tsx, frontend/src/pages/secret-scanning/SettingsPage/components/ProjectScanningConfigTab/ProjectScanningConfigTab.tsx
This PR revises the access restricted banner design and refactors/updates duplicate components to use a single component
```sh
```
---
=> improvement(frontend): revise access restricted banner and refactor/update relevant locations

backend/package-lock.json, backend/package.json
Updated passport-saml to address CVE https://github.com/Infisical/infisical/security/dependabot/255
---
=> fix: update passport saml

frontend/src/pages/auth/LoginPage/components/PasswordStep/PasswordStep.tsx, frontend/src/pages/auth/SelectOrgPage/SelectOrgPage.tsx, frontend/src/pages/auth/SelectOrgPage/SelectOrgSection.tsx
This PR makes the org selection and sso login loading screens consistent with our new loader and other loading screens
```sh
```
---
=> improvement(frontend): make login/org selection loading screens consistent

backend/src/ee/services/secret-approval-request/secret-approval-request-service.ts
=> Fix conditional permissions check on secret access request hidden values

backend/src/lib/api-docs/constants.ts, backend/src/server/routes/v2/organization-router.ts, backend/src/services/org/org-dal.ts, backend/src/services/org/org-fns.ts, backend/src/services/org/org-service.ts, backend/src/services/org/org-types.ts, backend/src/services/project-membership/project-membership-dal.ts, docs/api-reference/endpoints/organizations/bulk-delete-memberships.mdx, docs/docs.json, frontend/src/hooks/api/users/queries.tsx, frontend/src/hooks/api/users/types.ts, frontend/src/pages/organization/AccessManagementPage/components/OrgMembersTab/components/OrgMembersSection/OrgMembersSection.tsx, frontend/src/pages/organization/AccessManagementPage/components/OrgMembersTab/components/OrgMembersSection/OrgMembersTable.tsx, frontend/src/pages/organization/UserDetailsByIDPage/components/UserDetailsSection.tsx, frontend/src/pages/secret-manager/OverviewPage/components/SelectionPanel/SelectionPanel.tsx, frontend/src/pages/secret-manager/SecretDashboardPage/components/ActionBar/ActionBar.tsx
This PR adds a new bulk delete org memberships endpoint, api docs, bulk action table support and minor UI adjustments to secrets bulk action headers.
Also adds prevention of removing your own org membership (need to make sure this is cleanly done on a leave org endpoint)
```sh
```
---
=> improvement(org-memberships): add bulk delete org memberships endpoint and table support

backend/src/server/routes/v1/admin-router.ts, backend/src/services/super-admin/super-admin-service.ts, frontend/src/hooks/api/admin/mutation.ts, frontend/src/pages/admin/MachineIdentitiesResourcesPage/components/MachineIdentitiesTable.tsx, frontend/src/pages/admin/UserIdentitiesResourcesPage/components/UserIdentitiesTable.tsx, frontend/src/pages/organization/AccessManagementPage/components/OrgMembersTab/components/OrgMembersSection/OrgMembersTable.tsx
This PR adds bulk delete users support, bulk actions server admin table support, user table overflow/truncation handling and dropdown improvements on both user and MI tables.
Also adds checks on the backend to ensure there is always at least one server admin when deleting/un-assigning
```sh
```
---
=> improvement(server-admin): add bulk delete users support, bulk actions server admin table support, overflow/truncation and dropdown improvements

backend/src/services/smtp/emails/AccessApprovalRequestTemplate.tsx, backend/src/services/smtp/emails/BaseButton.tsx, backend/src/services/smtp/emails/BaseEmailWrapper.tsx, backend/src/services/smtp/emails/BaseLink.tsx, backend/src/services/smtp/emails/EmailMfaTemplate.tsx, backend/src/services/smtp/emails/EmailVerificationTemplate.tsx, backend/src/services/smtp/emails/ExternalImportFailedTemplate.tsx, backend/src/services/smtp/emails/IntegrationSyncFailedTemplate.tsx, backend/src/services/smtp/emails/NewDeviceLoginTemplate.tsx, backend/src/services/smtp/emails/OrgAdminBreakglassAccessTemplate.tsx, backend/src/services/smtp/emails/OrgAdminProjectGrantAccessTemplate.tsx, backend/src/services/smtp/emails/OrganizationInvitationTemplate.tsx, backend/src/services/smtp/emails/PasswordResetTemplate.tsx, backend/src/services/smtp/emails/PasswordSetupTemplate.tsx, backend/src/services/smtp/emails/ProjectAccessRequestTemplate.tsx, backend/src/services/smtp/emails/ProjectInvitationTemplate.tsx, backend/src/services/smtp/emails/ScimUserProvisionedTemplate.tsx, backend/src/services/smtp/emails/SecretApprovalRequestBypassedTemplate.tsx, backend/src/services/smtp/emails/SecretApprovalRequestNeedsReviewTemplate.tsx, backend/src/services/smtp/emails/SecretLeakIncidentTemplate.tsx, backend/src/services/smtp/emails/SecretRequestCompletedTemplate.tsx, backend/src/services/smtp/emails/SecretRotationFailedTemplate.tsx, backend/src/services/smtp/emails/SecretScanningScanFailedTemplate.tsx, backend/src/services/smtp/emails/SecretScanningSecretsDetectedTemplate.tsx, backend/src/services/smtp/emails/SecretSyncFailedTemplate.tsx, backend/src/services/smtp/emails/ServiceTokenExpiryNoticeTemplate.tsx, backend/src/services/smtp/emails/SignupEmailVerificationTemplate.tsx, backend/src/services/smtp/emails/UnlockAccountTemplate.tsx
This PR simplifies the email template design to avoid email client css constraints, refactors button/link usage to re-usable components and improves minor design elements
```sh
```
---
=> improvement(email-templates): simplify email design, refactor link/button to re-usable components and improve design

frontend/src/pages/secret-manager/SecretDashboardPage/components/SecretListView/SecretItem.tsx
=> Fix edge case where users with edit but not read permission on new commit row logic

frontend/src/pages/organization/AuditLogsPage/components/LogsFilter.tsx
This PR fixes the styling and overflow of the audit log filter dropdown
```sh
```
---
=> improvement(frontend): update styling and overflow for audit log filter

backend/src/services/app-connection/shared/sql/sql-connection-fns.ts
=> servername host for mssql

frontend/src/pages/organization/AuditLogsPage/components/LogsSection.tsx
This PR fixes a bug in integration audit log that show all the integration in project rather than show just the one needed. 
```sh
```
---
=> feat: resolved audit log showing all the integration

.github/workflows/nightly-tag-generation.yml, docs/docs.json, docs/self-hosting/guides/releases.mdx
=> Add Release Channels with nightly

docs/self-hosting/guides/mongo-to-postgres.mdx
Update migration docs to reflect simplified Docker image tagging (removed -postgres suffix)
```sh
```
---
=> Updated migration docs with latest image version changes

backend/src/ee/services/secret-scanning-v2/secret-scanning-v2-fns.ts, backend/src/lib/config/env.ts
This PR adds entropy check for parameter secret value scanning
```sh
```
---
=> misc: added entropy check for params secret scanning

backend/src/lib/config/env.ts, backend/src/server/routes/index.ts, backend/src/services/resource-cleanup/resource-cleanup-queue.ts
Move our daily resource clean up job from BullMQ to PGBoss
```sh
```
---
=> Move DailyResourceCleanUp to PGBoss

backend/src/db/migrations/20250808021941_access-policy-max-time-period.ts, backend/src/db/schemas/access-approval-policies.ts, backend/src/ee/routes/v1/access-approval-policy-router.ts, backend/src/ee/routes/v1/access-approval-request-router.ts, backend/src/ee/services/access-approval-policy/access-approval-policy-dal.ts, backend/src/ee/services/access-approval-policy/access-approval-policy-service.ts, backend/src/ee/services/access-approval-policy/access-approval-policy-types.ts, backend/src/ee/services/access-approval-request/access-approval-request-dal.ts, backend/src/ee/services/access-approval-request/access-approval-request-service.ts, backend/src/ee/services/access-approval-request/access-approval-request-types.ts, frontend/src/hooks/api/accessApproval/mutation.tsx, frontend/src/hooks/api/accessApproval/types.ts, frontend/src/pages/project/AccessControlPage/components/MembersTab/components/MemberRoleForm/SpecificPrivilegeSection.tsx, frontend/src/pages/secret-manager/SecretApprovalsPage/components/ApprovalPolicyList/components/AccessPolicyModal.tsx, frontend/src/pages/secret-manager/SecretDashboardPage/components/SecretListView/SecretDetailSidebar.tsx
Allow policy limits on access request times.
=> feat(access-policies): Allow policy limits on access request times

backend/src/db/schemas/secret-folders.ts, backend/src/server/routes/v1/secret-folder-router.ts, backend/src/services/secret-folder/secret-folder-service.ts
=> feat(api): Return path for folder create, update, delete

frontend/src/pages/secret-manager/SecretDashboardPage/SecretDashboardPage.tsx, frontend/src/pages/secret-manager/SecretDashboardPage/components/CommitForm/CommitForm.tsx
This PR revises the environment view commit modal wording/icons and autofocuses the commit message input on open
```sh
```
---
=> improvement(frontend): adjust commit modal wording and icons and autofocus commit message

frontend/src/pages/secret-manager/SecretApprovalsPage/components/ApprovalPolicyList/components/AccessPolicyModal.tsx
Fix form issue for access request policy form where not editing the form threw some error
=> Fix form issue

backend/src/server/routes/v2/project-router.ts, docs/api-reference/endpoints/workspaces/get-workspace-by-slug.mdx, docs/docs.json
This PR adds documentation for API to convert project id from a project slug
```sh
```
---
=> feat: added api document for project router get id from slug

docs/integrations/secret-syncs/aws-parameter-store.mdx
Suggest higher throughput quotas for AWS parameter store
=> feat(docs): Suggest higher throughput quotas for AWS parameter store

frontend/src/pages/secret-manager/SecretDashboardPage/components/ActionBar/ActionBar.tsx
adjust environment view dropdown filter alignment, add applied tags display and info tooltip to clarify behavior
```sh
```
---
=> improvement(frontend): adjust environment view dropdown alignment, add applied tags display and info tooltip to clarify behavior

docs/integrations/platforms/kubernetes/overview.mdx
Fixed two typos on overview page. Please, have a look and let me know if anything else needs to be checked/proofread as well.
=> Fix typos in overview.mdx

frontend/src/pages/organization/AppConnections/OauthCallbackPage/OauthCallbackPage.tsx
Fix an issue where gitlab self-hosted instance urls where not sent to the backend during creation what lead to an error when trying to validate the code.
```sh
```
---
=> Fix Gitlab OAuth redirection issue with instanceUrls

backend/src/db/manual-migrations/partition-audit-logs.ts
This PR finalizes the partitioning script to be up to date
```sh
```
---
=> misc: optimize partition script

k8-operator/api/v1alpha1/infisicalsecret_types.go, k8-operator/config/crd/bases/secrets.infisical.com_infisicalsecrets.yaml
This PR fixes a bug in #4321 making the instant update required in crd
```sh
```
---
=> feat: resolved instant update in required

frontend/src/pages/secret-manager/SecretDashboardPage/components/CommitForm/CommitForm.tsx
This PR adds a transition to the environment view commit modal on display
```sh
```
---
=> improvement(frontend): make commit popover animated

backend/src/lib/api-docs/constants.ts, backend/src/server/routes/index.ts, backend/src/server/routes/v1/app-connection-routers/render-connection-router.ts, backend/src/services/app-connection/render/render-connection-fns.ts, backend/src/services/app-connection/render/render-connection-service.ts, backend/src/services/app-connection/render/render-connection-types.ts, backend/src/services/certificate-authority/internal/internal-certificate-authority-fns.ts, backend/src/services/certificate-authority/internal/internal-certificate-authority-service.ts, backend/src/services/secret-sync/render/render-sync-enums.ts, backend/src/services/secret-sync/render/render-sync-fns.ts, backend/src/services/secret-sync/render/render-sync-schemas.ts, docs/integrations/secret-syncs/render.mdx, frontend/src/components/secret-syncs/forms/SecretSyncDestinationFields/RenderSyncFields.tsx, frontend/src/components/secret-syncs/forms/SecretSyncReviewFields/RenderSyncReviewFields.tsx, frontend/src/components/secret-syncs/forms/schemas/render-sync-destination-schema.ts, frontend/src/helpers/secretSyncs.ts, frontend/src/hooks/api/appConnections/render/queries.tsx, frontend/src/hooks/api/appConnections/render/types.ts, frontend/src/hooks/api/secretSyncs/types/render-sync.ts, frontend/src/pages/secret-manager/IntegrationsListPage/components/SecretSyncsTab/SecretSyncTable/SecretSyncDestinationCol/RenderSyncDestinationCol.tsx, frontend/src/pages/secret-manager/IntegrationsListPage/components/SecretSyncsTab/SecretSyncTable/helpers/index.ts, frontend/src/pages/secret-manager/SecretSyncDetailsByIDPage/components/SecretSyncDestinationSection/RenderSyncDestinationSection.tsx
This PR adds support for using Render environment groups inside render secret sync
https://render.com/docs/configure-environment-variables#environment-groups
---
=> feat: support render environment groups

backend/src/lib/template/dot-access.ts, backend/src/services/identity-jwt-auth/identity-jwt-auth-service.ts, backend/src/services/identity-oidc-auth/identity-oidc-auth-fns.ts, backend/src/services/identity-oidc-auth/identity-oidc-auth-service.ts
This PR adds support for number property matching in OIDC and JWT
```sh
```
---
=> misc: add support for number matching in oidc and jwt

backend/src/ee/services/secret-approval-request/secret-approval-request-service.ts, backend/src/services/secret-v2-bridge/secret-v2-bridge-dal.ts
This PR addresses the issue where user with limited RBAC tries to update a secret with a certain tag from the secret overview page. 
```sh
```
---
=> misc: address permission issue for secrets with tags

frontend/src/components/v2/DatePicker/DatePicker.tsx, frontend/src/pages/secret-manager/SecretDashboardPage/components/SecretListView/CreateReminderForm.tsx
This PR adjusts the secret reminder modal some attention, improving the date picker position, disabled dates view, alignment and text
```sh
```
---
=> improvement(frontend): give secret reminder form some love

docs/integrations/platforms/ansible.mdx
Documentation for the new OIDC auth method for Ansible
---
=> docs(ansible): oidc auth

docs/docs.json, docs/sdks/languages/cpp.mdx, docs/sdks/languages/csharp.mdx, docs/sdks/languages/dotnet.mdx, docs/sdks/languages/go.mdx, docs/sdks/languages/java.mdx, docs/sdks/languages/node.mdx, docs/sdks/languages/python.mdx, docs/sdks/languages/ruby.mdx, docs/sdks/languages/rust.mdx, docs/sdks/overview.mdx
This PR merges SDK docs from individual github repo README's to documentation page sites.
```sh
```
---
=> feat: merge sdk docs

backend/src/server/routes/index.ts, backend/src/server/routes/v3/external-migration-router.ts, backend/src/services/external-migration/external-migration-fns/vault.ts, backend/src/services/external-migration/external-migration-service.ts, backend/src/services/external-migration/external-migration-types.ts, docs/documentation/platform/external-migrations/vault.mdx, frontend/src/hooks/api/migration/mutations.tsx, frontend/src/pages/organization/SettingsPage/components/ExternalMigrationsTab/components/VaultPlatformModal.tsx
Added gateway support to vault migration along with support for the KV1 secret engine. The KV1 secret engine has a different API, hence why we need to differentiate between v1/v2.
---
=> feat(vault-migration): gateway support & kv v1 support

frontend/src/pages/organization/SettingsPage/components/ExternalMigrationsTab/components/VaultPlatformModal.tsx
Fixed UI glitch for vault migration
---
=> fix(vault-migration): ui bug

backend/src/services/identity-ua/identity-ua-service.ts
=> Disable lock

backend/src/services/identity-ua/identity-ua-service.ts
This PR reverts ua lockout made in login
```sh
```
---
=> feat: reverted lockout in login completely

backend/src/services/auth/auth-login-service.ts
Avoid throw an authEnforced error when user is trying to login using the enforced SAML/OIDC method
```sh
```
---
=> Check token source before throwing an error for auth enforced scenarios

frontend/src/helpers/project.ts, frontend/src/layouts/SecretManagerLayout/SecretManagerLayout.tsx, frontend/src/pages/organization/SettingsPage/components/ExternalMigrationsTab/components/VaultPlatformModal.tsx, frontend/src/pages/secret-manager/OverviewPage/OverviewPage.tsx
This PR brings back the default overview page until we resolve some of the customer pain points in our new overview design. 
#4449 
```sh
```
---
=> feat: union said - bring back overview page!!

backend/src/services/auth/auth-login-service.ts
Small fix for admin bypass flows on selectOrganization function.
```sh
```
---
=> Fix blocking issue for auth admin bypass on selectOrganization

backend/package-lock.json, backend/package.json, backend/src/@types/fastify.d.ts, backend/src/lib/config/env.ts, backend/src/server/plugins/auth/inject-identity.ts, backend/src/server/plugins/auth/verify-auth.ts, backend/src/server/plugins/primary-forwarding-mode.ts, backend/src/server/routes/index.ts
This PR adds support for primary forwarding for write operation in multi region deployment of Infisical
```sh
```
---
=> feat: primary forwarding mode completed

backend/src/@types/fastify.d.ts, backend/src/ee/services/event/event-bus-service.ts, backend/src/ee/services/event/event-sse-service.ts, backend/src/ee/services/event/event-sse-stream.ts, backend/src/lib/config/env.ts, backend/src/lib/config/redis.ts, backend/src/queue/queue-service.ts, backend/src/server/app.ts, docs/self-hosting/configuration/envars.mdx, sink/redis-cluster/README.md, sink/redis-cluster/docker-compose.yml
This PR implements support for redis cluster in Infisical. This include bulllmq hash slot change and other places needed
```sh
```
---
=> Redis cluster support

frontend/src/pages/secret-manager/SecretDashboardPage/SecretDashboardPage.tsx
Fix fast clicking issue on commit changes modal, if it's not disabled users can trigger multiple updates and send the same commit changes several times
```sh
```
---
=> Fix fast clicking issue on commit changes modal

backend/src/services/project/project-service.ts
When no admin user is assigned (even if a custom role with admin-like permissions exists), requestProjectAccess fails because there’s no user to send the request to. Added a step to handle this case by identifying users who can grant project access, so the feature now covers that scenario as well.
```sh
```
---
=> Improve requestProjectAccess check to retrieve users with permissions to grant access when no admin user is set

backend/src/services/identity-ua/identity-ua-service.ts
improve lock error message & disable lock when lockout
=> feat(ua-login): improve lock error message & disable lock when lockout is disabled

backend/src/ee/services/ldap-config/ldap-config-service.ts, backend/src/ee/services/oidc/oidc-config-service.ts, backend/src/ee/services/saml-config/saml-config-service.ts, backend/src/keystore/keystore.ts, backend/src/server/routes/index.ts, backend/src/services/org/org-service.ts, frontend/src/components/permissions/OrgPermissionCan.tsx, frontend/src/pages/organization/SettingsPage/components/OrgSsoTab/OrgGeneralAuthSection.tsx, frontend/src/pages/organization/SettingsPage/components/OrgSsoTab/OrgLDAPSection.tsx, frontend/src/pages/organization/SettingsPage/components/OrgSsoTab/OrgOIDCSection.tsx, frontend/src/pages/organization/SettingsPage/components/OrgSsoTab/OrgSSOSection.tsx, frontend/src/pages/organization/SettingsPage/components/OrgSsoTab/OrgSsoTab.tsx
This PR  prevents google oauth enforcement if sso configured, and prevents sso enablement if google oauth enforcement is enabled on both back/frontend. Also improves labeling and disabled relevant toggle switches with tooltips.
```sh
```
---
=> improvement(google-oauth-enforcement): prevent conflicting sso enforcement configuration 

backend/src/ee/services/dynamic-secret/providers/sql-database.ts
=> fix: resolved using host when it's postgres with gateway

backend/src/ee/services/dynamic-secret/providers/models.ts, backend/src/ee/services/dynamic-secret/providers/sql-database.ts, frontend/src/pages/secret-manager/SecretDashboardPage/components/ActionBar/CreateDynamicSecretForm/SqlDatabaseInputForm.tsx, frontend/src/pages/secret-manager/SecretDashboardPage/components/DynamicSecretListView/EditDynamicSecretForm/EditDynamicSecretSqlProviderForm.tsx
This PR addresses the following issues in MsSQL dynamic secret feature:
1. "Encryption" error when connecting to Azure SQL DB because it requires encrypt=true to be passed in. Other MsSQL distributions might require this as well so I made it a generic flag 
3. Gateway connection error because the received host field becomes "localhost" due to our gateway logic. More context in the comment
```sh
```
---
=> fix: address sql server dynamic secret integration

backend/src/ee/services/license/license-service.ts
Improvements on `getOrgPlanTable` function and added the logic to fetch the license plan table (shown on the `Usage & Billing` page) for **EnterpriseOnPrem** instances.
```sh
```
---
=> Improveme getOrgPlanTable and add EnterpriseOnPrem fetch plan table

docs/self-hosting/guides/upgrading-infisical.mdx
Updated docs to include:
- Downgrade recommendations: as it's a tricky process and if it's performed incorrectly it can lead to data inconsistencies
- Frontend caching issues: when deploying a new versions, usually the frontend can have old cache still in place, leading to rendering issues that can be misunderstood as a deployment/version issue.
```sh
```
---
=> Updated docs to include downgrade and cache issue

frontend/src/pages/organization/AccessManagementPage/components/OrgIdentityTab/components/IdentitySection/IdentitySection.tsx
Fix incorrect feature flag being used to check Identity Auth Templates.
```sh
```
---
=> Fix IdentitySection to use the correct flag on Identity Auth Templates

backend/src/ee/services/access-approval-request/access-approval-request-service.ts, backend/src/ee/services/secret-approval-request/secret-approval-request-fns.ts, backend/src/ee/services/secret-approval-request/secret-approval-request-service.ts, backend/src/ee/services/secret-rotation-v2/secret-rotation-v2-queue.ts, backend/src/ee/services/secret-scanning-v2/secret-scanning-v2-queue.ts, backend/src/queue/queue-service.ts, backend/src/server/routes/index.ts, backend/src/server/routes/v1/notification-router.ts, backend/src/services/auth/auth-login-service.ts, backend/src/services/external-migration/external-migration-queue.ts, backend/src/services/external-migration/external-migration-service.ts, backend/src/services/notification/notification-types.ts, backend/src/services/org-admin/org-admin-service.ts, backend/src/services/project-membership/project-membership-service.ts, backend/src/services/project/project-service.ts, backend/src/services/secret-sync/secret-sync-queue.ts, backend/src/services/telemetry/telemetry-types.ts, frontend/src/layouts/OrganizationLayout/components/NavBar/Notification.tsx, frontend/src/layouts/OrganizationLayout/components/NavBar/NotificationDropdown.tsx
Expand notification coverage to 15 new services
Also added posthog telemetry for notification updates (like isRead being set to true on notification click)
Includes minor UI updates as well
=> feat(notifications): expand notification coverage

backend/src/ee/services/audit-log/audit-log-types.ts, backend/src/ee/services/pit/pit-service.ts, backend/src/ee/services/secret-approval-request/secret-approval-request-service.ts, backend/src/server/routes/v3/deprecated-secret-router.ts, backend/src/server/routes/v4/secret-router.ts
This PR adds support for tracking secret tags in audit logs
```sh
```
---
=> misc: add secret tags to audit logs

backend/src/server/routes/v1/dashboard-router.ts
This PR adds a hard match secret key when resolving value for dashboard
```sh
```
---
=> fix(dashboard): correct secret key resolution when retrieving dashboard value

docs/integrations/platforms/infisical-agent.mdx, docs/integrations/platforms/kubernetes-injector.mdx
Improved the agent and agent injector docs to reflect sidecar support and the dynamic_secret templating function.
---
=> docs: improve agent & injector docs

frontend/src/hooks/api/users/queries.tsx, frontend/src/pages/user/PersonalSettingsPage/components/SecuritySection/MFASection.tsx
Improvements on the 2FA form to simplify the flow to set up this feature.
- Hide QR and recovery codes on email verification type
- Improve the process to only enable this 2FA when a valid setting is configured
- Fallback to email when mobile type authentication is deleted
- Remove recovery codes when this feature is disabled
```sh
```
---
=> Improve personal settings 2FA form

backend/src/ee/services/license/license-service.ts
Fix endpoint used by the license api to get the billing table on self-hosted instances
```sh
```
---
=> Fix license api endpoint for self-hosted get billing table

backend/src/db/migrations/20250602155452_pit-projects-commits-initialization.ts
Fix an issue in `backend/src/db/migrations/20250602155452_pit-projects-commits-initialization.ts` affecting projects where the number of folders exceeds the migration’s batching size. In such cases, some commits were processed in separate iterations, resulting in null references being used.
```sh
```
---
=> Fix PIT migration batch issue with folders overflowing the batch size

backend/src/services/smtp/emails/AccountDeletionConfirmationTemplate.tsx, backend/src/services/smtp/emails/index.ts, backend/src/services/smtp/smtp-service.ts, backend/src/services/user/user-service.ts
Adds confirmation email on account deletion
```sh
```
---
=> feat: Adds account deletion confirmation email

frontend/src/pages/pam/PamAccountsPage/components/PamAccountForm/GenericAccountFields.tsx, frontend/src/pages/pam/PamAccountsPage/components/PamFolderForm.tsx, frontend/src/pages/pam/PamResourcesPage/components/PamResourceForm/GenericResourceFields.tsx
Descriptions showed errors for name fields, so I updated the logic to be more inline with other form fields
=> fix pam forms

docs/documentation/platform/gateways/gateway-deployment.mdx
Fix broken doc link for gateway deployment
=> Fix broken link in the gateway doc
