Infisical/infisical

frontend/components/basic/buttons/Button.tsx
frontend/components/dashboard/DashboardInputField.tsx
frontend/components/dashboard/DropZone.tsx

issue: #47 
I convert components in the dashboard to typescript.
and I check the drag & drop feature 
https://user-images.githubusercontent.com/25437192/205468840-c0590f91-0a4e-4906-8ac1-433ffbaa59c8.mov

Update dashboard component

---

frontend/components/basic/InputField.tsx
frontend/components/basic/Layout.tsx
frontend/components/basic/Listbox.tsx
frontend/components/basic/buttons/Button.tsx
frontend/components/utilities/SecurityClient.js
frontend/components/utilities/attemptLogin.js
frontend/components/utilities/checks/PasswordCheck.ts
frontend/components/utilities/checks/tempLocalStorage.ts
frontend/pages/_app.js
frontend/pages/api/organization/GetOrgUserProjects.js
frontend/pages/api/workspace/getWorkspaces.ts
frontend/pages/signup.tsx
frontend/types/workspaces.d.ts

Convert JS to TS several components.

Convert JS to TS 

---

cli/packages/cmd/export.go
cli/packages/cmd/run.go
cli/packages/util/secrets.go
docs/cli/export.mdx

- I refactored some of the code in `cli/packages/cmd/run.go` so it could be
reused for the new command.
- I added a docs page for the new command.
Closes https://github.com/Infisical/infisical/issues/62

Add an `export` command

---

.github/workflows/check-be-pull-request.yml
.github/workflows/check-fe-pull-request.yml
.github/workflows/docker-image.yml

Two separate workflows that run on creation of pull requests:
* Frontend workflow watches for changes under `frontend` directory
* Backend workflow watches for changes under `backend` directory
For now, only executes `npm run build`. But the step for running tests is already included but commented out.
Also squeezed in a fix on build-arg for frontend image build.

Add PR gate workflows

---

backend/src/controllers/membershipOrgController.ts
backend/src/controllers/passwordController.ts
backend/src/helpers/signup.ts
backend/src/routes/password.ts
backend/src/templates/organizationInvitation.handlebars
backend/src/templates/passwordReset.handlebars
backend/src/templates/workspaceInvitation.handlebars

Backend reset password functionality so users can use their PDF keys to reset their Infisical account passwords.
Added endpoints:
- `POST /api/v1/password/email/password-reset`: send an email containing magic link to start password-reset flow.
- `POST /api/v1/password/email/password-reset-verify`: verify password-reset email magic link.
- `GET /api/v1/password/backup-private-key`: get encrypted copy of (backup) private key; secured by temp auth-token from prev-step.
- `POST /api/v1/password/password-reset`: post new password reset info (e.g. new salt, verifier, encrypted private key, etc.).

Begin reset password backend functionality

---

.prettierrc
backend/.eslintrc
backend/Dockerfile
backend/package-lock.json
backend/package.json
frontend/Dockerfile
frontend/Dockerfile.dev
frontend/Dockerfile.prod
frontend/package.json
package-lock.json
package.json

delete the prettier option in the automatic linter
and add `--ignore-scripts` for every `npm install` command

Adding automatic linter for checking commit

---

.env.example
backend/package-lock.json
docs/contributing/developing.mdx

According to issue #142, relocated `JWT_SERVICE_SECRET` and updated example image in `/docs/contributing/developing.mdx` to contain `JWT_SERVICE_SECRET` as well.

Fix `JWT_SERVICE_SECRET` not present in docs

---

docs/getting-started/quickstart.mdx

This change just fixes a typo I found in your Quickstart guide.

Fix typo in quickstart

---

.github/workflows/release_build.yml
.goreleaser.yaml

Hi, 
As already mentioned on Slack. You'll need to add a github secret called "AUR_KEY" containing your AUR ssh key for this to work. 
Closes #121

ci: add aur release

---

backend/src/controllers/v1/membershipOrgController.ts
backend/src/helpers/membership.ts
frontend/components/RouteGuard.js
frontend/components/utilities/SecurityClient.ts
frontend/pages/api/auth/CheckAuth.ts
frontend/pages/signupinvite.js

1. The membership invite to workspace was failing because
https://github.com/Infisical/infisical/blob/main/backend/src/controllers/v1/membershipController.ts#L187
The above line expects the middleware `requireWorkspaceAuth` to have workspace details. But due to not having populate query in it. Workspace id is only available causing the access to be undefined. 
1. This will fix workspace membership invite

fix(backend): resolved workspace membership invite failure

---

.gitignore
.goreleaser.yaml
cli/go.mod
cli/go.sum
cli/packages/cmd/man.go
cli/packages/cmd/root.go
cli/scripts/completions.sh
cli/scripts/manpages.sh

This adds support for the automatic generation of shell autocompletion files and linux manpages.

ci: add autocompletion and manpage

---

backend/src/app.ts
backend/src/controllers/v2/apiKeyDataController.ts
backend/src/controllers/v2/index.ts
backend/src/helpers/auth.ts
backend/src/middleware/requireAuth.ts
backend/src/models/apiKeyData.ts
backend/src/models/index.ts
backend/src/models/serviceTokenData.ts
backend/src/routes/v2/apiKeyData.ts
backend/src/routes/v2/index.ts
backend/src/routes/v2/workspace.ts
backend/src/types/express/index.d.ts
backend/src/utils/errors.ts

We will soon be opening up Infisical's API and documenting it so users can make API requests to Infisical.
This update adds backend support for API keys that users can use to authenticate with Infisical instead of JWTs; note that API keys v1 currently have full scope over a user's account and in the future we intend to apply scopes so users may pick what permissions API keys have.
Routes added:
- `GET api/v2/api-key-data`
- `POST api/v2/api-key-data`
- `DELETE api/v2/api-key-data`

Add API Key auth mode

---

.github/workflows/docker-image.yml

#168 
Added the short commit hash as a Docker tag. Kept the latest tag as well so that old images don't continue to be offered as latest on Docker Hub (there is nothing automatically updating this and Docker just assumes latest is truly latest).

Issue 159 - Docker image tags

---

README.md
frontend/public/locales/en/integrations.json
frontend/public/locales/en/settings-members.json
frontend/public/locales/en/signup.json
i18n/README.en.md

Fixing some typos in the `en` translation files and in the english READMEs. I've catched those typos while adding `fr` language support and wanted to split those two PR (not directly related)

fix: readme and translation typos

---

cli/packages/cmd/export.go
docs/cli/commands/export.mdx

I want to have a way to export the variables with the word `export ` at the beggning of each variable.
This is helpful to permit use the variables in bash subprocesses
The diference between use or not the `export` is described on [this post](https://stackoverflow.com/questions/1158091/defining-a-variable-with-or-without-export)
```
infisical export --format=dotenv-export
export INFISICAL_DEV_INT=1
export INFISICAL_DEV_STRING=some-string
```

feat(CLI): adding new export format (dotenv-export)

---

README.md

Update the translations section to say French instead of Frence.

docs(README): nit typo - Frence should say French

---

README.md

Just a tiny typo contribution to the readme. I will try to help with other Brazilian and European Portuguese topics!
Congrats on this fantastic project!

docs(README): fix typo - Portueguese should be Portuguese

---

cli/packages/cmd/root.go
cli/packages/config/config.go
cli/packages/util/constants.go
docs/cli/overview.mdx

Updates the cli to allow for an environment variable named `INFISICAL_URL` this way when a self hosted user is using the CLI they don't need to specify the domain over and over.
The order of respect for domains is as follows
Infisical Cloud Domain -> Environment Variable -> CLI Argument
This way the CLI argument can always override even the environment variable.

Allow INFISICAL_URL to use domain for self-hosted

---

backend/src/middleware/requireIntegrationAuthorizationAuth.ts
frontend/src/components/basic/dialog/ActivateBotDialog.tsx
frontend/src/components/basic/dialog/IntegrationAccessTokenDialog.tsx
frontend/src/components/integrations/IntegrationSection.tsx
frontend/src/pages/integrations/[id].tsx

Previously, users could authorize workspace bots without inputting their PATs for PAT-integrations like Render and Fly.io. This PR adjusts the sequence for that case so that bot authorization is only conducted after PATs are submitted.

Adjust integration bot authorization sequence

---

docs/spec.yaml

The project should have its id exposed.

Include Id on project

---

.github/workflows/release_build.yml
.goreleaser.yaml
cli/packages/util/constants.go

Hi, I'm not 100% sure but this should fix the homebrew error.

fix homebrew

---

frontend/src/context/WorkspaceContext/WorkspaceContext.tsx
frontend/src/views/Settings/ProjectSettingsPage/ProjectSettingsPage.tsx

As discussed with @dangtony98 
1. Removed workspace redirect in context to avoid when missing workspace id in pages like integration
2. Instead we will go for rather an error page with a button to take back to dashboard if api calls fails

feat(ui): removed workspace context redirect and added redirect when ws is deleted

---

frontend/src/const.ts
frontend/src/hooks/index.ts
frontend/src/hooks/useLeaveConfirm.tsx
frontend/src/pages/dashboard/[id].tsx

When a user is leaving the dashboard page and they have any saved changes, they should be asked "Do you want to save?".
[Fixes: https://github.com/Infisical/infisical/issues/118](https://github.com/Infisical/infisical/issues/52)
- `useLeaveConfirm` hook created, this handles both `routeChangeStart` & `beforeunload` events
- `leaveConfirmDefaultMessage` constant
- dashboard uses `useLeaveConfirm` hook and replaces `buttonReady` and `setButtonReady` for `hasUnsavedChanges` & `setHasUnsavedChanges`.
- `handleOnEnvironmentChange` handles environment **ListBox** `onChange`
The following scenarios were covered:
New feature (non-breaking change which adds functionality)

feat(ui): save changes when user leaving dashboard

---

backend/src/controllers/v1/authController.ts
backend/src/controllers/v2/authController.ts
backend/src/helpers/user.ts
backend/src/models/user.ts
backend/src/routes/v2/users.ts
backend/src/templates/emailVerification.handlebars
backend/src/templates/newDevice.handlebars
docs/self-hosting/configuration/envars.mdx

This PR adds an alert for whenever a new device is detected for a login. Under-the-hood:
- We record all device info (consisting of IP and user-agent) that a user uses to login.
- Use that info to detect new device logins and alert users about that.

New device (IP and user agent) login detection and alert

---

README.md

I was taking a hard look at your README yesterday because I think it's fantastic and we were mimicking it for our own open-source project https://github.com/Mirrorful/mirrorful (hope you don't mind.) Wanted to pay it forward by fixing the small typos I noticed.
- Fix the 'development' typo in sub header of README and do not hyphenate use-cases.

docs: fix nit typos in README

---

backend/src/integrations/sync.ts
backend/src/routes/v2/workspace.ts
backend/src/services/EventService.ts
docs/integrations/cloud/vercel.mdx

This PR patches some previously-failing edge-cases for syncing envars to Vercel that didn't work for some users:
- New envars synced to Vercel will default to type `encrypted`.
- Existing envars in Vercel that are updated via sync from Infisical to Vercel will default to the type of the existing envar in Vercel.
- Infisical will not update envars in Vercel of type `sensitive` since they can only be modified by Vercel's deployment systems.

Patch Vercel case where secrets can be of type plain and sensitive

---

cli/packages/cmd/cmd_test.go
cli/packages/cmd/run.go
cli/packages/cmd/secrets.go

This PR adds some more reserved env vars as well as support for reserved prefixes like `XDG_` which shouldn't be overwritten by infisical. 
There are probably more vars that should be reserved but I think the current ones should cover most cases. 
The PR also micro-improves the generation of the secrets map by preallocating its size.
https://github.com/jon4hz/infisical/blob/4a72d725b1038ea86d1cc9888bf78216658682bc/cli/packages/cmd/cmd_test.go
---

Improve env filter

---

cli/packages/util/config.go
cli/packages/util/helper.go

Currently `infisical` only searches in the current directory for a `.infisical.json` file. This PR adds a simple find function, to search for that config file in all parent directories. This way it doesn't matter if you are in a subdirectory of your repo, you'll still be able to execute `infisical` without any issue. 
```sh
infisical init
mkdir test
cd test
infisical run -- env
```
---

feat: search for workspace config in parent dir

---

cli/packages/cmd/run.go

Currently `infisical` doesn't support executing aliases as single command. 
The following script fails but should not imo:
```bash
alias ll="ls -l"
infisical run -- ll # fails
infisical run --command ll # works
```
The script fails because infisical tries to lookup `ll` in the `$PATH` which is impossible, because it's only an alias. If I executed it using `infisical run --command ll` it would have worked, because `infisical` seems to spawn a subshell when the `--command` arg is used. I think this is a bit intuitive and confusing.
This can be fixed if we always start a subshell to execute the command. Is there any reason that speaks against doing that? 
I also fixed a bug on windows, if you use something like "Git Bash", which sets the `$SHELL`  variable. At the moment `infisical` ignores …

fix: always execute cmd in subshell

---

cli/packages/cmd/init.go

Pretty prints new created workspace files. JSON-Indent is set to 4 spaces. 
None :(
```json
{"workspaceId":"123456789","defaultEnvironment":"","gitBranchToEnvironmentMapping":null}
```
```json
{
"workspaceId": "123456789",
"defaultEnvironment": "",
"gitBranchToEnvironmentMapping": null
}
```
---

fix: pretty print workspace file

---

cli/packages/cmd/export.go
cli/packages/cmd/run.go
cli/packages/cmd/secrets.go
cli/packages/util/helper.go
cli/packages/util/secrets.go
cli/packages/util/secrets_test.go
cli/packages/util/testdata/infisical-branch-env.json
cli/packages/util/testdata/infisical-default-env.json
cli/packages/util/testdata/infisical-no-matching-branch-env.json
docs/cli/project-config.mdx

I'm not sure if this is intended but at the moment `infisical` completely ignores the `defaultEnvironment` from the workspace file. This PR adds proper support for this config option. At first, it checks the env-branch mapping and if it can't find anything there, it returns the `defaultEnvironment` instead of an empty string. 
Added some test cases to cover the changes. 
---

fix: properly support default environment

---

docs/integrations/overview.mdx

We have AWS and AZURE integrations. So, AWS and AZURE (comming soon) is removed from the docs.

update AWS and AZURE integrations

---

docs/self-hosting/deployments/linux.mdx

Correct port used for running web interface for self-hosted docker container.
Simplify download of nginx config by avoiding cd'ing into nginx directory and back out again.
No testing performed due to documentation-only change
---

Correct port in self-host documentation and simplify downloading nginx config

---

backend/src/controllers/v1/integrationAuthController.ts
backend/src/controllers/v1/integrationController.ts
backend/src/helpers/integration.ts
backend/src/integrations/apps.ts
backend/src/integrations/exchange.ts
backend/src/integrations/index.ts
backend/src/integrations/refresh.ts
backend/src/integrations/sync.ts
backend/src/integrations/teams.ts
backend/src/models/integration.ts
backend/src/models/integrationAuth.ts
backend/src/routes/v1/integrationAuth.ts
backend/src/services/IntegrationService.ts
backend/src/variables/integration.ts
frontend/src/hooks/api/integrationAuth/index.tsx
frontend/src/hooks/api/integrationAuth/queries.tsx
frontend/src/hooks/api/integrationAuth/types.ts
frontend/src/pages/integrations/[id].tsx
frontend/src/pages/integrations/circleci/create.tsx
frontend/src/pages/integrations/flyio/create.tsx
frontend/src/pages/integrations/github/create.tsx
frontend/src/pages/integrations/gitlab/create.tsx
frontend/src/pages/integrations/heroku/create.tsx
frontend/src/pages/integrations/netlify/create.tsx
frontend/src/pages/integrations/render/create.tsx
frontend/src/pages/integrations/travisci/create.tsx
frontend/src/pages/integrations/vercel/create.tsx

This PR:
- Fixes the create integration page crashing for all integrations whenever a user connects to an integration where they don't currently have any projects there (previously this would cause a client-side recurring crash/error).
- Adds support for groups in the GitLab integration. Previously, the GitLab integration only worked for individual projects but now users can select whether or not they want to do an `individual` or `group` integration and, if they pick the `group` option, then they can select which `group` and subsequently projects from that `group`.

Patch create integration page on no integration projects and add support for groups in GitLab integration

---

backend/src/config/index.ts
backend/src/controllers/v1/signupController.ts
backend/src/controllers/v2/authController.ts
backend/src/helpers/nodemailer.ts
backend/src/routes/status/status.ts
frontend/package-lock.json
frontend/package.json
frontend/src/components/signup/TeamInviteStep.tsx
frontend/src/components/v2/EmailServiceSetupModal/EmailServiceSetupModal.tsx
frontend/src/components/v2/EmailServiceSetupModal/index.tsx
frontend/src/components/v2/index.tsx
frontend/src/hooks/api/serverDetails/index.ts
frontend/src/hooks/api/serverDetails/queries.tsx
frontend/src/hooks/api/serverDetails/types.ts
frontend/src/pages/signup.tsx
frontend/src/pages/verify-email.tsx
frontend/src/views/Settings/OrgSettingsPage/components/OrgIncidentContactsTable/OrgIncidentContactsTable.tsx
frontend/src/views/Settings/OrgSettingsPage/components/OrgMembersTable/OrgMembersTable.tsx
frontend/src/views/Settings/PersonalSettingsPage/SecuritySection/SecuritySection.tsx

This PR will remove the need for SMTP for the very first account that gets added to Infisical self-hosted. This improves several areas.
-  Reduce confusion for self-hosters by allowing them to create an account right away
- Allows one click deploys because now you do not need smpt for account creation
- Allows users to quickly play with self hosting without needing to go through the process of adding smtp  
When SMTP is not configured, the user will see a pop notifying them that the action cannot be completed because it requires email service.
During account creation, if email service is not set up, email confirmation will be skipped. 
manually tested when email is set up and not setup
```sh
```
---

Remove smtp require for selfhost setup

---

docs/self-hosting/overview.mdx

- [Environment variables doc](https://infisical.com/docs/self-hosting/configuration/envars) link was broken in [Self-hosting Overview doc](https://infisical.com/docs/self-hosting/overview) page.
- ![image](https://user-images.githubusercontent.com/1592319/226790168-eefb4400-c5d5-4d08-816a-dbe971d86557.png)
- No need to test.
---

Fixed broken docs link

---

frontend/src/views/Settings/OrgSettingsPage/OrgSettingsPage.tsx

There is a typo, when a user is deleted from an organization, a notification appears on bottom right corner of the screen which says "***Successfully removed used from org***". 
This PR fixes this typo. "***used -> user***"
🚀 🚀

Typo: User remove from Organization notification typo

---

frontend/src/components/dashboard/DeleteActionButton.tsx

https://github.com/Infisical/infisical/issues/367
- This PR removes the "Delete Key" modal when deleting a secret in the dashboard. There is already a "Save changes" button for this one so it is no longer necessary.  This will make deleting multiple secrets faster.
1. Go to dashboard where all the secrets are listed
2. Click the delete button 
```sh
```
---

[Adjustment][Sheen] removed prompt when deleting secret

---

helm-charts/infisical/templates/NOTES.txt

```bash
$ kubectl get all -n {{ .Release.Namespace }}
```
In this statement, the namespace is specified and output.
When using the helm command below, there is no output because the `-n` namespace option is not given.
```bash
$ helm status {{ .Release.Namespace }} {{ .Release.Name }}
$ helm get all {{ .Release.Namespace }} {{ .Release.Name }}
$ helm uninstall {{ .Release.Namespace }} {{ .Release.Name }}
```
```sh
```
---

Add namespace option for using helm

---

docs/cli/usage.mdx

Update CLI usage docs to showcase the ability to inject environment variables in shell aliases
Added a section in `docs/cli/usage.mdx` to demonstrate how environment variables from Infisical can be injected into custom shell aliases using `infisical run --command` command.
N/A
---

Add example in CLI usage docs to show how to utilize secrets in shell aliases

---

docker-compose.dev.yml
frontend/package-lock.json

Fixed docker compose dev failing due to missing next-i18n config file. This has been removed due to migration towards react-i18next
```sh
```
---

fix: docker-compose failing due to missing frontend i18n file

---

backend/src/integrations/sync.ts
frontend/src/components/integrations/Integration.tsx
frontend/src/pages/integrations/gitlab/create.tsx

Previously the GitLab integration synced environment variables to the default (all) environment in GitLab; this PR adds support for being able to specify a custom environment scope for this integration for folks.
---

Add support for custom environments in GitLab integration

---

frontend/README.md
frontend/src/components/v2/Card/Card.tsx
frontend/src/components/v2/DeleteActionModal/DeleteActionModal.tsx

**Fixes**: https://github.com/Infisical/infisical/issues/594
Delete tag card title was overflowing when a user creates a tag with a long name. I have added `break-words` css class to ensure that content does not flow outside the containing div element.
Along with the above fix, I have also corrected port number the README file for local development setup
Before:
After:
```sh
```
---

fix(ui): fixed tags overflow in delete card

---

frontend/src/components/v2/Select/Select.tsx
frontend/src/layouts/AppLayout/AppLayout.tsx

**Fixes**: https://github.com/Infisical/infisical/issues/594
The project list dropdown in the main dashboard is not having any scroll as of now. This makes the UI a bit bloated when a user adds more than a few projects. I am now adding a scroll bar to the list to improve the user experience.
Along with this, I have updated the up and down arrow icons in the `Select` dropdown component. It was using a different icon for the up arrow and a different icon for the down arrow. I have made it consistent now
```diff
- faChevronUp
+ faCaretUp
```
> I have also moved the `Add Project` button to the top of the list instead of the bottom otherwise It will not be visible when there are multiple projects. Ideally, this item should be fixed during the dropdown scroll but that change is gonna take me …

fix(ui): fixed scroll on project list selection

---

frontend/src/views/Settings/ProjectSettingsPage/ProjectSettingsPage.tsx

There was [a commit made a few days ago](https://github.com/Infisical/infisical/commit/2bae6cf084a7044142aa4fc8e24ba45804bb595a#diff-566693723d6f3823491cc7715cfaae938ba0fc1c1af729eb33f1292e0c4d71e3R93) which changed the behavior of the frontend to deny users the ability to add custom environments if they were not using Infisical Cloud (on the [app.infisical.com](https://app.infisical.com) domain)
I believe this to be accidental, since the previous code explicitly allowed this.
---
I have tested my changes, and they work without issue.

Allow custom environments in self-hosted instances

---

backend/src/controllers/v1/membershipOrgController.ts
backend/src/controllers/v1/workspaceController.ts
backend/src/controllers/v2/environmentController.ts
backend/src/ee/controllers/v1/organizationsController.ts
backend/src/ee/routes/v1/organizations.ts
backend/src/ee/services/EELicenseService.ts
backend/src/helpers/organization.ts
backend/src/helpers/workspace.ts

Previously, Infisical only considered feature limitations (paywall) at the organization-level which is insufficient/inconsistent with the actual pricing.
This PR adds support for applying limitations at the workspace-level (e.g. number of environments allowed on a select tier in Infisical Cloud); it works by allowing the frontend to query for an organization's plan and (optionally) a specific workspace in that organization.
---

Update getPlan to consider the user's current workspace

---

backend/src/ee/services/EELicenseService.ts
frontend/src/components/v2/UpgradePlanModal/UpgradePlanModal.tsx
frontend/src/pages/activity/[id].tsx
frontend/src/views/DashboardPage/DashboardPage.tsx
frontend/src/views/Settings/OrgSettingsPage/OrgSettingsPage.tsx

This adds the formal paywall to the point-in-time recovery feature (PIT) in self-hosted and ensures that the paywall redirects to the contact sales page.
To note, PIT was always under `EE` but not yet paywalled till now.
---

Add paywall for PIT and redirect paywall to contact sales in self-hosted

---

docs/cli/commands/run.mdx

Added the --path flag to the [infisical run](https://infisical.com/docs/cli/commands/run) docs.  It was previously missing.
I did not run any tests but assume it will be fine as it's just a basic content update to the docs.
---

add --path flag to docs

---

docs/contributing/overview.mdx
docs/self-hosting/configuration/envars.mdx

Fixed the description of the `CLIENT_SLUG_VERCEL` environment variable (was mentioning Netlify instead of Vercel).\
Added the link to the pull request documentation in the contribution overview.
Checked the local rendering of the relevant MDX files to make sure the changes where added correctly.
---

fix(docs): Wrong integration name and missing link

---

frontend/src/components/login/InitialLoginStep.tsx
frontend/src/components/signup/CodeInputStep.tsx
frontend/src/components/signup/EnterEmailStep.tsx
frontend/src/components/signup/UserInfoStep.tsx
frontend/src/pages/password-reset.tsx
frontend/src/pages/verify-email.tsx

Resolves #415 
Enable users to press `Enter` in these page:
- /signup
- /login
- /verify-email
**Sign Up**
https://github.com/Infisical/infisical/assets/32460534/2072317e-0740-43d8-87e5-0dbb89d9ca0e
**Login**
https://github.com/Infisical/infisical/assets/32460534/30e301e9-b85c-4c7a-851e-5123d46102c3
**Forgot Password** (refer https://github.com/Infisical/infisical/pull/711#issuecomment-1627628754 for complete demo)
https://github.com/Infisical/infisical/assets/32460534/d73d1bab-48c5-41cc-be92-5d6f647149c2
```sh
```
---

fix: enable users to press `Enter` in forms

---

frontend/src/context/SubscriptionContext/SubscriptionContext.tsx
frontend/src/views/Settings/BillingSettingsPage/components/BillingCloudTab/PreviewSection.tsx

This PR patches the subscription context to get the id of the current organization from `useOrganization` hook instead of `useWorkspace` because the latter is `undefined` when the user is at the organization top-level view.
---

Fix subscription context get organization from useOrganization

---

docs/mint.json

This PR removes each SDK page in the documentation in favor of each SDK's separate `README` on GitHub — it's difficult to maintain documentation across each avenue.
---

Remove individual SDK pages from docs

---

cli/packages/cmd/vault.go

The CLI `vault` and `vault set` commands were missing trailing `\n`, which isn't very comfortable for users (see the screenshot below, taken in bash):
Building and launching the CLI locally
---

fix(cli): Missing trailing linebreak in vault commands

---

backend/src/controllers/v2/usersController.ts
backend/src/controllers/v3/authController.ts
backend/src/models/user.ts
backend/src/routes/v2/users.ts
frontend/public/locales/en/translations.json
frontend/src/hooks/api/users/index.tsx
frontend/src/hooks/api/users/queries.tsx
frontend/src/hooks/api/users/types.ts
frontend/src/views/Login/components/InitialStep/InitialStep.tsx
frontend/src/views/Settings/OrgSettingsPage/components/OrgAuthTab/OrgSSOSection.tsx
frontend/src/views/Settings/OrgSettingsPage/components/OrgTabGroup/OrgTabGroup.tsx
frontend/src/views/Settings/PersonalSettingsPage/AuthMethodSection/AuthMethodSection.tsx
frontend/src/views/Settings/PersonalSettingsPage/AuthMethodSection/index.tsx
frontend/src/views/Settings/PersonalSettingsPage/PersonalAuthTab/PersonalAuthTab.tsx
frontend/src/views/Settings/PersonalSettingsPage/PersonalAuthTab/index.tsx
frontend/src/views/Settings/PersonalSettingsPage/PersonalGeneralTab/PersonalGeneralTab.tsx
frontend/src/views/Settings/PersonalSettingsPage/PersonalGeneralTab/index.tsx
frontend/src/views/Settings/PersonalSettingsPage/PersonalSecurityTab/index.tsx
frontend/src/views/Settings/PersonalSettingsPage/PersonalTabGroup/PersonalTabGroup.tsx
frontend/src/views/Settings/PersonalSettingsPage/SecuritySection/MFASection.tsx
frontend/src/views/Settings/PersonalSettingsPage/SecuritySection/index.tsx
frontend/src/views/Settings/PersonalSettingsPage/UserNameSection/UserNameSection.tsx

This PR adds an option to user settings for users to be able to change their authentication methods. For example, users can change from logging in via `Email` to `Google`.
---

Add user support for changing authentication methods

---

backend/src/helpers/workspace.ts
backend/src/utils/setup/backfillData.ts
backend/src/validation/workspace.ts

This PR patches the IP allowlisting implementation that was faulty for `IPv6` addresses. More specifically, it:
- Runs blocklist logic against the correct type determined off the IP address (previously, it would run an `IPv6` IP against blocklist logic for the `IPv4` format).
- Backfills workspace trusted IPs to also add default `IPv6 CIDR`.
- Initializes `IPv4 CIDR` and `IPv6 CIDR` upon new workspace creation.
---

Update IP allowlist implementation

---

frontend/src/pages/org/[id]/overview/index.tsx

1. Added loading skeleton cards for org overview page showing workspace explore cards
2. Fixed a small bug showing empty workspace when workspace are loading in overview page
3. Converted function to react components code syntax simplier
```sh
```
---

feat: added loading state for org overview page

---

backend/src/integrations/sync.ts

Resolves #794 
What happen is the previous implementation only sends env vars to update the app. This causes the app to reset to the default settings.
Fetch the current settings of the app first and include it in the update request.
```sh
```
---

fix: digital ocean reset settings on sync

---

docs/mint.json

Resolved the issue where clicking on the "Blog" section in the Doc API reference was redirecting to a 404: NOT_FOUND page. Now, it correctly displays relevant blog posts related to the platform.
Fix was made on the highlighted Blog tab:
Now linking to this Blog page when the Blog tab is clicked on:
Changed the link- https://blog.infisical.com/ that is  leading to the  404: NOT_FOUND page 
To this working link -https://infisical.com/blog
Video link performing the described functionality.
https://www.loom.com/share/e01c9662f1504a6ea983d061d082d8b2?sid=5164829b-61f9-4d1b-a253-4761cc53bbac
- [✓ ] Bug fix
---
- [ ✓] I have read the [contributing guide](https://infisical.com/docs/contributing/overview), agreed and acknowledged the [code of …

fix: Blog Section in Doc API Reference Redirects to 404

---

frontend/src/views/DashboardPage/components/SecretDropzone/SecretDropzone.tsx

1. A small bug fix when clicking `select all` button copy secret modal in dashboard the form is not getting dirty
```sh
```
---

fix: added dirty flag to set fn in dropzone paste secret

---

backend/Dockerfile

Backend image is always failed to start while running on non-root environment (e.g. OpenShift). Previous attempt to add recursive chown to `/app` folder causing way slower build times and it turns out I didn't have to change the ownership and just changed the environment variable for the npm cache folder to the 'node' user home folder.
```sh
```
---

fix: backend image failed to start due to npm cache permission

---

backend/src/utils/auth.ts
frontend/src/hooks/api/users/queries.tsx
frontend/src/views/Login/LoginSSO.tsx
frontend/src/views/Login/components/MFAStep/MFAStep.tsx
frontend/src/views/Login/components/PasswordStep/PasswordStep.tsx

Currently, if a user who registered via regular email-password method (without enabling any SSO authentication methods in their User Settings) logs in with an SSO authentication method, then they are taken to an empty page with `{}`; this has been very confusing for folks and even looks like a bug.
This PR adds linking such that, if an existing user with the same email as the SSO authenticated method is detected, then they are prompted to enter their password to authenticate with Infisical — As part of this login process, the SSO method of authentication is switched on for the user.
---

Add linking for existing users without SSO enabled logging in via SSO

---

frontend/src/views/DashboardPage/components/SecretInputRow/SecretInputRow.tsx

Makes 2 changes to the way tags are displayed on the dashboard page.
1. **Displays tags in alphabetical order** (currently it looks like tags are displayed in the order in which they were added, which doesn't seem like a useful ordering)
3. **Makes sure that each tag has a consistent color across all rows** (currently the first tag on each row has one color, the second another, the third another etc., but this is not a useful coloring)
Ran locally and compared the main branch to this PRs branch
Before this PR:
After this PR:
I also checked that the colors and the sorting stayed correct when (a) adding and removing existing tags from secrets and (b) creating new tags and adding and removing the new tags
---

Improve tag colors and sorting on dashboard page

---

backend/src/controllers/v2/environmentController.ts
backend/src/routes/v2/environment.ts
frontend/src/hooks/api/workspace/index.tsx
frontend/src/hooks/api/workspace/queries.tsx
frontend/src/hooks/api/workspace/types.ts
frontend/src/views/Settings/ProjectSettingsPage/components/EnvironmentSection/EnvironmentTable.tsx

Fixes #841 
Allows users to re-order their environments on the project settings page. These changes are then reflected in the ordering of columns on the secrets dashboard and in other places throughout Infisical.
Users can specify their desired ordering using the new up and down arrows on the project settings page
The up arrow on the top row, and the down arrow on the bottom row are disabled (and you can't click on them)
This is implemented using a new backend route `PATCH /v2/{workspaceId}/environments` which takes two environments (defined by name and slug) and swaps the order of them in the database.
https://github.com/Infisical/infisical/assets/16603122/d5966031-b47a-449c-a13d-5767cece2ee9
There is technically a bug with the implementation of this feature where if two users are …

Adds user customizable environment ordering

---

backend/src/helpers/secrets.ts

1. Integration on interpolation if key not found return empty and then console error so that can be tracked
```sh
```
---

fix(integration): instead of throwing error console and return empty string on interpolation

---

frontend/Dockerfile

Frontend image is always displaying some error logs while running on non-root environment (e.g. OpenShift). Previous attempt to add recursive `chmod` to `/app` folder causing way slower build times and it turns out I didn't have to `chmod` for all files and just `chmod` for files inside `/app/.next/server` and `/app/.next/static` folder that affected by `/app/scripts/replace-variable.sh`.
```sh
```
---

fix: frontend image displaying some errors due to sed write permission

---

frontend/src/views/SecretOverviewPage/SecretOverviewPage.tsx

This feature makes it possible to sort the secrets by name on the "Secrets Overview" page.
Related issue: https://github.com/Infisical/infisical/issues/877
Demo video: https://share.vidyard.com/watch/wC1GNWuVeLtqwmXfrmzRqX?
1. Go to secrets overview
2. Click on the arrow icon in the table header at "name"
---

feat: make secrets overview sortable

---

backend/src/controllers/v2/secretsController.ts
backend/src/ee/models/secretVersion.ts
backend/src/helpers/secrets.ts
backend/src/models/secret.ts
frontend/src/hooks/api/secrets/queries.tsx

This PR changes the approach to distinguishing between `signup` and other normal secrets for the purposes of telemetry. More specifically:
- When a new user signs up, then the secrets added to their default project are tagged `metadata.source = "signup"`.
- When a user updates the value of an existing secret via dashboard, then the `metadata.source` is `$unset` as this is no longer considered a `signup` secret.
- When the user fetches secrets back for their dashboard (moved from `GET v2/secrets` to `GET v3/secrets` then (1) if all the secrets are `signup` secrets, then it won't send telemetry; (2) if there is at least 1 non-signup secret, then it will send the number of non-signup secrets to telemetry.
---

Update signup secret distinction/tagging for better telemetry

---

backend/src/routes/v2/environment.ts
docs/api-reference/endpoints/environments/create.mdx
docs/api-reference/endpoints/environments/delete.mdx
docs/api-reference/endpoints/environments/list.mdx
docs/api-reference/endpoints/environments/update.mdx
docs/api-reference/endpoints/secrets/list.mdx
docs/api-reference/endpoints/secrets/read.mdx
docs/mint.json

This PR:
- Adds `API_KEY` as a form of authentication for the CRUD environment endpoints.
- Adds the environment endpoints to the REST API documentation.
---

Expose CRUD Environment Operations to Public REST API

---

backend/src/controllers/v3/secretsController.ts
backend/src/helpers/secrets.ts
backend/src/interfaces/services/SecretService/index.ts
backend/src/routes/v3/secrets.ts
frontend/src/hooks/api/secrets/queries.tsx

This PR rewires the dashboard to pull secrets from `v3/secrets` instead of `v2/secrets`.
Previously, `v3/secrets` did not support the `folderId` parameter like `v2/secrets` which led to bugs on the dashboard when attempting the transition; the simple change in this PR is:
- If `folderId` is present, then it is used in the query for secrets.
- If `folderId` is not present, then default to the `secretPath` parameter to obtain the `folderId`; if `secretPath` is not present, then the default path is set to `/`.
---

Rewire dashboard to pull from v3/secrets with folderId support

---

helm-charts/secrets-operator/templates/deployment.yaml

This PR fixes issue #922 It removes the extra line feeds on lines 60-61, 67-68, 83-84 and 98-99. This is a small fix, with no code changes, only the deployment.yaml file was updated to fix formatting issue.
I have tested the helm deploy locally
```sh
$ helm install infisical-sm helm-charts/secrets-operator/
NAME: infisical-sm
LAST DEPLOYED: Thu Aug 31 17:39:35 2023
NAMESPACE: infisical
STATUS: deployed
REVISION: 1
TEST SUITE: None
```
---

Fix for issue#922 - helm chart for secrets-operator

---

backend/src/integrations/sync.ts

This PR adds support for syncing secrets containing `/ ` to the AWS parameter store integration.
Previously, you could define a path (to prepend) like `/project/name/` to a secret like `test1/test2` to be synced for this integration. Now, doing so syncs the secret under `/project/name/test1/test2` to AWS parameter store.
---

Add support for syncing secrets containing / to AWS parameter store integration

---

frontend/src/hooks/api/integrations/queries.tsx
frontend/src/pages/integrations/aws-parameter-store/create.tsx
frontend/src/pages/integrations/aws-secret-manager/create.tsx
frontend/src/pages/integrations/azure-key-vault/create.tsx
frontend/src/pages/integrations/circleci/create.tsx
frontend/src/pages/integrations/cloud-66/create.tsx
frontend/src/pages/integrations/codefresh/create.tsx
frontend/src/pages/integrations/digital-ocean-app-platform/create.tsx
frontend/src/pages/integrations/flyio/create.tsx
frontend/src/pages/integrations/gcp-secret-manager/create.tsx
frontend/src/pages/integrations/gcp-secret-manager/pat/create.tsx
frontend/src/pages/integrations/github/create.tsx
frontend/src/pages/integrations/gitlab/create.tsx
frontend/src/pages/integrations/hashicorp-vault/create.tsx
frontend/src/pages/integrations/heroku/create.tsx
frontend/src/pages/integrations/laravel-forge/create.tsx
frontend/src/pages/integrations/netlify/create.tsx
frontend/src/pages/integrations/northflank/create.tsx
frontend/src/pages/integrations/render/create.tsx
frontend/src/pages/integrations/supabase/create.tsx
frontend/src/pages/integrations/teamcity/create.tsx
frontend/src/pages/integrations/terraform-cloud/create.tsx
frontend/src/pages/integrations/travisci/create.tsx
frontend/src/pages/integrations/windmill/create.tsx

In a previous PR, we removed support for `null` `appId` and `app` values for the endpoint responsible for creating a PAT integration; this caused issues for integrations that are still sending `null` values over during the creation process.
This PR fixes this issue by not sending any values at all if `appId` and `app` are not relevant.
---

Fix null appId argument for creating PAT integration

---

frontend/src/components/v2/FormControl/FormControl.tsx
frontend/src/components/v2/Tooltip/Tooltip.tsx
frontend/src/views/Settings/ProjectSettingsPage/components/WebhooksTab/AddWebhookForm.tsx

This PR updates the placeholder for the secret path to be less confusing and includes a helper text telling users that they can use glob patterns. It also adds a tooltip containing examples of various glob patterns they can use.
Fixes Issue: [#946](https://github.com/Infisical/infisical/issues/946)
This screenshot shows the design for the secret path field, The input field shows the updated placeholder wth the helper texts and also an info icon which the user clicks to  show examples of glob patterns

Add helper text and tooltip for secret path

---

cli/packages/cmd/secrets.go

[See](https://github.com/Infisical/infisical/issues/937)

fix: `path` option for `secret get` sub cmd

---

backend/Dockerfile

This PR fixes the root cause of #984. By calling node, instead of npm to start the backend the following items are addressed:
* issue #984 is no longer an issue becuase npm does not try to modify the npm cache
* solves issue with backend pods taking a long time to terminate
*  (npm does not pass SIGTERM and can cause issues with the app in k8s)
* see [Dockerfile Good Practices for Node and NPM](https://adambrodziak.pl/dockerfile-good-practices-for-node-and-npm#use-node-not-npm-to-start-the-server)
See Slack Thread: https://infisical-users.slack.com/archives/C04BSBMQAQ7/p1694706353813279?thread_ts=1694636663.038499&cid=C04BSBMQAQ7 for additional details.
This PR also contains a small tweak to the npm command in the production stage which cuts ~65MB from the final image per the "Dockerfile …

changing CMD for Dockerfile  to address issue #984

---

helm-charts/infisical/Chart.yaml
helm-charts/infisical/values.yaml

Updated helm values.yaml to set frontend resource requests to a high enough, but still moderately conservative value (150m) to allow page resources to consistently load.
Fixes #1005.
```sh
Deployed helm chart with frontend.resources.requests.cpu: 150m
2023-09-19T02:12:01.256298054Z ---------------------------------------------------------------------
SUCCESS: helm upgrade --history-max=5 --install=true --namespace=infiscial --timeout=10m0s --values=/home/shell/helm/values-infisical-0.3.3.yaml --version=0.3.3 --wait=true infiscial /home/shell/helm/infisical-0.3.3.tgz
---------------------------------------------------------------------
Verified login and page resources load consistently in browser after deployment.
```
---

Update cpu default frontend value.  Fixes #1005.

---

backend/src/utils/auth.ts
backend/src/variables/integration.ts

This PR updates the method used to obtain a user's email for GitHub SSO login by making an extra call to `/user/emails` endpoint in GitHub API.
---

Update method to obtain email for GitHub SSO

---

backend/src/helpers/integration.ts
backend/src/integrations/exchange.ts
frontend/src/pages/integrations/gitlab/create.tsx

Previously, the integration to self-hosted instances of GitLab was broken because Infisical wasn't keeping track of the self-hosted URL after the OAuth `code-token` exchange.
This PR fixes this issue so now it is possible to sync secrets to self-hosted GitLab 😄
---

Patch self-hosted gitlab integration

---

cli/go.mod
cli/packages/cmd/secrets.go

Fixes #1003 
Removes strings.ToUpper() formatting on the secrets key for get/set.
```sh
[scott@samus infisical]$ ./infisical-merge secrets set foo=bar
┌─────────────┬──────────────┬────────────────┐
│ SECRET NAME │ SECRET VALUE │ STATUS         │
├─────────────┼──────────────┼────────────────┤
│ foo         │ bar          │ SECRET CREATED │
└─────────────┴──────────────┴────────────────┘
[scott@samus infisical]$ ./infisical-merge secrets get foo
┌─────────────┬──────────────┬─────────────┐
│ SECRET NAME │ SECRET VALUE │ SECRET TYPE │
├─────────────┼──────────────┼─────────────┤
│ foo         │ bar          │ shared      │
└─────────────┴──────────────┴─────────────┘
[scott@samus infisical]$ ./infisical-merge secrets get ingress.hosts.0 …
```

Fix no Auto-Capitalization for secrets get/set. Fixes #1003

---

backend/src/integrations/sync.ts

Previously, the Vercel integration for custom preview branches was flaky because it had an incorrect filtering condition when comparing secrets pulled from Vercel to those in Infisical during the sync operation.
This PR corrects the condition.
To note, as with other integrations, in the future we will need to optimize integrations a lot.
---

Patch Vercel integration for custom preview branches

---

frontend/src/components/navigation/NavHeader.tsx

Resolved directory in dashboard showing folder name as you nest
Closes #1039 
```sh
```
---

fix: resolved dashboard showing text folderName in nesting folders

---

backend/src/index.ts

This should properly close out db connections and prevent slow shutdown during kubernetes upgrades
Nit:
The bull queue tries to reconnect even after .close() is called. Couldn't find a fix for it, so we'll come back to this.
Tested localy and the clean up is triggered properly 
---

handle siginit and sigterm

---

helm-charts/infisical/Chart.yaml
helm-charts/infisical/README.md
helm-charts/infisical/templates/backend-deployment.yaml
helm-charts/infisical/templates/frontend-deployment.yaml
helm-charts/infisical/values.yaml

Hello,
I use the helm chart to deploy Infisical in Kubernetes and I require to use affinity to move pods on specific nodes. This PR brings this feature in the helm chart.
Thank you for your work!
---

feat(helm-chart): allow to provide affinity values for the pods

---

backend/src/helpers/organization.ts
backend/src/helpers/user.ts
backend/src/helpers/workspace.ts
frontend/src/hooks/api/users/queries.tsx
frontend/src/layouts/AppLayout/AppLayout.tsx
frontend/src/views/Login/Login.utils.tsx
frontend/src/views/Org/NonePage/NonePage.tsx
frontend/src/views/Settings/BillingSettingsPage/components/BillingCloudTab/PreviewSection.tsx
frontend/src/views/Settings/ProjectSettingsPage/components/SecretTagsSection/SecretTagsSection.tsx

This PR:
- Correctly implements MongoDB transactions for the delete user, organization, and project operations.
- Fixes an issue to do with flaky organization deletion behavior due to not accounting for wiping the `organizationId` off local storage.
---

Patch delete user, org, project session impl and account for organizationId in local storage

---

cli/packages/cmd/secrets.go

Fixes https://github.com/Infisical/infisical/issues/1075 .
Currently trying out the project but I ran into this issue too. Felt like a nice to have to improve experience. 
This PR adds a new `--path` flag to the `secrets generate-example-env` command. As such it can be used like this:
```sh
./infisical secrets generate-example-env --path=users/lanre
```
```sh
./infisical secrets set PROJECT=oops --path users/lanre
./infisical secrets generate-example-env --path=users/lanre
```
---

[ENG-179] Add suport for --path for the secrets generate-example-env command

---

frontend/src/views/SecretOverviewPage/SecretOverviewPage.tsx

1. Fixed folder in overview not creating automatically when ur one level deep
```sh
```
---

fix:resolved overview page add secret not working when folder not exist in one level deep

---

helm-charts/infisical/Chart.yaml
helm-charts/infisical/templates/backend-deployment.yaml

Hey,
This request fixes an issue introduced with the new rewrite of the helm-chart. The resources part is commented but helm interprets the comment and if you have the key `resources` it computes it as a bad thing.
```sh
```
---

feat(helm-chart): repair usage of resources key

---

frontend/src/views/SecretMainPage/components/SecretListView/SecretItem.tsx

On clicking copy secret if an override is enabled, it copies the original value instead of the override value.
Fixes #1137 
---

Fix bug with copying secret to clipboard with an override

---

docs/cli/scanning-overview.mdx
docs/documentation/platform/audit-logs.mdx
docs/documentation/platform/token.mdx
docs/integrations/cicd/jenkins.mdx
docs/internals/overview.mdx
docs/internals/security.mdx

Some typos fixed in the documentation
My linter also removed some useless trailing spaces in the process
---

Docs: Fixing some typos

---

cli/packages/cmd/run.go

When using `infisical run`, I am often running another command that needs to be processed or consumed by another; such as:
infisical run -- supabase status -o env
The Injecting string was being printed directly to stdout and stopping such scripting from being successful, without further adding tail -n+2.
This change defaults the output to the INFO logging level, which means the behaviour is the exact same for everything; however those who wish can omit this output with -l error|fatal
Fixes #1091 
---

fix: "Injecting..." status string can be omitted by log levels

---

backend/src/helpers/bot.ts
cli/packages/api/api.go

Use RequestError instead of Error class so that error type of `bot_not_found_error` can be parsed from agent side to notify users that e2ee is enabled

parse bot not found in agent

---

cli/packages/cmd/agent.go

When secret templates have a path other than the root, the name of the template needs to be extracted

extract base from template source path

---

frontend/src/pages/integrations/vercel/create.tsx

Fixed issue with selecting the preview environment for the Vercel integration. This was happening because we were passing an empty value to the select item for branch name. 
Closes #1271.
---

Fix: Vercel integration preview environment client side error

---

backend/src/controllers/v1/universalAuthController.ts
backend/src/validation/auth.ts
frontend/src/views/Org/MembersPage/components/OrgIdentityTab/components/IdentitySection/IdentityUniversalAuthForm.tsx

This PR updates the default IP allowlist for universal auth to include consideration for IPv6 addresses via `::/0`; previously it only considered IPv4 addresses with `0.0.0.0/0`.
---

Add IPv6 consideration to default universal auth IP allowlist

---

backend/src/controllers/v1/integrationAuthController.ts
backend/src/controllers/v1/integrationController.ts
backend/src/routes/v1/integrationAuth.ts
backend/src/validation/integrationAuth.ts
frontend/src/hooks/api/integrationAuth/index.tsx
frontend/src/hooks/api/integrationAuth/queries.tsx
frontend/src/hooks/api/integrations/queries.tsx
frontend/src/hooks/api/workspace/queries.tsx
frontend/src/views/IntegrationsPage/IntegrationsPage.tsx

Previously, every new integration of the same category (e.g. Railway) in a project would use the same integration authentication credentials to create that integration. With this PR, whenever you create a new integration, the user is directed to input a new set of authentication credentials to be used for that integration instead of reusing a past one. Put differently, this allows users to use multiple authentication credentials for each integration category instead of being limited to one.
Highlights:
- When an integration is deleted, if there are no other integrations using the same linked integration authentication credential, then the linked authentication credential is also deleted; this is important for backwards compatibility since currently multiple integrations may be linked to …

Enable new integration auth credential for each new integration

---

backend/src/controllers/v3/secretsController.ts
backend/src/helpers/secrets.ts
backend/src/interfaces/services/SecretService/index.ts
backend/src/services/SecretImportService.ts
backend/src/validation/secrets.ts

This PR adds an optional query parameter `version` to both `GET` secret raw and regular endpoints to get a secret by its version if specified.
---

Add version query param to GET secret raw and regular endpoints

---

docs/documentation/platform/project.mdx

Added a tiny info box to make it more clear that secret reminders don't work with personal overrides.
---

(Docs): Personal overrides and secret reminders awareness

---

frontend/src/hooks/api/integrationAuth/types.ts
frontend/src/pages/integrations/vercel/create.tsx

This PR patches the Vercel integration for syncing environment variables to team accounts on Vercel by filling in the missing `teamId` to be passed into the backend to fetch apps for it.
---

Patch Vercel integration for team accounts

---

backend/src/lib/fn/string.ts

This PR removes `async` from the path check for integrations.
---

Remove async from isSamePath check in integration sync

---

backend/src/ee/routes/v1/license-router.ts
backend/src/ee/services/license/license-service.ts
backend/src/ee/services/license/license-types.ts
frontend/src/hooks/api/organization/queries.tsx

This PR includes two updates having to do with the license server / customer portal logic:
- It adds back the redirect endpoint + logic to direct customers to manage their billing/plan information.
- It fixes the free trial endpoint so customers can start free trials in Infisical Cloud
---

Add customer portal redirect and patch free trial endpoint

---

docs/cli/faq.mdx
frontend/src/views/Settings/ProjectSettingsPage/components/ProjectNameChangeSection/ProjectNameChangeSection.tsx

Add a simple button in a Project setting page so, user can easily copy the current Project ID and also added as a FAQ
1. Start the server
1. Select one of the project
1. Goto project setting page
1. There should  be a button that allow user to copy the current project id
---

feat: add copy project id button

---

.github/pull_request_template.md

Fix broken links in the pull request template and added latest contribution guide
NA
---

fix: update broken contribution links

---

backend/src/services/project/project-dal.ts

Fixed bug in list workspaces endpoint. It now correctly returns the organization ID as expected. 
---

(Fix): List workspaces organization ID

---

backend/src/server/routes/v2/organization-router.ts

In the old backend we were returning ID's of workspaces, contrary to what the documentation documentation states. This PR re-adds the missing workspace ID field.  
---

(Fix): Add ID to list workspaces endpoint

---

backend/src/server/routes/v3/secret-router.ts

remove certain python sdk events

---

backend/src/ee/routes/v1/saml-router.ts

This PR updates the Azure SAML integration to not request a specific authentication context. This is inline with Error Code: 75011 where Azure docs suggest "to resolve the problem check with the application developer if they can omit the RequestedAuthnContext element in the request."
---

Add disableRequestedAuthnContext for azure saml

---

backend/src/services/identity-access-token/identity-access-token-service.ts
backend/src/services/identity-ua/identity-ua-service.ts

This PR converts expiry TTLs to `Number` that was incorrect mapped as a side-effect of the Postgres migration initiative
---
- [ x] I have read the [contributing guide](https://infisical.com/docs/contributing/getting-started/overview), agreed and acknowledged the [code of conduct](https://infisical.com/docs/contributing/getting-started/code-of-conduct). 📝

Patch identity access token + client secret TTL

---

frontend/src/views/Settings/ProjectSettingsPage/components/WebhooksTab/WebhooksTab.tsx

This pull request removes the max-width constraint from the WebhooksTab.tsx component to ensure it aligns with the full-width layout pattern of other views, eliminating unused space on larger screens.
The previous 1024px max-width resulted in an inconsistent layout compared to other views. This change resolves the issue and maintains frontend layout consistency.
The testing for this fix involved manual verification in a web browser:
1. Opened the application in a web browser.
2. Navigated to a project > Project Settings > Webhooks tab.
3. Verified that the max-width constraint has been removed.
4. Confirmed that the WebhooksTab now aligns with the full-width layout consistency seen in other views. Ensured that there is no unused space on larger screens.
The change has been visually …

fix(frontend): Remove max-width to match other views

---

backend/src/services/secret-import/secret-import-fns.ts

1. Resolution to a bug reported by couple of users that secret import is throwing 500 error. The root cause was valid folders with empty secrets
```sh
```
---

fix: resolved secret import secrets failing when folder has empty secrets

---

.env.test.example
.github/workflows/release-standalone-docker-img-postgres-offical.yml
.github/workflows/run-backend-tests.yml
backend/.eslintignore
backend/.eslintrc.js
backend/e2e-test/routes/v1/identity.spec.ts
backend/e2e-test/routes/v1/login.spec.ts
backend/e2e-test/routes/v1/project-env.spec.ts
backend/e2e-test/routes/v1/secret-folder.spec.ts
backend/e2e-test/routes/v1/secret-import.spec.ts
backend/e2e-test/routes/v2/service-token.spec.ts
backend/e2e-test/routes/v3/secrets.spec.ts
backend/e2e-test/vitest-environment-knex.ts
backend/package-lock.json
backend/package.json
backend/scripts/create-seed-file.ts
backend/src/db/knexfile.ts
backend/src/db/seed-data.ts
backend/src/db/seeds/1-user.ts
backend/src/db/seeds/2-org.ts
backend/src/db/seeds/3-project.ts
backend/src/db/seeds/4-machine-identity.ts
backend/src/ee/services/license/__mocks__/licence-fns.ts
backend/src/lib/crypto/encryption.ts
backend/src/server/app.ts
backend/src/server/routes/v3/secret-router.ts
backend/src/services/secret/secret-dal.ts
backend/vitest.e2e.config.ts

1. This PR adds api integration test for all secret operations from external entities which includes dashboard, service token (cli) and identity token(sdk)
2. Fixed seed file issue faced when running seeding
3. Resolved a small bug in secret deletion
4. Added ci for running integration test
```sh
```
---

Integration test for secret ops

---

backend/src/ee/routes/v1/scim-router.ts
backend/src/ee/services/permission/permission-service.ts
backend/src/server/plugins/auth/inject-identity.ts
backend/src/server/routes/v3/secret-router.ts
backend/src/services/service-token/service-token-dal.ts
backend/src/services/service-token/service-token-service.ts

1. Email is added back on telemetry posthog event when using service token
2. Fixed eslint warning from scim feature development
```sh
```
---

fix(telemetry): added back email for telemetry when using service token

---

docker-compose.prod.yml

Wait for db service to be healthy before kicking off db-migration and backend services
Fix for Issue #1448 : (Clean install ends in db-migration service completing unsuccessfully)
- Added healthcheck for db service to help other services determine readiness.
- Modified db-migration and backend service definitions to wait on db service to be healthy before proceeding with deployment.
- Ran deployments on my local linux systems (physical and VMs) with different RAM configurations, and on a raspberry pi as well to verify that the deployments are successful, without the mentioned error.
---

Wait for db service to be healthy before kicking off db-migration and backend services

---

frontend/src/components/signup/EnterEmailStep.tsx

Set loading state for button based on send verification email mutation state
fix #1422
Use mutation loading state to show loading for send verification email button.
https://github.com/Infisical/infisical/assets/10532751/0c423494-3e42-4c57-b942-68e4f64eddc1
No new tests are required for this change.
---

fix(signup): set send verification email button loading state

---

backend/src/services/project-membership/project-membership-service.ts

Fixed a 500 status server error occurring when attempting to invite members to a project, when there's only 1 member in the organization. The issue was happening due to our mailing service. When we try to send emails, and the recipients array is empty, it will throw a `No recipients defined` error. 
---

Fix: Invite all members to project when there are no members to invite

---

docker-compose.prod.yml

/data/db doesn't seems to exist, would never persist data otherwise
The default location of postgresql data is /var/lib/postgresql/data, /data/db doesn't exists
- [ x ] Bug fix
Now it persists data

fix postgresql volume path on docker-compose.prod.yml

---

helm-charts/infisical-standalone-postgres/Chart.yaml
helm-charts/infisical-standalone-postgres/templates/jobs-rbac.yaml

The standalone helm chart has an RBAC binding that maps to a non-existent service account, this causes the schema migration init container to fail, resulting in nothing working. 
The message in the init container is:
```
Error from server (Forbidden): jobs.batch "infisical-schema-migration-10" is forbidden: User "system:serviceaccount:infisical:default" cannot get resource "jobs" in API group "batch" in the namespace "infisical"
Error from server (Forbidden): jobs.batch "infisical-schema-migration-10" is forbidden: User "system:serviceaccount:infisical:default" cannot get resource "jobs" in API group "batch" in the namespace "infisical"
Error from server (Forbidden): jobs.batch "infisical-schema-migration-10" is forbidden: User "system:serviceaccount:infisical:default" cannot get resource …
```

fix(helm-charts): standalone chart rbac fix for jobs

---

backend/src/services/secret/secret-service.ts

1. Before duplicate secret delete would fail due to this validation check. Updated the check to allow deleting secret even if there are dup keys
```sh
```
---

fix(server): duplicate secret deletion made possible

---

backend/src/db/knexfile.ts

When running the migration via knex command, we did not have cert support in postgres connection. This PR adds cert support needed to run secure schema migrations

Add postgres cert to migration knex command 

---

backend/src/db/migrations/20240226094411_instance-id.ts

When multiple super admin configs already exist and at least one has a value equal to `ADMIN_CONFIG_UUID` then this migration will fail because it will try to update one of the configs also to ADMIN_CONFIG_UUID. Since two ids cant be the same we get the following error during migration run in helm:
```
migration file "20240226094411_instance-id.ts" failed
migration failed with error: update "super_admin" set "id" = $1 where "id" is not null - duplicate key value violates unique constraint "super_admin_pkey"
update "super_admin" set "id" = $1 where "id" is not null - duplicate key value violates unique constraint "super_admin_pkey"
Key (id)=(00000000-0000-0000-0000-000000000000) already exists.
error: update "super_admin" set "id" = $1 where "id" is not null - duplicate key value violates …
```

patch super user migration

---

cli/agent-config.yaml
cli/packages/api/api.go
cli/packages/api/model.go
cli/packages/cmd/agent.go
cli/packages/cmd/run.go
cli/packages/models/cli.go
cli/packages/util/agent.go
cli/packages/util/secrets.go

This PR introduces custom polling intervals and exec commands. Additionally, now instead of re-rendering the secrets every 5 minutes, we only re-render the secrets when a change has actually happened. When a secret change is detected, 2 things will happen:
1. Secrets are re-rendered. 
2. The exec command (if any) will be executed.
The polling interval will default to 5 minutes if not defined, and if it's defined the minimum value is 60 seconds.
The exec command has support for a custom timeout. This means that if a command fails to execute with X amount of seconds, the execution flow will fail and print an error to the terminal. If no timeout is provided, it will default to 30 seconds.
Both the exec command and polling interval is defined on a template-level. 
```
infisical:
address: …
```

Feat: Agent exec and custom polling interval

---

backend/src/ee/services/audit-log/audit-log-queue.ts
backend/src/server/routes/v1/identity-ua.ts
backend/src/services/identity-ua/identity-ua-service.ts

fix(server): auditlog won't push if retention period is zero

---

cli/packages/util/secrets.go

With the recent commit, infisical cli secrets command started to break due to some type changes. This PR fixes the value which was forgotten to be changed.
cli/main.go file now compiles and runs successfully
---

Fixed mistype from Hash to Etag to fix the cli issue

---

backend/package-lock.json
backend/package.json
backend/src/ee/services/license/license-service.ts
backend/src/server/routes/index.ts

Changed license service to use redis cache keystore
```sh
```
---

feat(server): changed license service to use redis cache keystore

---

frontend/src/components/v2/Menu/Menu.tsx

Refactored `MenuItem` component: Replaced anchor tag with span for improved HTML semantics, resolving console errors without impacting functionality.
Previously, there was <a> tag under <a> tag which is not recommended
Now the html structure
Also there is just some autoformatting in this commit which was not previously formatted according to `prettier-plugin-tailwindcss`
---

Changed <a> to <div> to avoid nested <a>

---

backend/src/services/secret/secret-service.ts
frontend/src/views/SecretMainPage/components/SecretListView/SecretItem.tsx
frontend/src/views/SecretMainPage/components/SecretListView/SecretListView.tsx
frontend/src/views/SecretMainPage/components/SecretListView/SecretListView.utils.ts

Fixes a bug from frontend side, which previously allowed secrets to be renamed to empty string, thus breaking the system as they won't be able to rename or delete that secret again. Added a check to update the key only if it has value.
- TODO
Although this change is done from frontend, but this validation should also be in backend, which restricts the secret name to be sent as empty
Attached video for reference
https://github.com/Infisical/infisical/assets/47269183/d9c7dbd6-7daa-4826-833d-af3020aa6253
---

Stop ability to rename a secret to empty name from frontend

---

backend/src/db/seeds/1-user.ts
backend/src/server/routes/index.ts
backend/src/services/org/org-service.ts
backend/src/services/project-membership/project-membership-dal.ts

- We currently aren't removing project memberships & keys when organization memberships are removed, this PR aims to fix that. This was causing an edge case in the project upgrade, so I thought it would make sense to also fix the root cause while also fixing the project upgrade edge-case. #1535 
- Fixed super admin database seeding. 
---

Fix: Remove project keys & memberships when organization membership is deleted

---

backend/src/services/project/project-queue.ts

- There's an edge case where project upgrades may fail. This happens when a user in a project no longer has an organization membership. The root cause of this is because we don't remove project memberships and project keys when an organization membership is deleted. I have raised a PR to fix the project memberships/keys, #1536.
- I've also added better logging to the project queue, so we'll be able to better identity what's going wrong through CloudWatch.
---

Fix: Edge case causing project upgrade to fail

---

frontend/src/views/Settings/ProjectSettingsPage/components/ProjectNameChangeSection/CopyButton.tsx
frontend/src/views/Settings/ProjectSettingsPage/components/ProjectNameChangeSection/ProjectNameChangeSection.tsx

Since we're slowly starting to add project slugs as dependencies in consuming applications _(K8 operator as an example)_, we need a way for people to actually get the slug of their projects. I've added a new button on the project settings page that addresses this. 
---

Feat: Copy project slug button

---

cli/packages/cmd/secrets.go
docs/cli/commands/secrets.mdx

Closes #845 . This feature adds  a flag `--value` to `infisical secrets get` command which only prints the value of requested secret. 
Note: this flag only works with one secret request.
This will be very helpful for automation scripts and ci/cd pipelines to exactly get what they want
```sh
INFISICAL_DISABLE_UPDATE_CHECK=true go run main.go secrets get SOME_SECRET --path=/A --value
```
---

Feature to get only value of specific secret in `secrets get` command

---

backend/src/services/integration-auth/integration-auth-service.ts
backend/src/services/integration-auth/integration-sync-secret.ts
frontend/src/pages/integrations/railway/create.tsx

This PR patches/updates the Railway integration so that:
- The create integration page doesn't break due to incorrect query structure for fetching Railway services.
- Specifying a Railway service is now optional; hence, not selecting a service syncs variables to the Railway application's shared variables.
- [] Documentation
---

Update Railway integration get services query, make services optional

---

frontend/package-lock.json
frontend/src/views/SecretOverviewPage/components/SecretOverviewTableRow/SecretOverviewTableRow.tsx
frontend/src/views/SecretOverviewPage/components/SecretOverviewTableRow/SecretRenameRow.tsx

Adds a new feature for #862. Right now if we have to rename a secret, we have to visit each environment seperately, but with this feature, you'll be able to rename secrets directly from the overview page
Attaching the video showcase for reference
https://github.com/Infisical/infisical/assets/47269183/91548621-1ccc-419e-a241-8fc574ba939c
---

Feature: Rename secret from overview page, accross all environments

---

cli/packages/cmd/export.go
cli/packages/cmd/folder.go
cli/packages/cmd/run.go
cli/packages/cmd/secrets.go
cli/packages/util/helper.go

There appears to be an issue with using the CLI with the service token environment variable (setting `INFISICAL_TOKEN`). We haven't been able to reproduce the issue on our end, but by stepping through the code, I'm as certain as can be, that this will resolve all issues related to service token environment variable.
---

Fix: CLI Service Tokens

---

frontend/src/views/SecretMainPage/SecretMainPage.tsx
frontend/src/views/SecretOverviewPage/SecretOverviewPage.tsx

If user tries to visit a secrets page like `/project/<project-id>/secrets/some-env`, he is shown the secrets page and option to add secrets/folder. But in case the `some-env` doesn't exists, user is still shown that page, and errors occur.
This PR redirects the users to overview page and inform them that the env they are trying to accees doesn't exists
Attached video for reference
https://github.com/Infisical/infisical/assets/47269183/b5dfcf99-918e-4e54-8b11-ffcf58529463
---

Redirecting to overview page if environment doesn't exists in secrets main page

---

cli/packages/util/helper.go
cli/packages/util/secrets.go

Fix for version 0.18.2, where it will fail to expand secrets and throw an "invalid auth" error if you aren't using service tokens. 
---

Fix: CLI user authentication

---

docs/cli/usage.mdx

When the user use the CLI to set secrets through the terminal, it keeps the command in the terminal's history and memory.
This recommendation explains how to avoid this behaviour on a given set of Infisical commands, to improve local security and privacy.
```sh
cd ./docs && mintlify dev;
```
---

doc(cli): HISTIGNORE recommendation

---

frontend/src/views/SecretOverviewPage/components/SecretOverviewTableRow/SecretRenameRow.tsx

Change tooltip text from `Copy secret` to `Copy secret name` on Key copy button

Fix typo on Copy button tooltip

---

backend/src/services/integration-auth/integration-sync-secret.ts

This PR sets the recursive behavior flag to `false` for the AWS Parameter Store integration.
Previously, configuring the integration sync to AWS PS would override all nested parameter values in sub-routes; setting the flag to `false` avoids such unintended recursive deletion.
---

Remove recursive behavior in AWS PS integration

---

backend/src/server/plugins/swagger.ts

We are having an issue with Mintlify defaulting to the dev server. Changing the order in our swagger config resolves this issue. 
---

Fix: Mintlify interactive API docs defaulting to localhost server

---

backend/src/server/routes/v2/project-router.ts
backend/src/services/project/project-service.ts
backend/src/services/project/project-types.ts
frontend/src/components/signup/UserInfoStep.tsx
frontend/src/helpers/project.ts
frontend/src/hooks/api/workspace/queries.tsx
frontend/src/hooks/api/workspace/types.ts
frontend/src/layouts/AppLayout/AppLayout.tsx
frontend/src/pages/org/[id]/overview/index.tsx
frontend/src/services/ProjectService.ts
frontend/src/views/Signup/components/UserInfoSSOStep/UserInfoSSOStep.tsx

We actually don't need to take an org slug as a parameter anymore, since we can be sure the `actorOrgId` is always defined now!
---

Fix: Remove required org slug from create project route

---

helm-charts/secrets-operator/Chart.yaml
helm-charts/secrets-operator/templates/deployment.yaml
helm-charts/secrets-operator/templates/infisicalsecret-crd.yaml
helm-charts/secrets-operator/templates/metrics-service.yaml
helm-charts/secrets-operator/templates/serviceaccount.yaml
helm-charts/secrets-operator/values.yaml
k8-operator/Makefile
k8-operator/api/v1alpha1/infisicalsecret_types.go
k8-operator/config/crd/bases/secrets.infisical.com_infisicalsecrets.yaml
k8-operator/config/samples/sample.yaml
k8-operator/controllers/infisicalsecret_helper.go
k8-operator/packages/api/api.go

We allow users to have the managed kubernetes secret be created in any namespace by default. While this worked for most cases, it didn't for ArgoCD. ArgoCD would not know which resource the managed secret belonged to so it would auto prune it. 
To address the auto prune, we added a resource owner to the managed secret. This resolved the issue temporarily but left users who have managed secrets in namespaces not equal to the InfisicalSecret CRD in a error state https://github.com/Infisical/infisical/issues/1042#issuecomment-1862252370 . To Address both cases, this PR adds creation policy to the managed secret.
Creation polices: `Owner` and `Orphan` (default)
`Owner` will add owner reference to the managed secret 
`Orphan` will set no owner on the managed secret
```
apiVersion: …
```

add managed secret creation policy

---

cli/packages/cmd/secrets.go

By default it was false so you couldn't fetch secrets by name when they were imported

set imports=true for get secret by name

---

frontend/src/views/Settings/ProjectSettingsPage/components/EnvironmentSection/AddEnvironmentModal.tsx
frontend/src/views/Settings/ProjectSettingsPage/components/EnvironmentSection/UpdateEnvironmentModal.tsx

Both the popup to add an environment and the popup to edit an environment had "cancel" buttons that did nothing when clicked. I just added the handler
I tested the button and it now works. I also checked the other popups on the project settings general tab and they all work.
This is one of the modals i'm talking about:
---

Fix add and update environment popups cancel button

---

backend/src/services/project/project-service.ts

Fixed creating projects with Machine Identities that aren't org admins.

Fix: Creating projects with Machine Identities that aren't org admins

---

frontend/src/components/v2/Select/Select.tsx

Radix component have ability for keyboard navigation built-in but style is missing in primitive component.
https://github.com/Infisical/infisical/assets/40920317/586371af-1e2e-4fe0-a69f-301ba276a77b
---

fix: add highlighted style for select component

---

frontend/src/components/v2/SecretInput/SecretInput.tsx

typo `yellow` check the screenshot how it looks now.
---

fix class name typo

---

backend/src/lib/api-docs/constants.ts
backend/src/server/routes/v1/secret-tag-router.ts
backend/src/server/routes/v3/secret-router.ts
backend/src/services/project/project-dal.ts
backend/src/services/secret/secret-dal.ts
backend/src/services/secret/secret-service.ts
backend/src/services/secret/secret-types.ts
docs/api-reference/endpoints/secret-tags/create.mdx
docs/api-reference/endpoints/secret-tags/delete.mdx
docs/api-reference/endpoints/secret-tags/list.mdx
docs/api-reference/endpoints/secrets/attach-tags.mdx
docs/api-reference/endpoints/secrets/detach-tags.mdx
docs/mint.json

- The current way to add/remove tags from secrets isn't exactly built to be used by the public. To make the process of removing / adding tags programmatically more appealing to our API users, I have decided to create two new endpoints that make the process of adding/removing tags a whole lot easier.
- Exposed the existing tag router endpoints in docs
- Added docs for the new endpoints
---

Feat: Standalone tag attaching & detaching

---

.github/workflows/build-docker-image-to-prod.yml
.github/workflows/build-staging-and-deploy-aws.yml

This PR optimizes the Depot build workflows to reduce their overall runtime, with two primary changes:
1. When building the release production images, the workflows now build for both `amd64` and `arm64` first, in the `load: true` step. While the arm64 image is not actually necessary for the integration tests to run, this allows the arm64 image to be built at the same time as the amd64 one, so after the tests pass and the `push: true` step executes, both platforms will be pre-cached and can immediately push.
2. The deployment pipeline workflow built the standalone Docker image twice unnecessarily, likely a copy-paste from another CI workflow. I've removed the unnecessary `load: true` step, since nothing actually happens to the loaded image.
---

chore(ci): optimize Depot build workflows

---

backend/src/lib/config/env.ts
backend/src/server/app.ts
backend/src/server/plugins/maintenanceMode.ts
backend/src/server/routes/v1/admin-router.ts

Adds maintenance mode which can be toggled via `MAINTENANCE_MODE`. This will show maintenance mode on the frontend and block all get requests expect the post route needed to check auth for the cli.
Checked secret fetch via CLI and it works when maintenance mode is on.

add maintenance mode

---

frontend/src/views/Project/MembersPage/components/IdentityTab/components/IdentityRoleForm/IdentityRbacSection.tsx
frontend/src/views/Project/MembersPage/components/MemberListTab/MemberRoleForm/MemberRbacSection.tsx

1. Project role management rbac section button hiding fixed clickable even when hidden.
```sh
```
---

fix(ui): resolved multi role modal button hiding clickable

---

backend/src/lib/api-docs/constants.ts
backend/src/server/routes/index.ts
backend/src/server/routes/v3/secret-router.ts
backend/src/services/secret-import/secret-import-dal.ts
backend/src/services/secret/secret-dal.ts
backend/src/services/secret/secret-fns.ts
backend/src/services/secret/secret-service.ts
backend/src/services/secret/secret-types.ts
cli/packages/api/api.go
cli/packages/api/model.go
cli/packages/cmd/agent.go
cli/packages/cmd/run.go
cli/packages/cmd/secrets.go
cli/packages/models/cli.go
cli/packages/util/secrets.go

We have been getting a lot of requests for fetching secrets recursively, which we didn't have support for.
When the user specifies a path when making API calls, we will recursively get all folders that lives inside that path. We then get all the secrets from those paths and return them just like we used to. The only big change is that the `getSecrets` service now functions as a loop instead of just running a single time. Additionally the response now includes a `secretPath` field on each secret. 
This works on both the list secrets and list raw secrets endpoint. 
---

Feat: Recursively get all secrets from all folders in specified path

---

backend/src/ee/routes/v1/identity-project-additional-privilege-router.ts
backend/src/ee/routes/v1/user-additional-privilege-router.ts

This PR moves the default slug initialization for additional privileges out of the Fastify schema; it was otherwise defaulting to the same slug per instance of Infisical on each call to the API.
---

Move default slug init for users/identities out of fastify schema

---

backend/scripts/create-migration.ts
backend/src/db/migrations/20240405000045_org-memberships-unique-constraint.ts

We currently have no unique constraint on the `userId` and `orgId` field, which has led to duplicate organization memberships. We have as a part of this PR removed all duplicate (and broken) organization memberships from the production database. 
After this has been deployed, we should be getting error logs when it tries to create a duplicate membership, which will help us narrow down the exact cause of this. 
A small note: If self-hosted customers have duplicate memberships, they will have trouble upgrading to the latest version as the migration will fail to apply if there are duplicate memberships. To fix this they would simply have to remove the duplicate memberships from their database. This is an unlikely case but worth mentioning. 
---

Fix: Duplicate organization memberships

---

backend/src/db/migrations/20240405000045_org-memberships-unique-constraint.ts

This is an addition to the existing migration (#1656) which adds a unique constraint to organization memberships to avoid duplicates. This migration will remove all existing duplicate organization memberships as a part of the migration.

Feat: Delete duplicate memberships migration

---

k8-operator/README.md
k8-operator/kubectl-install/install-secrets-operator.yaml

About two weeks ago, [support for `universalAuth`](https://github.com/Infisical/infisical/blame/3f6999b2e32429134c34c9ad5d857a954a2850ec/k8-operator/api/v1alpha1/infisicalsecret_types.go#L13)  was added to the k8s-operator types.  After this change, `install-secrets-operator.yaml` was not updated.
This PR is simple, and checks in the file generated by `make kubectl-install`
I have also updated k8s-operator/README to include this as a step in the future, although there may be a better way to update Makefile targets to do this automatically. 
1. Verified manually that the `install-secrets-operator.yaml` file is updated with universalAuth after running make command.
2. Installed the operator using `kubectl apply -f install-secrets-operator.yaml` and verified presence of updated schema using …

fix: Run make kubectl-install

---

backend/src/lib/api-docs/constants.ts
backend/src/services/secret/secret-fns.ts

We are experiencing a surge in resource consumption sometimes, and the recursive fetch may be a cause of this after investigating logs.
This PR introduces a "hard limit" on how deep the recursive search can go. I've set it to 20 depth, which should be more than enough for the vast majority of use-cases.
---

Fix: Hard limit on recursive secret fetching

---

cli/packages/cmd/run.go

CLI fix pointer reference crash on `run` command.
---

Hotfix: CLI run command null pointer reference crash

---

backend/src/services/project-membership/project-membership-service.ts

Fixed inviting project members. The invite logic broke after we removed the `role` field from the project membership table.

Fix: Invite project member

---

backend/src/db/migrations/20240405000045_org-memberships-unique-constraint.ts

Fixed edge case for org membership migration where org membership user ID's could be null, causing a zod validation error, which results in the migration not being completed.

Fix: Duplicate org membership migration

---

backend/src/ee/services/secret-approval-request/secret-approval-request-service.ts
backend/src/services/secret/secret-fns.ts
backend/src/services/secret/secret-service.ts

Addresses customer confusion:
```
It took me way too long to figure this out, but the error
[Bad request]: Folder not  found
Actually means that I was passing in an incorrect environment.
```

Update folder not found error msg

---

cli/packages/cmd/secrets.go
cli/packages/util/secrets.go

UA access token was being overwritten by INFISICAL_TOKEN env variable in some cases, leading to weird behavior. This was because we were getting the INFISICAL_TOKEN env variable inside the `GetAllEnvironmentVariables`, and treating it like a service token.
---

Fix: UA Token being overwritten by INFISICAL_TOKEN env variable

---

cli/packages/cmd/folder.go
cli/packages/util/folders.go

Previously it wasn't possible to list folders with service tokens or universal auth, even though the functionality is there for it. I did some very minor tweaks to allow for service tokens and universal auth to be used. 
---

Feat: Allow "secrets folders get" command to be used with service token & universal auth

---

backend/src/ee/services/saml-config/saml-config-service.ts
backend/src/services/auth/auth-signup-service.ts

This PR addresses a bug with SAML which causes an organization membership to be set as "accepted" before the user has fully setup their account. This results in errors when trying to invite the organization member to projects, because there are no encryption keys associated to the user before the account has been fully set up.
---

Fix: SAML organization invite bug

---

frontend/src/views/Project/MembersPage/components/ServiceTokenTab/ServiceTokenTab.tsx
frontend/src/views/Settings/PersonalSettingsPage/PersonalTabGroup/PersonalTabGroup.tsx

This PR adds a deprecation notice banner to the Service Token section; it also updates the deprecation notice banner in the API Key section.
Details of the Service Token + API Key deprecation can be found [here](https://infisical.com/blog/deprecating-api-keys).
---

Add deprecation notice banner to service token section

---

backend/src/lib/api-docs/constants.ts
backend/src/server/routes/v3/secret-router.ts
backend/src/services/secret/secret-service.ts
backend/src/services/secret/secret-types.ts

- raw secrets can now be expanded in the server-side 
```sh
```
---

feat: added secret expand option in secrets get API

---

backend/src/lib/api-docs/constants.ts
backend/src/server/routes/v1/integration-router.ts
backend/src/services/integration-auth/integration-sync-secret.ts
backend/src/services/integration/integration-types.ts
frontend/src/hooks/api/integrations/queries.tsx
frontend/src/pages/integrations/aws-parameter-store/create.tsx
pg-migrator/src/models/integration/types.ts

This feature creates a boolean flag that allows users not to delete secrets in aws parameter store (only edit and create operations will be propagated from Infisical to AWS PS). 
```sh
```
---

Add option to not delete secrets in parameter store

---

frontend/src/components/navigation/NavHeader.tsx
frontend/src/components/v2/FontAwesomeSymbol/FontAwesomeSymbol.tsx
frontend/src/components/v2/FontAwesomeSymbol/index.tsx
frontend/src/components/v2/InfisicalSecretInput/InfisicalSecretInput.tsx
frontend/src/components/v2/SecretInput/SecretInput.tsx
frontend/src/components/v2/index.tsx
frontend/src/styles/globals.css
frontend/src/views/SecretMainPage/components/SecretListView/SecretItem.tsx
frontend/src/views/SecretMainPage/components/SecretListView/SecretListView.tsx
frontend/src/views/SecretMainPage/components/SecretListView/SecretListView.utils.ts

1. Fixed rendering issue caused by the auto completion over secret input
2. Simplified the `InfisicalSecretInput`
3. [Font awesome icons optimization by SVG Symbols](https://docs.fontawesome.com/web/add-icons/svg-symbols) to improve rendering time
4. Fixed redirect issue in dashboard
5. Fixed unique key error for secret input
```sh
```
---

Improvised secret input component and fontawesome performance improvment

---

backend/src/services/secret/secret-fns.ts
backend/src/services/secret/secret-service.ts

There is currently a bug that occurs when calling the V3 list secrets endpoint with`recursive` and `expandSecretReferences` set to true. 
If there are two or more secrets with the same key is found, the value will be identical for all the secrets found. This was due to a "unique" mapping issue. Before recursive mode was a thing, this would've worked just fine the way it is. But after adding recursive mode, we need to factor in the possibility of duplicate secret keys for the secrets we are iterating through. 
Smaller: I also decided to make the secretPath consistent, so we don't need to check for undefined anymore.
---

Fix: Secret expansion with recursive mode enabled

---

backend/src/services/integration-auth/integration-sync-secret.ts

1. By default ssm get secrets paginate by 10
2. Now it fetches everything from it
```sh
```
---

fix: get all secrets from aws ssm

---

docs/cli/commands/export.mdx
docs/cli/commands/run.mdx

This change will give support for imported secrets in `infisical export` command. With the same flag `--include-imports` as `infisical run` command already present in v0.16.10
This PR is for issue: https://github.com/Infisical/infisical/issues/1015
EDIT: added in this PR https://github.com/Infisical/infisical/pull/1663. But `--include-imports` flag still not documented, reset from main and commited changes in *.mdx.
1. Create two folders `folder-a` and `folder-b`
2. Create new secrets in `folder-a`
3. Create import in `folder-b` with `folder-a` as target, and create some secrets
4. This command should ouput `folder-a` and `folder-b` secrets
```sh
infisical export --path=/folder-b
```
5. With the new flag to false it will give only `folder-b` secrets
```sh
infisical export --path=/folder-b …
```

feat(cli): support of include-imports in export command

---

backend/src/services/identity-access-token/identity-access-token-dal.ts
docs/documentation/platform/identities/gcp-auth.mdx

This PR adds the necessary joins to validate access token IP addresses for AWS/GCP auth.
Previously, the missing joins resulted in the IP address validation always failing when trying to use an access token issued under one of these newer authentication methods.
---

Patch Identity Access Token Trusted IPs validation for AWS/GCP Auth

---

backend/src/server/app.ts
backend/src/server/config/rateLimiter.ts
backend/src/server/routes/index.ts

In the past we rate limited based on IP but this was highly inaccurate and subject to tampering. This PR improves rate limits by linking limits to the identity that is making the call. This can be service tokens, machine identity, API keys, or dashboard users. For APIs that do not require auth, IP address will be used.

rate limit based on identity

---

frontend/src/pages/login/select-organization.tsx

This PR covers an edge case where the user wouldn't be able to select an organization if the user had previously been removed from the only org they were a member of. 
We now redirect to `/org/none` where the user will be prompted to create a new organization. 
```sh
```
---

Fix: No orgs selectable if a user has been removed from an organization

---

backend/src/services/project-bot/project-bot-fns.ts
backend/src/services/project-bot/project-bot-service.ts
backend/src/services/secret/secret-fns.ts

Fix: Better error message on project not found during bot lookup

---

backend/src/services/integration-auth/integration-sync-secret.ts

- This fixes existing integration issues with Cloudflare pages. Before this implementation, secrets are not created and synced to CF because of a parsing issue causing a "cannot convert undefined or null to object" rejection during the sync process
- This also fixed the sync behavior of CF integration for when Infisical secrets are deleted. Before this implementation, synced secrets were inconsistent
```sh
```
---

fix: resolved cloudflare pages integration

---

docs/integrations/cloud/gcp-secret-manager.mdx

- added permission reminder for oauth usage. this is so that users who want to integrate with GCP secrets manager are made aware that their account will need to have sufficient IAM permissions 
```sh
```
---

doc: added reminder for GCP oauth user permissions

---

company/handbook/onboarding.mdx
company/handbook/overview.mdx
company/mint.json

added company handbook

---

backend/src/services/identity-project/identity-project-service.ts

- Previously, removing a machine identity from a single project causes it to be removed in all the other projects as well. This PR solves that issue by ensuring that it only gets deleted for the intended project 
```sh
```
---

fix: resolved identity deletion issue across projects

---

frontend/src/views/Org/MembersPage/components/OrgIdentityTab/components/IdentitySection/IdentityTable.tsx

Previously we've been getting a lot of bug reports from people mixing up the identity ID and client ID, which is very understandable since we display the ID of the identity on the identity row. The ID's are both UUID format, which makes it even easier to mix them up. 
In this PR I've introduced a new dropdown menu where the "Delete identity", "Update identity", and "Copy internal ID" now lives. 
---

Fix: Machine Identities user experience improvement

---

backend/src/services/integration/integration-service.ts
frontend/src/pages/integrations/aws-secret-manager/create.tsx

Previously, users were able to create integrations for environments that they do not have any access to. This happens for example when a user has permissions to create integrations but has no read permission for any of the environments. This PR fixes that by ensuring that users creating or updating integrations (either via Web or API) have read permissions to the env and secret path of interest 
```sh
```
---

misc: improved integration rbac control

---

frontend/src/views/Login/components/PasswordStep/PasswordStep.tsx

- Previously, the SSO login page won't display the "User locked error prompt". This problem is fixed in this PR
```sh
```
---

fix: added account locked prompt to sso signin flow

---

frontend/src/hooks/api/auth/queries.tsx

Currently there's a rare bug that causes the "Failed to get permissions" page to show when switching between organizations. This would sometimes happen because the projects wouldn't be invalidated properly, and then when the user clicked the project, their newly acquired access token wouldn't have access to the project because the token is scoped on an organization-level.
---

Fix: Select organization query invalidation

---

backend/src/db/migrations/20240529043051_snap-shot-secret-index-secretversionid.ts
backend/src/server/routes/v1/project-router.ts

Before this index, deleting a project would take up to 4 hours. With this index, the same query now takes 6 seconds. Brining back project delete because now the delete should run smoothly

add index to secret version secrets table 

---

cli/packages/cmd/agent.go
cli/packages/cmd/login.go
cli/packages/cmd/root.go
cli/packages/cmd/user.go
cli/packages/util/credentials.go
cli/packages/util/helper.go

With this update, users will no longer have to add the `/api` suffix when setting up the domain for the CLI
```sh
```
---

feat: removed the need to pass /api for cli domain

---

Dockerfile.standalone-infisical
standalone-entrypoint.sh

- This PR will enable self-hosted users to configure trust of custom SSL certs. This will be useful for configuring SSL between a self-hosted infisical instance and a self-hosted integration/SSO provider like Gitlab
**How to use**
mount the directory containing the `.pem` files to the `/usr/local/share/ca-certificates/` directory like the following:
```sh
```
---

feat: added support for configuring trust of custom SSL certs

---

backend/src/ee/services/license/license-dal.ts

Currently on Stripe we add all users (including Ghost users) which makes the pricing inconsistent with the actual seats. This PR adds a filter to ignore the ghost users in this counting.
- Create a project
- invite a couple of teammates to the org
- Now see the `users` table and see 3 of your non-ghost users & each project's 1 ghost user
- Now call the `licenseDALFactory.countOfOrgMembers()` method which is used in billing as well and you'll see now only non-ghost user count is reported
---

fix: remove ghost users being added as seats in stripe

---

helm-charts/secrets-operator/Chart.yaml
helm-charts/secrets-operator/values.yaml
k8-operator/packages/api/api.go
k8-operator/packages/api/models.go
k8-operator/packages/util/secrets.go

Currently only service token's support secret referencing. This PR adds secret referencing support by default to Machine Identity auth.
For service tokens we are using client-side secret referencing, but for Machine Identities we are using the new server-side functionality. We need to keep using the clientside secret referencing for service tokens, as they aren't running on the new `raw` endpoints. We need to keep it this way for now for backwards compatibility. 
---

Feat: Expand secret references with Machine Identity

---

backend/src/services/integration-auth/integration-sync-secret.ts
docs/integrations/cloud/aws-parameter-store.mdx

- Previously, tags configured in a newly created AWS parameter store integration won't get attached to already existing parameters. This PR fixes addresses that. It also makes sure that changes made to the tags of an integration will apply to the parameters in AWS
```sh
```
---

feat: added support for tagging existing aws params

---

frontend/src/helpers/string.ts
frontend/src/views/Project/MembersPage/components/MemberListTab/MemberRoleForm/SpecificPrivilegeSection.tsx

Previously, fetching secrets for users with additional privilege does not work. Upon investigation, this is because we're saving the path condition with no sanitation or pre-processing (in this case, removal of trailing slash)
Admin view of level1 path:
Permission of user1:
View of user1 in level1 path
```sh
```
---

fix: resolved trailing slash issue with additional privileges

---

backend/src/services/integration-auth/integration-sync-secret.ts
frontend/src/pages/integrations/cloudflare-pages/create.tsx

- This PR adds auto-redeploy integration option to cloudflare pages
```sh
```
---

misc: added auto-redeploy option for cf pages integration

---

frontend/src/components/v2/SecretInput/SecretInput.tsx
frontend/src/views/ShareSecretPage/components/AddShareSecretModal.tsx

`SecretInput` component in Share Secret Modal now masks when not in focus
```sh
```
---

fix: share secret input now masks value onBlur

---

README.md

Updated docker compose command (from compose V1 to compose v2). From July 2023 Compose V1 stopped receiving updates. Compose V2 comes automatically with latest docker
[https://docs.docker.com/compose/migrate/](https://docs.docker.com/compose/migrate/
)

Fix: Updated docker compose command (from compose V1 to compose v2)

---

k8-operator/controllers/infisicalsecret_helper.go

This pull request fixes https://github.com/Infisical/infisical/issues/1930 where the annotations on a managed Kubernetes secret were being reset during the update process. With this change, we ensure that existing annotations are preserved and only the `ETag` annotation is updated.
- Fixed the bug where updating the managed secret would reset all annotations. Now, only the `ETag` annotation is updated, preserving existing annotations.
1. Deploy the Kubernetes operator.
2. Check the annotations on the managed secret before updating.
3. Trigger an update.
4. Verify the annotations on the managed secret after the update.
- Before update (annotations present)
- After update before the fix (annotations reset)
- After update with the fix (annotations preserved)
---

fix: preserve existing annotations when updating managed secret

---

backend/src/ee/services/ldap-config/ldap-config-service.ts
backend/src/ee/services/saml-config/saml-config-service.ts
backend/src/ee/services/scim/scim-service.ts
backend/src/services/org/org-service.ts

Currently the pricing is updated only when a user does signup via email. This PR adds it to other auth service methods as well.
Add a user via any non-email auth method and see the org seats being updated.
---

fix: update org seats whenever membership status is accepted

---

backend/src/db/schemas/secrets.ts
backend/src/services/secret/secret-fns.ts
backend/src/services/secret/secret-queue.ts
backend/src/services/secret/secret-service.ts
frontend/src/views/SecretMainPage/components/SecretListView/SecretDetaiSidebar.tsx

By default when you create a secret, it will have multi line encoding off but we actually treat this as true in the backend and UI. User’s aren’t expecting their multi line secrets to be double quoted by and made into a single line with/n, however we are doing it by default at the moment. This PR makes multi line encoding opt in and not opt out

Patch multi line encoding when expandSecretRef is enabled

---

backend/src/lib/config/env.ts
backend/src/server/boot-strap-check.ts
backend/src/services/smtp/smtp-service.ts
docs/self-hosting/configuration/envars.mdx

This PR streamlines the SMTP configuration for Infisical to be inline with the parameters given by Nodemailer [here](https://nodemailer.com/smtp/); it should now be much more reliable various SMTP providers — that said self-signed certificates are currently not supported.
Specific adjustments:
- Removed `SMTP_SECURE` environment variable; the `secure` parameter as part of Nodemailer will be set to `true` henceforth when the `SMTP_PORT` is `465`.
- Added `SMTP_IGNORE_TLS`.
- Added `SMTP_REQUIRE_TLS`.
- Added `SMTP_TLS_REJECT_UNAUTHORIZED`.
---

Update SMTP configuration

---

backend/src/services/auth/auth-signup-service.ts
backend/src/services/user/user-dal.ts
backend/src/services/user/user-service.ts

Currently there's an issue related to email confirmation after logging in with SAML. The request will fail because a unique constraint is violated. Specifically, this happens when there are no verified users to merge, but a user with the same username already exists.
This is resolved by adding merge logic to cover the edge-case where the username is already reserved by another user.
---

Fix: Email confirmation during SAML login failing (edge-case)

---

.github/workflows/check-api-for-breaking-changes.yml

This fixes a typo in the GitHub Actions workflow file `.github/workflows/check-api-for-breaking-changes.yml`.
https://github.com/Infisical/infisical/blob/faa1572faf567d185b28dfab183e64192320d67c/.github/workflows/check-api-for-breaking-changes.yml#L50
```sh
```
---

fix: remove extraneous 'r' causing script error in github actions

---

.github/workflows/release_build_infisical_cli.yml

- This PR addresses github action issue with CLI release due to secret name mismatch. The invoked workflow is expecting "CLI_TESTS_INFISICAL_VAULT_FILE_PASSPHRASE" but it was previously called with the name "INFISICAL_VAULT_FILE_PASSPHRASE"
```sh
```
---

fix: resolved secret name mismatch for cli release action

---

frontend/src/views/Project/MembersPage/components/ProjectRoleListTab/components/ProjectRoleModifySection/MultiEnvProjectPermission.tsx
frontend/src/views/Project/MembersPage/components/ProjectRoleListTab/components/ProjectRoleModifySection/SecretRollbackPermission.tsx
frontend/src/views/Project/MembersPage/components/ProjectRoleListTab/components/ProjectRoleModifySection/SingleProjectPermission.tsx
frontend/src/views/Project/MembersPage/components/ProjectRoleListTab/components/ProjectRoleModifySection/WsProjectPermission.tsx

At present if you go to edit admin page or edit permission sometimes there exist an edge case for which all the permission keeps showing no access. 
This is because API based loading form in edit mode, gave empty string for select. This is fixed by returning early
```sh
```
---

broken permission page fixed

---

docs/integrations/platforms/kubernetes.mdx

I think it would be clearer if the Kubernetes documentation included all the steps. The existing link to the guide is mostly applicable if using REST endpoints, not the operator.
I have copied the documentation from the Kubernetes authentication docs page and made some modifications.

Improve k8s docs

---

.github/workflows/check-api-for-breaking-changes.yml
backend/src/db/migrations/20240614115952_tag-machine-identity.ts
backend/src/db/schemas/secret-tags.ts
backend/src/lib/api-docs/constants.ts
backend/src/server/routes/v1/secret-tag-router.ts
backend/src/server/routes/v3/secret-router.ts
backend/src/services/secret-tag/secret-tag-service.ts
backend/src/services/secret/secret-dal.ts
backend/src/services/secret/secret-fns.ts
backend/src/services/secret/secret-service.ts
backend/src/services/secret/secret-types.ts

This PR addresses the adds machine identity support to secret tag endpoints. The raw secret endpoints now accepts tag ids to attach tags to both created and updated secret. This PR is for tag support in terraform
```sh
```
---

Allow secret tag api for machine identity and raw secret endpoint tag support

---

backend/src/server/routes/v1/project-membership-router.ts
backend/src/services/project-membership/project-membership-service.ts
backend/src/services/project-membership/project-membership-types.ts
frontend/src/components/v2/LeaveProjectModal/LeaveProjectModal.tsx
frontend/src/components/v2/LeaveProjectModal/index.tsx
frontend/src/hooks/api/workspace/index.tsx
frontend/src/hooks/api/workspace/mutations.tsx
frontend/src/views/Settings/ProjectSettingsPage/components/DeleteProjectSection/DeleteProjectSection.tsx

This PR introduces support for leaving projects. Previously it wasn't possible to leave projects after you had been invited to it. It's only possible to leave a project if you've been added as a member. If you're a part of a project via. groups, you shouldn't be able to leave it manually.
To be able to leave a project you have to meet a set of conditions.
1. The project needs to be a V2 project.
2. There has to be at least 2 users in the project prior to leaving the project
3. After leaving the project, there has to be at least 1 admin left in the project
---

Feat: Leave Project

---

helm-charts/secrets-operator/Chart.yaml
helm-charts/secrets-operator/values.yaml
k8-operator/controllers/infisicalsecret_controller.go

Currently when the managed secret is deleted it'll be populated again on the next reconcile. This can be problematic especially if your resync interval is high. By adding reconcile on deletion, the user has a way to instantly refresh their secrets if needed.
The implementation takes place directly in the Manager, with minimal structural changes.
---

feat(k8-operator): reconcile on managed secret deletion

---

cli/packages/api/api.go
cli/packages/api/model.go
cli/packages/cmd/export.go
cli/packages/cmd/folder.go
cli/packages/cmd/run.go
cli/packages/cmd/secrets.go
cli/packages/models/cli.go
cli/packages/util/folders.go
cli/packages/util/secrets.go

We've previously only had support for token-based auth in the CLI for a specific set of operations _(mostly operations we deemed as important for CI/CD workflows)_. As Infisical grows, so does our users use-cases, and we need to allow all our CLI operations to be used via. token-based auth. This PR addresses the lack of a unified auth system in the CLI (#1802). 
---

feat(cli): Unify CLI auth methods

---

frontend/src/components/dashboard/DropZone.tsx
frontend/src/components/utilities/secrets/checkOverrides.ts
frontend/src/components/utilities/secrets/encryptSecrets.ts
frontend/src/components/v2/SecretInput/SecretInput.tsx
frontend/src/hooks/api/secretImports/queries.tsx
frontend/src/hooks/api/secretSnapshots/queries.tsx
frontend/src/hooks/api/secrets/queries.tsx
frontend/src/hooks/api/secrets/types.ts
frontend/src/views/SecretMainPage/components/ActionBar/ActionBar.tsx
frontend/src/views/SecretMainPage/components/CreateSecretForm/CreateSecretForm.tsx
frontend/src/views/SecretMainPage/components/SecretDropzone/SecretDropzone.tsx
frontend/src/views/SecretMainPage/components/SecretListView/SecretListView.tsx
frontend/src/views/SecretOverviewPage/SecretOverviewPage.tsx
frontend/src/views/SecretOverviewPage/components/CreateSecretForm/CreateSecretForm.tsx
frontend/src/views/SecretOverviewPage/components/SecretOverviewTableRow/SecretEditRow.tsx
frontend/src/views/SecretOverviewPage/components/SecretOverviewTableRow/SecretOverviewTableRow.tsx
frontend/src/views/SecretOverviewPage/components/SecretOverviewTableRow/SecretRenameRow.tsx
frontend/src/views/SecretOverviewPage/components/SelectionPanel/SelectionPanel.tsx

1. Currently when a value is imported and the user attempts to view the value in the secret's overview. This PR aims to make the imported value visible to the user instead of just showing "IMPORTED". Additionally, we now also show _where_ the value is being imported from.
2. In the secrets overview you can't view your overwritten values. In this update the user can now view and update their overwritten values in the secret overview.
3. I realized we were using hardcoded values for `shared` and `personal` secret types across the frontend. I've gone ahead and added an explicit type for the secret type and implemented it across the frontend. 
https://github.com/Infisical/infisical/assets/62331820/5f20c648-d132-462a-8701-b9a93f832e25
---

feat(platform): Show imported/overwritten values in secret overview

---

backend/src/ee/services/ldap-config/ldap-config-service.ts
backend/src/server/routes/index.ts

This PR patches an issue with `userAlias.userId` being `undefined` in an edge-case; it also adds sending an email verification code to users if email is not verified.
---

Patch LDAP undefined userId, email confirmation code sending

---

backend/src/lib/api-docs/constants.ts
backend/src/server/routes/v3/secret-router.ts
backend/src/services/secret/secret-service.ts
backend/src/services/secret/secret-types.ts

Currently we only support expansion when listing all secrets, but not when getting a singular secret. This PR adds support for secret expansion on a single secret. 
The implementation is borrowed from the existing secret expansion logic from the `getSecretsRaw` method. It has been tweaked to accept a single secret instead of an array.
---

feat(api): Expand single secret references

---

backend/src/db/migrations/20240624163425_certificate-alt-names.ts
backend/src/db/schemas/certificates.ts
backend/src/db/schemas/projects.ts
backend/src/lib/api-docs/constants.ts
backend/src/server/routes/v1/certificate-authority-router.ts
backend/src/services/certificate-authority/certificate-authority-service.ts
backend/src/services/certificate-authority/certificate-authority-types.ts
backend/src/services/certificate-authority/certificate-authority-validators.ts
docs/documentation/platform/pki/certificates.mdx
frontend/src/hooks/api/ca/types.ts
frontend/src/hooks/api/certificates/types.ts
frontend/src/views/Project/CertificatesPage/components/CertificatesTab/components/CertificateModal.tsx

This PR adds an `altNames` field onto certificates and corresponding support for [Subject Alternative Names (SANs)](https://en.wikipedia.org/wiki/Subject_Alternative_Name#:~:text=Subject%20Alternative%20Name%20(SAN)%20is,Subject%20Alternative%20Names%20(SANs).) which can be hostnames or email addresses for when issuing certificates.
---

Add Certificate Support for Alt Names (SANs)

---

backend/src/ee/services/audit-log/audit-log-types.ts
backend/src/lib/api-docs/constants.ts
backend/src/server/routes/v1/identity-aws-iam-auth-router.ts
backend/src/server/routes/v1/identity-azure-auth-router.ts
backend/src/server/routes/v1/identity-gcp-auth-router.ts
backend/src/server/routes/v1/identity-kubernetes-auth-router.ts
backend/src/server/routes/v1/identity-router.ts
backend/src/server/routes/v1/identity-ua.ts
backend/src/server/routes/v1/identity-universal-auth-router.ts
backend/src/server/routes/v1/index.ts
backend/src/services/identity-aws-auth/identity-aws-auth-service.ts
backend/src/services/identity-aws-auth/identity-aws-auth-types.ts
backend/src/services/identity-azure-auth/identity-azure-auth-service.ts
backend/src/services/identity-azure-auth/identity-azure-auth-types.ts
backend/src/services/identity-gcp-auth/identity-gcp-auth-service.ts
backend/src/services/identity-gcp-auth/identity-gcp-auth-types.ts
backend/src/services/identity-kubernetes-auth/identity-kubernetes-auth-service.ts
backend/src/services/identity-kubernetes-auth/identity-kubernetes-auth-types.ts
backend/src/services/identity-ua/identity-ua-service.ts
backend/src/services/identity-ua/identity-ua-types.ts
backend/src/services/identity/identity-org-dal.ts
backend/src/services/identity/identity-service.ts
backend/src/services/identity/identity-types.ts
docs/api-reference/endpoints/identities/get-by-id.mdx
docs/api-reference/endpoints/identities/list.mdx
docs/api-reference/endpoints/universal-auth/get-client-secret-by-id.mdx
docs/api-reference/endpoints/universal-auth/revoke.mdx
docs/mint.json

This PR introduces endpoints for identity and identity auth management in terraform. Implemented revoke endpoints for all identity auth and get identity for reading identity
```sh
```
---

Terraform identity management apis

---

backend/src/db/migrations/20240625115447_configurable-audit-log-retention.ts
backend/src/db/schemas/projects.ts
backend/src/ee/services/audit-log/audit-log-queue.ts
backend/src/server/routes/v1/project-router.ts
backend/src/services/project/project-service.ts
backend/src/services/project/project-types.ts
frontend/src/hooks/api/workspace/queries.tsx
frontend/src/hooks/api/workspace/types.ts
frontend/src/views/Settings/ProjectSettingsPage/components/AuditLogsRetentionSection/AuditLogsRetentionSection.tsx
frontend/src/views/Settings/ProjectSettingsPage/components/AuditLogsRetentionSection/index.tsx
frontend/src/views/Settings/ProjectSettingsPage/components/ProjectGeneralTab/ProjectGeneralTab.tsx

- This PR will enable users to configure audit logs retention period per project. For org-level logs, retention is set to their plan's value
```sh
```
---

feat: enabled customization of project audit logs retention period

---

helm-charts/secrets-operator/Chart.yaml
helm-charts/secrets-operator/values.yaml
k8-operator/controllers/infisicalsecret_helper.go

Fixes crash caused by users pre-creating secrets. It would fail to update the managed secret because the anotations map was `nil`.
```
2024-06-28T21:23:23+02:00       INFO    Observed a panic in reconciler: assignment to entry in nil map  {"controller": "infisicalsecret", "controllerGroup": "secrets.infisical.com", "controllerKind": "InfisicalSecret", "InfisicalSecret": {"name":"infisicalsecret-sample","namespace":"default"}, "namespace": "default", "name": "infisicalsecret-sample", "reconcileID": "1ccbe9a0-3d51-473f-853d-83c092cc7c81"}
panic: assignment to entry in nil map [recovered]
panic: assignment to entry in nil map
goroutine 150 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1() …
```

fix(k8-operator): crash on predefined managed secret

---

backend/src/services/identity/identity-service.ts

This PR resolves a present bug in which when switching a role of an identity from a custom role to a predefined role like `developer`, `admin` the role id not setting it to null. This causes the role deletion failing due to tangling reference
```sh
```
---

Resolved identity roleId not setting null for predefined role selection

---

backend/src/db/migrations/20240627142223_member-project-favorite.ts
backend/src/db/schemas/org-memberships.ts
backend/src/server/routes/index.ts
backend/src/server/routes/v1/user-router.ts
backend/src/services/user/user-service.ts
frontend/src/hooks/api/users/mutation.tsx
frontend/src/hooks/api/users/queries.tsx
frontend/src/layouts/AppLayout/AppLayout.tsx
frontend/src/pages/org/[id]/overview/index.tsx

- This PR will enable org members to create project favorites which will be listed accordingly in the ff UIs
```sh
```
---

feat: allow org members to mark projects as favorites

---

backend/src/ee/services/license/license-service.ts
backend/src/services/auth/auth-signup-service.ts

Previously, we weren't correctly propagating seat counts as part of updating license seats in the organization user invitation flow because the seat computation, after a user completed their account, was not part of that step transaction.
This PR fixes that by adding `tx` to the seat computation.
---

Fix license seat count upon complete account invite with tx

---

backend/src/ee/services/audit-log/audit-log-dal.ts

This PR relieves write lock load caused by bulk audit log deletion that happens every day midnight UTC. Instead of a full delete the query is converted to a batched one that deletes one batch at a time. This reduces the write ahead lock time for a full scan.
```sh
```
---

Changed audit log deletion to batched process

---

backend/src/db/migrations/20240702131735_secret-approval-groups.ts
backend/src/db/schemas/secret-approval-policies-approvers.ts
backend/src/db/schemas/secret-approval-requests-reviewers.ts
backend/src/db/schemas/secret-approval-requests.ts
backend/src/ee/routes/v1/secret-approval-policy-router.ts
backend/src/ee/routes/v1/secret-approval-request-router.ts
backend/src/ee/services/secret-approval-policy/secret-approval-policy-dal.ts
backend/src/ee/services/secret-approval-policy/secret-approval-policy-service.ts
backend/src/ee/services/secret-approval-policy/secret-approval-policy-types.ts
backend/src/ee/services/secret-approval-request/secret-approval-request-dal.ts
backend/src/ee/services/secret-approval-request/secret-approval-request-service.ts
backend/src/ee/services/secret-replication/secret-replication-service.ts
backend/src/server/routes/index.ts
backend/src/server/routes/v3/secret-router.ts
frontend/src/hooks/api/secretApproval/mutation.tsx
frontend/src/hooks/api/secretApproval/types.ts
frontend/src/hooks/api/secretApprovalRequest/types.ts
frontend/src/views/SecretApprovalPage/components/SecretApprovalPolicyList/SecretApprovalPolicyList.tsx
frontend/src/views/SecretApprovalPage/components/SecretApprovalPolicyList/components/SecretApprovalPolicyRow.tsx
frontend/src/views/SecretApprovalPage/components/SecretApprovalPolicyList/components/SecretPolicyForm.tsx
frontend/src/views/SecretApprovalPage/components/SecretApprovalRequest/SecretApprovalRequest.tsx
frontend/src/views/SecretApprovalPage/components/SecretApprovalRequest/components/SecretApprovalRequestAction.tsx
frontend/src/views/SecretApprovalPage/components/SecretApprovalRequest/components/SecretApprovalRequestChanges.tsx

This PR enables secret approval to work with users part of groups. Instead of project membership we now take user id in secret approval. The api now returns the corresponding user details for various user entities like statusChangeBy, committer etc
```sh
```
---
- [ x] I have read the [contributing guide](https://infisical.com/docs/contributing/getting-started/overview), agreed and acknowledged the [code of conduct](https://infisical.com/docs/contributing/getting-started/code-of-conduct). 📝

Secret approval with groups

---

backend/src/ee/services/ldap-config/ldap-config-service.ts

- This PR ensures that when `Trust LDAP emails` is set to true, then the system should no longer require the user to verify their email upon LDAP login
```sh
```
---

fix: addressed lap trust email issue during login

---

.github/workflows/build-binaries.yml

Renamed binary release to `infisical-core` rather than `infiscial-standalone`. This should help bring more clarity to the user. 
---

chore(binary): `rename infisical-standalone` to `infisical-core`

---

frontend/src/components/analytics/posthog.ts
frontend/src/components/utilities/telemetry/Telemetry.ts

Before this fix it used to be `ENV === "production" && TELEMETRY_CAPTURING_ENABLED === "true"` but this always set to false because TELEMETRY_CAPTURING_ENABLED is not a string, it is a bool

Fix posthog events on app.infisical frontend

---

frontend/src/components/v2/Alert/Alert.tsx
frontend/src/pages/integrations/flyio/create.tsx

This PR adds a banner to fly io integration as warning message to note users that there existing secrets will get removed upon integration.
This is because infisical has no way to compare the value from fly io secrets api as due to fly io security measure never returns the value of the secret. Thus cannot understand whether its a modified secret or not. 
```sh
```
---

feat: banner on warning secret deletion in fly.io integration

---

docs/contributing/platform/backend/how-to-create-a-feature.mdx

In the Contributing > Backend development guide section, the command `npm generate:component` should be corrected to `npm run generate:component`.
Context: As a first-time contributor following the development guides, I found this typo.
N/A
---

doc: Update how-to-create-a-feature.mdx

---

backend/src/services/secret-sharing/secret-sharing-dal.ts
backend/src/services/secret-sharing/secret-sharing-service.ts

- This PR modifies shared secret deletion so that it does a soft-delete rather than a hard delete. The intention here is to enable usage tracking overtime
```sh
```
---

misc: soft delete shared secrets upon expiry

---

backend/src/ee/services/license/license-service.ts
backend/src/ee/services/license/license-types.ts

This PR updates the `membersUsed` and `identitiesUsed` fields in the instance feature set on each call to `updateSubscriptionOrgMemberCount` for on-prem.
---

Update dynamic seat count on prem

---

backend/src/services/org/org-service.ts

In the past, a machine identity could be a part of a project but it could have no access role at the organization level, and this would prevent the actor from fetching the list of projects they have access to. If the user is a part of a project already, they should be able to fetch its details. Organization permission shouldn't get in the way.

Remove org read check on project fetch 

---

frontend/src/views/Org/IdentityPage/components/IdentityProjectsSection/IdentityAddToProjectModal.tsx

This PR filters out the projects listed in the identity-project provisioning modal to be only those in the current organization scope.
---

Fix Identity-Project Provisioning Modal — Filter Current Org Projects

---

backend/src/db/migrations/20240715113110_org-membership-active-status.ts
backend/src/db/schemas/org-memberships.ts
backend/src/db/seeds/2-org.ts
backend/src/ee/routes/v1/scim-router.ts
backend/src/ee/services/group/user-group-membership-dal.ts
backend/src/ee/services/ldap-config/ldap-config-service.ts
backend/src/ee/services/oidc/oidc-config-service.ts
backend/src/ee/services/saml-config/saml-config-service.ts
backend/src/ee/services/scim/scim-fns.ts
backend/src/ee/services/scim/scim-service.ts
backend/src/ee/services/scim/scim-types.ts
backend/src/server/routes/index.ts
backend/src/services/auth-token/auth-token-service.ts
backend/src/services/org/org-dal.ts
backend/src/services/org/org-service.ts
frontend/src/hooks/api/users/types.ts
frontend/src/views/Org/MembersPage/components/OrgMembersTab/components/OrgMembersSection/OrgMembersTable.tsx

This PR polishes the SCIM server implementation specifically to now account for user activation/deactivation.
The advantage of user activation/deactivation over deleting users is that users can be deactivated and reactivated, retaining all roles and permissions from pre-deactivation. This also more closely aligns with the model in SCIM.
More specifically:
- Adds an `isActive` field to the `OrgMembership` table.
- Adds logic into auth middleware to reject requests made by deactivated users. Note: This does mean making an extra call to fetch organization membership for user on each request.
- Adds logic into SCIM endpoints to deactivate users where necessary instead of deleting them.
This PR does not include internal user activation/deactivation that is outside the SCIM identity provider; …

Add SCIM user activation/deactivation

---

backend/src/ee/routes/v1/scim-router.ts
backend/src/ee/services/group/user-group-membership-dal.ts
backend/src/ee/services/scim/scim-service.ts

This PR further smoothens the SCIM implementation primarily by returning group memberships where needed; previously returned empty in various places which was not reflective of the actual group memberships in each group.
It also makes the add user to group operation idempotent to avoid throwing errors as JumpCloud tends to make such repeat operations.
---

Further SCIM Smoothening

---

backend/src/services/org/org-service.ts
frontend/src/views/Org/UserPage/UserPage.tsx
frontend/src/views/Org/UserPage/components/UserProjectsSection/UserProjectsSection.tsx

This PR contains three patches:
- It hides the edit user dropdown menu on the User Page if the current user is looking at themself.
- It unblocks the update organization membership endpoint that had an issue with a find function call.
- User can only be added to projects from User Page if their membership status is not invited.
---

Minor Patches for User Page

---

backend/src/services/secret-import/secret-import-fns.ts

This PR resolved get secret causing internal server error when import is failing due to undefined on deeper import check.
```sh
```
---

fix: resolved get secret failing when import is invalid

---

.github/workflows/build-binaries.yml

We were building the Binary on an amd64 architecture, which resulted in issues when dealing with libraries that use node native bindings (like our own SDK does, and like argon2 does). When using a package that uses native bindings, it uses "optional dependencies", and those will be installed when the package itself is installed via `npm install`.
The way it works is that it checks your OS/arch to figure out which native binding to download, and we were always building on am amd64 architecture. This means that PKG would always bundle the amd64 native bindings, instead of the arch-specific bindings.
The solution for this was creating a self-hosted runner, which will always run on `ubuntu 24.04, arm64`. I've updated the Github workflow to use the self-hosted runner when building for Linux …

fix(binary): aarch64 binary native bindings fix

---

docs/self-hosting/configuration/envars.mdx

Added the PORT configuration option to the documentation which controls the port the application listens on.
Added a missing `PORT` environment variable that changes which port the application listens in on.
I chose to add this because in my Docker deployments I like to specify the external IP with the `PORT` variable in the .env file.
However, when deploying this I was unable to connect to Infisical and after troubleshooting I noticed that the application was also listening on the port configured in the variable rather than the `8080` default. When I checked this documentation I found it was lacking this option.
Please feel free to edit the description text as you see fit.
```sh
```
---

Update envars.mdx - Added PORT

---

backend/src/ee/routes/v1/org-role-router.ts
frontend/src/hooks/api/roles/mutation.tsx

Previously, when updating Organization Role Details (e.g. name, description, slug), the frontend would send an empty array of permissions for the role to the server — this would in effect clear/reset the permissions on that role.
This PR prevents empty arrays from being sent on the update call and allows the `permissions` field on the PATCH endpoint to be `optional` as it should be for `PATCH`.
---

Fix updating org role details should not send empty array of permissions

---

frontend/src/hooks/api/secrets/queries.tsx
frontend/src/views/SecretMainPage/SecretMainPage.tsx
frontend/src/views/SecretOverviewPage/components/SecretV2MigrationSection/SecretV2MigrationSection.tsx

- in this PR, error notification prompts will show up in secrets overview and secrets main page when secrets cannot be fetched 
```sh
```
---

misc: added error prompt for fetch secrets issue with kms

---

frontend/src/views/SecretMainPage/components/CreateSecretForm/CreateSecretForm.tsx
frontend/src/views/SecretOverviewPage/components/CreateSecretForm/CreateSecretForm.tsx

This PR enhances the user experience and accessibility of our secret creation forms by passing `isRequired` prop to `FormControl`. The `noValidate` attribute disables the browser's built-in form validation. This allows custom error messages from `react-hook-form` to be displayed instead of the default browser messages with keeping accessibility benefits(screen readers will announce that fields with `required` attribute set are required). In this implementation, form validation is handled independently using the Zod library, without relying on the browser's validation mechanisms.
---

refactor(secret-key-input): pass `isRequired` prop to secret key input

---

frontend/src/helpers/parseEnvVar.ts
frontend/src/views/SecretMainPage/components/CreateSecretForm/CreateSecretForm.tsx
frontend/src/views/SecretOverviewPage/components/CreateSecretForm/CreateSecretForm.tsx

Parse Env Secret when Pasting from the clipboard. Splits the secret from the first "=" sign.
As Vercel does it.
https://github.com/user-attachments/assets/0c7aed76-ac7f-4547-9258-4695937ed3ac
---

feat: parse secrets (key,value) on paste

---

cli/packages/util/keyringwrapper.go

When we auto select file vault, we also need to set it's type. When we set the type, we don't need to fall back to file vault in the `GetValueInKeyring` and `DeleteValueInKeyring` because `currentVaultBackend` will be `file`. 
Also rephrased the text asking the user to eneter a passphrase.

Patch CLI auto select file vault 

---

cli/packages/util/keyringwrapper.go

Reverts Infisical/infisical#2252

Revert "Patch CLI auto select file vault "

---

cli/packages/cmd/vault.go
cli/packages/util/constants.go
cli/packages/util/helper.go
cli/packages/util/keyringwrapper.go
cli/packages/util/secrets.go
docs/cli/commands/vault.mdx

This PR fixes a major issue in CLI that got popped up due to recent release. Some of the users who started using  it suddenly ended up having the new fallback vault when doing normal commands like `run` etc. This caused a big hit on user experience. The fallback should not have triggered because else login would not have happened. 
The root issue was the switch from backup secret for offline access towards the keyring. According to docs keyring cannot sustain more than 3kb in mac. Thus total payload going more than that would fail. This is why we couldn't reproduce this on our end initially. To resolve this we moved back to old way but the encryption key is saved in keyring now.
```sh
```
---

Resolved keyring dataset too big by keeping only the encryption key

---

.github/workflows/run-cli-tests.yml

CLI tests are failing being the pass phrase is now different from the one that is being auto generated.

remove INFISICAL_VAULT_FILE_PASSPHRASE because it is being auto generated now

---

cli/packages/cmd/secrets.go

This PR resolved getting personal secret failing sometime in secret get command. The issue was it was not considered on get by key operation thus randomized return was happening.
```sh
```
---

fix: resolved cli failign to get overriden secret in get command

---

backend/src/lib/knex/index.ts
backend/src/services/secret-tag/secret-tag-dal.ts
backend/src/services/secret-v2-bridge/secret-v2-bridge-dal.ts
backend/src/services/secret/secret-queue.ts

This PR adds the knex batchInsert to our ormify function. BatchInsert allows chunking a lot of records into multiple chunks and insert each chunk thus overcoming max parameter issue with postgres
This is added to secret migration to support bigger folders
```sh
```
---

Secret migration switched to chunking based batch insert

---

cli/packages/util/credentials.go

Fixed Issue "creditnals misspeled in error #2269"
In file credentials.go at line 74 "credentials" was spelled wrong.
- [ ✅] Bug fix
---
- [ ✅] I have read the [contributing guide](https://infisical.com/docs/contributing/getting-started/overview), agreed and acknowledged the [code of conduct](https://infisical.com/docs/contributing/getting-started/code-of-conduct). 📝

replaced "creditnals" to "credentials"

---

Makefile
backend/src/ee/services/audit-log/audit-log-dal.ts
backend/src/server/routes/index.ts
backend/src/services/identity-ua/identity-ua-client-secret-dal.ts
backend/src/services/resource-cleanup/resource-cleanup-queue.ts

This PR adds universal auth client secret cleanup to the resource clean up queue function. This removes all the expired and invalid client secrets. The removal is executed in a batch by batch process with a delay of 10ms for db breathe.
This also adds a new command in make file to ensure PR is ready by checking the UI and api lint and type errors. This is an idea copied from external-secrets operator. Fixed a small bug in audit log pruning also.
```sh
```
---

Client secret cleanup on resource cleanup queue

---

cli/packages/cmd/secrets.go

This PR addresses two issues in the CLI:
1. `secrets set` command requiring local workspace config file even when using auth tokens
2. "not-found" texts are being displayed during `secrets get` even with the `--plain` flag
The PR also adds an API for fetching project ID by slug or name which will make CLI usage easier to automate
```sh
```
---

misc: addressed reported flaws with CLI usage

---

frontend/src/views/ShareSecretPage/components/ShareSecretsTable.tsx

The table on secret's sharing page has incorrect pagination. After going to next page, if it had less items then the per page limit, the pagination used to disapper.
Before:
https://github.com/user-attachments/assets/a42dab7b-d7b9-4380-9c2a-739dffd2a555
After fix:
https://github.com/user-attachments/assets/ac421656-99ef-49b5-a333-27621426e98c
---

Fixed Pagination Disappearing on Secret Sharing Page

---

backend/src/keystore/keystore.ts
backend/src/lib/fn/dates.ts
backend/src/server/routes/index.ts
backend/src/services/secret/secret-queue.ts

This PR resolves a major issue that is causing a race condition in sync integration. 
The issues happens when
1. A waterfall or multiple envs having same secret replication
2. Then immediately mutate the ones that are getting replicated
3. Now what will happen is two sync integration will trigger and there will conflict like aws secret delete one throwing failure because the other one already deleted
4. There is another issue in which aws gives invalid result as in even after delete an immediate get actually gives old value as eventual consistency is taking place
To resolve this we put a redis lock over the integration so that only one for an projectid environment slug and secret path happens. The other one will wait until its available. 
Another thing we do is keep a time over last …

fix: switched sync integration to have redis lock

---

backend/src/ee/services/audit-log/audit-log-service.ts
backend/src/lib/config/env.ts

Added `DISABLE_AUDIT_LOG_GENERATION` which when set to true will prevent the creation of audit logs in Infisical. 
This will be used for load testing purposes and help verify if audit logs are a bottle neck for performance

Add DISABLE_AUDIT_LOG_GENERATION

---

frontend/src/hooks/api/secrets/constants.ts
frontend/src/hooks/api/secrets/queries.tsx

Removed a notification alert that would appear if a user doesn't have access to a certain environment. Since we load all environments on the load page, this notification would always appear if the user has restricted access (as in, they can't read production but can read all other environments as an example).
The fix for this is very straightforward, as we just filter out the "You are not allowed to read on secrets" error.
I've added a new `constants.ts` file which contains the error message as a variable. This is done to follow @dangtony98's file structure that he used when implementing certificates. Example can be [found here](https://github.com/Infisical/infisical/blob/main/frontend/src/hooks/api/certificates/constants.tsx). 
---

Fix: Remove notification when unable to read secrets from environment

---

backend/src/services/identity-aws-auth/identity-aws-auth-service.ts

When the signing header has host defined, it will use that endpoint over the one in the identity. This will allow for cross region use.

Set default to host sts endpoint for aws auth

---

backend/src/ee/services/permission/org-permission.ts

Previously it was possible for organization members to invite new members, which isn't inline with the rest of our member management permissions on organization-level. This PR reduces the permission set for members so they're only able to read on member resources.
```sh
```
---

Fix: Disallow org members to invite new members

---

backend/src/services/auth/auth-login-service.ts

- This PR resolves the issue regarding "null null" names during user signup after invitation to an organization
```sh
```
---

fix: this pr addresses null null name issue with invited users

---

cli/packages/cmd/login.go
cli/packages/models/cli.go
cli/packages/util/helper.go

This PR implements persistent self-hosting domains for `infisical login`. Additionally, it also incldues a new flag on the login command, called `clear-domains`. In some cases users may want to wipe their saved domains, and this flag does exactly yhat.
---

Feat: Persistent self-hosting domains on `infisical login`

---

backend/src/ee/services/secret-approval-request/secret-approval-request-fns.ts

A bug recently introduced in the secret change emails PR resulted in the links being incorrectly formatted in the emails sent. The SITE_URL variable contains the protocol, and we were previously adding the protocol manually before the SITE_URL. This led to the URL being incorrectly formatted
---

Fix: Removed protocol parsing on secret change emails

---

backend/src/lib/config/env.ts

A basic fail-safe for trailing slashes in the SITE_URL. When we use the SITE_URL throughout the code, we assume that there is no trailing slash. This PR removes the need to assume. 
---

Fix: Always remove trailing slashes from SITE_URL

---

cli/go.mod
cli/go.sum
cli/packages/cmd/run.go
cli/packages/models/cli.go
cli/packages/util/exec.go
cli/packages/util/helper.go
cli/test/.snapshots/test-TestUniversalAuth_SecretsGetWrongEnvironment
docs/cli/commands/run.mdx

This PR aims to add support for secret watching. The user will now be able to pass a `--watch` flag to the `infisical run` command. When the `watch` flag is passed, Infisical will automatically reload the command passed to `infisical run`.
1. User runs `infisical run --watch --comand="while true; do printenv; sleep 500000; done"`. _(Both --command and -- supports the new `watch` flag)_
* At first this acts exactly like it always has, and prints the environment to the console and hangs until interrupted.
2. The user now changes a secret in Infisical.
3. At some point within the next 10 seconds (due to polling), the application will detect a change in the Infisical secrets, and then trigger a reload of the application.
4. The application reloads and the new secrets are loaded into the …

feat(cli): `run` watch mode

---

cli/agent-config.yaml
cli/packages/cmd/agent.go
docs/integrations/platforms/infisical-agent.mdx

- This PR will allow users to define templates directly inside Infisical agent configuration files like the following:
- Once this one's merged, we'll proceed with testing the following
https://github.com/Infisical/infisical/pull/2330
```sh
```
---

feat: added raw template for agent

---

backend/src/ee/services/audit-log/audit-log-dal.ts
backend/src/ee/services/secret-snapshot/snapshot-dal.ts
backend/src/services/identity-access-token/identity-access-token-dal.ts
backend/src/services/identity-ua/identity-ua-client-secret-dal.ts
backend/src/services/resource-cleanup/resource-cleanup-queue.ts
backend/src/services/secret-folder/secret-folder-version-dal.ts
backend/src/services/secret-sharing/secret-sharing-dal.ts
backend/src/services/secret-v2-bridge/secret-version-dal.ts
backend/src/services/secret/secret-version-dal.ts

This PR fixes a bug in resource clean up that could cause a looping in audit log and token cleanup. Also adds log point to identity present status of pruning. 
Root cause of multiple clean up runs:
If there are no issues then `deletedClientSecret.length > 0`  is false but `numberOfRetryOnFailure < MAX_RETRY_ON_FAILURE` will always be true because numberOfRetryOnFailure will be zero which is always less than max. To fix this, we need to check for `isretrying`
```sh
```
---

Audit log queue looping

---

backend/src/ee/routes/v1/access-approval-policy-router.ts
backend/src/ee/services/access-approval-policy/access-approval-policy-service.ts
backend/src/ee/services/access-approval-policy/access-approval-policy-types.ts
frontend/src/hooks/api/accessApproval/mutation.tsx
frontend/src/hooks/api/accessApproval/types.ts

Fixed issue with creation/editing access approval policies. The issue is that policies for secret approvals / access requests need to be somewhat identical now, after the policies for secret changes and access requests was merged into one. This PR uniforms the API endpoint input parameters for secret change policies and access request policies
---

fix(access-requests): policy creation and edits

---

frontend/src/views/SecretMainPage/components/CreateSecretForm/CreateSecretForm.tsx
frontend/src/views/SecretMainPage/components/SecretListView/SecretListView.tsx

Previously we were always showing a "success" notification when a secret change happened, regardless if it was pending review or not. Now we show an "info" / blue notification when the secret needs to be reviewed. This should help clear up confusion when making secret changes.

fix(ui): show info notification when secret change is pending review

---

backend/src/services/certificate-authority/certificate-authority-service.ts

- This PR addresses "cert invalid" issue thrown by Chrome, Firefox, and Brave browsers when using Infisical-generated certificates as server certificates
https://github.com/Infisical/infisical/issues/2346
Note: for this fix to work with existing setups, you will need to renew your Root CA using the same key pair and migrate your infra to use this newly generated certificate (i.e. in server certificate chains and trust stores)
```sh
```
---

fix: resolve cert invalid issue due to invalid root EKU

---

backend/src/ee/routes/v1/saml-router.ts
backend/src/server/routes/v1/sso-router.ts

This PR ensures that errors thrown during SAML/SSO logins are displayed to the user to allow them to debug the setup issues they encounter.
Before this PR, when errors are thrown during the SAML login process, it redirects the user to the signup page with an undefined token:
This PR updates the flow so that users actually see the error like the ff:
```sh
```
---

misc: throw SAML or SSO errors properly

---

docs/documentation/platform/pki/pki-issuer.mdx
docs/mint.json

This PR contains documentation for the upcoming/new Infisical PKI Issuer for [cert-manager](https://cert-manager.io/).
The Infisical PKI Issuer is somewhat similar to the Kubernetes Operator and is used to request and receive X.509 certificates from Infisical PKI.
---

Documentation for Infisical PKI Issuer for K8s Cert-Manager

---

backend/src/services/identity-oidc-auth/identity-oidc-auth-fns.ts
backend/src/services/identity-oidc-auth/identity-oidc-auth-service.ts
docs/documentation/platform/identities/oidc-auth/general.mdx
docs/documentation/platform/identities/oidc-auth/github.mdx
frontend/src/views/Org/MembersPage/components/OrgIdentityTab/components/IdentitySection/IdentityOidcAuthForm.tsx

- This PR will allow users to configure machine identity OIDC auth configurations using glob patterns like the following:
E.g.
To match something like repo:sheen-org/personal-assistant:ref:refs/heads/master
You can use:
repo:sheen-org/personal-assistant:ref:*/**
```sh
```
---

misc: support glob patterns for OIDC

---

backend/src/services/integration-auth/integration-sync-secret.ts
docs/integrations/cloud/aws-parameter-store.mdx

This PR modifies AWS Parameter integration sync logic to ensure that selected KMS key of integration is applied for ALL matching parameters on AWS (even those that already existed before the integration was created). This PR also removes keys from the logs
For this update to work for existing integrations, add the "ssm:DescribeParameters" permission to the linked AWS account/role.
```sh
```
---

misc: ensure that selected kms key in aws param integration is followed

---

backend/src/ee/services/group/user-group-membership-dal.ts
backend/src/lib/crypto/srp.ts
backend/src/lib/validator/validate-email.ts
backend/src/server/routes/index.ts
backend/src/server/routes/v1/invite-org-router.ts
backend/src/server/routes/v2/project-membership-router.ts
backend/src/services/auth/auth-signup-service.ts
backend/src/services/org/org-service.ts
backend/src/services/org/org-types.ts
backend/src/services/project-membership/project-membership-service.ts
backend/src/services/user/user-dal.ts
backend/src/services/user/user-fns.ts
backend/src/services/user/user-types.ts
frontend/src/hooks/api/users/types.ts
frontend/src/views/Org/MembersPage/components/OrgMembersTab/components/OrgMembersSection/AddOrgMemberModal.tsx
frontend/src/views/Project/MembersPage/components/MembersTab/components/AddMemberModal.tsx
frontend/src/views/Project/MembersPage/components/MembersTab/components/MembersTable.tsx

This PR addresses a painpoint in which organizations has to wait for user confirmation before getting started. This will allow organization to invite users and then start assigning them to projects already. Helps smoother the automation too.
```sh
```
---

Manager users without waiting for confirmation of mail

---

frontend/src/views/Login/Login.utils.tsx

Redirect users to already selected organization (if present) when they land at the base url. Fixes [ENG-1514](https://linear.app/infisical/issue/ENG-1514/refreshing-page-keeps-asking-you-to-choose-org).
- Log in to a user who is a part of two orgs and select one. 
- Navigate to the base url `localhost:8080`. 
- This should redirect to the selected organization now instead of the org selection page.
---

fix: redirect to selected org if already present

---

backend/src/services/identity-project/identity-project-dal.ts

This PR rectifies a pagination bug with project identities. Previously pagination was being applied after left join of membership roles causing identities with multiple roles to skew pagination. 
```sh
```
---

Fix: Apply Project Identity Pagination Prior to Left Join of Roles

---

frontend/src/views/Login/Login.utils.tsx

This PR reverts #2412 because it will send users to orgs they had previously logged into but not currently selected. This causes a black screen with permission error.

revert PR #2412

---

frontend/src/components/v2/Pagination/Pagination.tsx
frontend/src/hooks/api/secretImports/queries.tsx
frontend/src/hooks/api/secrets/queries.tsx
frontend/src/views/SecretMainPage/SecretMainPage.tsx
frontend/src/views/SecretMainPage/SecretMainPage.types.ts
frontend/src/views/SecretMainPage/components/ActionBar/ActionBar.tsx
frontend/src/views/SecretMainPage/components/SecretImportListView/SecretImportListView.tsx
frontend/src/views/SecretMainPage/components/SecretListView/SecretListView.tsx
frontend/src/views/SecretOverviewPage/SecretOverviewPage.tsx

This PR adds client-side pagination to the secrets overview page as well as a few performance improvements. In addition, first and last page buttons have been added to the pagination component.
https://github.com/user-attachments/assets/43d20cd4-aea8-4bbe-8cc5-b61646be796b
```sh
```
---

Feature: Secrets Overview Page Pagination/Optimizations

---

frontend/src/views/SecretMainPage/SecretMainPage.tsx

This PR corrects the secret offset in the environment view pagination when imports are present.
```sh
```
---

Fix: Account for secret import count in secrets offset

---

backend/src/ee/services/permission/project-permission.ts
backend/src/services/project-role/project-role-service.ts
docs/api-reference/endpoints/project-roles/create.mdx
docs/internals/permissions.mdx
docs/mint.json

An issue was raised, outlining that project roles could be created with invalid subject/actions permissions. This PR introduces a runtime check that validates the subject/actions being passed to the create role endpoint.
Additionally, I've also added a new Permissions internals documentation section, that describes the different valid combinations of subjects and actions.
---

fix(project-roles): creation of invalid project roles

---

frontend/src/views/Org/MembersPage/components/OrgIdentityTab/components/IdentitySection/IdentityTable.tsx
frontend/src/views/Project/MembersPage/components/IdentityTab/IdentityTab.tsx
frontend/src/views/SecretMainPage/SecretMainPage.tsx
frontend/src/views/SecretOverviewPage/SecretOverviewPage.tsx
frontend/src/views/SecretOverviewPage/components/SecretOverviewTableRow/SecretOverviewTableRow.tsx

This PR hides environments the user does not have read access to on the secrets overview page. Also includes increased default pagination size for secrets and identities from 10 to 50 and temporary fix to prevent expanded secrets component width being set to 0.
(Example user without production env read permissions)
resolves #2371
```sh
```
---

Fix: Restricted Secret Environment UI Corrections

---

backend/src/services/group-project/group-project-dal.ts
backend/src/services/project-membership/project-membership-service.ts

- This PR addresses the issue encountered by users wherein not ALL group members appear in the "Required Approvers" field during policy creation. This also fixes handling of unique users
```sh
```
---

fix: address group view issue encountered during policy creation

---

backend/src/services/identity/identity-service.ts
backend/src/services/org/org-service.ts
frontend/src/views/Org/MembersPage/components/OrgIdentityTab/components/IdentitySection/IdentitySection.tsx
frontend/src/views/Org/MembersPage/components/OrgMembersTab/components/OrgMembersSection/OrgMembersSection.tsx

Stop enforcing user and machine Identity limits for Enterprise customers. Context : [ISSUE](https://linear.app/infisical/issue/ENG-1500/allow-feature-set-to-be-set-to-unlimited-number-of-uses)

Don't enforce max user and identity limits

---

backend/src/server/routes/index.ts
backend/src/services/org/org-service.ts

This PR will enable the direct assignment of users to projects even when the users to add are already members of the project via groups
```sh
```
---

misc: allow direct project assignment even with group access

---

backend/src/services/integration-auth/integration-app-list.ts
backend/src/services/integration-auth/integration-sync-secret.ts
frontend/src/pages/integrations/aws-secret-manager/create.tsx

This PR introduces support for secrets prefixing for the AWS Secrets Manager integration.
Additionally I've also taken the liberty to improve our GitHub repos fetching. Previously we were handling the pagination logic manually, but GitHub actually exposes a [`pagination` method](https://docs.github.com/en/rest/using-the-rest-api/using-pagination-in-the-rest-api?apiVersion=2022-11-28#example-using-the-octokitjs-pagination-method) which handles this for us. It's also the recommended method of handling pagination.
---

feat(integrations): aws secrets manager secrets prefixing support

---

backend/src/server/routes/v1/identity-aws-iam-auth-router.ts
backend/src/server/routes/v1/identity-azure-auth-router.ts
backend/src/server/routes/v1/identity-gcp-auth-router.ts

When using the agent, the identity id is read from a file. The file i was using had a new line and this caused the login to fail. Adding in trim to resolve this.

add trip on identityId for identity logins

---

frontend/src/context/UserContext/UserContext.tsx

- This solves the following error which occurs when page is loaded before the user data is available
```sh
```
---

fix: add loading screen for user context

---

frontend/src/views/Settings/BillingSettingsPage/components/BillingCloudTab/ManagePlansTable.tsx

This PR removes the column for the team plan so that the cloud-plans modal now looks like the following:
```sh
```
---

misc: removed teams from cloud plans

---

docs/sdks/languages/node.mdx
docs/sdks/overview.mdx

Redirects node documentation to new SDK docs, hosted on GitHub.
---

docs: redirect node docs to new sdk

---

backend/src/keystore/keystore.ts
backend/src/queue/queue-service.ts
backend/src/services/secret/secret-queue.ts
backend/src/services/secret/secret-types.ts
backend/src/services/smtp/smtp-service.ts
backend/src/services/smtp/templates/integrationSyncFailed.handlebars

This PR aims to add support for email notifications, when an integration fails to sync for whatever reason. A key difference is that: If the integration is manually triggered, only the actor who triggered it will get the email. If it's an automated sync, all project members will receive the notification.
---

feat(integrations): email when integration sync fails

---

frontend/src/layouts/AppLayout/ErrorBoundary.tsx
frontend/src/pages/_app.tsx

This PR aims to add a better and more descriptive error page when we would usually show the default Next.js application error page. 
---

feat: next.js error boundary 

---

backend/src/lib/fn/string.ts
backend/src/server/routes/v1/secret-folder-router.ts

This PR fixes the folders API, and ensures that all paths are correctly being prefixed with a slash. A bug was identified through the Terraform provider, where the secret folder resource would strip the first letter of the path if it isn't a slash. It turned out to be an API issue after I confirmed that the issue was also present through regular API requests. Always prepending a slash fixes this issue entirely, and adds more consistency. 
---

fix(folders-api): prefix paths

---

frontend/src/hooks/api/secretImports/queries.tsx
frontend/src/views/SecretOverviewPage/SecretOverviewPage.tsx

This PR fixes a smaller UI bug, which caused the missing secrets counter to not factor in imported secrets.
---

fix(dashboard): fix imports missing secrets counter

---

backend/src/services/project-membership/project-membership-service.ts

This will make the API throw a 404 instead of 400 error when a membership is not found. This is more inline with HTTP standards and will make error checking easier in our consuming applications such as Terraform.
---

fix: throw not found when entity is not found

---

backend/src/ee/services/access-approval-policy/access-approval-policy-service.ts
backend/src/ee/services/access-approval-request/access-approval-request-service.ts
backend/src/ee/services/group/group-dal.ts
backend/src/ee/services/group/group-service.ts
backend/src/ee/services/scim/scim-service.ts

findAllGroupMembers in groupDAL fetches all users irrespective of whether they are present in the group or not and returns a flag to indicate if present or not. This renames it to findAllGroupPossibleMembers and adds a filter on this flag for approvals using groups.

check user group membership correctly

---

frontend/src/views/SecretMainPage/components/SecretListView/SecretItem.tsx

Added a error feedback ui to show error when saving secret item and fails in validation for client.
```sh
```
---

feat: added error feedback on secret items saving for debugging

---

backend/src/ee/services/permission/permission-dal.ts
frontend/src/hooks/api/kms/queries.tsx
frontend/src/layouts/AppLayout/AppLayout.tsx
frontend/src/pages/org/[id]/overview/index.tsx

This PR fixes org permission not able to retrieve when its a custom role not in group level rather in direct org membership. Seems the zod validator didn't catch it as it was optional or unknown. 
This PR also fixes external kms throwing forbidden error for members in an org
```sh
```
---

fix: resolved permission not defined for custom org role

---

frontend/src/pages/signupinvite.tsx

This PR resolves the following issue: https://github.com/Infisical/infisical/issues/2446
Basically it removes a condition in the signupinvite page that blocked invited users from creating an account when instance allow signup option is set to "Disabled"
```sh
```
---

misc: addressed invalid redirect condition in signup invite page

---

backend/src/ee/services/dynamic-secret/dynamic-secret-service.ts
backend/src/ee/services/dynamic-secret/dynamic-secret-types.ts
backend/src/server/routes/v3/dashboard-router.ts
backend/src/services/secret-v2-bridge/secret-v2-bridge-service.ts
backend/src/services/secret/secret-service.ts
frontend/src/views/SecretMainPage/SecretMainPage.tsx

This PR refactors the secrets overview endpoint to filter environments for secrets based off the users read access. This allows retrieval of folders for all environments but only permissive secrets.
https://github.com/user-attachments/assets/638cf8a2-b724-4ba7-8c47-f64aac3d78b5
```sh
```
---

Fix: Secrets Overview Endpoint Filter Secrets for Read Permissive Environments

---

docs/cli/commands/login.mdx

1. Add `oidc-auth` in method options in documentation for cli login 
2. Changed order in login command documentation to make the auth section first and then flags section. The auth section makes sense to come first because most will refer that to do various authentication. The flag section is a bit confusing for many users as it doesn't tell the relation between various options together
```sh
```
---

docs: added oidc method in login command method argument and changed order to make auth section first

---

frontend/src/views/Project/CertificatesPage/components/CertificatesTab/components/CertificateModal.tsx
frontend/src/views/Project/CertificatesPage/components/PkiAlertsTab/components/PkiAlertModal.tsx
frontend/src/views/Project/CertificatesPage/components/PkiAlertsTab/components/PkiCollectionModal.tsx

This PR resolves modal close unresponsive issues in certificate-related modals
```sh
```
---

fix: address modal close unresponsive

---

backend/src/server/routes/index.ts

Removing health for RDS/Redis from infisical health check. This is because if DB is unhealthy for a short while, all  containers will be killed since they register as unhealthy

remove health checks for rds and redis

---

frontend/src/views/SecretOverviewPage/SecretOverviewPage.tsx
frontend/src/views/SecretOverviewPage/components/CreateSecretForm/CreateSecretForm.tsx

- This PR ensures that the correct notification modal pops up after secret modification in overview page when path has an approval policy
```sh
```
---

misc: added proper notifs for paths with policies in overview

---

backend/src/server/routes/v1/integration-router.ts
backend/src/services/integration/integration-service.ts
backend/src/services/integration/integration-types.ts

This PR is a prerequisite for adding integrations support to Terraform. It sets all the update fields to optional, like it should be. Currently the update endpoint _requires_ you to make certain changes. 
---

fix: made all update fields optional

---

helm-charts/secrets-operator/Chart.yaml
helm-charts/secrets-operator/values.yaml
k8-operator/controllers/infisicalsecret_controller.go

This PR resolves a bug in the operator which was causing the operator not to reflect changes to the Infisical CRD. This was due to a state issue which caused the old CRD details to remain, even after updating the CRD.
The full issue is mentioned in https://github.com/Infisical/infisical/issues/2400
---

fix(k8-operator): updating CRD does not reflect in operator

---

backend/src/keystore/keystore.ts
backend/src/server/routes/index.ts
backend/src/services/project-env/project-env-service.ts

Previously when creating multiple project environments at once, it was possible that our database would throw an error, due to the unique composite constraint on project ID / position. This would happen because the transactions would turn into race conditions of whichever would first finish wish the selected position.
The solution for this is to use the keystore to ensure that only one project environment update / create / delete operation will run at once.
---

fix: allow creation of multiple project envs

---

backend/src/services/identity/identity-org-dal.ts

The counts on the identity at the org level were incorrect. This fix applies the limit on the parent query instead of the subquery

Resolve identity count issue

---

frontend/next.config.js

Adds CSP directive to allow sending requests to Posthog and hence fixes the console errors we see each time Posthog tries to send a request.

fix: add CSP directive to allow posthog

---

backend/e2e-test/routes/v1/project-env.spec.ts
backend/src/lib/api-docs/constants.ts
backend/src/server/routes/v1/project-env-router.ts
backend/src/services/project-env/project-env-dal.ts
backend/src/services/project-env/project-env-service.ts
backend/src/services/project-env/project-env-types.ts

This PR fixes positions for updating and deleting environments. There was an issue with positions shifting unnecessarily in Terraform, this PR fixes this behavior. Additionally, this PR adds support for the `position` argument when creating environments, which is also needed for Terraform. 
---

fix: project environment positions

---

frontend/src/views/SecretOverviewPage/SecretOverviewPage.tsx

This PR moves the secret overview pagination component outside the table container to make overflow scroll more intuitive for users.
```sh
```
---

Improvement: Secret Overview Table Scroll

---

.github/workflows/build-binaries.yml
backend/package-lock.json
frontend/package-lock.json
frontend/package.json

This PR introduces RPM binary support and fixes frontend.
Overrides in frontend package.json fixes a binary build issue https://github.com/storybookjs/storybook/issues/25075#issuecomment-1836132637
Downgrading slugify version is necessary to make the binary build correctly, because the binary uses commonJS. And slugify >1.1.0 is ESM-only. We also lock the slugify version on the backend.  
---

feat: rpm binary

---

backend/src/db/migrations/20241007202149_default-org-membership-roles.ts
backend/src/db/schemas/organizations.ts
backend/src/ee/services/ldap-config/ldap-config-service.ts
backend/src/ee/services/oidc/oidc-config-service.ts
backend/src/ee/services/saml-config/saml-config-service.ts
backend/src/ee/services/scim/scim-service.ts
backend/src/server/routes/index.ts
backend/src/server/routes/v1/organization-router.ts
backend/src/services/org/org-dal.ts
backend/src/services/org/org-role-fns.ts
backend/src/services/org/org-role-service.ts
backend/src/services/org/org-service.ts
backend/src/services/org/org-types.ts
frontend/src/hooks/api/organization/queries.tsx
frontend/src/hooks/api/organization/types.ts
frontend/src/views/Org/MembersPage/components/OrgMembersTab/components/OrgMembersSection/AddOrgMemberModal.tsx
frontend/src/views/Org/MembersPage/components/OrgRoleTabSection/OrgRoleTable.tsx
frontend/src/views/Settings/OrgSettingsPage/components/OrgNameChangeSection/OrgNameChangeSection.tsx

This PR adds the capability to set a default org membership role other than `member`. The PR also includes code for default project membership roles but is currently commented out as there is no practical application for usage yet.
https://github.com/user-attachments/assets/6b8b82b1-5f43-4d9e-9dfd-f53225d0b731
```sh
```
---

Feat: Default Org Membership Role

---

backend/src/server/routes/v3/external-migration-router.ts
nginx/default.conf
nginx/default.dev.conf

This PR allows larger file uploads specifically for the /api/v3/migrate route. It fixes both Nginx and Fastify restrictions. 
---

fix: allow 25MB uploads for migrations

---

backend/src/services/external-migration/external-migration-fns.ts
backend/src/services/external-migration/external-migration-types.ts

It's possible to set undefined variable keys in EnvKey. We currently don't handle this case in the EnvKey migration script. This PR adds support for undefined variable values.
---

fix: handle undefined variable values

---

backend/src/db/migrations/20241015084434_increase-identity-metadata-col-length.ts
backend/src/ee/routes/v1/saml-router.ts

This PR increases the string length of the value column in the identity metadata column to account for long user attribute values like arrays, etc.
```sh
```
---

misc: increase identity metadata col length

---

backend/src/services/external-migration/external-migration-fns.ts
backend/src/services/external-migration/external-migration-queue.ts

There is an edge-case in EnvKey imports, resulting in imports failing due to a vague database error. The error is happening because we're trying to find a project env with an undefined projectId. This PR introduces an extra step that will "backfill" any missing / corrupt data.
---

fix: envkey project imports

---

backend/src/services/integration-auth/integration-sync-secret.ts

This PR covers the following case: When a secret exists in aws parameter store but has a empty value for the corresponding key in Infisical. When we try to sync the empty secret to aws, aws will throw a error because all values must have at least one value.
This PR fixes this by requiring that all syncs for aws parameter will require a value in Infisical. If `shouldDisableDelete` isn't enabled (meaning we can delete secrets in aws) and we remove the corresponding key from aws for which a value does not exist in Infisical.

prevent sync of empty secret in ssm

---

docs/contributing/platform/developing.mdx

This PR updates the documentation to replace the deprecated `docker-compose` command with `docker compose`. This change resolves the issue where developers may encounter errors if they use the outdated `docker-compose` command on newer Docker installations.
**Fixes Issue #2576 **
Testing involved following the setup instructions in the updated documentation and running `docker compose -f docker-compose.dev.yml up --build --force-recreate` to ensure compatibility.
```sh
adityagoyal@Adityas-MBP-3 infisical % docker compose -f docker-compose.dev.yml up --build --force-recreate
WARN[0000] /Users/adityagoyal/Projects/OpenSource/infisical/docker-compose.dev.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 
[+] Running 57/43
✔ …
```

Updated docs to use docker compose instead of docker-compose

---

backend/src/ee/routes/v1/scim-router.ts

Some providers like okta don't provider type in emails section it seems. I just. removed it as we don't even use it also. So why make it required. We only care about primary flag in email.
On response we just make it fallback to work.
```sh
```
---

feat: field type is not even used in schema so removed as some providers don't provide it

---

frontend/src/views/Org/RolePage/components/OrgRoleModifySection.utils.ts
frontend/src/views/Org/RolePage/components/RolePermissionsSection/RolePermissionsSection.tsx

This PR brings back organization kms permission in ui for org rbac
```sh
```
---

feat: added organization kms in org role permission section

---

frontend/src/components/tags/CreateTagModal/CreateTagModal.tsx

This PR fixes a default color not being set in the create tag modal for secrets.
```sh
```
---

Fix: Set Default Value for Color in Tags Modal

---

frontend/src/components/v2/Table/Table.tsx
frontend/src/views/SecretOverviewPage/SecretOverviewPage.tsx
frontend/src/views/SecretOverviewPage/components/SecretOverviewTableRow/SecretOverviewTableRow.tsx

This PR caps the width of expanded secrets on the overview table to prevent the need to scroll back and forth when editing secrets with table overflow.
```sh
```
---

Improvement: Cap Expanded Secret View Width when Overview Table Overflows

---

backend/src/lib/errors/index.ts
backend/src/server/config/rateLimiter.ts
backend/src/server/plugins/error-handler.ts

Previously rate limits were throwing 500 errors which is not descriptive at all. This PR adds a new error type specifically for rate limits, and modifies the rate limiter config to throw a custom error.
```sh
```
---

fix: better rate limit errors

---

backend/package.json
backend/scripts/migrate-organization.ts

Script to dump database apart from the audit logs table, import into another Postgres instance and delete all data for organizations except one given organization.
Use `npm run migrate:org` in backend to test.
Note: 
- Ensure you run the import scripts on an empty postgres instance. 
- This can be done by just using `docker-compose -f <>.yml up db --build` and then using `npm run migrate:org` to import first.
- You use same `ENCRYPTION_KEY` and `ROOT_ENCRYPTION_KEY`
---

feat: add migration script to migrate org

---

backend/src/ee/routes/v1/group-router.ts
backend/src/ee/services/access-approval-policy/access-approval-policy-service.ts
backend/src/ee/services/access-approval-request/access-approval-request-service.ts
backend/src/ee/services/group/group-dal.ts
backend/src/ee/services/group/group-service.ts
backend/src/ee/services/group/group-types.ts
backend/src/ee/services/scim/scim-service.ts
backend/src/lib/api-docs/constants.ts
frontend/src/hooks/api/groups/queries.tsx
frontend/src/hooks/index.ts
frontend/src/hooks/useResetPageHelper.ts
frontend/src/views/Org/MembersPage/components/OrgGroupsTab/components/OrgGroupsSection/OrgGroupMembersModal.tsx
frontend/src/views/Org/MembersPage/components/OrgGroupsTab/components/OrgGroupsSection/OrgGroupsTable.tsx
frontend/src/views/Org/MembersPage/components/OrgIdentityTab/components/IdentitySection/IdentityTable.tsx
frontend/src/views/Project/KmsPage/components/CmekTable.tsx
frontend/src/views/Project/MembersPage/components/IdentityTab/IdentityTab.tsx
frontend/src/views/SecretMainPage/SecretMainPage.tsx
frontend/src/views/SecretOverviewPage/SecretOverviewPage.tsx

This PR fixes Organization User Groups search functionality and adds sort to all columns, and also corrects pagination total count for group users endpoint and improves search functionality to include first and last name in addition to username.
```sh
```
---

Fix: Group Tables/Pagination Fixes and Improvements

---

frontend/src/views/SecretOverviewPage/components/SecretOverviewTableRow/SecretOverviewTableRow.tsx

This PR caps secret overview expanded secret view width to tw container max to prevent overflow on uw monitors
```sh
```
---

Fix: cap width for tw container size on uw monitors

---

frontend/src/components/navigation/RegionSelect.tsx

This PR refines the region select display check to prevent dedicated cloud instances from seeing the select.
```sh
```
---

Fix: refine check of when to display region select

---

docker-compose.prod.yml

Added restart policies for Redis container to enhance stability and prevent failures during system restarts or crashes. These policies ensure the services restart automatically, making the setup more resilient in environments where reboots or failures may occur.
As discussed in this [thread on slack](https://infisical-users.slack.com/archives/C04BSBMQAQ7/p1729154447243339) - 
Tested by rebooting the system and ensuring that Redis and PostgreSQL containers restart automatically and remain stable without manual intervention.
---

Fix(docker-compose): prevent container restart failures on system reboot

---

frontend/src/layouts/AppLayout/AppLayout.tsx
frontend/src/layouts/AppLayout/components/InsecureConnectionBanner/InsecureConnectionBanner.tsx
frontend/src/layouts/AppLayout/components/InsecureConnectionBanner/index.tsx

This PR displays a dismissible warning banner when an Infisical instance is accessed via an insecure connection (ie not via HTTPS)
```sh
```
---

Feature: Display Warning Banner for Insecure Connection

---

frontend/src/hooks/usePagination.tsx
frontend/src/views/Org/MembersPage/components/OrgMembersTab/components/OrgMembersSection/OrgInviteLink.tsx

This PR prevents truncation of invite links when in an insecure context to allow direct copy of link and also increases the default page size for pagination to 100.
```sh
```
---

Improvement: Display Full Invite Link in Insecure Context and Increase Default Pagination Size to 100

---

backend/src/services/integration-auth/integration-sync-secret.ts

Tiny PR to make Azure DevOps (ADO) variables encrypted rather than plaintext when synced from Infisical. Previously, ADO variables were being synced from Infisical as plain variables, which would show up in ADO variable groups and build logs in plaintext. Since many values stored in Infisical are meant to be secret, these variables should be encrypted in ADO.
Relevant REST API documentation for ADO variable group updates: https://learn.microsoft.com/en-us/rest/api/azure/devops/distributedtask/variablegroups/update?view=azure-devops-rest-7.2. I've tested this API call and can confirm this correctly encrypts the values at rest in ADO. When these variables are referenced in ADO processes, they are appropriately masked in any output logs.
---

Make synced Azure DevOps variables secret

---

backend/src/services/external-migration/external-migration-fns.ts

This PR resolves two critical issues with the EnvKey import migration.
1. Duplicate branches
2. This would happen if you had a branch in on an environment in the root of a project, and then at the same time had a branch with the same name, in a block on the same environment.
2. Secret values from the base environment were ending up inside branches for secrets with matching names. 
---

fix(external-migrations): env-key edge cases

---

backend/e2e-test/routes/v1/secret-replication.spec.ts
backend/src/keystore/keystore.ts
backend/src/services/secret/secret-queue.ts

This PR resolves a race condition in stale check that was happening. We now have a debounce in queue level with 3second buffer to handle this corner case. I have also made get integration list after the lock acquire to work with consistent data.
```sh
```
---

feat: added queue level debounce for secret sync and removed stale check

---

frontend/package-lock.json
frontend/package.json

This PR removes the `ip` package from the frontend which is unused; in doing so, it removes the vulnerable dependency as stated [here](https://github.com/advisories/GHSA-2p57-rm9w-gvfp).
---

Remove unused ip package from frontend

---

backend/src/services/secret-v2-bridge/secret-v2-bridge-fns.ts
backend/src/services/secret-v2-bridge/secret-v2-bridge-service.ts

This PR includes the following fixes for secret references:
- Allow secrets to reference the same secret multiple times
- Prevent stripping of special characters when expanding secret references
```sh
```
---

Fix: Secret Reference Multiple References and Special Character Stripping

---

.github/workflows/release_build_infisical_cli.yml
.gitignore
docs/cli/overview.mdx
npm/.eslintrc.json
npm/README.md
npm/package-lock.json
npm/package.json
npm/src/index.cjs

feat: infisical cli for npm

---

npm/package-lock.json
npm/package.json
npm/src/index.cjs

While going over the NPM CLI port I found an issue with the Windows download, causing it to fail during Windows downloads due to a wrong extension format. I've added zip support to resolve this.
Additionally I also found a discrepancy with the symlink creation on global installations. This PR also resolves that issue.
This can be tested locally by CD'ing into the /npm folder and running
```bash
cd /npm
npm install -g .
whereis infisical # Should print a path pointing to a correctly symlinked path
``` 
Make sure to change the `version` field in the `package.json` file when doing a local test, since 0.0.0 is not a valid CLI version.
---

fix: cli npm release windows and symlink bugs

---

cli/packages/cmd/login.go

- This PR updates the label of self-hosting option during CLI login to include dedicated instances
```sh
```
---

misc: updated login self-hosting label to include dedicated

---

backend/src/db/migrations/20240802181855_ca-cert-version.ts
docker-compose.prod.yml

We didn't do a check to see if the column already exists. Because of this, we get this error during migrations:
```
| migration file "20240802181855_ca-cert-version.ts" failed
infisical-db-migration  | migration failed with error: alter table "certificates" add column "caCertId" uuid null - column "caCertId" of relation "certificates" already exists
```

Fix ca version migration 

---

backend/src/db/migrations/20240818024923_cert-alerting.ts
backend/src/db/utils.ts

We were creating triggers even if they were already created. This fix only creates triggers on new tables. The error this addresses is:
```
migration file "20240818024923_cert-alerting.ts" failed
infisical-db-migration  | migration failed with error: 
infisical-db-migration  | CREATE TRIGGER "pki_collections_updatedAt"
infisical-db-migration  | BEFORE UPDATE ON pki_collections
infisical-db-migration  | FOR EACH ROW
infisical-db-migration  | EXECUTE PROCEDURE on_update_timestamp();
infisical-db-migration  |  - trigger "pki_collections_updatedAt" for relation "pki_collections" already exists
infisical-db-migration  | 
infisical-db-migration  | CREATE TRIGGER "pki_collections_updatedAt"
infisical-db-migration  | BEFORE UPDATE ON pki_collections
infisical-db-migration  | FOR EACH ROW …
```

only create triggers when create new table

---

backend/src/ee/services/permission/permission-fns.ts
backend/src/ee/services/permission/permission-service.ts

This PR addresses handling of missing keys in user/identity metadata during permissions checks by proxying the template value if not present.
```sh
```
---

Fix: Handle Missing User/Identity Metadata Keys in Permissions Check

---

backend/src/server/routes/v2/project-membership-router.ts

This PR ensures that if roleSlugs is defined during user project invite, the roles are actually assigned correctly
```sh
```
---

misc: address role slug issue in invite user endpoint

---

backend/e2e-test/mocks/smtp.ts
backend/src/ee/services/oidc/oidc-config-service.ts
backend/src/lib/errors/index.ts
backend/src/server/boot-strap-check.ts
backend/src/server/plugins/error-handler.ts
backend/src/services/smtp/smtp-service.ts

- shows SMTP errors to the OIDC error callback page for immediate feedback
- ensures that OIDC cannot be enabled when SMTP is not confirmed to be good
- updates bootstrap SMTP check to display the actual error
- ensures that user can login with OIDC if user account is previously created using org invite flow 
```sh
```
---

misc: added OIDC error and edge-case handling

---

backend/scripts/migrate-organization.ts
backend/src/db/migrations/20241110032223_add-missing-oidc-org-cascade-reference.ts

- updates org migration script to use pg_restore
- adds handling for special characters
```sh
```
---

misc: finalize org migration script

---

backend/src/services/secret-v2-bridge/secret-v2-bridge-service.ts

This PR addresses incorrect handling of empty values for secrets on update (value not updated), bulk create (threw error), and bulk update (threw error).
```sh
```
---

Fix: Handle Empty Secret Values in Update, Bulk Create and Bulk Update Secret(s)

---

frontend/src/hooks/api/auditLogs/types.tsx
frontend/src/views/Org/AuditLogsPage/components/LogsSection.tsx

This PR fixes an issue related to user audit logs. The API expects `actor` as the field for actor ID. But the frontend was sending `actorId` instead of `actor`.
---

fix(audit-logs): actor / actor ID mismatch

---

.husky/pre-commit

This PR improves the pre-commit hook, so a proper error is displayed if the CLI is not installed on the host machine.
---

chore: check for CLI installation before pre-commit

---

docs/cli/overview.mdx
npm/README.md

This PR contains some simple README improvements for our new NPM CLI Installer, to reduce confusion between the CLI and Node SDK
---

chore(cli-installer): readme improvements

---

backend/src/services/integration-auth/integration-sync-secret.ts

Previously:
When syncing secrets with Terraform Cloud, they would be visible in TFCloud UI
Now:
All synced secrets are marked as sensitive and hidden from UI
Previously synced secrets will be marked as sensitive on next sync
Video:
https://github.com/user-attachments/assets/9f7ab058-b1f3-4032-88f1-60884b8c1161
Manually tested
---

Improvement(Terraform Cloud Integration): Synced secrets are hidden from Terraform UI

---

docs/integrations/platforms/kubernetes.mdx

was reading [k8s integration docs](https://infisical.com/docs/integrations/platforms/kubernetes#sync-infisical-secrets-to-your-cluster) and found small typo in the `example-infisical-secret-crd.yaml` template
N/A, just fixing typo
---

fixing small typo in docs/integrations/platforms/kubernetes

---

backend/src/db/migrations/20241121131344_make-identity-metadata-not-nullable-again.ts

- made identity metadata value field not nullable again
```sh
```
---

misc: made identity metadata value not nullable

---

backend/src/ee/services/permission/permission-dal.ts
backend/src/services/identity-token-auth/identity-token-auth-service.ts

This PR fixes two bugs in infisical
1. Token auth token revocation failure due to ambiguous key error
2. Token auth update token failing due to same errror
3. Workspace permission failing because of null values in some fields which was because of both membership id and groupmembership id being null. This was because of an issue in joining
```sh
```
---

fix: db error on token auth and permission issue

---

backend/src/services/identity-project/identity-project-service.ts
backend/src/services/project-membership/project-membership-service.ts
frontend/src/views/Project/IdentityDetailsPage/components/IdentityRoleDetailsSection/IdentityRoleDetailsSection.tsx
frontend/src/views/Project/MemberDetailsPage/components/MemberRoleDetailsSection/MemberRoleDetailsSection.tsx

This PR prevents setting a project membership  role slug value to "custom" which is reserved. This PR also corrects mapping of updated roles for users/identities
```sh
```
---

Fix: Prevent Updating Identity/User Project Role to reserved "Custom" Slug

---

backend/src/services/project/project-dal.ts

This PR fixes errors for finding projects. Previously it wouldn't factor in Not Found or Unauthorized errors. If a NotFound error was thrown from within the DAL, it would translate to a 500 / Database error.
This issue was especially visible when trying to fetch secrets with an invalid project slug (`workspaceSlug`). 
---

fix: improve project DAL error handling

---

cli/packages/cmd/export.go
cli/packages/cmd/init.go
cli/packages/cmd/login.go
cli/packages/cmd/root.go
cli/packages/cmd/secrets.go
cli/packages/cmd/tokens.go
cli/packages/util/credentials.go
cli/packages/util/folders.go
cli/packages/util/secrets.go

This PR adds support for the `--domain` flag or the `INFISICAL_API_URL` when users are logging in. Below I've attached a video that demonstrates the new functionality. This PR addresses https://github.com/Infisical/infisical/issues/2407
https://github.com/user-attachments/assets/5eb2d446-8f86-49d9-8ee8-66d32a9a298b
---

fix: allow preset domains for `infisical login`

---

backend/src/ee/services/dynamic-secret/providers/aws-elasticache.ts
backend/src/ee/services/dynamic-secret/providers/aws-iam.ts
backend/src/ee/services/dynamic-secret/providers/azure-entra-id.ts
backend/src/ee/services/dynamic-secret/providers/cassandra.ts
backend/src/ee/services/dynamic-secret/providers/elastic-search.ts
backend/src/ee/services/dynamic-secret/providers/ldap.ts
backend/src/ee/services/dynamic-secret/providers/mongo-db.ts
backend/src/ee/services/dynamic-secret/providers/rabbit-mq.ts
backend/src/ee/services/dynamic-secret/providers/redis.ts
backend/src/ee/services/dynamic-secret/providers/sap-hana.ts
backend/src/ee/services/dynamic-secret/providers/snowflake.ts
backend/src/ee/services/dynamic-secret/providers/sql-database.ts
backend/src/ee/services/dynamic-secret/providers/totp.ts

I realized while doing some testing for dynamic secrets, that we have a recurring pattern in our dynamic secret providers that would in some cases cause a 500 error. This would happen when the renewal statement was empty.
Additionally, I also found a bug with Cassandra, that would make custom renewal statements break the dynamic secret. Cassandra was using the revocation statement in the renewal, which means when you would attempt to renew a Cassandra dynamic secret, it will actually revoke the credential.
I also did some general cleanup, nothing major though.
---

fix(dynamic-secrets): renewal 500 error

---

backend/src/services/integration-auth/integration-sync-secret.ts

This fix ensures we only attempt to sync Azure Key Vault secrets that are not disabled in Azure.
**Now:**
**Previously** fetching the disabled key would throw an error, and block remaining sync functions
Manually tested by creating disabled secrets in Azure and manually triggering sync to replicate issue and create fix
---

Fix(Azure Key Vault): Ignore disabled secrets

---

frontend/src/views/SecretMainPage/components/ActionBar/FolderForm.tsx

Simple fix
Error from: "Folder name cannot contain spaces. Only underscore and dashes"
Error to: "Folder name can only contain letters, numbers, dashes, and underscores"
manual testing
---

improve: Folder name input validation text

---

frontend/src/hooks/usePagination.tsx
frontend/src/views/Org/IdentityPage/components/IdentityProjectsSection/IdentityProjectRow.tsx
frontend/src/views/Org/IdentityPage/components/IdentityProjectsSection/IdentityProjectsTable.tsx
frontend/src/views/Org/MembersPage/MembersPage.tsx
frontend/src/views/Org/MembersPage/components/OrgGroupsTab/components/OrgGroupsSection/OrgGroupsSection.tsx
frontend/src/views/Org/MembersPage/components/OrgGroupsTab/components/OrgGroupsSection/OrgGroupsTable.tsx
frontend/src/views/Org/MembersPage/components/OrgMembersTab/OrgMembersTab.tsx
frontend/src/views/Org/MembersPage/components/OrgMembersTab/components/OrgMembersSection/OrgMembersTable.tsx
frontend/src/views/Org/Types/TabSections.ts
frontend/src/views/Org/UserPage/components/UserProjectsSection/UserProjectRow.tsx
frontend/src/views/Org/UserPage/components/UserProjectsSection/UserProjectsTable.tsx
frontend/src/views/Project/MembersPage/MembersPage.tsx
frontend/src/views/Project/MembersPage/components/GroupsTab/components/GroupsSection/GroupsTable.tsx
frontend/src/views/Project/MembersPage/components/MembersTab/MembersTab.tsx
frontend/src/views/Project/MembersPage/components/MembersTab/components/AddMemberModal.tsx
frontend/src/views/Project/MembersPage/components/MembersTab/components/MembersTable.tsx

This PR adds pagination, sort and filtering for the user/identity projects tables and org/project members tables. Also includes minor UI improvements.
User Projects:
Identity Projects:
Org Members:
Project Members:
Project Groups: 
Org Groups:
```sh
```
---

Improvement: Users, Groups and Projects Table Pagination

---

backend/src/ee/services/permission/org-permission.ts

This PR fixes an org custom role will full permission not able to create an admin role. This was happening because there is an unused permission in admin which was not set in other places
```sh
```
---

feat: removed unusued permission from org admin

---

frontend/src/components/navigation/NavHeader.tsx

Uses can now copy the full secret path without needing to reconstruct it manually.
---

improvement: copy full secret path 

---

cli/test/.snapshots/test-TestUniversalAuth_SecretsGetWrongEnvironment
cli/test/.snapshots/test-testUserAuth_SecretsGetAllWithoutConnection
cli/test/helper.go
cli/test/secrets_test.go

This will resolve the CLI tests failing and blocking our release CI. I added a function which removes `reqId` and `requestId` from the error response. I added `reqId` because we will be modifying the response to be `reqId` in the near future.
---

fix(cli): CLI tests failing due to dynamic request ID

---

frontend/src/components/v2/FilterableSelect/FilterableSelect.tsx
frontend/src/layouts/AppLayout/AppLayout.tsx
frontend/src/layouts/AppLayout/components/ProjectSelect/ProjectSelect.tsx
frontend/src/layouts/AppLayout/components/ProjectSelect/index.ts

This PR refactors and adds filter support to the sidebar project selection. Minor UI adjustments included.
```sh
```
---

Improvement: Sidebar Project Selection Filter Support

---

frontend/src/components/v2/Select/components/index.tsx
frontend/src/views/Org/MembersPage/components/OrgMembersTab/components/OrgMembersSection/OrgMembersTable.tsx
frontend/src/views/Org/UserPage/UserPage.tsx
frontend/src/views/Org/UserPage/components/UserDetailsSection.tsx

This PR adds truncation for the FilterableSelect component list option and removes displaying null for user's who do not have a last name set in org access control components.
```sh
```
---

Improvements: Truncate Filterable Select List Options and Fix Null Display of User Last Name

---

backend/src/services/project/project-service.ts

The project creation for identity was checking a minimum membership level requirement from organization level for being a part of project. The weird part is, if its custom role, it's assigned from organization custom role which was also failing. 
Now it automatically assign the machine identity as admin on project creation.
```sh
```
---

fix: resolved reduntant min membership check over project creation

---

backend/src/server/plugins/error-handler.ts
backend/src/server/routes/sanitizedSchemas.ts
frontend/src/hooks/api/types.ts

When input schema validation failed, the server would return a HTTP code 401 which could in some cases break the client.
This PR changes the schema validation HTTP error code to be 422 (Unprocessable Content) to be inline with standards.
Manual Testing
---

fix: Schema validation errors correctly returned as 422

---

backend/src/ee/services/dynamic-secret/providers/aws-elasticache.ts
backend/src/ee/services/dynamic-secret/providers/azure-entra-id.ts
backend/src/ee/services/dynamic-secret/providers/cassandra.ts
backend/src/ee/services/dynamic-secret/providers/elastic-search.ts
backend/src/ee/services/dynamic-secret/providers/mongo-atlas.ts
backend/src/ee/services/dynamic-secret/providers/mongo-db.ts
backend/src/ee/services/dynamic-secret/providers/rabbit-mq.ts
backend/src/ee/services/dynamic-secret/providers/redis.ts
backend/src/ee/services/dynamic-secret/providers/snowflake.ts
backend/src/ee/services/dynamic-secret/providers/sql-database.ts

This PR removes two characters `$`,`#` from password generator for dynamic secret that needs url encoding. 
```sh
```
---

feat: updated random pass generator of dynamic secret to use safe chars

---

frontend/src/components/notifications/Notifications.tsx
frontend/src/components/v2/CopyButton/CopyButton.tsx
frontend/src/components/v2/CopyButton/index.tsx
frontend/src/components/v2/Tooltip/Tooltip.tsx
frontend/src/hooks/api/dashboard/queries.tsx
frontend/src/hooks/api/secrets/queries.tsx
frontend/src/reactQuery.tsx

This PR adds copyable request IDs to serverside error notifications.
To handle this, 2 new `createNotification` props were created:
`cta: reactNode` : accepts child components to render on the bottom left of the notification (used for "Show More" modal above)
`copyActions?: { icon?: IconDefinition; value: string; name: string; label?: string }[]` : allows injecting multiple copyable values to the notification. `icon` default is faCopy, `label` will be displayed to the left of the copy button.
other changes:
New `CopyButton` component for ease of use and consistency across app
`Tooltip` component now has `prop.size` for when standard tooltip is too large
manually tested
---

Improvement(notifications): Add copyable request IDs to server side errors

---

backend/src/services/secret/secret-queue.ts

This PR contains a minor improvement for integration error sync messages by checking if the response data on a sync error is present, otherwise defaulting to an error message.
```sh
```
---

Improvement: Integration Error - Handle Response Data Empty String

---

backend/src/ee/services/audit-log/audit-log-types.ts
backend/src/lib/api-docs/constants.ts
backend/src/server/routes/v1/integration-auth-router.ts
backend/src/server/routes/v1/integration-router.ts
backend/src/services/integration-auth/integration-auth-service.ts
backend/src/services/integration-auth/integration-auth-types.ts
backend/src/services/integration/integration-service.ts
backend/src/services/integration/integration-types.ts
frontend/src/hooks/api/auditLogs/constants.tsx
frontend/src/hooks/api/auditLogs/enums.tsx

This PR adds endpoint to update integration auth id. Used by terraform.
```sh
```
---

feat: added endpoint to update integration auth

---

frontend/src/components/v2/projects/NewProjectModal.tsx

Removed the previously necessary 2 second delay when creating projects, and instead added a forceful refetch of projects. We are already invalidating the get all projects query after creating a new project, so this seems redundant right? No. When we invalidate queries, it doesn't wait for them to invalidate. It starts the invalidation, and then redirects to the project page, which causes the UI to glitch out. To completely fix this, we do a manual refetch and await it.
---

fix(dashboard): improved project creation speed

---

frontend/src/helpers/parseEnvVar.ts
frontend/src/views/SecretMainPage/components/CreateSecretForm/CreateSecretForm.tsx
frontend/src/views/SecretOverviewPage/components/CreateSecretForm/CreateSecretForm.tsx

Fixed pasting secrets into the create secret modal. Previously the paste behavior was very buggy, and caused the value to be wiped if you pasted again. It would also wipe the secret key if you pasted a new value. All in all it felt very unnatural to use the secret paste feature.
Additionally I also fixed the splitter, so the value becomes everything after the FIRST splitter (such as `:` or `=`), instead of the last.
---

fix(dashboard): pasting secrets into create secret modal

---

backend/src/services/smtp/smtp-service.ts
backend/src/services/smtp/templates/accessApprovalRequest.handlebars
backend/src/services/smtp/templates/accessSecretRequestBypassed.handlebars
backend/src/services/smtp/templates/emailMfa.handlebars
backend/src/services/smtp/templates/emailVerification.handlebars
backend/src/services/smtp/templates/externalImportFailed.handlebars
backend/src/services/smtp/templates/externalImportStarted.handlebars
backend/src/services/smtp/templates/externalImportSuccessful.handlebars
backend/src/services/smtp/templates/historicalSecretLeakIncident.handlebars
backend/src/services/smtp/templates/integrationSyncFailed.handlebars
backend/src/services/smtp/templates/newDevice.handlebars
backend/src/services/smtp/templates/organizationInvitation.handlebars
backend/src/services/smtp/templates/passwordReset.handlebars
backend/src/services/smtp/templates/pkiExpirationAlert.handlebars
backend/src/services/smtp/templates/scimUserProvisioned.handlebars
backend/src/services/smtp/templates/secretApprovalRequestNeedsReview.handlebars
backend/src/services/smtp/templates/secretLeakIncident.handlebars
backend/src/services/smtp/templates/secretReminder.handlebars
backend/src/services/smtp/templates/signupEmailVerification.handlebars
backend/src/services/smtp/templates/unlockAccount.handlebars
backend/src/services/smtp/templates/workspaceInvitation.handlebars

Adds a simple email footer to all email templates.
`Email sent via Infisical at ${URL}`
manually sent emails and caught by mailhog
---

improvement: Add email footer with instance URL

---

backend/src/db/migrations/20241213122320_add-index-for-secret-version-v2-folder.ts
backend/src/services/secret-v2-bridge/secret-version-dal.ts

This PR addresses the high CPU usage issue of the following query:
Explain result before optimization:
Explain result after optimization:
```sh
```
---

misc: address cpu usage issue of secret version query

---

backend/src/services/project/project-dal.ts

This PR fixes failing access to projects when there are only part of it via groups. This was because of the temporary all filter missing for group project access listing.
```sh
```
---

fix: group only access to project failing

---

backend/src/services/project/project-service.ts

This PR fixes a false `User not logged into org` error from the backend when they access `Access Control` page in organization. This was due to missing actorOrgId
```sh
```
---

fix: resolves a false org not logged in error

---

frontend/src/components/v2/Modal/Modal.tsx
frontend/src/views/SecretOverviewPage/SecretOverviewPage.tsx

- As mentioned in #2845, it can be frustrating for the user to see their data being lost when they mistakenly click outside
the modal while adding secrets.
This PR provides a probable fix for this by ensuring that the modal remains open.
**Note:** This is just one of the ways of fixing this problem. We need to decide an uniform way of handling modals throughout the product ( should modals close when clicked outside? ). This PR serves as a starting point for starting this discussion.
- This PR also includes a commit to enable the `modal` mode for radix dialogs. This ensures that interaction with outside elements is disabled and only dialog content is visible to screen readers. ( [Ref](https://www.radix-ui.com/primitives/docs/components/dialog) )
- Tested manually by opening the "Create …

improv ui: don't close "Create Secrets" modal when clicking outside it

---

backend/src/lib/api-docs/constants.ts
backend/src/services/integration-auth/integration-sync-secret-fns.ts
backend/src/services/integration-auth/integration-sync-secret.ts
backend/src/services/integration/integration-schema.ts
frontend/src/hooks/api/integrations/queries.tsx
frontend/src/hooks/api/integrations/types.ts
frontend/src/pages/integrations/azure-app-configuration/create.tsx
frontend/src/views/IntegrationsPage/IntegrationDetailsPage/components/IntegrationSettingsSection.tsx

This PR adds support for environment labeling and references as secret values.
The labeling is necessary incase there are multiple integrations for multiple environments, and the keys are overlapping. Azure supports multiple secrets with the same key, with different labels.
Reference support allows for users to set the secret value to an azure reference. If this happens, we set the content type of the azure key, to `application/vnd.microsoft.appconfig.keyvaultref+json;charset=utf-8`, which indicates that the secret should be treated as a reference in Azure App Config. 
---

feat(azure-app-integration): label & reference support

---

backend/e2e-test/mocks/queue.ts
backend/src/lib/knex/index.ts
backend/src/queue/queue-service.ts
backend/src/server/routes/index.ts
backend/src/server/routes/v2/organization-router.ts
backend/src/services/auth-token/auth-token-dal.ts
backend/src/services/auth-token/auth-token-service.ts
backend/src/services/auth/auth-login-service.ts
backend/src/services/org/org-service.ts
backend/src/services/project/project-service.ts
backend/src/services/resource-cleanup/resource-cleanup-queue.ts
backend/src/services/secret/secret-dal.ts
backend/src/services/secret/secret-fns.ts
backend/src/services/secret/secret-queue.ts
backend/src/services/secret/secret-service.ts
frontend/src/hooks/api/auth/queries.tsx
frontend/src/hooks/api/organization/queries.tsx
frontend/src/views/Login/Login.utils.tsx
frontend/src/views/Org/components/CreateOrgModal.tsx

This PR fixes secret reminders not getting deleted when secrets are deleted. Additionally, I've also added coverage for project and organization deletions. This means if a project or organization is deleted, all secrets within that have reminders, will have their reminder job removed, just like on a normal secret deletion.
**Misc**
1. While testing the deletion of reminders on org-level, I realized that after a user deletes an organization, they're completely unable to create a new organization without logging out. This PR also addresses this issue. I also found a lot of UI bugs with the `/org/none` page, this PR fixes those as well to make the entire flow run more smoothly.
2. Added new `$notNull` filter for the `find` ORM.
---

fix(secret-reminders): proper cleanup on deleted resources

---

backend/src/ee/routes/v1/index.ts
backend/src/ee/routes/v1/ssh-certificate-router.ts
docs/api-reference/endpoints/ssh/ca/create.mdx
docs/api-reference/endpoints/ssh/ca/delete.mdx
docs/api-reference/endpoints/ssh/ca/list-certificate-templates.mdx
docs/api-reference/endpoints/ssh/ca/list.mdx
docs/api-reference/endpoints/ssh/ca/public-key.mdx
docs/api-reference/endpoints/ssh/ca/read.mdx
docs/api-reference/endpoints/ssh/ca/update.mdx
docs/api-reference/endpoints/ssh/certificate-templates/create.mdx
docs/api-reference/endpoints/ssh/certificate-templates/delete.mdx
docs/api-reference/endpoints/ssh/certificate-templates/list.mdx
docs/api-reference/endpoints/ssh/certificate-templates/read.mdx
docs/api-reference/endpoints/ssh/certificate-templates/update.mdx
docs/api-reference/endpoints/ssh/certificates/issue-credentials.mdx
docs/api-reference/endpoints/ssh/certificates/sign-key.mdx
docs/mint.json
frontend/src/hooks/api/ssh-ca/mutations.tsx

This PR exposes SSH endpoints to the API reference and updates the SSH `sign` and `issue` endpoint structures.
---

Expose ssh endpoints to api reference, update ssh sign/issue endpoints

---

cli/go.mod
cli/go.sum
cli/packages/cmd/ssh.go

This PR adds two commands `infisical ssh sign-key` and `infisical ssh issue-credentials` for the upcoming Infisical SSH functionality:
More specifics:
- `sign-key`: Used to request a SSH certificate from Infisical by sending in an existing SSH public key to be signed by the SSH CA bound to a SSH template; this command is used when a developer/host has an existing SSH key pair already that they want to be used.
- `issue-credentials`: Used to request a new set of SSH credentials (public key, private key, certificate) from Infisical.
Both commands above are executed against a SSH template in Infisical (scoped to a SSH project); they work by placing resulting SSH credentials, as applicable to each command, into certain folder paths as specified by `outFilePath`.
---

CLI - SSH Capabilities

---

backend/src/server/plugins/error-handler.ts
backend/src/services/secret/secret-queue.ts

- This PR adds metrics for API errors and integration sync errors
```sh
```
---

misc: added metric for api errors

---

frontend/src/hooks/api/ca/queries.tsx

Fixes [#2786](https://github.com/Infisical/infisical/issues/2786#issue-2687943170)
This pull request addresses a bug in the Certificate Authorities section where clicking on a CA table row after selecting View Certificate results in a page error. 
**Root Cause**
The issue arises due to two hooks, useGetCaCerts and useGetCaCert, which are both using the same query key ("ca-cert") for fetching data:
useGetCaCerts: Called when clicking on a CA table row, it fetches an array of objects.
useGetCaCert: Called when clicking on the three dots and selecting View Certificate, it fetches a single object.
Since both hooks are using the same query key, the cache will store only the most recent data fetched. On clicking on View Certificate the useGetCert hook is called which returns an object and this …

Fix Error When Clicking on CA Table Row After Viewing Certificate in Certificate Authorities Tab

---

backend/src/services/integration-auth/integration-sync-secret.ts

By azure app configuration api, to pull rest of the values from paginated data is, using [@nextLink](https://learn.microsoft.com/en-us/azure/azure-app-configuration/rest-api-key-value?pivots=v1#pagination). The app name act as the base url. The nextLink act as a relative url that gives access to rest of the values. 
```sh
```
---

fix: resolved azure app config api not pulling all keys

---

Dockerfile.fips.standalone-infisical

- This ensures that ssh-keygen can be used for the fips version which uses a debian base
```sh
```
---

misc: updated openssh installation for fips

---

backend/src/services/integration-auth/integration-sync-secret.ts

This PR sets the `ForceDeleteWithoutRecovery` flag to `true` when deleting secrets from AWS Secrets Manager on integration sync. This resolves a bug where deleted secrets in AWS (because removed or set to an empty value within Infisical) still within their recovery window would cause an error to be thrown on subsequent syncs if the value was set or a new secret was added with the same name.
```sh
```
---

Fix: Set Force Flag on Delete Secret Command for AWS Secrets Manager

---

.github/workflows/deployment-pipeline.yml

Bump aws-actions/amazon-ecs-deploy-task-definition to resolve:
```
Error: Failed to register task definition in ECS: Unexpected key 'enableFaultInjection' found in params
Error: Unexpected key 'enableFaultInjection' found in params
```
errors.
deploy gamma; then follow up with prod
---

ci: Bump aws-actions/amazon-ecs-deploy-task-definition to v2

---

k8-operator/kubectl-install/install-secrets-operator.yaml

This PR updates the k8's manifest to be in sync with the operator.
Generated with
```
./bin/kustomize build ./config/default > ./kubectl-install/install-secrets-operator.yaml
```
---

fix: k8's manifest out of sync

---

backend/src/ee/services/audit-log/audit-log-dal.ts
frontend/src/hooks/api/auditLogs/constants.tsx
frontend/src/hooks/api/auditLogs/enums.tsx

This PR aims to resolve a time conversion bug happening in the audit logs. The frontend sends an ISO 8601 formatted timestamp to the API. This PR tells Postgres to explicitly handle timezone conversion on our behalf.
Additionally I also added the deleted-secrets event type to the frontend. Previously it was displaying `undefined`.
---

fix(audit-logs): time conversion bug

---

backend/src/ee/services/audit-log/audit-log-types.ts
backend/src/server/plugins/audit-log.ts
backend/src/server/routes/v1/secret-sharing-router.ts
backend/src/services/auth/auth-type.ts
frontend/src/hooks/api/auditLogs/constants.tsx
frontend/src/hooks/api/auditLogs/enums.tsx
frontend/src/hooks/api/auditLogs/types.tsx
frontend/src/pages/organization/AuditLogsPage/components/LogsFilter.tsx
frontend/src/pages/organization/AuditLogsPage/components/LogsTableRow.tsx

This PR introduces support for secret sharing audit logs. The 3 new events are:
1. Shared secret created
2. Shared secret deleted
3. Shared secret read
The created/deleted events will only happen if the secret is created within an organization. And the read event will be logged regardless if it's a public user, or an authenticated organization member reading the secret. This means we now have a new actor type called `Unknown User`. The Unknown user actor type will be used when the actor isn't authenticated.
**Smaller:**
I also added `isClearable` to the project selector in the audit logs tab, and removed the useEffect that made it default to a project on load.
---

feat(audit-logs): shared secrets audit logs

---

backend/src/lib/config/env.ts
backend/src/server/app.ts
docs/self-hosting/configuration/envars.mdx

This PR introduces support for custom CORS settings, defined in the environment variables of the instance. Currently we allow for customization of the allowed origins, and allowed headers.
---

feat(api): custom cors settings

---

frontend/src/pages/organization/UserDetailsByIDPage/components/UserDetailsSection.tsx

This PR fixes copying the user's username to the clipboard on the user details page.
```sh
```
---

Fix: Copy Username on User Details Page

---

.infisicalignore
docs/documentation/platform/audit-log-streams/audit-log-streams.mdx

This PR introduces better documentation for the Audit Log Streams. The purpose of the PR is to add transparency of the audit log structure, so the user know what to expect in their external logging provider. 
---

docs(audit-logs): audit log streams structure

---

backend/src/server/plugins/secret-scanner.ts
frontend/src/lib/fn/csv.ts
frontend/src/pages/organization/SecretScanningPage/SecretScanningPage.tsx
frontend/src/pages/organization/SecretScanningPage/components/ExportResultsModal.tsx
frontend/src/pages/organization/SecretScanningPage/components/ExportSecretScansModal.tsx
frontend/src/pages/organization/SecretScanningPage/components/SecretScanningLogsTable.tsx
frontend/src/pages/organization/SecretScanningPage/route.tsx

This PR introduces support for exporting radar secret scans to CSV or JSON. It supports filtering for status (all, resolved, or unresolved), github organization, and github repository.
@akhilmhdh We found an issue where the `installation_id` query parameter wouldn't get added to the parameters, even though it was included in the search validation. For now I've just entirely removed the search validation for the organization/secret-scanning endpoint. Please let me know your thoughts on this. 
Additionally Maidul and I have resolved a lot of issues with the Radar, that made it impossible to use for new users.
---

feat(radar): export radar data

---

backend/src/ee/routes/v1/secret-scanning-router.ts
backend/src/ee/services/secret-scanning/secret-scanning-dal.ts
backend/src/ee/services/secret-scanning/secret-scanning-service.ts
backend/src/ee/services/secret-scanning/secret-scanning-types.ts
frontend/src/hooks/api/secretScanning/index.tsx
frontend/src/hooks/api/secretScanning/mutation.ts
frontend/src/hooks/api/secretScanning/queries.ts
frontend/src/hooks/api/secretScanning/types.ts
frontend/src/pages/organization/SecretScanningPage/SecretScanningPage.tsx
frontend/src/pages/organization/SecretScanningPage/components/ExportSecretScansModal.tsx
frontend/src/pages/organization/SecretScanningPage/components/SecretScanningFilters.tsx
frontend/src/pages/organization/SecretScanningPage/components/types.ts

This PR adds pagination and filtering support to the Infisical Radar. Users can now select which repositories they wish to view leaks for, and what status they want to view.
This PR builds on top of #2981, which added exporting ability. I had to tweak the export logic slightly to work with pagination, as you'll notice in this PR.
---

feat(radar): pagination and filtering

---

backend/src/db/migrations/20250115222458_groups-unique-name.ts
backend/src/ee/services/group/group-service.ts
backend/src/ee/services/scim/scim-service.ts
backend/src/lib/api-docs/constants.ts
backend/src/lib/validator/index.ts
backend/src/lib/validator/validate-uuid.ts
backend/src/server/routes/v2/group-project-router.ts
backend/src/services/group-project/group-project-service.ts
backend/src/services/group-project/group-project-types.ts
backend/src/services/secret-sharing/secret-sharing-service.ts

This PR adds unique names to groups within organizations. The same group name can be used in different organizations, but one organization can only have one group with the same name.
The migration for this factors in the possibility that there already exists groups with duplicate names, which we need to resolve before adding the new unique constraint. We do this by suffixing `(<number>)` at the end of the duplicate group names.
This PR serves as a prerequisite to the Terraform PR, https://github.com/Infisical/terraform-provider-infisical/pull/88
---

feat(groups): unique names

---

frontend/src/pages/auth/SelectOrgPage/SelectOrgPage.tsx

This PR resolves an issue with the `infisical login` CLI command, which causes the CLI to never receive the auth token. Instead of opening a new window, now we are directly just redirecting the current page.
---

fix: saml redirect failing due to blocked pop-ups

---

backend/src/ee/services/scim/scim-service.ts

This PR fixes the SCIM user patch endpoint so that it does not mistakenly mark an email as "verified" even when it isn't. 
```sh
```
---

misc: address scim email verification patch issue

---

backend/src/server/routes/index.ts
backend/src/services/project/project-service.ts

This PR fixes project delete failing due to multiple reasons
1. When project delete triggers a cascade, the project role table is tried to delete. But this causes the project group and user table to throw a foreign key error.
2. When the same secret manager key id is in two projects, causes foreign key error. Happened due to project split.
```sh
```
---

fix: resolved failing project delete

---

frontend/src/layouts/OrganizationLayout/OrganizationLayout.tsx

This PR fixes org sidebar not showing up in org identity, groups, user detail section
```sh
```
---

fix: resolved org sidebar not showing in org member detail window

---

frontend/src/pages/secret-manager/SettingsPage/components/EnvironmentSection/AddEnvironmentModal.tsx
frontend/src/pages/secret-manager/SettingsPage/components/EnvironmentSection/UpdateEnvironmentModal.tsx

Our backend API env router has env slug max length as `64`. It seems for some reason frontend is validating it as `32` max. 
Updated to `64`
```sh
```
---

feat: updated ui validation for env to 64 like api

---

frontend/src/pages/secret-manager/integrations/TeamcityConfigurePage/TeamcityConfigurePage.tsx

This PR fixes a broken select on the Team City integration page that blocked creation.
```sh
```
---

Fix: UI Fix for Team City Integrations Create Page

---

frontend/src/pages/secret-manager/SecretDashboardPage/components/SecretListView/SecretListView.tsx

When updating a personal secret, it was triggering an update for shared secrets as well. This was purely a frontend issue, and no changes were needed on the backend. It was sending out multiple requests, one for personal and one for shared. In reality it's only supposed to send a request to update the personal secret. 
---

fix: approvals triggering for personal secrets

---

backend/src/server/routes/v1/identity-aws-iam-auth-router.ts
backend/src/server/routes/v1/identity-azure-auth-router.ts
backend/src/server/routes/v1/identity-gcp-auth-router.ts
backend/src/server/routes/v1/identity-jwt-auth-router.ts
backend/src/server/routes/v1/identity-kubernetes-auth-router.ts
backend/src/server/routes/v1/identity-oidc-auth-router.ts
backend/src/server/routes/v1/identity-token-auth-router.ts
backend/src/server/routes/v1/identity-universal-auth-router.ts
backend/src/services/identity-aws-auth/identity-aws-auth-service.ts
backend/src/services/identity-azure-auth/identity-azure-auth-service.ts
backend/src/services/identity-gcp-auth/identity-gcp-auth-service.ts
backend/src/services/identity-jwt-auth/identity-jwt-auth-service.ts
backend/src/services/identity-kubernetes-auth/identity-kubernetes-auth-service.ts
backend/src/services/identity-oidc-auth/identity-oidc-auth-service.ts
backend/src/services/identity-token-auth/identity-token-auth-service.ts
backend/src/services/identity-ua/identity-ua-service.ts
frontend/src/pages/organization/AccessManagementPage/components/OrgIdentityTab/components/IdentitySection/IdentityAwsAuthForm.tsx
frontend/src/pages/organization/AccessManagementPage/components/OrgIdentityTab/components/IdentitySection/IdentityAzureAuthForm.tsx
frontend/src/pages/organization/AccessManagementPage/components/OrgIdentityTab/components/IdentitySection/IdentityGcpAuthForm.tsx
frontend/src/pages/organization/AccessManagementPage/components/OrgIdentityTab/components/IdentitySection/IdentityJwtAuthForm.tsx
frontend/src/pages/organization/AccessManagementPage/components/OrgIdentityTab/components/IdentitySection/IdentityKubernetesAuthForm.tsx
frontend/src/pages/organization/AccessManagementPage/components/OrgIdentityTab/components/IdentitySection/IdentityOidcAuthForm.tsx
frontend/src/pages/organization/AccessManagementPage/components/OrgIdentityTab/components/IdentitySection/IdentityTokenAuthForm.tsx
frontend/src/pages/organization/AccessManagementPage/components/OrgIdentityTab/components/IdentitySection/IdentityUniversalAuthForm.tsx

Our backend logic considers max ttl and ttl to be zero and zero means it's non expiring. But our frontend and router doesn't accept 0. So made modifications as needed.
```sh
```
---

Resolved ttl and max ttl to be zero

---

backend/src/server/routes/v1/integration-auth-router.ts
backend/src/services/integration-auth/integration-app-list.ts
backend/src/services/integration-auth/integration-auth-service.ts
backend/src/services/integration-auth/integration-auth-types.ts
backend/src/services/integration-auth/integration-sync-secret.ts
backend/src/services/integration-auth/integration-token.ts
frontend/src/hooks/api/integrationAuth/index.tsx
frontend/src/hooks/api/integrationAuth/queries.tsx
frontend/src/hooks/api/integrationAuth/types.ts
frontend/src/pages/secret-manager/integrations/VercelConfigurePage/VercelConfigurePage.tsx

This PR aims to add support for custom environments for our Vercel Integration. Previously, the user wasn't able to select custom environments. The sync logic is slightly different for custom environments, requiring the usage of the `customEnvironmentIds` field.
---

feat(integrations/vercel): custom environments support

---

backend/src/server/routes/v1/password-router.ts
backend/src/services/auth-token/auth-token-service.ts
backend/src/services/auth-token/auth-token-types.ts
backend/src/services/auth/auth-password-service.ts
backend/src/services/auth/auth-password-type.ts
backend/src/services/smtp/smtp-service.ts
backend/src/services/smtp/templates/passwordSetup.handlebars
frontend/src/const/routes.ts
frontend/src/hooks/api/auth/queries.tsx
frontend/src/hooks/api/auth/types.ts
frontend/src/pages/auth/PasswordResetPage/PasswordResetPage.tsx
frontend/src/pages/auth/PasswordSetupPage/PasswordSetupPage.tsx
frontend/src/pages/auth/PasswordSetupPage/route.tsx
frontend/src/pages/middlewares/authenticate.tsx
frontend/src/pages/secret-manager/IntegrationsListPage/IntegrationsListPage.tsx
frontend/src/pages/secret-manager/SecretSyncDetailsByIDPage/SecretSyncDetailsByIDPage.tsx
frontend/src/pages/user/PersonalSettingsPage/components/ChangePasswordSection/ChangePasswordSection.tsx
frontend/src/routeTree.gen.ts
frontend/src/routes.ts

This PR adds support to setup a password for users who signed up via methods other than email/password. Also updates reset password from backup key to store hashed password.
PR also includes adjustments to Secret Syncs layout to conform to nav restructure.
```sh
```
---

Feature: Setup Password

---

backend/src/ee/services/audit-log/audit-log-dal.ts
backend/src/ee/services/audit-log/audit-log-service.ts
backend/src/ee/services/audit-log/audit-log-types.ts
backend/src/lib/api-docs/constants.ts
backend/src/server/routes/v1/organization-router.ts
frontend/src/hooks/api/auditLogs/types.tsx
frontend/src/pages/organization/AuditLogsPage/components/LogsFilter.tsx
frontend/src/pages/organization/AuditLogsPage/components/LogsSection.tsx
frontend/src/pages/organization/AuditLogsPage/components/types.tsx

This PR adds the ability to query audit logs by secret path. The user will need to select a project first, and then they can query by secret path.
---

feat(audit-logs): query by secret path

---

backend/src/ee/services/permission/project-permission.ts
frontend/src/pages/project/RoleDetailsBySlugPage/components/ProjectRoleModifySection.utils.tsx
frontend/src/pages/project/RoleDetailsBySlugPage/components/SecretPermissionConditions.tsx

This PR adds secret path validation in project permission for both ui and server when the path doesn't start with `/`
```sh
```
---

feat: added validation for secret path in permission

---

helm-charts/secrets-operator/Chart.yaml
helm-charts/secrets-operator/values.yaml
k8-operator/controllers/infisicalsecret/conditions.go
k8-operator/controllers/infisicalsecret/infisicalsecret_controller.go
k8-operator/controllers/infisicalsecret/infisicalsecret_helper.go

This PR contains a few fixes for the K8's operator.
1. InfisicalSecret CRD now prints the amount of secrets that were synced.
2. Example output: `Successfully synced 5 secrets. Operator will requeue after [10s]`
3. This is also added to the successful sync status condition.
2. Fixed the InfisicalSecret CRD trying to reconcile when condition status's are updated. This was causing the operator to requeue far more often than necessary. 
---

k8s: bug fixes and better prints

---

docs/sdks/languages/csharp.mdx

The InfisicalClient variable was wrong in the Basic Usage code block
A copy/paste of the Basic Usage code block doesn't compile. It's because the infisical client variable was wrongly spelled
---

fix: wrong client variable in c# code example

---

frontend/src/pages/secret-manager/OverviewPage/components/SecretOverviewTableRow/SecretRenameRow.tsx

issue: #3047 
In this PR, I updated two things. The first is to make the `Copy Secret Key` icon visible at all times instead of only on hover. I think this will improve usability, being a user myself, I didn't know this would happen until I accidentally hovered over it. In addition, I noticed that the tooltips were not inline with the Copy icon, and when you change the secret name, the Save and Cancel icon tooltips were also not aligned.
In line 198, I simply changed the opacity to 100 and removed the hover property.
I addressed the alignment issue by wrapping each Tooltip with a `div` that has the `relative` property, which fixed the offset bug.
I tested my changes by running the dev environment and making sure that the tooltips were centered over the icons. I also resized the window …

Improve Visibility and Alignment of Tooltips and Copy Secret Key Icon

---

helm-charts/secrets-operator/Chart.yaml
helm-charts/secrets-operator/values.yaml
k8-operator/config/samples/crd/infisicalsecret/infisical-secret-crd-with-template.yml
k8-operator/controllers/infisicalsecret/infisicalsecret_helper.go

This PR fixes an issue with k8s operator template function `decodeBase64ToBytes` to save files as ansii format instead of making it binary. This was because golang templating engine when it gets as bytes it's encoding it as ansii.
We fixed this by stating that type is string, so the templating engine of golang doesn't do any encoding and save it as it is.
```sh
```
---

Resolved base64 decode saving file as ansii

---

.github/workflows/helm-release-infisical-core.yml
.github/workflows/release_docker_k8_operator.yaml
helm-charts/upload-infisical-core-helm-cloudsmith.sh
helm-charts/upload-k8s-operator-cloudsmith.sh

Combine image release with helm release so that one happens after the other. This will help reduce manual work.

Combine image release with helm

---

backend/src/db/migrations/20250204025010_app-connections-and-secret-syncs-unique-constraint.ts
backend/src/lib/error-codes/database.ts
backend/src/lib/error-codes/index.ts
backend/src/services/app-connection/app-connection-service.ts
backend/src/services/secret-sync/secret-sync-dal.ts
backend/src/services/secret-sync/secret-sync-service.ts

This PR moves the unique name constraint on app connections and secret syncs from the API to the DB layer to prevent concurrency bypass with terraform.
- [] Improvement
---

Fix: Move App Connection and Secret Sync Unique Name Constraint to DB

---

frontend/src/hooks/api/dashboard/types.ts
frontend/src/pages/secret-manager/OverviewPage/components/SelectionPanel/SelectionPanel.tsx
frontend/src/pages/secret-manager/OverviewPage/components/SelectionPanel/components/MoveSecretsDialog/MoveSecretsDialog.tsx
frontend/src/pages/secret-manager/OverviewPage/components/SelectionPanel/components/MoveSecretsDialog/index.ts
frontend/src/pages/secret-manager/OverviewPage/components/SelectionPanel/components/index.ts

This PR adds support to move secrets across multiple environments on the secret overview page
```sh
```
---

Feature: Secrets Overview Page Move Secrets

---

backend/src/services/secret-folder/secret-folder-dal.ts

This PR excludes folders with `isReserved` equal to `true` to prevent displaying reserved folders in deep search / moving secrets.
```sh
```
---

Fix: Exclude Reserved Folders from Deep Search Folder Query

---

backend/src/lib/api-docs/constants.ts
backend/src/server/routes/v3/secret-router.ts
backend/src/services/secret-v2-bridge/secret-v2-bridge-dal.ts
backend/src/services/secret-v2-bridge/secret-v2-bridge-types.ts
backend/src/services/secret/secret-service.ts
backend/src/services/secret/secret-types.ts

This PR adds support for filtering secrets by their metadata. If multiple metadata fields are passed in, the operation will work as an `AND` operator, which means the secrets returned will match all the metadata fields.
The format for the `secretMetadata` query parameter is `key1:value1,key2:value2`.
The metadata filter is limited to max 10 metadata key-value pairs. This is to avoid overloading the backend, and to avoid bad actors passing into a list with millions of key-value pairs, which could result in a DoS attack.
```typescript
if (metadata.length > 10) {
ctx.addIssue({
code: z.ZodIssueCode.custom,
message: "You can only filter by up to 10 metadata fields"
});
}
```
---

feat(api): list secrets filter by metadata

---

backend/src/db/migrations/20250207002643_secret-syncs-increase-message-length.ts
backend/src/services/secret-sync/secret-sync-fns.ts
frontend/src/pages/secret-manager/IntegrationsListPage/components/SecretSyncsTab/SecretSyncTable/SecretSyncRow.tsx

This PR increases that max message length for job failure messages on Secret Syncs, and handles truncation if a message exceeds this limit.
```sh
```
---

Improvement: Increase Max Error Message Size for Secret Syncs

---

backend/src/db/migrations/20250205045509_increase-gcp-auth-limit.ts
backend/src/db/migrations/20250205220952_kms-keys-drop-slug-col.ts
backend/src/db/schemas/kms-keys.ts
backend/src/ee/services/audit-log/audit-log-types.ts
backend/src/lib/api-docs/constants.ts
backend/src/lib/knex/index.ts
backend/src/lib/knex/prependTableNameToFindFilter.ts
backend/src/server/routes/v1/cmek-router.ts
backend/src/services/cmek/cmek-service.ts
backend/src/services/kms/kms-key-dal.ts
backend/src/services/secret-sync/secret-sync-dal.ts
docs/api-reference/endpoints/kms/keys/get-by-id.mdx
docs/api-reference/endpoints/kms/keys/get-by-name.mdx
docs/mint.json
frontend/src/hooks/api/auditLogs/constants.tsx
frontend/src/hooks/api/auditLogs/enums.tsx
frontend/src/pages/kms/OverviewPage/components/CmekTable.tsx

This PR adds two new CMEK endpoints to retrieve a key by ID and name. In addition, all CMEK endpoints have been updated to return the key with the `version` and `encryptionAlgorithm` properites to normalize responses (previously only list keys did this). `isReserved` has also been omitted as it is not informative to the user. Minor CMEK UI adjustments.
In addition the `slug` column on the `kms_keys` table has been removed.
```sh
```
---

Improvement: CMEK Additions and Normalization

---

frontend/src/components/v2/Breadcrumb/Breadcrumb.tsx

This PR removes `capitalize` from the breadcrumbs container to prevent casing changes of user named resources.
```sh
```
---

Improvement: Remove Capitalizion from Breadcrumbs Container

---

docs/changelog/overview.mdx

Update changelog with January 2025 entries

---

backend/src/server/routes/v3/secret-router.ts

This PR restricts the usage of colons in secret key. Additionally it fixes not being able to update already incorrectly formatted secret keys to a correctly formatted key
---

fix(api): disallow colon in secret name & allow updating malformed secret name

---

backend/src/services/identity-aws-auth/identity-aws-auth-validators.ts

This PR further improves our AWS ARN regex validation. It's now more permissive, as we seem to have missed a few cases previously. 
---

fix: arn regex validation

---

.github/workflows/check-api-for-breaking-changes.yml

The osdiff repo recently changed location which broke our breaking change check workflow. This PR resolves it. 
---

fix: breaking change check fix

---

frontend/src/layouts/OrganizationLayout/components/MinimizedOrgSidebar/MinimizedOrgSidebar.tsx

Fix flickering in the left sidebar's "Org" option for Safari users. The first part of the video shows the fix applied, while the second part demonstrates the previous issue.
Root cause: 
When using the modal option, the following setting was applied to the dropdown menu:
`"The modality of the dropdown menu. When set to true, interaction with outside elements will be disabled, and only menu content will be visible to screen readers."`
This caused the icon to lose focus, leading to the flickering issue in Safari. Since the dropdown is rendered on top of the rest of the content and is hidden when it loses focus, this setting is unnecessary.
https://github.com/user-attachments/assets/0612edc4-1603-48b9-aa03-d1a0eca03680
```sh
```
---

Set modal=false on DropdownMenu on MinimizedOrgSidebar orgDetails option

---

.github/workflows/release_docker_k8_operator.yaml

This PR fixes our k8s release step by adding the required permissions to the workflow.
Failed workflow example: https://github.com/Infisical/infisical/actions/runs/14182290011/job/39730940713
---

fix: add permissions to k8s release

---

backend/src/services/secret-import/secret-import-service.ts

Fix for getFolderIsImportedBy function throwing when the folder did not exist on at least one environment
```sh
```
---

Avoid throwing on getFolderIsImportedBy no folder found

---

backend/src/server/routes/index.ts
backend/src/services/microsoft-teams/microsoft-teams-service.ts
backend/src/services/super-admin/super-admin-service.ts
frontend/src/pages/admin/OverviewPage/components/MicrosoftTeamsIntegrationForm.tsx

This PR fixes issues with the Microsoft Teams workflow integration on deployments using horizontal scaling. The issue was that the `teamsBot` and `adapter` variables defined in the microsoft-teams-service.ts` service handler were stateful. This means that if I trigger an update for instance-level settings, it wouldn't propagate to all the API instances. We are now using cron to forcefully resync every 5 minutes if a change has happened in the server config.
---

fix(workflow-integrations): microsoft teams scaling issues

---

backend/src/ee/services/secret-approval-request/secret-approval-request-dal.ts

Fix approval request ordering to be by date.
Whenever there are more than 20 requests by multiple users, some requests get pushed to the second page even if they're the most recent.

Fix approval request ordering

---

frontend/src/pages/secret-manager/IntegrationsListPage/IntegrationsListPage.tsx

This PR removes the legacy badge/banner from the Native Integrations UI
```sh
```
---

improvement(native-integrations): Remove legacy badge/banner from native integrations UI

---

backend/src/ee/services/oidc/oidc-config-service.ts

This PR adds handling for the groups claim if it is a string instead of the expected string array.
```sh
```
---

improvement(oidc-group-membership-mapping): Update OIDC group claims to handle single group string

---

frontend/src/pages/auth/LoginPage/LoginPage.tsx

At last, we fixed the CLI login bug with callback port not being used correctly.
The issue was that on the login page we had a useEffect that would redirect to select org, and within select org we'd do SAML auth flow or redirect to the organization page. But at the same time, it would also load the `InitialStep` component because the step would always default to 1 on page load. Inside the InitialStep component we also handle SAML auth. This created a race condition leading to strange behavior for SAML auth handling.
The solution is to first wait for the useEffect to finish before rendering the rest of the login page.
---

fix(auth): cli auth bug

---

frontend/src/components/secret-syncs/forms/SecretSyncOptionsFields/SecretSyncOptionsFields.tsx
frontend/src/pages/organization/SsoPage/components/OrgSsoTab/OrgSsoTab.tsx

This PR adds an empty display if no SSO options are enabled for the server on the SSO Settings Page
```sh
```
---

improvement(sso-page): Add empty display for SSO general tab if no SSO is enabled

---

backend/src/services/identity-kubernetes-auth/identity-kubernetes-auth-service.ts

This PR addresses an issue with Kubernetes auth, which assumes that users using Kubernetes auth doesn't have a protocol specified for their kubernetes host URL. This was recently introduced when rolling out gateway support for k8s auth, #3590 
---

fix(identities-auth): fixed kubernetes auth login

---

backend/src/db/migrations/20250517002223_secret-share-to-specific-emails.ts
backend/src/db/schemas/secret-sharing.ts
backend/src/server/routes/v1/secret-sharing-router.ts
backend/src/services/secret-sharing/secret-sharing-service.ts
backend/src/services/secret-sharing/secret-sharing-types.ts
frontend/src/hooks/api/secretSharing/queries.ts
frontend/src/hooks/api/secretSharing/types.ts
frontend/src/pages/organization/SettingsPage/components/OrgProductSelectSection/OrgProductSelectSection.tsx
frontend/src/pages/public/ShareSecretPage/ShareSecretPage.tsx
frontend/src/pages/public/ShareSecretPage/components/ShareSecretForm.tsx
frontend/src/pages/public/ViewSecretRequestByIDPage/ViewSecretRequestByIDPage.tsx
frontend/src/pages/public/ViewSharedSecretByIDPage/ViewSharedSecretByIDPage.tsx
frontend/src/pages/public/ViewSharedSecretByIDPage/route.tsx
frontend/src/pages/secret-manager/SettingsPage/components/ProjectGeneralTab/ProjectGeneralTab.tsx
frontend/src/pages/secret-manager/SettingsPage/components/SecretSharingSection/SecretSharingSection.tsx

Allows you to specify emails to share secrets with. Works with both out-of-org and in-org users.

feat(secret-sharing): Specify Emails

---

cli/packages/cmd/agent.go

This PR fixes the exit code on secrets error if `exit-on-auth` is set to true.
We are using the agent in our K8s agent injector, and it depends on the exit codes being correct.
---

fix(agent): exit code 1 on fetch secrets error

---

k8-operator/controllers/infisicalpushsecret/infisicalpushsecret_controller.go
k8-operator/main.go

This PR serves as a fix for the error below. Essentially when users would try to create namespace-scoped installations, it would fail because the PushSecret controller manager would try to watch for clustergenerator crd changes. This doesn't work in namespace-scoped installations because they don't have access to cluster resources by default when rbac is scoped as well.
```
E0520 17:51:12.363296       1 reflector.go:140] pkg/mod/k8s.io/client-go@v0.26.1/tools/cache/reflector.go:169: Failed to watch *v1alpha1.ClusterGenerator: failed to list *v1alpha1.ClusterGenerator: clustergenerators.secrets.infisical.com is forbidden: User "system:serviceaccount:custom-namespace:infisical-opera-controller-manager" cannot list resource "clustergenerators" in API group "secrets.infisical.com" at the …
```

fix(k8s): disable clustergenerator watching in namespace scoped installations

---

frontend/src/pages/organization/AccessManagementPage/components/UpgradePrivilegeSystemModal/UpgradePrivilegeSystemModal.tsx

This PR adds proper notice for non-admins trying to do privilege upgrade
```sh
```
---

misc: added proper notice for non-admins doing privilege upgrade

---

backend/src/server/routes/v1/identity-kubernetes-auth-router.ts
backend/src/services/identity-kubernetes-auth/identity-kubernetes-auth-service.ts

Currently users can't use https/http on gateway kubernetes hosts. This PR handles the split operation for both with/without protocol.
Example:
Previously `https://kubernetes.default.svc.cluster.local:443` would fail if a gateway is selected.
---

fix: allow https on gateway k8s hosts

---

backend/src/ee/services/access-approval-policy/access-approval-policy-dal.ts
backend/src/ee/services/access-approval-request/access-approval-request-service.ts
frontend/src/pages/secret-manager/SecretApprovalsPage/components/ApprovalPolicyList/components/AccessPolicyModal.tsx

Fix for an edge case where we were retrieving a deleted policy when there was one valid in place (blocking users from requesting access), and minor fix on default values on policy form where by default some prefilled values were not set on the form leading to errors on the validation although there were values on the inputs.
```sh
```
---

feat(access-request): fix deleted policy interfering with the newest and valid policy and fix for default values on the creation form

---

frontend/package-lock.json
frontend/package.json
frontend/src/main.tsx

In air gapped, lotties won't load because the WASM player is fetched from CDN. This PR bundles the player so we can fetch it directly from file system
Note: When using @lottiefiles/dotlottie-web directly, we need to make sure its version matches the one required by @lottiefiles/dotlottie-react. You can double check this with:
`npm list @lottiefiles/dotlottie-web`
The version should match in both places:
@lottiefiles/dotlottie-web@0.38.2  <-- This version
@lottiefiles/dotlottie-web@0.38.2    <-- Should match this version
If they don't match, the Lottie animations will fail to load because the WASM binary version needs to be compatible with the React components.

Add support for offline lottie 

---

cli/packages/cmd/dynamic_secrets.go
cli/packages/cmd/folder.go
cli/packages/cmd/secrets.go
cli/packages/util/folders.go
cli/packages/util/secrets.go

- This PR ensures that the `infisical init` error only shows up when project ID flag is not defined for the command. 
```sh
```
---

misc: workspace file now only needed when project id is omitted (CLI)

---

backend/src/services/smtp/emails/BaseEmailWrapper.tsx

This PR adds a small amount of y padding so emails aren't flush with top of container if they don't auto center
```sh
```
---

improvement(email-templates): Add y-padding to email body

---

frontend/src/pages/project/RoleDetailsBySlugPage/components/ProjectRoleModifySection.utils.tsx

This PR adds frontend permission schema checks for comma separated values in EQ and NEQ checks.
```sh
```
---

improvement(permissions): Prevent comma separated values with eq and neq checks

---

frontend/src/hooks/api/roles/mutation.tsx
frontend/src/pages/organization/AccessManagementPage/AccessManagementPage.tsx

This PR adds a permission display when no elements on the org access control page are visible. 
Also includes fix for role permissions update mutation
```sh
```
---

improvement(org-access-control): Add org access control no access display

---

helm-charts/infisical-gateway/CHANGELOG.md
helm-charts/infisical-gateway/Chart.yaml
helm-charts/infisical-gateway/values.yaml

Bumps the CLI image version to the latest version to support using the gateway as reviewer for K8's identity auth.
Related PR: https://github.com/Infisical/infisical/pull/3731
---

helm(infisical-gateway): bump CLI image version to latest

---

backend/src/db/migrations/20250610173646_identity-kubernetes-auth-optional-host-url.ts
backend/src/db/schemas/identity-kubernetes-auths.ts
backend/src/lib/gateway/types.ts
backend/src/server/routes/v1/identity-kubernetes-auth-router.ts
backend/src/services/identity-kubernetes-auth/identity-kubernetes-auth-service.ts
backend/src/services/identity-kubernetes-auth/identity-kubernetes-auth-types.ts
cli/packages/gateway/connection.go
cli/packages/gateway/constants.go
frontend/src/hooks/api/identities/types.ts
frontend/src/pages/organization/AccessManagementPage/components/OrgIdentityTab/components/IdentitySection/IdentityKubernetesAuthForm.tsx
helm-charts/infisical-gateway/CHANGELOG.md
helm-charts/infisical-gateway/Chart.yaml
helm-charts/infisical-gateway/values.yaml

This PR expands on the gateway HTTP proxy initiative, and the gateway can now be used as an end-to-end proxy for Kubernetes API. The new action will off-load the cluster URL, CA Certificate, and token management directly to the gateway. This means the user won't need to specify certificates, tokens, or cluster URL's anymore.
Currently we're rolling this out for K8's auth, But we are planning on adding it to the Kubernetes dynamic secrets as well.
---

feat(gateway): use gateway for full k8s request life-cycle

---

backend/src/lib/gateway/gateway.ts
backend/src/lib/gateway/types.ts
backend/src/services/identity-kubernetes-auth/identity-kubernetes-auth-service.ts
cli/packages/gateway/connection.go

Minor change to allow for actual empty target URLs. Previously we'd specifically handle `/:0`, but now it just works as an empty string, meaning we can now pass undefined target hosts when using gateway's on the backend.
---

fix: allow for empty target URLs

---

backend/src/server/plugins/serve-ui.ts

This aims to fix the issue where it says 
```
TypeError
Cannot read properties of undefined (reading 'component')
```
by telling the browser to not cache any chunks. It seems that the existing no cache header from fastify isn't doing the trick. this may be worth a shot

disable caching for frontend assets 

---

backend/src/services/org/org-service.ts
backend/src/services/smtp/emails/OrganizationInvitationTemplate.tsx

The issue with the `firstName` and `email` usage in the `inviteUserToOrganization` function was that, for Terraform and machine identity flows, the email was not being sent. As a result, users were not receiving the invitation email.
This has been fixed to handle these cases properly, and the template message has been updated accordingly.
```sh
```
---

feat(invite-users): fix issue where invitations were not sent when the actor was an identity

---

backend/src/services/identity-aws-auth/identity-aws-auth-service.ts
backend/src/services/identity-aws-auth/identity-aws-auth-types.ts
docs/documentation/platform/identities/aws-auth.mdx

This PR adds documentation for how to use identity AWS auth from within an EKS pod.
Additionally I've added a smaller fix to allow for lowercase `authorization` header in the AWS auth login handler. When we compose a signed request with `@aws-sdk/signature-v4` in Node.js, the authorization header is lowercase, which we currently don't handle on the API-side.
The SDK currently normalizes the authorization header to be uppercase (which the API expects), but this fix will fix it on server-side as well.
---

docs(identities/aws-auth): eks pod auth

---

backend/src/ee/routes/v1/secret-approval-request-router.ts
backend/src/ee/services/secret-approval-request/secret-approval-request-service.ts
frontend/src/components/v2/SecretInput/SecretInput.tsx
frontend/src/hooks/api/secretApprovalRequest/types.ts
frontend/src/pages/secret-manager/SecretApprovalsPage/components/SecretApprovalRequest/components/SecretApprovalRequestChangeItem.tsx

This PR fixes a smaller UI bug related to how hidden secret values are displayed in the secret change approval page. Previously it would allow you to click the "Hide/Unhide" icons. Now it mirrors the logic we have on the main secrets page.
I've also removed the `*****` value being returned directly on the API level. I've made it more inline with our secrets router which returns `<hidden-by-infisical>`, and a boolean flag to indicate if the secret value is hidden or not.
---

fix: hidden secret value in secret approvals

---

backend/src/ee/routes/v1/group-router.ts
backend/src/ee/services/group/group-dal.ts

This PR ensures that custom role slug of a group is returned. Mainly used by Terraform resource
```sh
```
---

misc: add custom role slug in fetch group

---

frontend/src/pages/project/RoleDetailsBySlugPage/components/DuplicateProjectRoleModal.tsx

Duplicating predefined roles in project would fail due to those roles having `read`, `readValue` and `describeSecret` permission to keep backward compatibility.
This PR fixes that by removing `read` action if the permission contains the newer permission set.
```sh
```
---

fix: resolved failing duplication of predefined roles

---

docs/docs.json

This PR is a fix for the SDK and changelog tabs in the documentation navigation. There was a missing group name causing the page to not render.
---

fix(docs): sdk and changelog tab not loading

---

cli/packages/cmd/user.go
docs/cli/commands/user.mdx

This PR will allow users to fetch just the JWT for `infisical user get token` command using the `--plain` flag
```sh
```
---

misc: add plain support for user get token in CLI

---

backend/src/services/secret-folder/secret-folder-service.ts

This PR resolves an issue with deleting folders with UUID as names. Our delete folder endpoint supports both ID's and folder names as input. 
Previously, if the folder had a UUID as name, it would be impossible to delete because it would try to delete by ID. The fix is to first check for name, and if nothing is found then find by ID instead.
To reproduce the issue, use the Go SDK as seen below:
```go
func TestInfisical(t *testing.T) {
if err := godotenv.Load("../../.env"); err != nil {
t.Fatalf("Failed to load environment variables: %v", err)
}
environment := os.Getenv("ENVIRONMENT")
clientID := os.Getenv("INFISICAL_CLIENT_ID")
clientSecret := os.Getenv("INFISICAL_CLIENT_SECRET")
projectID := os.Getenv("INFISICAL_PROJECT_ID")
siteURL := os.Getenv("INFISICAL_SITE_URL")
client := …
```

fix(secret-folders): delete folder by ID

---

helm-charts/infisical-standalone-postgres/CHANGELOG.md
helm-charts/infisical-standalone-postgres/templates/infisical.yaml
helm-charts/infisical-standalone-postgres/values.yaml

This PR adds support for `topologySpreadConstraints` in the Infisical core helm chart. This makes it possible for users to deploy Infisical across multiple availability zones and nodes (useful for HA)
---

feat(helm-charts/infiscal-core): topologySpreadConstraints support

---

backend/src/server/routes/v1/secret-sync-routers/secret-sync-endpoints.ts

This PR fixes audit log details not being passed from remove/import secrets endpoints for secret syncs
```sh
```
---

fix(secret-syncs): pass audit log info from import/delete secrets for sync endpoint

---

backend/src/db/knexfile.ts
backend/src/db/migrations/20250602155451_fix-secret-versions.ts

This PR moves the logger init function for standalone migrations to the entry knexfile
```sh
```
---

fix(migration): move logger init for standalone migration to entry knexfile

---

backend/src/db/migrations/20250710022434_add-index-for-access-token.ts

This PR will address issue with very long identity deletions due to a sequential scan over ALL identity access rows during CASCADE

add index for referencing columns in identity access token

---

backend/src/services/secret-folder/secret-folder-service.ts

Minor fix to createFolder function that was sending the new folder ID instead of the parent folder ID to the createCommit function.
```sh
```
---

Fix folder creation commits triggered on new folder instead of the parent

---

backend/src/db/migrations/20250710115149_required-path-on-approval-policies.ts
backend/src/db/schemas/access-approval-policies.ts
backend/src/db/schemas/secret-approval-policies.ts
backend/src/ee/routes/v1/access-approval-policy-router.ts
backend/src/ee/routes/v1/secret-approval-policy-router.ts
backend/src/ee/services/access-approval-policy/access-approval-policy-dal.ts
backend/src/ee/services/access-approval-policy/access-approval-policy-service.ts
backend/src/ee/services/access-approval-policy/access-approval-policy-types.ts
backend/src/ee/services/secret-approval-policy/secret-approval-policy-service.ts
backend/src/ee/services/secret-approval-policy/secret-approval-policy-types.ts
frontend/src/hooks/api/accessApproval/types.ts
frontend/src/hooks/api/secretApproval/types.ts
frontend/src/pages/secret-manager/SecretApprovalsPage/components/ApprovalPolicyList/components/AccessPolicyModal.tsx

This PR improves how we handle approval policies. We have some discrepancies in how paths are handled in change/access policies.
**Change policy:** Allows for an empty path, and it will result in a environment-wide policy
**Access policy**: Doesn't allow for an empty path, it'll break if an empty path is used.
For access policies I've added extra validation to ensure policies are never created/updated with an empty path. 
For _both_ access and change policies, I've added extra checks to ensure there can never be duplicate policies, because this would mess up the UI when creating access requests; and there's really no logical reason to have duplicate policies for a path by our current approach for approval policies
---

fix(approval-policies): improve policies handling

---

backend/src/db/migrations/20250710153448_adjust-approval-request-user-cols.ts
backend/src/db/schemas/access-approval-policies-approvers.ts
backend/src/db/schemas/certificate-authorities.ts
backend/src/db/schemas/certificates.ts
backend/src/db/schemas/secret-approval-requests.ts
backend/src/ee/routes/v1/secret-approval-request-router.ts
backend/src/ee/services/audit-log/audit-log-types.ts
backend/src/ee/services/secret-approval-request/secret-approval-request-dal.ts
backend/src/ee/services/secret-approval-request/secret-approval-request-service.ts
frontend/src/pages/secret-manager/SecretApprovalsPage/components/SecretApprovalRequest/SecretApprovalRequest.tsx
frontend/src/pages/secret-manager/SecretApprovalsPage/components/SecretApprovalRequest/components/SecretApprovalRequestChanges.tsx

This PR fixes approval requests when a user deletes their account:
- secret approval request committer is now nullable to preserve secret change requests even when a user deletes their account (this was blocking user deletion)
- access requests now cascade delete when a user deletes there account 
```sh
```
---

fix(approval-workflows): allow null committer on secret approval request and cascade delete on access request

---

frontend/src/pages/secret-manager/OverviewPage/components/SecretOverviewTableRow/SecretOverviewTableRow.tsx

This PR makes the empty value circle on the secret overview table yellow instead of gray like the good ol' days
```sh
```
---

improvement(frontend): make empty value circle display on overview page yellow

---

backend/src/ee/services/access-approval-request/access-approval-request-service.ts
frontend/src/pages/secret-manager/SecretApprovalsPage/components/AccessApprovalRequest/components/ReviewAccessModal.tsx

This PR updates the frontend and backend to allow all users to reject their own access requests
```sh
```
---

improvement(access-approval): allow all users to reject their own access requests

---

frontend/src/components/v2/Breadcrumb/Breadcrumb.tsx
frontend/src/layouts/OrganizationLayout/components/NavBar/Navbar.tsx
frontend/src/layouts/ProjectLayout/components/ProjectSelect/ProjectSelect.tsx

This PR prevents the organization name from wrapping in the nav bar header, and expands header height if breadcrumbs wraps
```sh
```
---

improvement(frontend): prevent organization name wrap in header

---

backend/src/server/routes/v1/identity-oci-auth-router.ts
backend/src/services/identity-oci-auth/identity-oci-auth-types.ts

This PR adds support for OCI auth on the Go SDK, which works differently than the Node SDK. The Go SDK sends a Date header, not a x-date header. The signature generated doesn't include the date, and instead expects a separate `date` header to be present.
---

fix: oci auth for go sdk

---

backend/src/services/app-connection/github/github-connection-fns.ts

This PR improves error handling during GitHub credential validation by explicitly propagating relevant error messages from GitHub to the client. Previously, generic error messages were returned, which made debugging and user feedback more difficult.
This should in-turn help with debugging connection issues like #3820
---

fix: propogate Github app connection errors to the client properly

---

backend/src/services/app-connection/1password/1password-connection-fns.ts

This PR adds a response content type check in the case of OnePassword app connection - which should in-turn help with debugging connection issues like #4177
---

fix: verify response type

---

backend/src/services/secret-import/secret-import-fns.ts
backend/src/services/secret-sync/secret-sync-queue.ts
backend/src/services/secret-v2-bridge/secret-v2-bridge-fns.ts
backend/src/services/secret-v2-bridge/secret-v2-bridge-service.ts
backend/src/services/secret/secret-queue.ts

Change allSettled() => all() when the secret references are expanded, so if any error is thrown during that process (read access errors) it throws as well on the main function.
```sh
```
---

Throw when user does not have permission to read the referenced secret value

---

backend/src/server/lib/cookie.ts
backend/src/server/routes/v1/admin-router.ts
backend/src/server/routes/v1/sso-router.ts
backend/src/server/routes/v2/mfa-router.ts
backend/src/server/routes/v2/organization-router.ts
backend/src/server/routes/v3/login-router.ts
backend/src/server/routes/v3/signup-router.ts
nginx/default.conf
nginx/default.dev.conf

This PR adds a `aod` (Authentication origin domain) cookie that is shared between domains (`.infisical.com`) this is required for the dynamic dashboard button on the marketing website if people are already signed in.
---

feat(ENG-3247): add auth origin domain cookie on token creation

---

backend/src/services/secret-sync/render/render-sync-fns.ts

This PR fixes an edge case related to upserting empty secret values and deleting variables on Render - in render secret sync.
---

fix: render sync fns

---

frontend/src/pages/organization/ProjectsPage/ProjectsPage.tsx

Closes #4217
This addresses a banner flicker issue even when Redis is properly configured. This ensures the warning banner only renders once the server status data has fully loaded.
```sh
```
---

fix: redis banner appears only when it is not configured

---

frontend/src/pages/secret-scanning/SettingsPage/SettingsPage.tsx
frontend/src/pages/secret-scanning/SettingsPage/components/ProjectScanningConfigTab/ProjectScanningConfigTab.tsx

Users were not able to delete project for secret scanning when there plan doesn't include it. This has been fixed in this PR
```sh
```
---

fix: resolved project deletion not working for secret scanning on missing plan

---

backend/src/server/routes/v1/dashboard-router.ts
backend/src/services/secret-v2-bridge/secret-v2-bridge-dal.ts
backend/src/services/secret-v2-bridge/secret-v2-bridge-types.ts
backend/src/services/secret/secret-service.ts
backend/src/services/secret/secret-types.ts
frontend/src/pages/secret-manager/OverviewPage/components/SecretSearchInput/SecretSearchInput.tsx
frontend/src/pages/secret-manager/OverviewPage/components/SecretSearchInput/components/QuickSearchSecretItem.tsx

This PR updates the search functionality of the single env view secret dashboard to support tags and metadata
```sh
```
---

improvement(dashboard): add secret tag/metadata search functionality to single env view dashboard

---

frontend/src/components/projects/NewProjectModal.tsx
frontend/src/components/v2/Select/Select.tsx

This PR adjusts the styling of the project template and kms select dropdowns in the create project modal to use popper styling and inverts the kms modal
```sh
```
---

improvement(frontend): Adjust select dropdown styling in add project modal

---

frontend/src/hooks/api/identities/mutations.tsx
frontend/src/hooks/api/identities/queries.tsx

Fix org identity table query invalidation on update/create/delete identity
```sh
```
---

fix(frontend): correct org identity mutation table invalidation

---

frontend/src/hooks/useResizableColWidth.tsx
frontend/src/pages/secret-manager/SecretDashboardPage/SecretDashboardPage.tsx
frontend/src/pages/secret-manager/SecretDashboardPage/components/FolderListView/FolderListView.tsx
frontend/src/pages/secret-manager/SecretDashboardPage/components/SecretListView/SecretItem.tsx
frontend/src/pages/secret-manager/SecretDashboardPage/components/SecretListView/SecretListView.tsx

This PR adds col resize to the secret dashboard env view
minor UI fix for folder cols when pending commit
```sh
```
---

improvement(frontend): add col resize to secret dashboard env view

---

backend/src/lib/api-docs/constants.ts
backend/src/services/secret-sync/render/render-sync-fns.ts
backend/src/services/secret-sync/render/render-sync-schemas.ts
frontend/src/components/secret-syncs/forms/SecretSyncDestinationFields/RenderSyncFields.tsx
frontend/src/components/secret-syncs/forms/SecretSyncOptionsFields/RenderSyncOptionsFields.tsx
frontend/src/components/secret-syncs/forms/SecretSyncOptionsFields/SecretSyncOptionsFields.tsx
frontend/src/components/secret-syncs/forms/SecretSyncReviewFields/RenderSyncReviewFields.tsx
frontend/src/components/secret-syncs/forms/SecretSyncReviewFields/SecretSyncReviewFields.tsx
frontend/src/components/secret-syncs/forms/schemas/render-sync-destination-schema.ts
frontend/src/helpers/secretSyncs.ts
frontend/src/hooks/api/secretSyncs/render-sync.ts
frontend/src/hooks/api/secretSyncs/types/index.ts
frontend/src/hooks/api/secretSyncs/types/render-sync.ts
frontend/src/pages/secret-manager/IntegrationsListPage/components/SecretSyncsTab/SecretSyncTable/SecretSyncDestinationCol/RenderSyncDestinationCol.tsx
frontend/src/pages/secret-manager/SecretSyncDetailsByIDPage/components/SecretSyncDestinationSection/RenderSyncDestinationSection.tsx
frontend/src/pages/secret-manager/SecretSyncDetailsByIDPage/components/SecretSyncOptionsSection/RenderSyncOptionsSection.tsx
frontend/src/pages/secret-manager/SecretSyncDetailsByIDPage/components/SecretSyncOptionsSection/SecretSyncOptionsSection.tsx

Added support for automatically redeploying services on sync. We supported this for native integrations, but we haven't added it to secret syncs which is a blocker for some users.
---

feat(secret-sync/render): auto redeploy on sync

---

Dockerfile.fips.standalone-infisical
backend/Dockerfile.dev.fips
backend/src/db/migrations/utils/env-config.ts
backend/src/lib/crypto/cryptography/crypto.ts

This PR fixes the increased storage consumption by the FIPS image due to the OpenSSL build step.
Additionally I found an issue with running migrations on a fresh installation in FIPS mode. This PR addresses it by taking an optional preconfigured env parameter. The issue was that inside the crypto.initialize function, we call `getConfig()` which doesn't get the migration env config, which means the `ENCRYPTION_KEY` will be uninitialized.
---

fix(fips): increased image size and migrations

---

backend/src/ee/services/secret-rotation-v2/shared/sql-credentials/sql-credentials-rotation-fns.ts
backend/src/ee/services/secret-rotation-v2/shared/utils/index.ts

This is potential fix for oracle db secret rotation failing for identifier too long error
```sh
```
---

fix: potential fix for oracle db rotation failing

---

frontend/src/components/secret-rotations-v2/CreateSecretRotationV2Modal.tsx
frontend/src/components/secret-scanning/CreateSecretScanningDataSourceModal.tsx
frontend/src/components/secret-syncs/CreateSecretSyncModal.tsx

This PR removes the disabling of clicking outside modal to close on several modals to address preventing interacting with toast notifications
```sh
```
---

improvement(frontend): remove click outside moda tol close disabling on various modals

---

frontend/src/layouts/SecretScanningLayout/SecretScanningLayout.tsx

This PR adds back the secret scanning unresolved finding count badge to the sidebar that "mysteriously" disappeared...
```sh
```
---

improvement(frontend): add back secret scanning unresolved finding count to sidebar

---

frontend/src/components/v2/InfisicalSecretInput/InfisicalSecretInput.tsx

This PR improves the styling of the secret reference dropdown on our secret input and reduces the debounce for snappier performance. Also now auto-selects the first suggestion
```sh
```
---

improvement(frontend): improve secret reference styling and reduce debounce

---

backend/src/ee/services/license/license-service.ts
frontend/src/pages/organization/BillingPage/components/BillingDetailsTab/PmtMethodsTable.tsx

Disable ability to remove a payment method if a customer only has one payment method on file
```sh
```
---

Prevent users from deleting the last payment method attached to the org

---

frontend/src/layouts/OrganizationLayout/OrganizationLayout.tsx
frontend/src/layouts/OrganizationLayout/components/InsecureConnectionBanner/InsecureConnectionBanner.tsx
frontend/src/layouts/OrganizationLayout/components/OrgAlertBanner/OrgAlertBanner.tsx
frontend/src/layouts/OrganizationLayout/components/OrgAlertBanner/index.ts
frontend/src/layouts/OrganizationLayout/components/RedisBanner/RedisBanner.tsx
frontend/src/layouts/OrganizationLayout/components/RedisBanner/index.ts
frontend/src/layouts/OrganizationLayout/components/SmtpBanner/SmtpBanner.tsx
frontend/src/layouts/OrganizationLayout/components/SmtpBanner/index.ts
frontend/src/pages/organization/ProjectsPage/ProjectsPage.tsx

This PR moves and redesigns the redis configuration alert banner, updates the insecure context banner design, and adds an smtp configuration banner. Banners updated to be dismissible but show on app refresh
```sh
```
---

improvement(frontend): revise org alter banner designs and add smtp banner

---

frontend/src/pages/organization/AppConnections/OauthCallbackPage/OauthCallbackPage.tsx

This PR is a fix for creating/updating github app connections. It fails due to `host` being undefined, which is always the case when creating app connections without a custom github instance.
---

fix(app-connections): github app connection creation

---

backend/src/queue/queue-service.ts
backend/src/services/external-migration/external-migration-fns/vault.ts
backend/src/services/external-migration/external-migration-queue.ts
backend/src/services/external-migration/external-migration-service.ts
backend/src/services/external-migration/external-migration-types.ts

This PR fixes the vault parsing. The mounts are returned in a `data` object, which the migration didn't factor in. This is tested for both Vault self-hosted and Vault dedicated. 
Additionally, I've also fixed the mailing inconsistency where users would receive migration email updates mentioning "EnvKey", even though they were doing a Vault migration. 
---

fix(external-migration/vault): fix vault parsing

---

frontend/src/pages/secret-manager/OverviewPage/components/SecretSearchInput/SecretSearchInput.tsx
frontend/src/pages/secret-manager/SecretApprovalsPage/components/SecretApprovalRequest/components/SecretApprovalRequestChanges.tsx

This PR adjusts the secret dashboard search bar padding when no clear icon is present and fixes access approval reviewer tooltips display
```sh
```
---

improvements: adjust secret search padding when no clear icon and fix access approval reviewer tooltips display

---

docs/integrations/platforms/kubernetes-injector.mdx

This PR documents the new LDAP auth method for the Infisical Agent Injector, which we are introducing in the latest version of the agent injector. https://github.com/Infisical/infisical-agent-injector/pull/2
---

docs(agent-injector): ldap auth method

---

helm-charts/secrets-operator/templates/deployment.yaml
helm-charts/secrets-operator/values.yaml

While container images are publicly available, there are use cases where they might not be. For example for customers whitelisting only their private registry, registering authentication, to pull images and use pull through cache rules. This MR would add the support to define an `imagePullSecrets` if required.
- [ x] Improvement
```sh
helm template secrets-operator helm-charts/secrets-operator --set 'imagePullSecrets[0].name=registry-secret' | grep imagePullSecrets -A 1
imagePullSecrets:
- name: registry-secret
```
---

feat(helm): add support for imagePullSecrets

---

frontend/src/pages/secret-manager/SecretDashboardPage/components/SecretListView/SecretItem.tsx
frontend/src/pages/secret-manager/SecretDashboardPage/components/SecretListView/SecretListView.tsx

Fix weird behavior when typing the original value on a pending change caused the change to not be valid and go back to the last edited value. Also reduced the row debounce time to 200ms
```sh
```
---

Allow users to type the same original value on bulk commits and remove them if no changes are left

---

frontend/src/pages/secret-manager/OverviewPage/OverviewPage.tsx

This PR updates the secret overview table to have a sticky header, adds underlines to env col headers to make more clear they are links, and limits table height and adds scroll to ensure explore/headers are always visible
```sh
```
---

improvement(frontend): make secret overview table header sticky, add underlines to env header links and limit table height for scroll

---

backend/src/services/certificate-authority/certificate-authority-validators.ts
backend/src/services/certificate-authority/internal/internal-certificate-authority-fns.ts
backend/src/services/certificate-authority/internal/internal-certificate-authority-service.ts
backend/src/services/certificate/certificate-types.ts

Fixed the SAN extension field value validation when creating a new certificate.
The SAN field now allows both IP addresses and non-TLD domains, as allowed by x509 specifications.
The exact issue is mentioned here: [https://github.com/Infisical/infisical/pull/4282#issuecomment-3154680591](https://github.com/Infisical/infisical/pull/4282#issuecomment-3154680591)
[Screencast From 2025-08-05 20-11-55.webm](https://github.com/user-attachments/assets/0116b86d-e191-43a2-91d4-d2e4b08ffc1d)
---

FIX: SAN extension field in certificate issuance

---

backend/src/ee/routes/v1/ldap-router.ts
backend/src/ee/services/ldap-config/ldap-config-service.ts
backend/src/ee/services/ldap-config/ldap-config-types.ts
frontend/src/hooks/api/ldapConfig/mutations.tsx
frontend/src/pages/organization/SettingsPage/components/OrgSsoTab/LDAPModal.tsx

This PR will address the issue where "Testing Connection" disables the LDAP configuration for the organization. Essentially, this allows users to test LDAP config without updating the org configuration. This PR also adds LDAP test connection after creation and update
```sh
```
---

misc: address LDAP config update and test issues

---

frontend/src/pages/organization/AuditLogsPage/components/LogsSection.tsx

This PR fixes audit log in integration page date issue where it only shows audit log for 1 hour. This was because of missing preset of date in it
```sh
```
---

feat: resolved audit log date issue in integration page

---

helm-charts/secrets-operator/templates/deployment.yaml
helm-charts/secrets-operator/templates/metrics-service.yaml
k8-operator/config/default/metrics_service.yaml
k8-operator/config/manager/manager.yaml

This PR fixes a recently introduced bug caused by the v4 kubebuilder upgrade, resulting in duplicate helm labels. This was not caught by testing because a regular helm installation / upgrade doesn't warn or error out about this, but other flows such as using kustomize will throw an error in such cases.
This patch will resolve https://github.com/Infisical/infisical/issues/4347
---

fix(k8s-operator): duplicate helm labels

---

backend/src/services/project-env/project-env-service.ts
frontend/src/pages/secret-manager/SettingsPage/components/EnvironmentSection/EnvironmentTable.tsx

Block users from editing their project environments if they exceed the limit of their plan. Won't block or delete them but to in order to edit any of them, the max number of environments of the plan should be greater or equal to the number of envs on the project
```sh
```
---

Disable environments edit when a project has more environment than the allowed by the org plan

---

backend/src/services/secret-sync/aws-parameter-store/aws-parameter-store-sync-fns.ts

This PR updates the AWS parameter store sync to account for path segments present in the keySchema
```sh
```
---

fix(aws-parameter-store-sync): handle keyschema with path segments for aws parameter store

---

backend/src/services/org-membership/org-membership-dal.ts

Previously the logic was `(status = invited AND ...) OR ...` but it should now be `(status = invited) AND (... OR ...)`

Fix daily re-invite users job logic

---

frontend/src/components/v2/SecretInput/SecretInput.tsx
frontend/src/pages/secret-manager/SecretDashboardPage/components/SecretListView/SecretItem.tsx

This PR updates the secret input to use a fixed length mask when unfocused to prevent inference attacks
```sh
```
---

improvement(frontend): Use fixed length mask for secrets when unfocused to prevent inference attacks

---

backend/src/ee/services/audit-log/audit-log-service.ts
backend/src/ee/services/permission/default-roles.ts
backend/src/ee/services/permission/org-permission.ts
backend/src/ee/services/permission/project-permission.ts
frontend/src/context/OrgPermissionContext/index.tsx
frontend/src/context/OrgPermissionContext/types.ts
frontend/src/context/ProjectPermissionContext/index.tsx
frontend/src/context/ProjectPermissionContext/types.ts
frontend/src/context/index.tsx
frontend/src/pages/organization/AuditLogsPage/components/LogsSection.tsx
frontend/src/pages/organization/RoleByIDPage/components/OrgRoleModifySection.utils.ts
frontend/src/pages/organization/RoleByIDPage/components/RolePermissionsSection/OrgPermissionAuditLogsRow.tsx
frontend/src/pages/organization/RoleByIDPage/components/RolePermissionsSection/RolePermissionsSection.tsx
frontend/src/pages/project/RoleDetailsBySlugPage/components/ProjectRoleModifySection.utils.tsx
frontend/src/pages/secret-manager/IntegrationsDetailsByIDPage/components/IntegrationAuditLogsSection.tsx
frontend/src/pages/secret-manager/SecretSyncDetailsByIDPage/components/SecretSyncAuditLogsSection.tsx

Removed unused permission options for Audit Logs (only Read is currently supported). Leaving Create/Update/Delete visible could cause confusion, so these have been removed.
Also fixed the LogsSection component: it previously only checked for Org-level permissions when displaying Project-level audit logs. As a result, even if a user had the correct Project-level permissions, logs were not shown if the Org-level audit log permission was missing. This has now been corrected.
```sh
```
---

Improve Audit Logs permissions

---

backend/package.json
backend/src/keystore/keystore.ts
backend/src/services/identity-ua/identity-ua-service.ts

Large diff is from putting most of the function in a try-catch

Lockout lock fix

---

frontend/src/pages/auth/SelectOrgPage/SelectOrgSection.tsx
frontend/src/pages/organization/SettingsPage/components/OrgSsoTab/OrgGeneralAuthSection.tsx

Fix for endless loop of login when Google SSO enforcement is active but there is a Google SAML config in place 
The user goes to Infinity like this: 
1. Sets up Google SAML.
2. Enables Google SSO enforcement
3. Logs in via Google SSO
4. Selects the organization, redirects for SAML SSO
5. Now comes back to the main page - trigger google SSO enforcement
6. Kicks back - repeat
```sh
```
---

Fix Google SSO issue with SAML configs when SSO is enforced and not SAML

---

backend/src/keystore/keystore.ts
backend/src/services/secret-sync/aws-parameter-store/aws-parameter-store-sync-fns.ts
backend/src/services/secret-sync/aws-secrets-manager/aws-secrets-manager-sync-fns.ts
backend/src/services/secret-sync/secret-sync-queue.ts
frontend/src/components/secret-syncs/SecretSyncStatusBadge.tsx

This PR limits the amount of concurrent syncs that can run with the same app connection ID. Also makes re-queuing attempts more frequent, but increases the retry limit. Also increases retry limit for aws syncs.
```sh
```
---

improvement(secret-syncs): limit app connection concurrent syncs

---

backend/src/ee/services/license/license-service.ts

This PR adds an update license org identity seat count prior to starting the pro trial as a fallback
```sh
```
---

improvement(pro-trial): sync org identity seat count prior to starting trial as fallback for correct count

---

frontend/src/components/v2/SecretInput/SecretInput.tsx

This PR fixes the InfisicalSecretInput component from input duplication when using sequential references
```sh
```
---

fix(frontend): use unique formatter key in for secret references

---

backend/src/services/user/user-service.ts
docs/documentation/platform/auth-methods/email-password.mdx
frontend/src/pages/user/PersonalSettingsPage/components/ChangeEmailSection/ChangeEmailSection.tsx

This update ensures users aren’t blocked when changing their email addresses. By default, the EMAIL login flow will now be enabled, so if SSO/SAML is misconfigured or unavailable, users can still access their accounts via email. Admins can later revert to SSO/SAML if needed.
```sh
```
---

Enable email login on change of emails flows to avoid blocked users

---

backend/src/ee/services/license/license-service.ts
backend/src/ee/services/license/license-types.ts

Enterprise offline licenses were missing the `slug` field on the `onPremFeatures` object, what lead to some scenarios where isEnterprise checks were not working as expected
```sh
```
---

Fix missing slug on onPremFeatures for offline licenses

---

frontend/src/hooks/api/secrets/mutations.tsx
frontend/src/hooks/api/secrets/types.ts
frontend/src/pages/secret-manager/OverviewPage/components/SelectionPanel/components/MoveSecretsDialog/MoveSecretsDialog.tsx
frontend/src/pages/secret-manager/SecretDashboardPage/components/ActionBar/ActionBar.tsx

This PR fixes the move secret mutation to use projectSlug instead of project ID for the secret overview and environment view dashboards
```sh
```
---

fix(secret-dashboard): add project slug param for moving secrets on dashboard overview and environment view

---

frontend/src/pages/secret-manager/OverviewPage/OverviewPage.tsx
frontend/src/pages/secret-manager/SecretDashboardPage/SecretDashboardPage.tsx

This PR fixes rotated secrets from incorrectly being selected when using the select all rows checkbox. bulk actions don't apply to rotated secrets. 
```sh
```
---

fix(dashboard): prevent rotation secrets from bulk selection

---

backend/src/server/routes/v4/secret-router.ts

This PR fixes secret move failing due to recent workspace id removal revamp happened. The service would accept both slug and id, but the. router expected slug only which should have been project id. The frontend was passing id only
```sh
```
---

feat: resolved secret move failing

---

.github/workflows/release_helm_gateway.yaml
frontend/src/pages/organization/Gateways/Relay/RelayListPage/RelayListPage.tsx
helm-charts/infisical-gateway/Chart.yaml
helm-charts/infisical-gateway/values.yaml

This PR updates the gateway chart versions together with the default CLI tag to use 
```sh
```
---

misc: updated gateway chart versions and tag

---

backend/src/services/secret-v2-bridge/secret-v2-bridge-fns.ts
frontend/src/components/secrets/SecretReferenceDetails/SecretReferenceDetails.tsx

Fixing an issue where on circle references we were computing those without accounting if we already resolved the reference previously or not, leading to repeated cycles.
This PR will ensure that secret references are only computed once per secret.
```sh
```
---

Prevent secrets referencing themselves to loop over and over again, compute them only once

---

backend/src/db/migrations/20250921120821_k8-auth-name-increase.ts

This PR addresses k8s auth failing when allowed service name increases to more than 255 characters
```sh
```
---

fix: increased service name size to 1000

---

backend/src/server/routes/v1/project-router.ts
backend/src/server/routes/v2/deprecated-project-router.ts
frontend/src/pages/organization/AccessManagementPage/components/OrgIdentityTab/components/IdentitySection/IdentityOidcAuthForm.tsx

This PR fixes get project details by slug failing for a bit more longer slug. This happens when user provides a workspace name longer and it breaks the slug validator
```sh
```
---

 feat: resolved project slug short on get urls and improved error message for oidc auth

---

backend/src/ee/services/secret-approval-request/secret-approval-request-service.ts

This PR fixes the scenario where users without read access to secrets and that are not reviewers could see secret values when a secret change request was created. From now on only reviewers will always be able to see the values of the **before** and **after**, but if the user is not a reviewer we will check for secret value read permissions.
```sh
```
---

Secret Approval Request: check if user is a reviewer to trigger hasSecretReadValueOrDescribePermission

---

backend/src/ee/routes/v1/secret-router.ts
backend/src/ee/services/secret-rotation-v2/redis-credentials/redis-credentials-rotation-fns.ts
backend/src/lib/api-docs/constants.ts
backend/src/services/certificate-authority/acme/acme-certificate-authority-fns.ts
backend/src/services/certificate-authority/azure-ad-cs/azure-ad-cs-certificate-authority-fns.ts
backend/src/services/certificate-authority/internal/internal-certificate-authority-fns.ts
backend/src/services/pki-subscriber/pki-subscriber-service.ts
backend/src/services/secret-v2-bridge/secret-v2-bridge-fns.ts
backend/src/services/webhook/webhook-fns.ts
docs/integrations/platforms/kubernetes/infisical-secret-crd.mdx
frontend/src/pages/secret-manager/SecretDashboardPage/components/SecretListView/SecretDetailSidebar.tsx

This PR fixes the access-list broken and also avoid calling access-list from frontend in case you don't have license.
Added documentation for instantUpdate for k8s operator
```sh
```
---

feat: fixed broken access-list and update on k8s doc

---

.github/workflows/release-standalone-docker-img-postgres-offical.yml

Automatically trigger Infisical Binary releases when a new standalone docker image is released. This works for both nighly and stable.
---

feat: auto trigger binary release

---

frontend/src/hooks/api/users/queries.tsx

fixes 404 Error after account deletion.
Auth token remains set even after the account is deleted, causing an error. Clearing the token fixes the issue.
```sh
```
---

fix: 404 Error after account deletion
