docs/gettingStarted.mdx

This PR updates the icon syntax in the Card component so in the future, it works via. Learn more [here](https://mintlify.com/docs/components/card)
```
<Card
icon="name"
iconType="regular | solid | etc..."
/>
```

Update icon syntax in Card component

---

docs/mint.json

Mintlify has launched a major update that reduces page load times by 88%. In the new update, custom Tailwind classes cannot be supported.
This PR updates your anchors to use the new gradient syntax. You also had custom classes on your CTA button, this button will default to your brand colors.

Switch to new gradient syntax

---

docs/mint.json

This PR updates the anchor colors so it's consistent and fix the missing background image

Update anchor colors and background image

---

frontend/.eslintrc.json
frontend/README.md

Every files in the frontend folder has an error like this `Parsing error : Cannot find module 'next/babel'`
So I fix it and fix the typo in readme

Fix babel error

---

frontend/components/basic/InputField.tsx
frontend/pages/login.js
frontend/pages/settings/personal/[id].js
frontend/pages/signup.tsx
frontend/pages/signupinvite.js

https://web.dev/sign-in-form-best-practices/

Add autocomplete to sign in/up forms

---

docs/contributing/developing.mdx

I've updated the content of the developing.mdx file that explains how to start and run the localhost of Infiscal.
The changes are mainly done in the **Set up environment variables** as it's the one that gave me more problems and because the rest it's clear enough already.
I also recommend referring to this file somewhere in the main ReadMe of this repository or as you already have linked, in the [get started contribution guide](https://infisical.com/docs/contributing/overview), because when I started trying to run the localhost I didn't know that this file existed.
If you have any suggestions or changes that you want to make just tell me.

Updated the start developing guide as suggested in issue #75

---

frontend/components/utilities/attemptLogin.js

BEFORE
AFTER
I found I miss the error handling with login. So I fix it.

Fix login runtime error

---

.env.example
backend/src/config/index.ts
backend/src/helpers/nodemailer.ts
backend/src/services/smtp.ts
docs/self-hosting/configuration/envars.mdx

update env vars for smtp

---

frontend/pages/signup.tsx

feat(frontend/signup): add resend code functionality

---

frontend/components/basic/InputField.tsx
frontend/components/basic/table/ServiceTokenTable.js
frontend/components/basic/table/UserTable.js
frontend/components/dashboard/DashboardInputField.tsx
frontend/components/integrations/Integration.tsx
frontend/components/navigation/NavBarDashboard.tsx
frontend/components/navigation/NavHeader.tsx
frontend/pages/dashboard.js
frontend/pages/dashboard/[id].js
frontend/pages/heroku.js
frontend/pages/home/[id].tsx
frontend/pages/index.js
frontend/pages/integrations/[id].js
frontend/pages/login.tsx
frontend/pages/netlify.js
frontend/pages/password-reset.tsx
frontend/pages/settings/billing/[id].js
frontend/pages/settings/org/[id].js
frontend/pages/settings/personal/[id].js
frontend/pages/settings/project/[id].js
frontend/pages/signup.tsx
frontend/pages/signupinvite.js
frontend/pages/users/[id].js
frontend/pages/vercel.js
frontend/pages/verify-email.tsx

1. Removed unncessary react import made in project
Slight reduction in bundle size 
Ref: https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html

chore(frontend): removed unneccessary react import in project

---

backend/src/app.ts
backend/src/controllers/v1/secretController.ts
backend/src/controllers/v2/index.ts
backend/src/controllers/v2/workspaceController.ts
backend/src/helpers/bot.ts
backend/src/helpers/secret.ts
backend/src/routes/v2/index.ts
backend/src/routes/v2/secret.ts
backend/src/routes/v2/workspace.ts
frontend/components/utilities/secrets/pushKeys.ts
frontend/pages/api/files/UploadSecrets.ts

Migrated `POST /v1/secret/:workspaceId` to `POST /v2/workspace/:workspaceId/secrets`. It was necessary to clear up room in `/v2/secret` for upcoming secret CRUD operations.

Migrated `POST /v1/secret/:workspaceId` to `POST /v2/workspace/:workspaceId/secrets`

---

docs/integrations/frameworks/dotnet.mdx

docs: add dotnet example

---

backend/src/controllers/v1/keyController.ts
backend/src/controllers/v1/membershipController.ts
backend/src/controllers/v1/workspaceController.ts
backend/src/controllers/v2/workspaceController.ts
backend/src/ee/routes/v1/secret.ts
backend/src/ee/routes/v1/workspace.ts
backend/src/helpers/membership.ts
backend/src/helpers/rateLimiter.ts
backend/src/helpers/signup.ts
backend/src/middleware/requireBotAuth.ts
backend/src/middleware/requireIntegrationAuth.ts
backend/src/middleware/requireIntegrationAuthorizationAuth.ts
backend/src/middleware/requireSecretAuth.ts
backend/src/middleware/requireServiceTokenDataAuth.ts
backend/src/middleware/requireWorkspaceAuth.ts
backend/src/models/membership.ts
backend/src/routes/v1/bot.ts
backend/src/routes/v1/integration.ts
backend/src/routes/v1/integrationAuth.ts
backend/src/routes/v1/key.ts
backend/src/routes/v1/secret.ts
backend/src/routes/v1/serviceToken.ts
backend/src/routes/v1/workspace.ts
backend/src/routes/v2/serviceTokenData.ts
backend/src/routes/v2/workspace.ts
backend/src/variables/index.ts
backend/src/variables/organization.ts

Deprecate statuses from workspaces as workspaces statuses are legacy and no longer applicable.

Remove accept statuses

---

frontend/components/basic/dialog/DeleteEnvVar.tsx
frontend/components/dashboard/DeleteActionButton.tsx
frontend/components/dashboard/SideBar.tsx
frontend/public/locales/en/dashboard.json

This is my solution for issue #175 :)
https://user-images.githubusercontent.com/68869379/210918265-cfc7078f-2013-4b94-b131-d78ec7231f19.mp4
> The bug on the version history box on sidebar has because when recording the server wasn't running :p

Add popup before secret delete

---

.github/workflows/docker-image.yml

Add local cache according to https://docs.docker.com/build/ci/github-actions/examples/#cache

Docker cache

---

.github/workflows/docker-image.yml

Depot docker

---

backend/spec.json
backend/src/app.ts
backend/src/controllers/v1/organizationController.ts
backend/src/controllers/v2/index.ts
backend/src/controllers/v2/organizationsController.ts
backend/src/controllers/v2/usersController.ts
backend/src/controllers/v2/workspaceController.ts
backend/src/helpers/membership.ts
backend/src/helpers/membershipOrg.ts
backend/src/middleware/index.ts
backend/src/middleware/requireMembershipAuth.ts
backend/src/middleware/requireMembershipOrgAuth.ts
backend/src/routes/v1/membership.ts
backend/src/routes/v1/organization.ts
backend/src/routes/v2/index.ts
backend/src/routes/v2/organizations.ts
backend/src/routes/v2/secret.ts
backend/src/routes/v2/users.ts
backend/src/routes/v2/workspace.ts
backend/swagger/index.ts
docs/api-reference/endpoints/organizations/delete-membership.mdx
docs/api-reference/endpoints/organizations/memberships.mdx
docs/api-reference/endpoints/organizations/update-membership.mdx
docs/api-reference/endpoints/organizations/workspaces.mdx
docs/api-reference/endpoints/users/me.mdx
docs/api-reference/endpoints/users/my-organizations.mdx
docs/mint.json
docs/spec.yaml

This PR refactors and adds new organization-related endpoints to the API reference:
- Get organization memberships.
- Update organization membership.
- Delete organization membership.
- Get organization projects.
- Get my organizations.

Add new organization endpoints to API reference

---

docs/security/overview.mdx

docs: Fix typo in encryption overview

---

i18n/README.es.md

This branch refers to Issue Help us translate Infisical https://github.com/Infisical/infisical/issues/181

Adding Spanish translation to the README 🌎ES

---

i18n/README.ko.md

Hope this helps more korean users to use infisical :)

Translate README.md to korean

---

frontend/src/pages/dashboard/[id].tsx

new secrets are added to the top

---

frontend/package-lock.json
frontend/package.json

Fixed #252  Added Prettier-plugin-tailwindcss.

added prettier-plugin-tailwindcss

---

docker-compose.dev.yml
frontend/package-lock.json
frontend/package.json
frontend/src/components/utilities/SecurityClient.ts
frontend/src/config/request.ts
frontend/src/context/AuthContext/AuthContext.tsx
frontend/src/context/AuthContext/index.tsx
frontend/src/hooks/api/auth/index.tsx
frontend/src/hooks/api/auth/queries.tsx
frontend/src/hooks/api/auth/types.ts
frontend/src/hooks/api/index.tsx
frontend/src/hooks/index.ts
frontend/src/hooks/useToggle.tsx
frontend/src/pages/_app.tsx
frontend/src/pages/login.tsx
frontend/src/reactQuery.ts

1. Added new auth guard
2. Added react-query with axios and interceptor to auto refresh
3. Setup for react-query folder structure

feat(ui): added new auth guard with react-query and axios

---

frontend/src/components/basic/table/EnvironmentsTable.tsx
frontend/src/pages/settings/billing/[id].tsx
frontend/src/pages/settings/org/[id].tsx

Add check for subscriptions call before setting the current plan

---

backend/src/integrations/apps.ts
backend/src/integrations/exchange.ts
frontend/src/pages/integrations/[id].tsx
frontend/src/pages/integrations/github/oauth2/callback.tsx

This PR patches some strange issues with some integration routes suddenly requiring encoding headers.

Patch encoding header issue for some integrations for getting their apps

---

README.md
i18n/README.id.md

translate: add Bahasa Indonesia for README

---

.github/pull_request_template.md

Added a base PR template suggestion to structure and normalize our PRs. It will basically look like this one, although contributors will remain free to use whatever layout they want, of course :v:
---

feat(docs): added a base pull request template

---

i18n/README.pt-br.md

Readme translation made to Portuguese Brazil.
---

Readme translation to PT-BR.

---

backend/package-lock.json
backend/package.json
backend/src/config/request.ts
backend/src/integrations/sync.ts

This PR introduces axios-retry to the backend so that axios requests can be retried if failed automatically. Currently, this is only added for the Vercel integration that is flaky sometimes but we will work to make it standard across the entire backend.

Add axios-retry for Vercel integration for now

---

README.md

*Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.*
Another small README typo that I noticed. Links to a different repo.
N/A - docs.
*Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration. You may want to add screenshots when relevant and possible*
```sh
```
---

chore(docs): Update README MIT License badge link

---

helm-charts/README.md
helm-charts/infisical/README.md
helm-charts/infisical/examples/kind.sh
helm-charts/secrets-operator/README.md

<kbd>fix</kbd>
- Markdown link format for Infisical's documentation 
<kbd>docs</kbd>
- Improved the Helm charts documentation (global, infisical and secrets-operator)
---

chore(docs): helm charts + local cluster setup script

---

backend/Dockerfile
backend/package.json
docker-compose.yml

Updates package.json `npm start` command
Delete unnecessary `npm run start` commands
Implement some best practices in backend/Dockerfile
---

Builds Docker image of backend component with multi-stage Dockerfile

---

cli/packages/cmd/run.go

Reverts Infisical/infisical#374

Revert "fix: always execute cmd in subshell"

---

backend/src/integrations/sync.ts

This PR fixes setting deleted secrets for the Azure KV integration. For context, soft-delete is enabled for a key vault, then Azure KV requires secrets to be recovered before they can be set again; this PR does exactly that.

Add secret recovery for setting deleted secrets for Azure integration

---

README.md
i18n/README.de.md
i18n/README.id.md
i18n/README.ja.md
i18n/README.pt-br.md

First of all, we translated the README.
---

Add Japanese README.md

---

docs/integrations/frameworks/terraform.mdx
docs/integrations/overview.mdx

As asked from @dangtony98: some docs on how to use infisical with terraform. 
---

docs: add terraform

---

frontend/src/pages/dashboard/[id].tsx
frontend/src/pages/login.tsx

Fixes #322 
https://user-images.githubusercontent.com/58552561/221286992-a878cf00-99cd-43c3-9581-668576a6912f.mp4
---

Fix: Unable to login after deleting all projects

---

docs/integrations/frameworks/sveltekit.mdx

Adding documentation for SvelteKit
---

Adding documentation for SvelteKit

---

docs/integrations/overview.mdx

Adding SvelteKit into the index of Integrations
---

Adding sveltekit into the index of Integrations

---

docs/api-reference/overview/examples/create-secrets.mdx
docs/api-reference/overview/examples/delete-secrets.mdx
docs/api-reference/overview/examples/retrieve-secrets.mdx
docs/api-reference/overview/examples/update-secrets.mdx

docs: python docs for example CRUD

---

docs/mint.json
docs/sdk/overview/usage.mdx

This PR adds docs for the Node SDK

Add docs for Node SDK

---

i18n/README.it.md

Translation of the README.md document into Italian.
Syntactic and semantic checking done.
---

README.md Italian translation

---

backend/package.json
backend/tests/example.test.ts
backend/tests/utils/crypto.test.ts
backend/tests/utils/posthog.test.ts

unit tests for `utils/posthog.ts` and `utils/crypto.ts`

unit tests for utils/posthog and utils/crypto

---

backend/src/controllers/v1/integrationAuthController.ts
backend/src/integrations/apps.ts
backend/src/integrations/sync.ts
backend/src/models/integration.ts
backend/src/routes/v1/integrationAuth.ts
frontend/src/hooks/api/integrationAuth/index.tsx
frontend/src/hooks/api/integrationAuth/queries.tsx
frontend/src/pages/integrations/gitlab/create.tsx
frontend/src/pages/integrations/vercel/create.tsx

This PR adds support for syncing envars from Infisical to Vercel preview branches. Previously, the Vercel integration supported syncing to previews (without specified custom branches); this expands expands the scope of the integration to be more complete.
---

Add support for syncing to Vercel preview branches

---

frontend/src/pages/activity/[id].tsx

This error fixes an uncaught lint error from the previous commit.
---

Patch uncaught lint error

---

frontend/src/pages/dashboard/[id].tsx

There is a bug in new dashboard that causes sluggish feeling due to execessive rendering and onScroll effect.
Nil
---

feat(ui): rollback to old dashboard page

---

backend/src/controllers/v2/serviceTokenDataController.ts
frontend/src/views/Settings/ProjectSettingsPage/components/ServiceTokenSection/ServiceTokenSection.tsx

https://github.com/Infisical/infisical/issues/33
-Added support for service tokens that do not expire
```sh
```
---

[Feature][Sheen] added never expire service token

---

README.md

Translated README.md file in Hindi

Translated readme in Hindi Language

---

README.md

Added country flag [India]

---

docs/getting-started/quickstart.mdx
docs/sdks/languages/node.mdx

This PR updates the documentation to be inline withe the new `1.1.0` Node SDK that supports performing queries and mutations for individual secrets via blind-indexing.
---

Revise docs for Node SDK

---

docs/getting-started/quickstart.mdx
docs/sdks/languages/go.mdx
docs/sdks/languages/java.mdx
docs/sdks/languages/node.mdx
docs/sdks/languages/python.mdx
docs/sdks/languages/ruby.mdx
docs/sdks/languages/rust.mdx
docs/sdks/overview.mdx

This PR adds documentation for the new [Python SDK](https://github.com/Infisical/infisical-python).
Ran a bunch of [tests](https://github.com/Infisical/infisical-python/blob/main/tests/test_client/test_infisical_client.py) that require an `INFISICAL_TOKEN`. These tests cover the main secret operations including `create`, `read`/`get`, `update`, `delete`.
---

Finish Python SDK docs

---

README.md
SECURITY.md

This PR updates the main README.
---

Updated README

---

.github/workflows/release_build.yml
.goreleaser.yaml
cli/packages/util/check-for-update.go

This is part one of making tags on our repo link to different builds such as CLI and docker images needed for semantic versioning

Only trigger CLI builds for tags with prefix infisical-cli/v*.*.*

---

.env.example
README.md
docs/mint.json
docs/self-hosting/overview.mdx

This PR adds instructions for how to deploy Infisical locally to your machine and corrects some instruction on where to view Infisical once its started up locally.
---

Add local machine to deployment options

---

backend/src/ee/helpers/action.ts
backend/src/ee/helpers/log.ts
backend/src/ee/helpers/secret.ts
backend/src/ee/helpers/secretVersion.ts
backend/src/helpers/auth.ts
backend/src/helpers/bot.ts
backend/src/helpers/event.ts
backend/src/helpers/integration.ts
backend/src/helpers/key.ts
backend/src/helpers/membershipOrg.ts
backend/src/helpers/organization.ts
backend/src/helpers/secret.ts
backend/src/helpers/token.ts
backend/src/helpers/user.ts
backend/src/integrations/apps.ts
backend/src/integrations/exchange.ts
backend/src/integrations/refresh.ts
backend/src/integrations/revoke.ts
backend/src/integrations/teams.ts
backend/src/middleware/requireIntegrationAuthorizationAuth.ts
backend/src/utils/crypto.ts
backend/tests/unit-tests/utils/crypto.test.ts

I would like to replace Sentry logs. Am i doing correctly ?. If i am doing correctly i will continue it. Is it 
**breaking change ?** Sorry i am new. I appreciate for any responses.
*Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration. You may want to add screenshots when relevant and possible*
```sh
```
---

Replace Sentry error handling logic

---

frontend/src/components/v2/Popoverv2/Popoverv2.tsx
frontend/src/reactQuery.ts

Fixed token going missing due to react query cache invalidation. 
After frontend migration security client will be removed and this part would be moved to apiRequest file scoping the getToken also. For now to maintain securityClient getToken needs to be exported like previous
---

fix(ui): resolved token missing due to cache invalidation

---

cli/config/config.go
cli/config/infisical-scan.toml
cli/detect/detect.go
cli/detect/detect_test.go
cli/packages/cmd/scan.go

rebrand and small tweeks

---

docs/cli/commands/scan-git-changes.mdx
docs/cli/commands/scan.mdx
docs/cli/scanning-overview.mdx
docs/documentation/getting-started/introduction.mdx
docs/mint.json

Docs for Infisical scan commands
---

add docs for infisical scan

---

README.md

Update read me with scanning feature 
---

Infisical scan docs

---

README.md

add pre commit install command to README.md

---

cli/packages/api/api.go
cli/packages/api/model.go
cli/packages/cmd/login.go
cli/packages/models/cli.go
cli/packages/util/credentials.go
cli/packages/util/helper.go

CLI will now auto renew credentials when they expire using refresh token  
tested manually 
---

add refresh token to cli

---

cli/packages/api/api.go
cli/packages/api/model.go
cli/packages/cmd/login.go
cli/packages/models/cli.go
cli/packages/util/credentials.go
cli/packages/util/helper.go

Reverts Infisical/infisical#601

Revert "add refresh token to cli"

---

backend/src/integrations/sync.ts

The GitLab integration works by fetching existing envars in GitLab, comparing them with what's inside Infisical, and making the right CRUD operations to update the envars back in GitLab so they're in sync. However, the GitLab integration previously only fetched back 20 envars by default which made for incorrect CRUD operations to be called to the GitLab API.
As such, this PR adds support for paginating through all envars in GitLab. Put differently, we can now reliably handle more than 20 envars for this integration.
---

Add pagination to retrieve envars for GitLab integration

---

docs/changelog/overview.mdx
docs/documentation/getting-started/introduction.mdx
docs/mint.json

This PR adds a monthly changelog (to be updated to weekly) to the documentation.
---

Add preliminary changelog to docs

---

docs/contributing/developing.mdx
docs/contributing/overview.mdx
docs/contributing/pull-requests.mdx
docs/mint.json

This PR adds more clarity to the contributing and coding process for Infisical including:
- Updated requirements/scopes for what's expected of a PR (e.g. a `Feature` vs `Bug`); this includes outlining a new policy for recording any newly-added features.
- The PR review process.
Note: We definitely have a long way to go in terms of adding in more robust documentation in this area but this is a good start; I'll work on improving this significantly later this quarter.
---

Update contributing docs to include expectations and procedures for submitting pull requests

---

backend/package-lock.json
backend/package.json
backend/src/helpers/rateLimiter.ts

All instances of the backend will now share the same rate limits 
Listed locally

use mongo rate limit store

---

backend/src/ee/controllers/v1/secretSnapshotController.ts
backend/src/ee/models/secretVersion.ts
backend/src/utils/setup/backfillData.ts

Patch backfill data

---

frontend/src/components/v2/DeleteActionModal/DeleteActionModal.tsx

1. Resolved reloading when submitting in dashboardpage
```sh
```
---

fix(ui): resolved reloading when form submission

---

backend/src/controllers/v2/secretsController.ts
backend/src/controllers/v2/serviceTokenDataController.ts
backend/src/controllers/v3/secretsController.ts
backend/src/helpers/secrets.ts
backend/src/interfaces/services/SecretService/index.ts
backend/src/models/serviceTokenData.ts
backend/src/routes/v2/secrets.ts
backend/src/routes/v2/serviceTokenData.ts
backend/src/routes/v3/secrets.ts
backend/src/services/FolderService.ts
backend/src/services/SecretService.ts
backend/src/utils/setup/backfillData.ts
backend/src/utils/setup/index.ts
frontend/src/components/navigation/NavHeader.tsx
frontend/src/hooks/api/serviceTokens/types.ts
frontend/src/views/DashboardPage/components/FolderSection/FolderSection.tsx
frontend/src/views/Settings/ProjectSettingsPage/ProjectSettingsPage.tsx
frontend/src/views/Settings/ProjectSettingsPage/components/ServiceTokenSection/ServiceTokenSection.tsx

1. Folder scoped service token support in API
2. Service token ui added secretpath option
---

Folder scoped service token

---

backend/src/controllers/v1/secretsFolderController.ts
backend/src/controllers/v2/secretsController.ts
backend/src/routes/v1/secretsFolder.ts
frontend/src/hooks/api/secretFolders/index.tsx
frontend/src/hooks/api/secretFolders/queries.tsx
frontend/src/hooks/api/secretFolders/types.ts
frontend/src/hooks/api/secrets/queries.tsx
frontend/src/hooks/api/secrets/types.ts
frontend/src/pages/dashboard/[id].tsx
frontend/src/styles/globals.css
frontend/src/views/DashboardPage/DashboardEnvOverview.tsx
frontend/src/views/DashboardPage/components/EnvComparisonRow/EnvComparisonRow.tsx
frontend/src/views/DashboardPage/components/EnvComparisonRow/FolderComparisonRow.tsx

1. Added backend api support for filtering folders and secrets by path name
2. Implemented frontend ui for sec overview section
3. Implemented API changes in frontend
```sh
```
---

Folder support in secret overview page

---

backend/src/controllers/v3/secretsController.ts
backend/src/helpers/secrets.ts
cli/packages/api/api.go
cli/packages/api/model.go
cli/packages/cmd/run.go
cli/packages/cmd/secrets.go
cli/packages/models/cli.go
cli/packages/util/secrets.go

Swap out v2 to v3 secrets api
---

cli: switch from v2 secrets to v3

---

frontend/src/components/basic/table/ProjectUsersTable.tsx

This PR fixes the RBAC paywall to be rewired to the new subscription hook.
---

Rewire RBAC paywall to new mechanism

---

backend/src/ee/controllers/v1/secretController.ts
frontend/src/hooks/api/secrets/queries.tsx
frontend/src/hooks/index.ts
frontend/src/hooks/useSyntaxHighlight.tsx
frontend/src/views/DashboardPage/components/EnvComparisonRow/EnvComparisonRow.tsx
frontend/src/views/DashboardPage/components/SecretDetailDrawer/SecretDetailDrawer.tsx
frontend/src/views/DashboardPage/components/SecretInputRow/MaskedInput.tsx
frontend/src/views/DashboardPage/components/SecretInputRow/SecretInputRow.tsx

1. Fixed secret version missing
2. New multi line secret support
---

multi line support for secrets

---

backend/src/ee/services/EELicenseService.ts
backend/src/helpers/organization.ts
frontend/src/hooks/api/subscriptions/types.ts
frontend/src/layouts/AppLayout/components/NavBar/NavBar.tsx
frontend/src/views/Settings/BillingSettingsPage/components/BillingCloudTab/PreviewSection.tsx

Previously, all users on Infisical Cloud were initialized to the Starter Tier, which is the free plan, and paid to upgrade to a paid plan like the Team or Pro Tier.
They could also manually request a coupon to temporarily upgrade to the Pro Tier — that was the trialing mechanism.
This PR, however, makes this entire process more seamless for everyone as automatically initializes every new user with a 1-month trial for the Pro Tier.
---

Initialize users on Infisical Cloud to Pro (Trial) Tier

---

backend/src/ee/controllers/v1/organizationsController.ts
backend/src/ee/routes/v1/organizations.ts
backend/src/ee/services/EELicenseService.ts
frontend/src/components/v2/UpgradePlanModal/UpgradePlanModal.tsx
frontend/src/hooks/api/organization/index.ts
frontend/src/hooks/api/organization/queries.tsx
frontend/src/hooks/api/organization/types.ts
frontend/src/hooks/api/subscriptions/types.ts
frontend/src/layouts/AppLayout/components/NavBar/NavBar.tsx
frontend/src/views/Settings/BillingSettingsPage/components/BillingCloudTab/PreviewSection.tsx

This PR modifies the free trial mechanism such that users on Infisical Cloud start on the Starter tier and can opt to try the Pro Free Trial.
This is opposed to the current mechanism that initializes everyone on a free trial by default.
---

Infisical Cloud Pro Free Trial Update

---

backend/src/services/smtp.ts
backend/src/variables/smtp.ts
docs/self-hosting/configuration/email.mdx

This PR configures support for Office365 SMTP and adds docs for it as well.
---

Add support for Office365 SMTP

---

README.md

This PR fixes broken link to the YouTube page in the Readme file
This PR fixes broken link to the YouTube page in the Readme file

docs(readme):update broken YouTube  page link

---

frontend/src/views/IntegrationsPage/components/CloudIntegrationSection/CloudIntegrationSection.tsx
frontend/src/views/IntegrationsPage/components/FrameworkIntegrationSection/FrameworkIntegrationSection.tsx

feat: sort cloud and framework integrations alphabetically

---

docs/documentation/platform/token.mdx

Fixes #753 
Fixes typo in docs
- [] New feature
- [] Breaking change

fixed typo

---

backend/src/services/SecretImportService.ts
frontend/src/views/DashboardPage/DashboardPage.tsx
frontend/src/views/DashboardPage/components/SecretImportSection/SecretImportItem.tsx

1. Resolved empty state when expanding secret of fresh environment
2. Resolved empty state coming up even when an import exist
3. Added empty state for the secret import expansion table 
```sh
```
---

fix: resolved empty secrets on fresh env and added empty states

---

backend/src/routes/v3/secrets.ts

1. made include imports optional in raw secrets fetch
```sh
```
---

made include_imports optional in raw secrets fetch

---

backend/src/helpers/botOrg.ts
backend/src/helpers/organization.ts
backend/src/utils/setup/backfillData.ts
frontend/src/views/Signup/components/UserInfoSSOStep/UserInfoSSOStep.tsx

This PR initializes an organization bot whenever a new organization is created; previously, we only backfilled the bot for existing organizations but forgot to account for when a new one is created.
---

Initialize organization bot upon creating organization

---

backend/src/controllers/v1/membershipOrgController.ts
backend/src/ee/controllers/v1/ssoController.ts
frontend/src/pages/project/[id]/members/index.tsx
frontend/src/views/Org/MembersPage/components/OrgMembersTable/OrgMembersTable.tsx
frontend/src/views/Signup/components/UserInfoSSOStep/UserInfoSSOStep.tsx

This PR blocks users from inviting members to an organization from within Infisical if SAML SSO is configured.
---

Block inviting members to organization if SAML SSO is configured

---

docs/contributing/developing.mdx

docs: add running infisical docs locally guide

---

backend/src/controllers/v1/secretImportController.ts
backend/src/controllers/v2/secretsController.ts
backend/src/controllers/v3/secretsController.ts
backend/src/routes/v1/secretImport.ts

1. Resolved all imports deleting
2. Resolved include_imports false 
```sh
```
---

fix: resolved secret import delete and include_import response control

---

backend/src/ee/controllers/v1/workspaceController.ts
frontend/src/layouts/AppLayout/AppLayout.tsx
frontend/src/pages/org/[id]/overview/index.tsx
frontend/src/views/IntegrationsPage/IntegrationPage.utils.tsx
frontend/src/views/IntegrationsPage/components/CloudIntegrationSection/CloudIntegrationSection.tsx
frontend/src/views/Project/IPAllowListPage/components/IPAllowlistModal.tsx
frontend/src/views/Project/IPAllowListPage/components/IPAllowlistTable.tsx

This PR patches a few bugs that was breaking integrations and causing `PATCH` for IP whitelisting to behave incorrectly.
- Update `localStorage.projectData.id` to correctly reflect the current project when navigating to a project — this is potentially a temporary solution.
- Ensure that `PATCH` to update a IP whitelist entry correctly updates if entry changes from a specific IP address to a CIDR range and back.
---

Fix PATCH IP whitelist behavior and breaking integrations due to incorrect project id in local storage

---

k8-operator/packages/api/api.go

Better log for k8-operator

---

backend/src/helpers/bot.ts
backend/src/helpers/integration.ts
backend/src/helpers/secrets.ts
backend/src/integrations/sync.ts
backend/tsconfig.json

1. Added support for secret expansion and import feature in integrations
2. Added guard for infinite recursion
```sh
```
---

Secret expansion and import in integrations

---

backend/package-lock.json
backend/package.json
backend/src/config/index.ts
backend/src/controllers/v2/usersController.ts
backend/src/ee/routes/v1/sso.ts
backend/src/models/user.ts
backend/src/routes/v1/auth.ts
backend/src/routes/v2/users.ts
backend/src/utils/auth.ts
backend/src/utils/setup/index.ts
docs/self-hosting/configuration/envars.mdx
frontend/src/hooks/api/users/queries.tsx
frontend/src/views/Login/components/InitialStep/InitialStep.tsx
frontend/src/views/Settings/PersonalSettingsPage/AuthMethodSection/AuthMethodSection.tsx

Initial commit for github sign in feature #771

initial-setup for github signin

---

frontend/src/components/v2/Button/Button.tsx
frontend/src/hooks/api/secrets/queries.tsx
frontend/src/hooks/index.ts
frontend/src/hooks/useDebounce.tsx
frontend/src/views/DashboardPage/DashboardPage.tsx
frontend/src/views/DashboardPage/DashboardPage.utils.ts
frontend/src/views/DashboardPage/components/SecretDropzone/SecretDropzone.tsx

1. Added pull secret feature in dashboard
2. JSON env parsing on upload
3. Multi line formatting on secret download
```sh
```
---

feat: added copy secret feature in dashboard 

---

backend/src/controllers/v1/secretImportController.ts
backend/src/controllers/v1/secretsFolderController.ts
backend/src/routes/v1/secretImport.ts
backend/src/routes/v1/secretsFolder.ts
backend/src/services/FolderService.ts

1. Added service token support for secret import and folder
```sh
```
---

feat: implemented service token support for folder and secret import api

---

backend/src/controllers/v2/secretsController.ts
frontend/src/views/DashboardPage/components/SecretDropzone/SecretDropzone.tsx

1. Fixed secret list empty when secret path / is provided but their exist no folder.
```sh
```
---

fix: secret path / with a new env causes secret list to be empty

---

backend/src/integrations/sync.ts

1. Resolved supabase integration failure by deleting reserved secret
```sh
```
---

fix: supabase failed integration due to res secret deletion

---

backend/src/controllers/v3/secretsController.ts
backend/src/helpers/secrets.ts
backend/src/interfaces/services/SecretService/index.ts
backend/src/routes/v3/secrets.ts
frontend/src/helpers/project.ts
frontend/src/hooks/api/secrets/types.ts

added a check for signup events

---

docs/self-hosting/deployment-options/kubernetes-helm.mdx

Added blog link for setting up infisical in development cluster
Previewed the changes in markdown viewer and able to view the new changes
---

added blog link for setting up infisical in developement cluster

---

frontend/src/views/Login/components/PasswordStep/PasswordStep.tsx
frontend/src/views/Login/components/SAMLSSOStep/SAMLSSOStep.tsx

- closes #850 
I did some manual testing and it is working ok
```sh
https://app.infisical.com/login/sso?token=randomnumber
```
is breaking your client  side , I think it should be fixed
---

fix: form not submitting on keyboard enter

---

frontend/src/views/Project/AuditLogsPage/components/LogsSection.tsx

As part of the new Audit Logs V2 rollout, this PR makes it clearer to users that this is a paid feature by adding a paywall to it.
---

Add paywall to Audit Logs V2

---

frontend/src/components/v2/SecretInput/SecretInput.tsx
frontend/src/views/DashboardPage/components/SecretInputRow/SecretInputRow.tsx
frontend/src/views/SecretOverviewPage/components/SecretOverviewTableRow/SecretEditRow.tsx

1. Resolved multi line breaking when < is present
2. Made secret multi line input component much simpler
```sh
```
---

fix(multi-line): resolved breaking ui when secret value contains < or >

---

frontend/src/hooks/api/secrets/queries.tsx

fix: moved backend get sec to v2 for dashboard

---

frontend/src/views/Settings/ProjectSettingsPage/components/WebhooksTab/WebhooksTab.tsx

WebhooksTab.tsx used wrong format of date
Tested in UI manually
---

Fix date-fn format string

---

docs/changelog/overview.mdx
docs/cli/token.mdx
docs/contributing/pull-requests.mdx
docs/documentation/platform/project.mdx
docs/self-hosting/configuration/envars.mdx
docs/self-hosting/deployment-options/digital-ocean-marketplace.mdx

Multiple typos fixed across the documentation
Not applicable

docs: Fixing multiple typos

---

frontend/src/pages/login/index.tsx
frontend/src/styles/globals.css

currently login page is not scrollable and some contents are hidden, this PR aims to fix that
after:
[Screencast 2023-09-11 22:43:34.webm](https://github.com/Infisical/infisical/assets/84864519/97b0e3e6-7bcb-40a3-a32d-482ea6110922)

fix: overflow issue login page

---

backend/src/controllers/v1/secretImpsController.ts
backend/src/controllers/v1/secretsFolderController.ts
backend/src/controllers/v2/secretsController.ts
backend/src/controllers/v3/secretsController.ts
backend/src/ee/services/ProjectRoleService.ts
backend/src/helpers/bot.ts
backend/src/services/SecretImportService.ts
frontend/src/context/ProjectPermissionContext/types.ts
frontend/src/views/DashboardPage/DashboardPage.tsx
frontend/src/views/DashboardPage/components/FolderSection/FolderSection.tsx
frontend/src/views/DashboardPage/components/SecretImportSection/SecretImportItem.tsx
frontend/src/views/Project/MembersPage/components/ProjectRoleListTab/components/ProjectRoleModifySection/MultiEnvProjectPermission.tsx
frontend/src/views/Project/MembersPage/components/ProjectRoleListTab/components/ProjectRoleModifySection/ProjectRoleModifySection.tsx
frontend/src/views/Project/MembersPage/components/ProjectRoleListTab/components/ProjectRoleModifySection/ProjectRoleModifySection.utils.ts
frontend/src/views/SecretOverviewPage/SecretOverviewPage.tsx

1. Grouped folder and import permission into secrets
2. Made environments and folder list view without permission
```sh
```
---

feat(rbac): grouped folder and imports permission into secret permission

---

backend/src/helpers/integration.ts
backend/src/integrations/apps.ts
backend/src/integrations/teams.ts
backend/src/validation/integration.ts
backend/src/validation/integrationAuth.ts

Currently, the integration between Infisical and self-hosted instances of GitLab is broken (GitLab Cloud works fine) because not all methods involving GitLab URLs were updated to accommodate for self-hosted instances of GitLab.
This PR points all such URLs to self-hosted instances of GitLab if applicable.
---

Update all GitLab integration URLs to point to self-hosted instances if applicable (else GitLab Cloud)

---

backend/src/controllers/v1/organizationController.ts
backend/src/controllers/v3/secretsController.ts
backend/src/ee/controllers/v1/roleController.ts
backend/src/ee/controllers/v1/workspaceController.ts
backend/src/ee/services/ProjectRoleService.ts
backend/src/ee/services/RoleService.ts
backend/src/helpers/signup.ts
backend/src/models/membershipOrg.ts
backend/src/queues/secret-scanning/githubScanFullRepository.ts
backend/src/queues/secret-scanning/githubScanPushEvent.ts
backend/src/routes/v2/organizations.ts
backend/src/utils/setup/backfillData.ts
backend/src/validation/secrets.ts
backend/src/variables/organization.ts
frontend/src/context/ProjectPermissionContext/ProjectPermissionContext.tsx
frontend/src/layouts/AppLayout/AppLayout.tsx
frontend/src/styles/globals.css
frontend/src/views/IntegrationsPage/IntegrationsPage.tsx
frontend/src/views/Org/MembersPage/components/OrgRoleTabSection/OrgRoleModifySection/OrgRoleModifySection.tsx
frontend/src/views/Project/MembersPage/components/MemberListTab/MemberListTab.tsx
frontend/src/views/Project/MembersPage/components/ProjectRoleListTab/components/ProjectRoleModifySection/ProjectRoleModifySection.tsx
frontend/src/views/Project/MembersPage/components/ProjectRoleListTab/components/ProjectRoleModifySection/SingleProjectPermission.tsx

1. Removed owner
2. Wrote migration script to map owners to admin
3. Changed member name to developer in ui for project members
4. Updated project member permissions
```sh
```
---

feat(rbac): removed owner role and changed member permissions

---

backend/src/services/RedisService.ts
backend/src/validation/secrets.ts
frontend/src/views/IntegrationsPage/IntegrationsPage.tsx

1. Fixed redis type error
2. Fixed bot deactivation when all integration auths are deleted.
3. Fixed v3 secret raw patch endpoint 
```sh
```
---

fix: integration bot deactive resolved and redis type error

---

frontend/src/hoc/withPermission/withPermission.tsx
frontend/src/views/Project/MembersPage/components/ProjectRoleListTab/components/ProjectRoleModifySection/WsProjectPermission.tsx

change certain permissioning text

---

frontend/src/components/v2/Accordion/Accordion.stories.tsx
frontend/src/components/v2/Accordion/Accordion.tsx
frontend/tailwind.config.js

1. Implemented accordion component
2. Stripped off unused old tailwind config for some code editor
```sh
```
---

fix: resolved broken style of accordion component and added storybook

---

frontend/package-lock.json
frontend/package.json
frontend/src/components/v2/SecretInput/SecretInput.tsx
frontend/src/views/DashboardPage/components/SecretInputRow/SecretInputRow.tsx

1. Switched back to textarea for multi line 
```sh
```
---

Stable multiline input

---

backend/src/controllers/v1/integrationAuthController.ts
backend/src/helpers/integration.ts
backend/src/validation/integrationAuth.ts
frontend/src/hooks/api/integrationAuth/queries.tsx
frontend/src/pages/integrations/teamcity/create.tsx

The permissions update introduced a `ZodError` validating an `appId` parameter as part of the request URL parameters; however, it's actually passed in as part of the query parameters.
This PR adjusts the validation with `zod` to correctly validate the parameter on the appropriate part of the request.
---

Fix TeamCity integration blank screen issue

---

frontend/src/layouts/AppLayout/AppLayout.tsx
frontend/src/views/Project/MembersPage/components/ProjectRoleListTab/components/ProjectRoleModifySection/ProjectRoleModifySection.tsx

1. Brought back audit log
```sh
```
---

feat: made audit log options back

---

backend/src/controllers/v3/secretsController.ts
backend/src/helpers/secrets.ts
backend/src/interfaces/services/SecretService/index.ts
backend/src/services/SecretImportService.ts
backend/src/validation/secrets.ts

1. Get imported secret using v3 get a secret by name api
```sh
```
---

feat: added support for getting imported secrets in v3 getSecret api

---

backend/src/controllers/v2/environmentController.ts

fix: renaming environments not updated in some models

---

frontend/src/components/v2/Modal/Modal.tsx
frontend/src/views/SecretMainPage/SecretMainPage.store.tsx
frontend/src/views/SecretMainPage/SecretMainPage.tsx
frontend/src/views/SecretMainPage/components/ActionBar/ActionBar.tsx
frontend/src/views/SecretMainPage/components/CreateSecretForm/CreateSecretForm.tsx
frontend/src/views/SecretMainPage/components/CreateSecretForm/index.tsx
frontend/src/views/SecretMainPage/components/SecretDropzone/CopySecretsFromBoard.tsx
frontend/src/views/SecretMainPage/components/SecretDropzone/SecretDropzone.tsx
frontend/src/views/SecretMainPage/components/SecretListView/SecretListView.tsx

1. Resolved copy secret from env not working
2. Add  secret in empty state card
```sh
```
---

feat(dashboard-v3): patched dashboard copy sec bug

---

backend/src/controllers/v3/secretsController.ts

1. Removed permission check on imported secrets when using service token
```sh
```
---

fix: resolved permission check on imported secrets when using service token

---

backend/package-lock.json
backend/package.json

https://github.com/advisories/GHSA-m95q-7qp3-xv42
---

Upgrading `zod`

---

backend/src/controllers/v2/environmentController.ts

fixes #920
`secretimports` -> `imports` -> `environment` was missing in #1030

fix: renaming environments not updated in `secretimports` model

---

cli/packages/cmd/login.go
frontend/next.config.js
frontend/src/views/Login/Login.tsx
frontend/src/views/Login/components/InitialStep/InitialStep.tsx
frontend/src/views/Login/components/MFAStep/MFAStep.tsx
frontend/src/views/Login/components/PasswordStep/PasswordStep.tsx

localhost requires table look up which may not be present in all systems. Switching to 127.0.0.1 may help https://github.com/Infisical/infisical/issues/1057
tested locally 
---

change broswer based login from localhost to 127.0.0.1

---

backend/src/integrations/sync.ts
backend/src/queues/integrations/syncSecretsToThirdPartyServices.ts
frontend/src/components/v2/SecretInput/SecretInput.tsx
frontend/src/pages/integrations/github/create.tsx
frontend/src/views/IntegrationsPage/components/IntegrationsSection/IntegrationsSection.tsx
frontend/src/views/SecretApprovalPage/SecretApprovalPage.tsx

allow multiple simultaneous integrations with checkly and github

---

docs/cli/commands/export.mdx

docs: fix missing export format `yaml`

---

backend/.eslintrc
backend/src/middleware/requestErrorHandler.ts
backend/src/utils/requestError.ts

Add stack trace error logging in the console (with Winston) for prod - this will enable self-hosted users to debug better. Modified that all unexpected errors are sent to Sentry in prod.
Tested in a prod env with the change password function by throwing different errors and with different log levels. Checked custom error levels cast to Winston properly. Checked that the correct log level will be sent to Sentry.
---

Improve-logging

---

backend/src/controllers/v1/secretsFolderController.ts
backend/src/controllers/v3/secretsController.ts
backend/src/helpers/secrets.ts
backend/src/interfaces/services/SecretService/index.ts
backend/src/services/FolderService.ts
backend/src/validation/secrets.ts
frontend/src/components/v2/Drawer/Drawer.tsx
frontend/src/hooks/api/secrets/mutations.tsx
frontend/src/hooks/api/secrets/types.ts
frontend/src/views/SecretMainPage/components/SecretListView/SecretListView.tsx
frontend/src/views/SecretOverviewPage/SecretOverviewPage.tsx
frontend/src/views/SecretOverviewPage/components/SecretOverviewTableRow/SecretEditRow.tsx
frontend/src/views/SecretOverviewPage/components/SecretOverviewTableRow/SecretOverviewTableRow.tsx

1. When a secret is created on the overview page in a env where folders may not exist, folders will be created recursively
2. Added secret id based deletion for secrets v3
```sh
```
---

feat: added support for recursive file creation

---

backend/src/controllers/v3/secretsController.ts
backend/src/helpers/secrets.ts
backend/src/interfaces/services/SecretService/index.ts
backend/src/validation/secrets.ts
frontend/src/hooks/api/secrets/mutations.tsx
frontend/src/hooks/api/secrets/types.ts
frontend/src/views/SecretMainPage/components/SecretListView/SecretListView.tsx
frontend/src/views/SecretOverviewPage/SecretOverviewPage.tsx
frontend/src/views/SecretOverviewPage/components/SecretOverviewTableRow/SecretEditRow.tsx
frontend/src/views/SecretOverviewPage/components/SecretOverviewTableRow/SecretOverviewTableRow.tsx

- Changed secret update to use id with name
- Fixed delete reset on overview page
```sh
```
---

feat: changed secret update to use id

---

backend/src/routes/v1/secretImps.ts
backend/src/routes/v1/secretsFolder.ts

feat: added api key support for folder and secret import

---

backend/src/controllers/v3/secretsController.ts
backend/src/helpers/secrets.ts

fix: batch deleting secrets not getting synced for integrations

---

cypress.config.js
cypress/e2e/org-overview.cy.js
cypress/e2e/org-settings.cy.js
cypress/e2e/project-overview.cy.js
cypress/fixtures/example.json
cypress/support/commands.js
cypress/support/e2e.js
frontend/.eslintrc.js
frontend/cypress.config.js
frontend/cypress/e2e/org-overview.cy.js
frontend/cypress/e2e/org-settings.cy.js
frontend/cypress/e2e/project-secret-operations.cy.js
frontend/cypress/fixtures/example.json
frontend/cypress/support/commands.js
frontend/cypress/support/e2e.js
frontend/package-lock.json
frontend/package.json
frontend/src/components/v2/DeleteActionModal/DeleteActionModal.tsx
frontend/src/views/SecretMainPage/SecretMainPage.tsx
frontend/src/views/SecretMainPage/components/ActionBar/ActionBar.tsx
frontend/src/views/SecretMainPage/components/CreateSecretForm/CreateSecretForm.tsx
frontend/src/views/SecretMainPage/components/SecretListView/SecretListView.tsx
frontend/src/views/Settings/OrgSettingsPage/components/OrgGeneralTab/OrgGeneralTab.tsx
frontend/src/views/Settings/ProjectSettingsPage/components/DeleteProjectSection/DeleteProjectSection.tsx

adding cypress tests

---

backend/package-lock.json

This PR updates the `@node-saml/node-saml` to `v4.0.5` dependency as well as a few others.
---

Update subdependencies, node-saml

---

frontend/src/components/navigation/NavHeader.tsx
frontend/src/views/SecretOverviewPage/SecretOverviewPage.tsx

1. Resolved nav header not working on clicking breadcrumb to go back
```sh
```
---

fix: resolved nav header secret path issues

---

backend/package-lock.json
backend/package.json
backend/src/controllers/v1/integrationAuthController.ts
backend/src/controllers/v2/secretController.ts

This PR removes the `mongodb` dependency from `backend`; the dependency was seldom used — any place where it was used has been updated.
---

Remove mongodb direct dependency from backend

---

backend/package-lock.json
backend/package.json
backend/src/controllers/v1/integrationAuthController.ts
backend/src/controllers/v2/secretController.ts

Reverts Infisical/infisical#1128

Revert "Remove mongodb direct dependency from backend"

---

backend/package-lock.json
backend/package.json
backend/src/controllers/v1/integrationAuthController.ts
backend/src/controllers/v2/secretController.ts

Reverts Infisical/infisical#1129

Revert "Revert "Remove mongodb direct dependency from backend""

---

frontend/src/components/v2/ContentLoader/ContentLoader.tsx

fix: standalone build failure due to ts error

---

backend/src/controllers/v1/webhookController.ts
backend/src/models/webhooks.ts
backend/src/services/WebhookService.ts

feat: backward compatiable enc key in webhook

---

backend/src/controllers/v2/index.ts
backend/src/controllers/v2/membershipController.ts
backend/src/ee/models/auditLog/enums.ts
backend/src/ee/models/auditLog/types.ts
backend/src/index.ts
backend/src/routes/v2/index.ts
backend/src/routes/v2/membership.ts
backend/src/validation/membership.ts
frontend/src/hooks/api/types.ts
frontend/src/hooks/api/users/index.tsx
frontend/src/hooks/api/users/mutation.tsx
frontend/src/hooks/api/users/queries.tsx
frontend/src/hooks/api/users/types.ts
frontend/src/layouts/AppLayout/AppLayout.tsx
frontend/src/pages/org/[id]/overview/index.tsx
frontend/src/views/Project/MembersPage/components/MemberListTab/MemberListTab.tsx

1. Changed 2 api calls to singular call with support of batch in adding users to workspace membership
2. Minor ui adjustment in sidebar top headers
3. This also close #1149 
```sh
```
---

fix: changed 2 fold operation of member workspace to one api call

---

backend/spec.json
backend/swagger/index.ts
docs/mint.json
docs/spec.yaml

Prior to this fix, requests in the documentation's API Reference section fails. This PR fixes that.

fix: resolve API reference failing requests

---

backend/spec.json
backend/src/controllers/v1/secretImpsController.ts
backend/src/controllers/v1/secretsFolderController.ts
backend/src/controllers/v2/environmentController.ts
backend/src/controllers/v3/secretsController.ts
backend/swagger/index.ts
docs/api-reference/endpoints/environments/list.mdx
docs/api-reference/endpoints/folders/delete.mdx
docs/api-reference/endpoints/folders/update.mdx
docs/api-reference/endpoints/secrets/create.mdx
docs/api-reference/endpoints/secrets/delete.mdx
docs/api-reference/endpoints/secrets/list.mdx
docs/api-reference/endpoints/secrets/read.mdx
docs/api-reference/endpoints/secrets/rollback-version.mdx
docs/api-reference/endpoints/secrets/update.mdx
docs/api-reference/endpoints/secrets/versions.mdx
docs/api-reference/endpoints/workspaces/logs.mdx
docs/mint.json
docs/spec.yaml

This PR updates the API Reference params, responses, etc. for secrets, folders, environments, and secret imports endpoints.
Some findings:
- Out-of-date endpoint documentation.
- Lack of standardization for data structures / responses for select endpoints.
- Suboptimal DX for select endpoints.
Overall, an API revision is highly recommended.
---

Update API Reference params, responses, etc. for secrets, folders, environments, and secret imports endpoints

---

backend/src/controllers/v2/organizationsController.ts
frontend/src/components/signup/DonwloadBackupPDFStep.tsx
frontend/src/components/utilities/attemptLogin.ts

1. CB timing issue with back up key generation in signup (now same as admin page synced one)
2. Removed owner check in custom role as its not used anymore
3. Login client init synced instead promise and then async
```sh
```
---

fix: resolved backup key generation in signup, removed owner check and logic race condition error

---

backend/package-lock.json
backend/package.json
backend/src/config/index.ts
backend/src/index.ts
backend/src/utils/logging/index.ts
backend/src/utils/logging/logger.ts

1. Added aws cloudwatch support for pino
```sh
```
---

feat(aws-cloudwatch): added support for aws cloudwatch transport in pino

---

backend/package-lock.json
backend/package.json
backend/tsconfig.json

1. Changed from babel to swc for ts node to boost speed in dev reload
```sh
```
---

feat: added swc compiler for ts-node for speed boost

---

cli/packages/api/api.go
cli/packages/api/model.go
cli/packages/cmd/folder.go
cli/packages/cmd/secrets.go
cli/packages/models/cli.go
cli/packages/util/folders.go
cli/packages/visualize/folders.go

- Create, Get and Delete folders via the cmd line
Closes #1191

feat: cli-folders-cmd

---

docs/self-hosting/configuration/envars.mdx

This MR fixes the default for the password value.
none

Fixed 'SMTP_PASSWORD' default value

---

docs/integrations/platforms/kubernetes.mdx

Add docs for secret type and  label propagation
---

add docs for k8 secret type and label propagation

---

backend/package-lock.json
backend/package.json

This PR addresses https://github.com/Infisical/infisical/security/dependabot/65 
Tested web hooks which uses Axios and all worked as expected 
---

Address axios vulnerability

---

frontend/package-lock.json
frontend/package.json
frontend/src/views/Project/MembersPage/components/ServiceTokenTab/components/ServiceTokenSection/AddServiceTokenModal.tsx
frontend/src/views/SecretOverviewPage/SecretOverviewPage.tsx
frontend/src/views/SecretOverviewPage/components/ProjectIndexSecretsSection/ProjectIndexSecretsSection.tsx

1. Brought back secret blind indexing popup in secret overview page for user attention
- chore
```sh
```
---

feat: brought back secret indexing popup in overview page

---

frontend/package-lock.json

Building prod images failed: https://github.com/Infisical/infisical/actions/runs/7200051217/job/19613110199
error message: 
```
npm ci can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
#24 2.866 npm ERR! 
#24 2.866 npm ERR! Invalid: lock file's @radix-ui/react-focus-scope@1.0.2 does not satisfy @radix-ui/react-focus-scope@1.0.4
```
I ran `npm install` in frontend to produce this package lock file

sync package.lock frontend

---

docs/integrations/cicd/bitbucket.mdx
docs/integrations/cicd/circleci.mdx
docs/integrations/cicd/codefresh.mdx
docs/integrations/cicd/githubactions.mdx
docs/integrations/cicd/gitlab.mdx
docs/integrations/cicd/travisci.mdx
docs/integrations/cloud/aws-parameter-store.mdx
docs/integrations/cloud/aws-secret-manager.mdx
docs/integrations/cloud/azure-key-vault.mdx
docs/integrations/cloud/checkly.mdx
docs/integrations/cloud/cloudflare-pages.mdx
docs/integrations/cloud/cloudflare-workers.mdx
docs/integrations/cloud/flyio.mdx
docs/integrations/cloud/gcp-secret-manager.mdx
docs/integrations/cloud/hasura-cloud.mdx
docs/integrations/cloud/heroku.mdx
docs/integrations/cloud/laravel-forge.mdx
docs/integrations/cloud/netlify.mdx
docs/integrations/cloud/northflank.mdx
docs/integrations/cloud/qovery.mdx
docs/integrations/cloud/railway.mdx
docs/integrations/cloud/render.mdx
docs/integrations/cloud/supabase.mdx
docs/integrations/cloud/teamcity.mdx
docs/integrations/cloud/terraform-cloud.mdx
docs/integrations/cloud/vercel.mdx
docs/integrations/cloud/windmill.mdx

This PR makes a small stylistic adjustment to the integration pages to use the Steps component in Mintlify.
---

Add Mintlify steps to integration pages

---

backend/src/utils/authn/passport/saml.ts
frontend/src/views/Login/Login.utils.tsx
frontend/src/views/Login/components/MFAStep/MFAStep.tsx
frontend/src/views/Login/components/PasswordStep/PasswordStep.tsx
frontend/src/views/Signup/SignupSSO.tsx

This PR updates the redirect logic after successfully logging a user in to the appropriate organization where applicable such as in the case of SAML SSO.
---

Update redirect to org after SAML SSO

---

docs/documentation/platform/sso/azure.mdx
docs/documentation/platform/sso/github.mdx
docs/documentation/platform/sso/gitlab.mdx
docs/documentation/platform/sso/google.mdx
docs/documentation/platform/sso/jumpcloud.mdx
docs/documentation/platform/sso/okta.mdx

This PR updates the configuration docs for SSO methods to include the latest required envars and to make use of the new Mintlify `Steps` component.
---

Update SSO docs to use Mintlify steps

---

backend/src/ee/controllers/v1/secretApprovalRequestsController.ts
frontend/src/views/SecretApprovalPage/components/SecretApprovalRequest/SecretApprovalRequest.tsx
frontend/src/views/SecretApprovalPage/components/SecretApprovalRequest/components/SecretApprovalRequestAction.tsx
frontend/src/views/SecretApprovalPage/components/SecretApprovalRequest/components/SecretApprovalRequestChanges.tsx

1. Resolved secret approval not loading when approved for a commiteer
```sh
```
---

fix: secret approval loading failed for commiter on approval

---

helm-charts/secrets-operator/Chart.yaml
k8-operator/controllers/infisicalsecret_helper.go

Add owner ref to fix https://github.com/Infisical/infisical/issues/1042

add owner reference to InfisicalSecret 

---

backend/src/controllers/v1/universalAuthController.ts
helm-charts/secrets-operator/Chart.yaml
k8-operator/controllers/infisicalsecret_helper.go

add crd owner

---

backend/src/validation/serviceTokenData.ts

fix: made expire optional on service token creation

---

docs/self-hosting/deployment-options/docker-compose.mdx
docs/self-hosting/deployment-options/standalone-infisical.mdx

Restyle self-hosting docs for Docker / Docker Compose.
---

Restyle self-hosting docs for Docker / Docker Compose

---

backend/src/ee/models/auditLog/enums.ts
backend/src/utils/posthog.ts
cli/packages/cmd/export.go
frontend/src/hooks/api/auditLogs/constants.tsx
frontend/src/hooks/api/auditLogs/enums.tsx

removed posthog cli export events

---

frontend/src/components/signup/DonwloadBackupPDFStep.tsx
frontend/src/views/admin/SignUpPage/SignUpPage.tsx

Fixed a small typos in the error message. (`Faield` -> `Failed`)
---

Fix error message typos

---

cli/packages/api/api.go
cli/packages/util/secrets.go

For the following scenario I didn't change my template at all.
---

fix(cli): secret-path directive for agent

---

frontend/src/hooks/api/integrationAuth/queries.tsx
frontend/src/pages/integrations/railway/create.tsx

This PR fixes a client-side Railway integration rendering issue causing a client-side exception due to change of behavior of a package dependency.
---

Fix client-side railway integration issue

---

backend/spec.json
backend/src/controllers/v2/organizationsController.ts
docs/api-reference/endpoints/organizations/workspaces.mdx
docs/spec.yaml
frontend/src/views/Org/MembersPage/components/OrgIdentityTab/components/IdentitySection/IdentitySection.tsx
frontend/src/views/Org/MembersPage/components/OrgIdentityTab/components/IdentitySection/IdentityTable.tsx

This PR updates various items related to Identities:
- Opens identities documentation in a new tab instead of the current tab.
- Updates get organization projects API to be compatible with identities.
- Adds an `ID` column to the identities table.
---

Update various identities items

---

docs/contributing/sdk/developing.mdx

Fix image in SDK contribution guide. 
---

(Fix): Image in SDK contribution guide not loading

---

backend/src/helpers/secrets.ts

Resolved undefined value being interpolated when value not present. 
Now it just keeps the old value
```sh
```
---

fix(secret-reference): fixed undefined if value not found

---

docs/sdks/languages/csharp.mdx
docs/sdks/languages/go.mdx
docs/sdks/languages/java.mdx
docs/sdks/languages/node.mdx
docs/sdks/languages/php.mdx
docs/sdks/languages/python.mdx
docs/sdks/languages/ruby.mdx
docs/sdks/languages/rust.mdx
docs/sdks/overview.mdx

- Added .NET SDK documentation
- Added cryptography docs to all existing SDK docs
- Removed unfinished SDK's from the docs to reduce clutter
- Fixed formatting in all docs to properly display parameters
---

(Docs): .NET SDK documentation & updates existing SDK docs

---

docs/sdks/languages/csharp.mdx
docs/sdks/languages/java.mdx
docs/sdks/languages/node.mdx
docs/sdks/languages/python.mdx

Improved searchability and added links repo/package links to each SDK documentation. 
---

(Docs): SDK SEO Improvements & links to packages/repos

---

cli/packages/cmd/export.go
cli/packages/cmd/run.go
cli/packages/cmd/secrets.go
cli/packages/util/config.go
cli/packages/util/helper.go
cli/packages/util/secrets.go
docs/cli/commands/run.mdx

Adds project-config-dir fag to CLI run command
Manually tested run, secrets and export command. Also tested with secret refs. All works

add project-config-dir flag for run command

---

frontend/src/components/v2/Alert/Alert.tsx
frontend/src/pages/org/[id]/overview/index.tsx

feat: added main banner for migration

---

docs/changelog/overview.mdx

Changelog for january _(thus far)_. 
---

[JAN] Changelog points

---

docs/documentation/getting-started/sdks.mdx
docs/documentation/guides/node.mdx
docs/documentation/guides/python.mdx
docs/sdks/overview.mdx

Updated our SDK guides to reflect the new SDK's.
---

(Docs): Improve SDK docs

---

backend/src/ee/routes/v1/project-router.ts
backend/src/ee/routes/v1/secret-rotation-router.ts
backend/src/lib/fn/string.ts
backend/src/server/plugins/error-handler.ts
backend/src/server/routes/v1/integration-router.ts
backend/src/server/routes/v1/secret-folder-router.ts
backend/src/server/routes/v1/secret-import-router.ts
backend/src/server/routes/v1/webhook-router.ts
backend/src/server/routes/v2/service-token-router.ts
backend/src/server/routes/v3/secret-router.ts
backend/src/services/secret-blind-index/secret-blind-index-service.ts
backend/src/services/secret-folder/secret-folder-dal.ts
frontend/src/components/permissions/ProjectPermissionCan.tsx
frontend/src/context/ProjectPermissionContext/ProjectPermissionContext.tsx
frontend/src/hoc/withProjectPermission/withProjectPermission.tsx
frontend/src/hooks/api/roles/queries.tsx
frontend/src/hooks/api/users/types.ts
frontend/src/views/IntegrationsPage/components/CloudIntegrationSection/CloudIntegrationSection.tsx
frontend/src/views/SecretApprovalPage/components/SecretApprovalPolicyList/SecretApprovalPolicyList.tsx
frontend/src/views/SecretApprovalPage/components/SecretApprovalPolicyList/components/SecretApprovalPolicyRow.tsx
frontend/src/views/SecretMainPage/SecretMainPage.tsx
frontend/src/views/SecretMainPage/components/SecretListView/SecretDetaiSidebar.tsx
frontend/src/views/SecretMainPage/components/SecretListView/SecretItem.tsx
frontend/src/views/SecretOverviewPage/components/ProjectIndexSecretsSection/ProjectIndexSecretsSection.tsx
frontend/src/views/SecretRotationPage/SecretRotationPage.tsx
frontend/src/views/Settings/ProjectSettingsPage/components/EnvironmentSection/EnvironmentSection.tsx
frontend/src/views/Settings/ProjectSettingsPage/components/SecretTagsSection/SecretTagsSection.tsx

1. Showing blind index for everyone
2. Admin only message for everyone
```sh
```
---

feat: changed blind index banner for everyone

---

docs/documentation/platform/token.mdx

I did not find anymore where to manage token and reading the doc did not help me. I found the MR which changes the section of the link and so I update the doc according it
```sh
```
---

Update the path where managing service tokens

---

backend/package-lock.json
backend/package.json
backend/src/db/schemas/secret-versions.ts
backend/src/db/schemas/secrets.ts
backend/src/ee/services/secret-approval-request/secret-approval-request-service.ts
backend/src/ee/services/secret-rotation/secret-rotation-queue/secret-rotation-queue.ts
backend/src/services/secret/secret-service.ts

1. Added. cloudwatch
2. Made secret blind index nullable everywhere
```sh
```
---

feat: added cloudwatch support and removed parsed secret blindindex

---

backend/src/server/routes/sanitizedSchemas.ts
backend/src/server/routes/v2/service-token-router.ts

Fix old python SDK versions that depend on specific API response structure. 
---

(Fix): Old Python SDK versions

---

frontend/src/components/v2/SecretInput/SecretInput.tsx

1. Fixed showing invalid characters due to encoding
```sh
```
---

fix: resolved encoding issue in multi line input

---

backend/src/server/routes/index.ts
backend/src/server/routes/v2/organization-router.ts
backend/src/services/org/org-service.ts
backend/src/services/org/org-types.ts
backend/src/services/project/project-dal.ts

We missed an endpoint during the postgres migration. This PR re-adds the missing get organization workspace endpoint as it's documented [here](https://infisical.com/docs/api-reference/endpoints/organizations/workspaces).
---

(Feat): Re-add missing V2 workspaces endpoint

---

docs/mint.json

Running the following still works!
```sh
mintlify dev
```
---

remove deprecated basePath setting

---

backend/src/ee/services/audit-log/audit-log-dal.ts
backend/src/services/secret-tag/secret-tag-service.ts
backend/src/services/service-token/service-token-service.ts
backend/src/services/webhook/webhook-dal.ts

1. Desc sort for audit log
2. Asc sort for webhook, service token, secret-tag
```sh
```
---

feat: enabled order by desc for audit log and added sort for couple of get queries

---

backend/src/server/routes/v3/secret-router.ts

fix posthog events

---

backend/src/db/instance.ts
backend/src/ee/routes/v1/saml-router.ts
backend/src/main.ts
backend/src/server/boot-strap-check.ts
backend/src/server/routes/index.ts
backend/src/server/routes/v1/admin-router.ts
backend/src/server/routes/v1/sso-router.ts
backend/src/services/super-admin/super-admin-service.ts

1. Resolved server cfg init in replication mode
```sh
```
---

feat: fixed server cfg stale in replication

---

frontend/src/views/admin/DashboardPage/DashboardPage.tsx

fix admin dashboard styling

---

backend/src/lib/config/env.ts
backend/src/services/super-admin/super-admin-service.ts

add initial org rename

---

backend/src/services/secret/secret-service.ts

- patch secret get by version 
- always default to shared for service token 
postman
---

patch get secret by name

---

backend/src/ee/routes/v1/saml-router.ts

This PR amends the spelling for `spInitiated` property part of Azure SAML functionality.
---

Correct spInitiated spelling in Azure SAML

---

frontend/src/views/Settings/PersonalSettingsPage/APIKeySection/AddAPIKeyModal.tsx

This PR addresses a bug that prevented the ‘Create API Key’ modal from closing when the ‘Cancel’ button was clicked. This issue was present in the following navigation path: Personal Settings -> API Keys -> Add API Key. Initially, the modal would not close upon pressing the ‘Cancel’ button. To fix this bug, I added `onClick={() => handlePopUpToggle("addAPIKey", false)}` to the button. Now, the modal closes as expected when the ‘Cancel’ button is clicked, Fixes Infisical/infisical/#1399.
```
<Button colorSchema="secondary" variant="plain">
Cancel
</Button>
```
```
<Button 
colorSchema="secondary" 
variant="plain" 
onClick={() => handlePopUpToggle("addAPIKey", false)}
>
Cancel
</Button>
```
*Steps to test the fix.*
1. Go to Personal Settings > API Keys
2. Click on Add API Key
3. Click …

(Fix): Create API Modal closes on Cancel button

---

docs/self-hosting/configuration/envars.mdx
docs/self-hosting/deployment-options/docker-compose.mdx

Docker compose docs with postgrese

Docker compose docs with postgres

---

docs/integrations/platforms/ansible.mdx

docs: cover ansible forking error

---

frontend/src/views/SecretMainPage/components/SecretListView/CreateReminderForm.tsx
frontend/src/views/SecretMainPage/components/SecretListView/SecretDetaiSidebar.tsx
frontend/src/views/SecretMainPage/components/SecretListView/SecretItem.tsx

Prior to this PR, the secret reminders felt a bit half-baked. By half baked I mean that it wasn't possible to update secret reminders without removing and re-creating the reminder, and it wasn't possible to view the existing secret reminder values. This PR fixes both those issues and makes the secret reminders feel more seemless.
- Added functionality for editing existing reminders. 
- Fixed not being able to view existing reminder values. 
- Added reminders to the "More" sidebar drawer.  
- The reminder toolbar now shows "Every X days" instead of "Reminder", when a reminder is enabled for the secret. 
---

(Fix): Improve reminders

---

backend/src/server/routes/v1/identity-router.ts
backend/src/server/routes/v2/user-router.ts

1. Enabled identity auth mode in identity crud
2. Enabled api key auth mode for user me endpoint
```sh
```
---

feat: made identity crud with identity auth mode and api key for user me

---

.github/workflows/check-fe-ts-and-lint.yml

chore: added type and lint check for frontend ci/cd

---

backend/src/services/project-membership/project-membership-service.ts
backend/src/services/project/project-fns.ts
backend/src/services/project/project-queue.ts
docs/api-reference/endpoints/workspaces/create-workspace.mdx
docs/api-reference/endpoints/workspaces/delete-workspace.mdx
docs/api-reference/endpoints/workspaces/get-workspace.mdx
docs/api-reference/endpoints/workspaces/update-workspace.mdx
frontend/src/views/SecretOverviewPage/SecretOverviewPage.tsx

Fixed issues with sudo users and project upgrades. 
1. Service tokens not behaving as expected after upgrading.
2. Minor documentation changes to new endpoints. 
3. Fix for deleting project members on old projects. 
---

(Fix): Project upgrade

---

frontend/src/components/v2/UpgradeOverlay/UpgradeOverlay.tsx
frontend/src/components/v2/UpgradeProjectAlert/UpgradeProjectAlert.tsx

We now show the upgrade project alert to all users, but only admins can actually perform the upgrade. This should help increase adoption. 
---

(style): Show upgrade alert to all users

---

CONTRIBUTING.md

Fixes link to "Contributing Guide" in `CONTRIBUTING.md`
No tests are required to test this change.

Fix broken contributing guide link

---

docs/documentation/platform/project-upgrade.mdx
frontend/src/components/v2/UpgradeProjectAlert/UpgradeProjectAlert.tsx

Transparency notice regarding the recent project upgrades & creation of new projects moving forward. This PR includes the actual docs page, and a new "Learn more" link on the upgrade alert. 
---

Chore: Project upgrade notice

---

frontend/src/i18n.ts
frontend/src/views/SecretMainPage/SecretMainPage.tsx
frontend/src/views/Settings/PersonalSettingsPage/PersonalGeneralTab/PersonalGeneralTab.tsx

1. As the team discussed, i18n is too incomplete at this moment and we are gonna keep english for now and later when infisical is moving slowly or rather stable we will be fixing up i18n. The old ones are not removed instead we keep i18n at english only for now
2 Secret blind index banner to secret dashboard page
```sh
```
---

feat(ui): secret blind index banner in secret main page and removed i18n to keep only english for now

---

docs/integrations/platforms/docker-intro.mdx

This PR fixes a few typos and slightly rewords the `Docker` page.
---

docs: improve docker page

---

cli/packages/cmd/export.go
cli/packages/util/secrets.go

feat: cli export allow filtering with tags

---

backend/src/services/secret-tag/secret-tag-service.ts

Resolved a minor bug in create tag process in which missing scope of project
```sh
```
---

fix(server): resolved broken create tag scoped to project

---

pg-migrator/src/index.ts

- Migrator fixed admin config issue having missing 000 uuid
```sh
```
---

fix(pg-migrator): added uuid 0000 for admin config

---

docs/self-hosting/guides/mongo-to-postgres.mdx

Pins the migration guide to infisical version v0.46.7-postgres

update mongo to postgres doc

---

frontend/src/pages/integrations/cloudflare-workers/create.tsx

This PR add a secret path as a input field for cloud worker integrations. Instead of hard coded secret path "/". Also handle error message for better UX
---

feat: add support for secret path for cloud worker

---

docs/changelog/overview.mdx

This PR updates the changelog to be up to speed with the updates for February.
---

Update changelog to include updates for Feb

---

backend/src/ee/services/audit-log/audit-log-queue.ts
backend/src/ee/services/license/license-service.ts

feat(server): moved back audit log to queue now with keystore license

---

docs/documentation/platform/project-upgrade.mdx

Small typo in this [page](https://infisical.com/docs/documentation/platform/project-upgrade)
I've tried to set a Next.js redirection through `next.config.js` but didn't succeed.. Maybe you could try something on your side if you want to redirect every `app.infisical.com/(docs|blog|...)` path to the `infisical.com` either through next.js or higher like your reverse proxy (e.g. ingress-nginx if you're using k8s, cc @maidul98) 
NA
---

chore(doc): fix typo

---

.github/resources/changelog-generator.py
.github/workflows/generate-release-changelog.yml

First prototype of gpt based changelog generation inspired from photoroom article. 
@maidul98 before merging this we need to setup the github action permission to enable committing and setup the secrets
```sh
```
---

chore: added gpt based changelog generator

---

backend/src/services/integration-auth/integration-sync-secret.ts

fix(server): removed global aws cred config in secret integration

---

cli/packages/cmd/agent.go
cli/packages/cmd/export.go
cli/packages/cmd/run.go
cli/packages/cmd/secrets.go
cli/packages/models/cli.go
cli/packages/util/secrets.go

- This PR introduces support for secret referencing through the Agent. This is a feature that already exists in the CLI, so adding it to the agent was fairly straight forward with minimal modifications to the existing functions. The main change is adding support for universal auth authentication to the secret expansion functions.
- I also did a bit of code cleanup as we had a lot of dead code which wasn't used anywhere.
---

Feat: Agent secret referencing support

---

frontend/src/components/navigation/NavHeader.tsx
frontend/src/components/signup/UserInfoStep.tsx
frontend/src/layouts/AppLayout/AppLayout.tsx
frontend/src/pages/org/[id]/overview/index.tsx
frontend/src/views/Settings/OrgSettingsPage/components/OrgDeleteSection/OrgDeleteSection.tsx
frontend/src/views/Settings/OrgSettingsPage/components/OrgNameChangeSection/OrgNameChangeSection.tsx
frontend/src/views/Settings/ProjectSettingsPage/components/ProjectNameChangeSection/ProjectNameChangeSection.tsx
frontend/src/views/Signup/components/UserInfoSSOStep/UserInfoSSOStep.tsx

Fix Issue #1427, truncate project, org name or folder name that too long
---

fix: truncate too long proj or org name

---

backend/src/db/migrations/20240312162549_temp-roles.ts
backend/src/db/migrations/20240312162556_temp-role-identity.ts

feat(server): removed stream in project multi role migration

---

backend/src/db/instance.ts
backend/src/db/knexfile.ts
backend/src/lib/config/env.ts

It is easer to pass in individual connection details in ecs over connection string

add individual pg connection properties

---

frontend/src/views/Project/MembersPage/components/MemberListTab/MemberListTab.tsx

Fix: #1563 
- [ X] Bug fix
This issue was related to the usage of email instead of the username. A video of the fix is attached
https://github.com/Infisical/infisical/assets/6097052/cecba2b5-ccbe-48fa-ad86-4f83bf46e5f5
---

fix issue on removing member from project

---

docs/mint.json
docs/self-hosting/ee.mdx

This PR adds documentation for how to use paid / EE features in self-hosted Infisical.
---

Add simple docs for Infisical EE

---

backend/src/services/integration-auth/integration-app-list.ts

This PR adds pagination to the `getAppsRender` method to list all Render services that can be integrated with.
---

Add pagination to getAppsRender

---

backend/src/ee/routes/v1/project-router.ts
backend/src/ee/routes/v1/snapshot-router.ts
backend/src/lib/api-docs/constants.ts
backend/src/lib/api-docs/index.ts
backend/src/server/routes/v1/identity-access-token-router.ts
backend/src/server/routes/v1/identity-router.ts
backend/src/server/routes/v1/identity-ua.ts
backend/src/server/routes/v1/project-env-router.ts
backend/src/server/routes/v1/project-membership-router.ts
backend/src/server/routes/v1/project-router.ts
backend/src/server/routes/v1/secret-folder-router.ts
backend/src/server/routes/v1/secret-import-router.ts
backend/src/server/routes/v2/identity-org-router.ts
backend/src/server/routes/v2/identity-project-router.ts
backend/src/server/routes/v2/organization-router.ts
backend/src/server/routes/v2/project-membership-router.ts
backend/src/server/routes/v2/project-router.ts
backend/src/server/routes/v3/secret-router.ts
docs/api-reference/endpoints/folders/delete.mdx
docs/mint.json
docs/sdks/languages/csharp.mdx
docs/sdks/languages/java.mdx
docs/sdks/languages/node.mdx
docs/sdks/languages/python.mdx

* The documentation now uses tabs. This change has mainly been made to make it easier to navigate the documentation.
* All API routes now have a description on their inputs. I decided to define all the messages in the `api-docs/constants.ts` file to consolidate the messages. Having the messages spread out across a large number of files can from my experience make it frustrating to make changes.
* This is just a smaller question of if we would rather have the descriptions spread out across a large number of files or not, and I'd love to hear what peoples thoughts are on this approach.  
---

Feat: Documentation improvements

---

backend/src/ee/services/secret-approval-request/secret-approval-request-service.ts
cli/packages/api/api.go
cli/packages/api/model.go
cli/packages/cmd/init.go
cli/packages/cmd/login.go

Prerequisite for scoped JWT tokens. We had to make the interactive login work with the new select organization logic. This PR introduces the new logic. 
---

Feat: CLI support for scoped JWT tokens

---

backend/src/server/routes/v1/integration-router.ts
backend/src/services/integration-auth/integration-sync-secret.ts
frontend/src/hooks/api/integrations/queries.tsx
frontend/src/pages/integrations/render/create.tsx

This PR adds an option to the Render integration to redeploy the target Render service upon the secret sync operation.
---

Render integration auto-redeployment capability on secret sync

---

frontend/src/pages/login/select-organization.tsx

Fixes issue with CLI login for organizations that have SAML enforced.
---

Fix: SAML CLI login

---

frontend/src/pages/login/select-organization.tsx
frontend/src/pages/org/[id]/overview/index.tsx

- Minor changes to the project cards making them a bit more intuitive. The entire project card is now clickable instead of just the "Explore" button. 
- Cleaned up code on the select org page
- Removed "Logout" button on select org page because to improve UX.
- We were getting reports of users accidentally clicking the Logout button, and at a second look the logout button is more distractive than anything. 
---

Fix: Select organization UX & project card enhancements

---

frontend/src/components/utilities/intercom/intercom.ts
frontend/src/components/v2/Menu/Menu.tsx
frontend/src/layouts/AdminLayout/AdminLayout.tsx

I noticed we were getting warnings when I was reviewing a PR a few days ago, this fixes those warnings.
---

Fix: Github warnings / Lint warnings

---

backend/src/ee/services/secret-rotation/secret-rotation-queue/secret-rotation-queue-fn.ts
backend/src/lib/knex/connection.ts
backend/src/lib/knex/index.ts

1. Secret rotation fix
```sh
```
---

fix(server): updated secret rotation to pick on db host in validation

---

.github/workflows/build-staging-and-deploy-aws.yml

deploy to ecs using OIDC with aws

---

frontend/src/components/v2/UpgradeProjectAlert/UpgradeProjectAlert.tsx
frontend/src/views/Settings/ProjectSettingsPage/components/E2EESection/E2EESection.tsx

Deprecate E2EE button and replace it with an upgrade notice.

Feat: Deprecate E2EE mode switching

---

frontend/src/pages/integrations/cloudflare-pages/create.tsx

Add a secret path field for cloudflare page integration Fix: https://github.com/Infisical/infisical/issues/1155.
Similar to this PR https://github.com/Infisical/infisical/pull/1495
---

feat: add support for secret path for cloudflare page

---

cli/packages/api/api.go
cli/packages/api/model.go
cli/packages/cmd/secrets.go

As reported here https://infisical-users.slack.com/archives/C04BSBMQAQ7/p1709582727603379, when running `infisical secrets set` to update a variable, it was throwing error from the api
When calling the update `CallUpdateSecretsV3` method, we were also passing the `SecretName` parameter with the request which we pass only if we want to rename the secret, but based on the functionality of cli, we are only updating the value of the secret, not the name. So sending `SecretName` to the api was considering if it want to update the secret name, but as the variable already exists, it throws error
```sh
infisical secrets set VAR1=value1 --env=dev // success
infisical secrets set VAR1=value10 --env=dev // now success
```
---

Fixed CLI issue of updating variables using `infisical secrets set`

---

backend/src/lib/api-docs/constants.ts
backend/src/services/secret/secret-service.ts

Some minor changes to improve clarity.

Fix: Minor naming changes

---

frontend/src/hooks/api/dynamicSecret/index.ts
frontend/src/hooks/api/dynamicSecret/queries.ts
frontend/src/hooks/api/dynamicSecret/types.ts
frontend/src/hooks/api/dynamicSecretLease/queries.ts
frontend/src/hooks/api/dynamicSecretLease/types.ts
frontend/src/views/SecretOverviewPage/SecretOverviewPage.tsx
frontend/src/views/SecretOverviewPage/components/SecretOverviewDynamicSecretRow/SecretOverviewDynamicSecretRow.tsx
frontend/src/views/SecretOverviewPage/components/SecretOverviewDynamicSecretRow/index.tsx

1. Dynamic secret in overview page
```sh
```
---

feat: added dynamic secret to overview page

---

backend/src/services/dynamic-secret-lease/dynamic-secret-lease-service.ts
backend/src/services/dynamic-secret/dynamic-secret-service.ts

allow viewer to generate and list dynamic secret

---

backend/src/lib/api-docs/constants.ts
backend/src/server/routes/v1/integration-auth-router.ts
backend/src/server/routes/v1/integration-router.ts
backend/src/server/routes/v1/project-router.ts
docs/api-reference/endpoints/integrations/create-auth.mdx
docs/api-reference/endpoints/integrations/create.mdx
docs/api-reference/endpoints/integrations/delete-auth-by-id.mdx
docs/api-reference/endpoints/integrations/delete-auth.mdx
docs/api-reference/endpoints/integrations/delete.mdx
docs/api-reference/endpoints/integrations/find-auth.mdx
docs/api-reference/endpoints/integrations/list-auth.mdx
docs/api-reference/endpoints/integrations/update.mdx
docs/mint.json

1. updated api reference documentation with aws ssm integration
```sh
```
---

AWS SSM integration api documentation

---

backend/src/ee/routes/v1/identity-project-additional-privilege-router.ts
backend/src/lib/api-docs/constants.ts
docs/api-reference/endpoints/identity-specific-privilege/create-permanent.mdx
docs/api-reference/endpoints/identity-specific-privilege/create-temporary.mdx
docs/api-reference/endpoints/identity-specific-privilege/delete.mdx
docs/api-reference/endpoints/identity-specific-privilege/find-by-slug.mdx
docs/api-reference/endpoints/identity-specific-privilege/list.mdx
docs/api-reference/endpoints/identity-specific-privilege/update.mdx
docs/mint.json

1, API reference doc for identity specific privilege
```sh
```
---

docs: added api reference for specific privilege identity

---

cli/packages/cmd/secrets.go

Fixed getting secrets by name through CLI

Fix: CLI get secrets by name

---

backend/src/server/config/rateLimiter.ts
backend/src/server/routes/v1/invite-org-router.ts
backend/src/server/routes/v2/project-router.ts

This PR adds a separate rate limiter for the invite user to org endpoint
---

Add separate rate limit to invite user to org

---

backend/src/server/routes/index.ts
backend/src/services/project/project-service.ts

This PR removes the organization's cached plan upon creation/deletion of a project.
---

Remove plan cache upon create/delete project

---

backend/src/server/routes/index.ts
backend/src/services/project-role/project-role-service.ts
frontend/src/views/Org/MembersPage/components/OrgRoleTabSection/OrgRoleTable.tsx
frontend/src/views/Project/MembersPage/components/ProjectRoleListTab/components/ProjectRoleList/ProjectRoleList.tsx

Fixed vague errors when deleting roles that are assigned to identities or project members. 
---

Fix: Error handling when deleting roles that are assigned to identities or users

---

cli/packages/cmd/export.go
cli/packages/cmd/secrets.go

- Added imports support to export command
- Added secret interpolation support to get secrets by name command
---

Feat: CLI Improvements

---

backend/src/services/auth/auth-login-service.ts
backend/src/services/auth/auth-password-service.ts

Removes the extra whitespace for the error message
Doesn't really resolves the issue #1667 but still good to have imo.
Will update the PR to resolve the issue once I get some response from someone.

removed extra whitespace from error message

---

docs/api-reference/overview/examples/integration.mdx
docs/mint.json

docs: added guide to setup integration with api

---

docs/documentation/platform/token.mdx

docs:fixed broken link

---

docs/documentation/getting-started/introduction.mdx

docs: fixed another broken link

---

backend/src/services/integration/integration-service.ts

This PR deletes a corresponding integration auth upon deleting an integration if no other integrations share the same integration auth.
---

Integration Auth deletion upon Integration deletion

---

backend/src/services/project/project-dal.ts
frontend/src/components/integrations/NoEnvironmentsBanner.tsx
frontend/src/views/IntegrationsPage/components/CloudIntegrationSection/CloudIntegrationSection.tsx

Currently there's a bug when trying to fetch workspaces with no environments, which results in the API throwing a 500 error. This PR aims to fix this issue. Additionally I've also disabled the creation of new integrations when no environments are present on the project (see screenshot below)
---

FIx: Fetching workspaces with no environments

---

backend/src/lib/api-docs/constants.ts
backend/src/server/routes/v1/project-router.ts
docs/api-reference/endpoints/integrations/list-project-integrations.mdx
docs/mint.json

Expose List integratiosn API

---

backend/src/ee/routes/v1/project-router.ts
backend/src/lib/fn/dates.ts
backend/src/lib/fn/index.ts
frontend/src/views/Project/AuditLogsPage/components/LogsSection.tsx

1. Added end date by default to reduce the dataset on sorting
```sh
```
---

fix: resolved slow audit log list

---

backend/src/ee/services/dynamic-secret-lease/dynamic-secret-lease-service.ts
backend/src/ee/services/dynamic-secret/providers/models.ts
backend/src/ee/services/dynamic-secret/providers/sql-database.ts
frontend/src/hooks/api/dynamicSecret/types.ts
frontend/src/views/SecretMainPage/components/ActionBar/CreateDynamicSecretForm/SqlDatabaseInputForm.tsx
frontend/src/views/SecretMainPage/components/DynamicSecretListView/EditDynamicSecretForm/EditDynamicSecretSqlProviderForm.tsx

1. Added mysql dynamic secret support
```sh
```
---

Dynamic secret mysql support

---

backend/.eslintrc.js
backend/src/db/migrations/20240414192520_drop-role-roleid-project-membership.ts
backend/src/db/schemas/identity-project-memberships.ts
backend/src/db/schemas/project-memberships.ts
backend/src/db/seeds/3-project.ts
backend/src/db/seeds/4-machine-identity.ts
backend/src/ee/services/permission/permission-dal.ts
backend/src/server/routes/v1/project-membership-router.ts
backend/src/server/routes/v1/project-router.ts
backend/src/services/identity-project/identity-project-service.ts
backend/src/services/project/project-queue.ts
backend/src/services/project/project-service.ts
docker-compose.dev.yml

1. Removed as title said fields from db. 
2. Added eslint override to migration files as many will become any due to new ts schema not having said fields
3. Updated permission-dal and other fields where role and roleId being used from project membership
```sh
```
---

chore: rolling migration removed role and roleId field from project membership and identity project membership

---

frontend/src/views/SecretOverviewPage/SecretOverviewPage.tsx

fixed import icon in the overview dashboard

---

cli/packages/cmd/agent.go
cli/packages/cmd/export.go
docs/cli/commands/export.mdx

1. Same template setup for export command from agent setup
```sh
```
---

feat(cli): added template feature to cli export command

---

backend/package-lock.json
backend/package.json
backend/src/ee/services/dynamic-secret/providers/models.ts
backend/src/ee/services/dynamic-secret/providers/sql-database.ts
frontend/src/hooks/api/dynamicSecret/types.ts
frontend/src/views/SecretMainPage/components/ActionBar/CreateDynamicSecretForm/SqlDatabaseInputForm.tsx
frontend/src/views/SecretMainPage/components/DynamicSecretListView/EditDynamicSecretForm/EditDynamicSecretSqlProviderForm.tsx

This is untested version of dynamic secret generation with oracle db. Keeping this PR in draft until find a way to test it against
```sh
```
---

feat: dynamic secret for oracle

---

backend/src/ee/routes/v1/project-router.ts
backend/src/ee/routes/v1/snapshot-router.ts
backend/src/server/plugins/swagger.ts
backend/src/server/routes/v1/project-env-router.ts
backend/src/server/routes/v1/project-membership-router.ts
backend/src/server/routes/v1/secret-folder-router.ts
backend/src/server/routes/v1/secret-import-router.ts
backend/src/server/routes/v2/identity-org-router.ts
backend/src/server/routes/v2/organization-router.ts
backend/src/server/routes/v2/project-router.ts
backend/src/server/routes/v2/user-router.ts
backend/src/server/routes/v3/secret-router.ts
docs/mint.json

- Removed endpoints from documentation that only support API key auth
- Removed API key authorization documentation
---

Feat: Remove API Key auth docs

---

backend/src/lib/api-docs/constants.ts
backend/src/server/routes/v1/integration-router.ts
backend/src/services/integration-auth/integration-sync-secret.ts
backend/src/services/integration/integration-types.ts
docs/integrations/cloud/aws-parameter-store.mdx
docs/integrations/cloud/aws-secret-manager.mdx
frontend/src/hooks/api/integrations/queries.tsx
frontend/src/pages/integrations/aws-parameter-store/create.tsx
frontend/src/pages/integrations/aws-secret-manager/create.tsx
pg-migrator/src/models/integration/types.ts

Feat: Tags for AWS integrations

---

.github/workflows/check-api-for-breaking-changes.yml
backend/package-lock.json
backend/src/ee/routes/v1/dynamic-secret-lease-router.ts

Fix breaking API change check.
---

Fix: API Breaking Change Check

---

backend/src/services/integration-auth/integration-app-list.ts

This PR adds pagination to the `getAppsVercel` method so the full list of Vercel apps is returned when setting up the integration.
---

Add pagination to getAppsVercel

---

backend/src/server/routes/v1/project-router.ts
backend/src/server/routes/v2/project-membership-router.ts
backend/src/server/routes/v2/project-router.ts

This PR makes sure that the Authorization tab is displayed in the API reference for all public project endpoints.
---

Add security/description to project endpoint schemas for API reference

---

backend/src/ee/services/secret-snapshot/secret-snapshot-service.ts
backend/src/ee/services/secret-snapshot/snapshot-dal.ts
backend/src/ee/services/secret-snapshot/snapshot-service-fns.ts
backend/src/services/project-membership/project-membership-service.ts

Chore: Documentation

---

backend/src/ee/routes/v1/project-role-router.ts
frontend/src/components/v2/UpgradeProjectAlert/UpgradeProjectAlert.tsx
frontend/src/context/ProjectPermissionContext/ProjectPermissionContext.tsx
frontend/src/hooks/api/roles/queries.tsx
frontend/src/hooks/api/users/types.ts

Fixed minor role bug making it impossible to identify default project roles based on assigned roles. Permission based auth works as expected, the bug just resulted in a minor UI issue when upgrading projects, because project upgrades check the project role to determine if a user should be able to upgrade a project or not.
---

Fix: Frontend roles bug

---

backend/e2e-test/routes/v3/secrets.spec.ts
backend/src/lib/api-docs/constants.ts
backend/src/server/routes/v3/secret-router.ts
backend/src/services/secret/secret-service.ts
backend/src/services/secret/secret-types.ts
docs/api-reference/endpoints/secrets/create-many.mdx
docs/api-reference/endpoints/secrets/delete-many.mdx
docs/api-reference/endpoints/secrets/update-many.mdx

1. API endpoints for batch raw secrets
2. Docs for the same
```sh
```
---

Batch raw secrets api

---

docs/integrations/cloud/aws-amplify.mdx

docs: added -y flag in infisical cli installation in amplify doc to skip confirmation prompt

---

backend/src/services/secret-import/secret-import-fns.ts
backend/src/services/secret-import/secret-import-service.ts
backend/src/services/secret/secret-service.ts

- API will now fetch secrets from imported made inside imports and goes till level 10
```sh
```
---

feat(server): recursive imported secret fetch for api

---

frontend/src/components/v2/SecretPathInput/SecretPathInput.tsx
frontend/src/components/v2/SecretPathInput/index.tsx
frontend/src/pages/integrations/cloudflare-pages/create.tsx
frontend/src/pages/integrations/cloudflare-workers/create.tsx
frontend/src/pages/integrations/gcp-secret-manager/create.tsx
frontend/src/pages/integrations/gitlab/create.tsx
frontend/src/pages/integrations/hasura-cloud/create.tsx
frontend/src/pages/integrations/heroku/create.tsx
frontend/src/pages/integrations/render/create.tsx
frontend/src/views/Project/MembersPage/components/IdentityTab/components/IdentityRoleForm/SpecificPrivilegeSection.tsx
frontend/src/views/Project/MembersPage/components/MemberListTab/MemberRoleForm/SpecificPrivilegeSection.tsx
frontend/src/views/SecretApprovalPage/components/SecretApprovalPolicyList/components/SecretPolicyForm.tsx
frontend/src/views/SecretMainPage/components/ActionBar/CreateSecretImportForm.tsx
frontend/src/views/SecretMainPage/components/SecretDropzone/CopySecretsFromBoard.tsx
frontend/src/views/SecretRotationPage/components/CreateRotationForm/steps/RotationOutputForm.tsx

- Created component for Secret Path input with autocomplete support
- Migrated existing usage of secret path inputs to the new component
https://github.com/Infisical/infisical/assets/65645666/5d45c05e-cfd9-405b-a033-d7365d4065de
```sh
```
---

Feature: added auto-complete for secret path inputs

---

.github/resources/rename_migration_files.py
.github/workflows/update-be-new-migration-latest-timestamp.yml

1. This github action will rename the migration files newly added ones of a PR to latest timestamp according with knex
```sh
```
---

feat: github action to rename new migration file to latest timestamp

---

backend/src/db/migrations/20240426171026_test.ts

Reverts Infisical/infisical#1740

Revert "Revert "test migration rename""

---

backend/src/db/migrations/20240426171026_test.ts

Reverts Infisical/infisical#1742

Revert "Revert "Revert "Revert "test migration rename""""

---

backend/src/db/migrations/20240426171026_test.ts

Reverts Infisical/infisical#1744

Revert "Revert "Revert "Revert "Revert "Revert "test migration rename""""""

---

backend/src/db/migrations/20240426171026_test.ts

Reverts Infisical/infisical#1746

Revert "Revert "Revert "Revert "Revert "Revert "Revert "Revert "test migration rename""""""""

---

backend/src/db/migrations/20240426171026_test.ts

Reverts Infisical/infisical#1748

Revert "Revert "Revert "Revert "Revert "Revert "Revert "Revert "Revert "Revert "test migration rename""""""""""

---

backend/src/db/migrations/20240426171026_test.ts

Reverts Infisical/infisical#1750

Revert "Revert "Revert "Revert "Revert "Revert "Revert "Revert "Revert "Revert "Revert "Revert "test migration rename""""""""""""

---

backend/src/db/migrations/20240429154610_audit-log-index.ts

1. Added a compound index over [projectId, createdAt] and [orgId, createdAt] for audit log to resolve latency
```sh
```
---

fix(server): added index for audit log to resolve high latency or timeout

---

helm-charts/infisical-standalone-postgres/Chart.yaml
helm-charts/infisical-standalone-postgres/templates/infisical.yaml
helm-charts/infisical-standalone-postgres/templates/schema-migration-job.yaml
helm-charts/infisical-standalone-postgres/values.yaml

Added `imagePullSecrets` support to `infisical.yaml` and `schema-migration-job.yaml` templates in `infisical-standalone-postgres` chart. This change allows users to configure image pull secrets for pulling container images from private registries.
Verified the changes with the following tests:
* Test 1: Install the chart with default imagePullSecret values:
```yaml
imagePullSecrets: []
```
Check deployment imagePullSecrets value
```sh
$ cd helm-charts/infisical-standalone-postgres
$ helm install infisical-test .
$ kubectl get deployment infisical-test-infisical-standalone-infisical -o yaml | yq '.spec.template.spec.imagePullSecrets'
```
Output
```sh
null
```
Infisical deployment is running:
```sh
$ kubectl get deployment infisical-test-infisical-standalone-infisical
NAME …
```

added imagePullSecrets support to infisical-standalone-postgres chart

---

docs/documentation/platform/secret-versioning.mdx

Fix typo in docs

---

backend/src/services/integration-auth/integration-auth-service.ts
backend/src/services/integration-auth/integration-sync-secret.ts
docs/integrations/cloud/aws-secret-manager.mdx
frontend/src/hooks/api/integrationAuth/queries.tsx
frontend/src/pages/integrations/aws-parameter-store/create.tsx
frontend/src/pages/integrations/aws-secret-manager/create.tsx

This PR re-implements some aspects to do with KMS ID option for the AWS PS/SM integrations.
For context, the current KMS ID integration option implementation resulted in an `undefined` KMS ID for certain cases which led to secrets not being synced.
---

Update implementation for AWS SM/PS integration KMS ID option

---

frontend/src/components/v2/InfisicalSecretInput/InfisicalSecretInput.tsx

- Address multiline issues in secret input caused by auto-complete changes
```sh
```
---

fix: address infisical secret input ux issue with enter and arrow keys

---

frontend/src/components/v2/InfisicalSecretInput/InfisicalSecretInput.tsx

fix: address functional issues with secret input

---

docs/mint.json

1. Added missing bulk secret operations in documentation
```sh
```
---

doc: resolved missing bulk secret api operations

---

backend/src/server/routes/v2/organization-router.ts

Added slug to API response from workspace get all

---

frontend/src/pages/org/[id]/overview/index.tsx

There was a small bug with the or condition

Make migration notice visible 

---

backend/src/ee/routes/v1/identity-project-additional-privilege-router.ts
backend/src/ee/services/identity-project-additional-privilege/identity-project-additional-privilege-service.ts
backend/src/lib/api-docs/constants.ts
backend/src/server/routes/sanitizedSchemas.ts
frontend/package-lock.json
frontend/src/components/v2/SecretPathInput/SecretPathInput.tsx
frontend/src/hooks/api/identityProjectAdditionalPrivilege/queries.tsx
frontend/src/hooks/api/roles/types.ts
frontend/src/views/Project/MembersPage/components/IdentityTab/components/IdentityRoleForm/SpecificPrivilegeSection.tsx
frontend/src/views/Project/MembersPage/components/MemberListTab/MemberRoleForm/SpecificPrivilegeSection.tsx

1. Fixed secretPath input showing invalid `/` for a path applied
2. Improved specific identity privilege api to make it easier to understand. Removed unneccessary packed type and api always expects and handles unpacked permission.
```sh
```
---

Privilege identity api change

---

backend/src/lib/api-docs/constants.ts

doc: fixed typo in api privilege documentation

---

docs/integrations/platforms/kubernetes.mdx
helm-charts/secrets-operator/Chart.yaml
helm-charts/secrets-operator/templates/infisicalsecret-crd.yaml
helm-charts/secrets-operator/values.yaml
k8-operator/api/v1alpha1/infisicalsecret_types.go
k8-operator/config/crd/bases/secrets.infisical.com_infisicalsecrets.yaml
k8-operator/config/samples/sample.yaml
k8-operator/controllers/infisicalsecret_helper.go
k8-operator/packages/api/api.go
k8-operator/packages/api/models.go
k8-operator/packages/util/secrets.go

Added recursive support to the K8 operator. 
---

Feat: Recursive support for K8 operaetor

---

docs/documentation/platform/identities/universal-auth.mdx

This PR adds a mermaid diagram to the documentation for the Universal Auth method.
---

Add mermaid diagram for Universal Auth

---

backend/src/lib/api-docs/constants.ts
backend/src/server/routes/v3/secret-router.ts
backend/src/services/identity-ua/identity-ua-service.ts
backend/src/services/secret/secret-service.ts
backend/src/services/secret/secret-types.ts

1. Workspace slug support for secret v3 Get Key. Needed for external secret operator support
2. Improved error message for invalid UA auth
```sh
```
---

Workspace slug support in secret v3 Get Key

---

backend/src/services/org/org-service.ts

This PR updates the `isEmailVerified` field to `true` if users verify their email through the org invitation flow.
---

Update isEmailVerified field upon invite signups

---

docs/integrations/cicd/githubactions.mdx

- Added link to official Github Action
```sh
```
---

misc: updated documentation for github integration to include official action

---

backend/src/lib/api-docs/constants.ts
backend/src/server/routes/index.ts
backend/src/server/routes/v1/secret-folder-router.ts
backend/src/services/secret-folder/secret-folder-service.ts
backend/src/services/secret-folder/secret-folder-types.ts
frontend/src/hooks/api/secretFolders/queries.tsx
frontend/src/hooks/api/secretFolders/types.ts
frontend/src/views/SecretOverviewPage/SecretOverviewPage.tsx
frontend/src/views/SecretOverviewPage/components/SecretOverviewFolderRow/SecretOverviewFolderRow.tsx

- Added support for secret folder rename in the overview page
- Added validation to ensure that folder names remain unique
```sh
```
---

Feature: add support for secret folder rename in the overview page

---

backend/src/server/plugins/maintenanceMode.ts

feat: maintaince mode enable machine identity login and renew

---

frontend/src/pages/org/[id]/overview/index.tsx

fix: removed migration notice

---

backend/src/server/routes/v1/integration-router.ts
backend/src/services/integration-auth/integration-sync-secret.ts
backend/src/services/integration/integration-service.ts
backend/src/services/integration/integration-types.ts
docs/integrations/cloud/aws-secret-manager.mdx

Allow updating tags in AWS Secret Manager integration

---

backend/src/ee/services/secret-scanning/secret-scanning-service.ts
backend/src/lib/config/env.ts
backend/src/server/routes/v1/admin-router.ts
frontend/src/components/v2/NoticeBanner/NoticeBanner.tsx
frontend/src/components/v2/NoticeBanner/index.tsx
frontend/src/components/v2/index.tsx
frontend/src/hooks/api/admin/types.ts
frontend/src/pages/org/[id]/secret-scanning/index.tsx

feat: added secret-scanning disable option

---

docs/self-hosting/deployment-options/kubernetes-helm.mdx

Correct typo from 'Halm' to 'Helm'
Documentation change only.
---

Fix: Correct typo from 'Halm' to 'Helm'

---

backend/src/services/secret/secret-service.ts

Fixes secret expansion with multiple secrets with the same key.
---

Fix: Fix secret expansion II

---

backend/src/services/secret/secret-fns.ts
backend/src/services/secret/secret-service.ts

1. Added missing transaction for secret reference mapping
```sh
```
---

fix: resolved create secret failing for reference

---

backend/src/lib/api-docs/constants.ts
backend/src/server/routes/v1/identity-access-token-router.ts
backend/src/services/identity-access-token/identity-access-token-service.ts
docs/api-reference/endpoints/universal-auth/revoke-access-token.mdx
docs/mint.json

1. Endpoint for revocation of access token
2. Docs for it
```sh
```
---

Revoke access token endpoint

---

backend/src/ee/routes/v1/identity-project-additional-privilege-router.ts
backend/src/server/routes/sanitizedSchemas.ts

feat: added validation for project permission body in identity specific privilege

---

backend/src/lib/logger/logger.ts

- added logger redaction for specific keys/paths
```sh
```
---

misc: added logger redaction

---

backend/src/services/integration-auth/integration-sync-secret.ts

- modified digital ocean integration so that envs are encrypted by default
Before update:
After update 
```sh
```
---

misc: made digital ocean envs encrypted by default

---

backend/src/db/migrations/20240520064127_add-integration-sync-status.ts
backend/src/db/schemas/integrations.ts
backend/src/ee/services/audit-log/audit-log-types.ts
backend/src/lib/api-docs/constants.ts
backend/src/server/routes/v1/integration-router.ts
backend/src/services/integration/integration-service.ts
backend/src/services/integration/integration-types.ts
backend/src/services/secret/secret-queue.ts
frontend/src/hooks/api/integrations/queries.tsx
frontend/src/hooks/api/integrations/types.ts
frontend/src/hooks/api/workspace/queries.tsx
frontend/src/views/IntegrationsPage/components/IntegrationsSection/IntegrationsSection.tsx

- Add integration sync status
```sh
```
---

feat: added integration sync status

---

frontend/src/views/SecretMainPage/components/SecretDropzone/SecretDropzone.tsx

fix: address json drag behavior

---

frontend/src/helpers/secret.ts
frontend/src/hooks/api/secrets/queries.tsx
frontend/src/views/SecretMainPage/components/ActionBar/ActionBar.tsx

- personal overrides will now be included during env download
- secret references will now be expanded during env download
```sh
```
---

feat: added personal overrides and support for secret ref during download

---

docs/documentation/guides/node.mdx
docs/documentation/guides/python.mdx
docs/sdks/languages/csharp.mdx
docs/sdks/languages/java.mdx
docs/sdks/languages/node.mdx
docs/sdks/languages/python.mdx

As we are adding new authentication methods to the SDK's, we're also updating the docs to reflect the newly deprecated fields, new parameters, and of course the new authentication methods.
**Note ℹ️: Do not merge this until we've released the new SDK update.**
---

Docs: Updated docs to reflect new SDK structure

---

docs/documentation/guides/node.mdx
docs/sdks/languages/csharp.mdx
docs/sdks/languages/java.mdx
docs/sdks/languages/node.mdx
docs/sdks/languages/python.mdx

Documentation for native Azure & Kubernetes auth for SDK's.
---

Docs: Azure & Kubernetes auth SDK documentation

---

backend/src/server/routes/v1/integration-auth-router.ts
backend/src/services/integration-auth/integration-team.ts
frontend/src/hooks/api/integrationAuth/types.ts
frontend/src/pages/integrations/gitlab/create.tsx

Before this, gitlab integration creation flow would result to an error when the groups option is selected. This PR addresses that concern
Before PR
After PR
```sh
```
---

fix: resolved gitlab integration creation issue with groups selection

---

backend/src/services/auth/auth-fns.ts
backend/src/services/smtp/templates/unlockAccount.handlebars
frontend/src/views/Login/components/MFAStep/MFAStep.tsx

misc: minor ui adjustments

---

cli/packages/cmd/secrets.go
docs/cli/commands/secrets.mdx

- With this PR, devs can now create personal secrets using the CLI 
```sh
```
---

feat: added support for personal secrets creation via CLI

---

backend/src/lib/api-docs/constants.ts

1. Description update over isTemporary to address 2 options
```sh
```
---

docs: updated the cause of option1 and option2 in role update commit

---

helm-charts/secrets-operator/values.yaml
k8-operator/packages/api/api.go
k8-operator/packages/api/models.go
k8-operator/packages/util/secrets.go

Support for imports when using Machine Identity based auth.
---

Feat: Include Imports for Machine Identity auth

---

docs/self-hosting/deployment-options/kubernetes-helm.mdx

docs: fix typo

---

frontend/src/components/v2/Select/Select.tsx

resolved select in popper mode list overflow
```sh
```
---

fix: ui issue resolved for list overflow

---

frontend/src/views/SecretOverviewPage/SecretOverviewPage.tsx

added sorting for folders in overview

---

backend/src/lib/api-docs/constants.ts
backend/src/server/routes/v1/integration-router.ts
backend/src/services/integration-auth/integration-sync-secret.ts
backend/src/services/integration/integration-schema.ts
backend/src/services/integration/integration-types.ts
frontend/src/hooks/api/integrations/queries.tsx
frontend/src/pages/integrations/github/create.tsx

- This PR will allow users to configure integration with Github in such a way that it does not delete existing records that do not exist on Infisical. 
```sh
```
---

feat: added option for disabling github secret deletion

---

docs/mint.json
docs/sdks/languages/go.mdx

Docs: Go SDK

---

frontend/src/views/SecretMainPage/components/SecretImportListView/SecretImportListView.tsx

- This PR ensures that we're displaying unique secret entries in the import list view, prioritizing the entry defined in the direct import over indirect ones in case of duplicates 
Before changes:
After changes:
Note: CLI is already doing the same type of filtering here
```sh
```
---

fix: resolved import override behavior

---

backend/src/services/secret/secret-fns.ts
backend/src/services/secret/secret-service.ts

- This PR ensures that we're returning unique secret import entries prioritizing those defined in the direct import over indirect ones in case of duplicates 
- This is an API-layer counterpart for the following
https://github.com/Infisical/infisical/pull/1948
```sh
```
---

feat: handled import override in the API layer

---

frontend/src/helpers/project.ts

1. This is will resolve clients stuck on backup password state
```sh
```
---

fix: stuck on password step resolved

---

backend/src/services/org/org-service.ts

1. This fixes cloud sign up failing in stage.
```sh
```
---

fix: resolved signup failing in cloud

---

backend/src/ee/routes/v1/secret-approval-policy-router.ts
backend/src/ee/services/secret-approval-policy/secret-approval-policy-service.ts
frontend/src/components/v2/SecretPathInput/SecretPathInput.tsx
frontend/src/hooks/api/secretImports/queries.tsx
frontend/src/views/SecretOverviewPage/components/SecretOverviewTableRow/SecretOverviewTableRow.tsx

This PR resolves mainly two issues that has been reported
1. Failing to generate secret approval requests for policies with trailing slash
2. Secret overview missing nested imported secrets
```sh
```
---

Trailing slash in secret approval policy and overview bug

---

.github/workflows/release_build_infisical_cli.yml

misc: resolved goreleaser hardcoded version

---

docs/sdks/languages/go.mdx

Fixed smaller Go SDK typos. 
---

Fix: Go SDK Docs typos

---

frontend/src/hooks/api/workspace/types.ts
frontend/src/lib/fn/date.ts
frontend/src/pages/org/[id]/overview/index.tsx

- With this PR, users can now toggle between two projects view mode (either list view or grid view)
Grid:
List:
```sh
```
---

feat: added projects list view

---

helm-charts/secrets-operator/templates/manager-rbac.yaml
k8-operator/config/rbac/role.yaml
k8-operator/config/samples/k8s-auth/sample.yaml
k8-operator/controllers/infisicalsecret_controller.go

Missing RBAC for service accounts

Add missing RBAC to k8s 

---

docs/integrations/platforms/ansible.mdx

* Added on-site Ansible documentation. 
---

Docs: Ansible documentation

---

docs/sdks/languages/go.mdx

Updated SDK docs to reflect the latest changes. 
---

docs(sdks): Updated Go SDK docs

---

frontend/src/pages/signupinvite.tsx

Fix for `null` name fields allowed on signup.
---

Fix: `null` name fields on signup

---

backend/package-lock.json
backend/src/lib/api-docs/constants.ts
backend/src/lib/errors/index.ts
backend/src/server/plugins/error-handler.ts
backend/src/server/routes/v1/secret-tag-router.ts
backend/src/services/secret-tag/secret-tag-service.ts
backend/src/services/secret-tag/secret-tag-types.ts
docs/api-reference/endpoints/secret-tags/get-by-id.mdx
docs/api-reference/endpoints/secret-tags/get-by-slug.mdx
docs/api-reference/endpoints/secret-tags/update.mdx
docs/mint.json

This PR introduces missing API endpoints for secret tag
1. Update
2. Get By ID
3. Get By Slug
These are at the moment used by terraform `infisical_secret_tag` resource and datasource
```sh
```
---

New API endpoints for Tag update, get by id and get by slug

---

backend/src/server/routes/v3/secret-router.ts

remove k8s events from posthog

---

backend/src/services/integration-auth/integration-sync-secret.ts
backend/src/services/secret/secret-queue.ts

1. Fixed silent integration errors. This made it hard to figure out if your secrets were actually syncing or not, because it wouldn't be visible in the Integrations UI on the dashboard if it failed.
2. Smaller redundancies in the integration flows.
---

Fix: Silent integration errors

---

backend/src/ee/services/secret-snapshot/snapshot-dal.ts

- Some snapshots are not being pruned correctly because they belong to a non-root folder that for some reason do not have a corresponding secret folder version
```sh
```
---

misc: added special pruning of non-root folders

---

cli/packages/cmd/agent.go
cli/packages/cmd/login.go
cli/packages/util/auth.go
cli/packages/util/constants.go
cli/packages/util/helper.go
docs/cli/commands/login.mdx

Note: This PR is brached from #1978, and should only be reviewed/merged _after_ #1978.
This PR introduces support for all authentication methods in the `infisical login` command. 
---

feat(cli): Support for all authentication methods in `infisical login` command

---

backend/src/lib/crypto/srp.ts
backend/src/services/auth/auth-login-service.ts
backend/src/services/auth/auth-signup-service.ts
backend/src/services/super-admin/super-admin-service.ts

We recently introduced master key removal and it caused users in enc v1 to fail on generateSrpKey. This will resolve that problem.
```sh
```
---

feat: resolved generate srp failing for user enc v1 users

---

frontend/src/components/notifications/Notifications.tsx
frontend/src/views/ShareSecretPage/components/AddShareSecretForm.tsx
frontend/src/views/ShareSecretPage/components/ViewAndCopySharedSecret.tsx
frontend/src/views/ShareSecretPublicPage/ShareSecretPublicPage.tsx
frontend/src/views/ShareSecretPublicPage/components/SecretTable.tsx

updated secret sharing design

---

docs/sdks/overview.mdx

Removed incorrect duplicate FAQ section
---

fix(docs): duplicate faq item

---

docs/style.css

Add CSS to support updated HTML structure
Check that the code looks good

Update style.css in docs

---

backend/src/services/secret-blind-index/secret-blind-index-dal.ts
frontend/src/views/Settings/ProjectSettingsPage/components/ProjectGeneralTab/ProjectGeneralTab.tsx
frontend/src/views/Settings/ProjectSettingsPage/components/RebuildSecretIndicesSection/RebuildSecretIndicesSection.tsx

- This will enable users to manually resolve secret indexing issues that they encounter upon secret modifications
Project page:
Note: the ideal scenario here is where blind indexing issues never occur in the first place. While these cases are under investigation, it would be great to have a way of letting users unblock themselves when necessary
```sh
```
---

feat: added project setting for rebuilding secret indices

---

frontend/src/views/SecretMainPage/components/SecretListView/SecretDetaiSidebar.tsx
frontend/src/views/SecretMainPage/components/SecretListView/SecretItem.tsx
frontend/src/views/SecretMainPage/components/SecretListView/SecretListView.tsx
frontend/src/views/SecretMainPage/components/SecretListView/SecretListView.utils.ts
frontend/src/views/ShareSecretPage/components/AddShareSecretForm.tsx
frontend/src/views/ShareSecretPage/components/AddShareSecretModal.tsx

- This will enable users to create "shared secrets" from the secrets main page of a project
https://github.com/Infisical/infisical/assets/65645666/8f3d2b1e-40d8-4797-8f19-8adae1ecbcba
```sh
```
---

feat: added option to share secret directly from main page

---

.infisicalignore
backend/src/ee/services/ldap-config/ldap-config-service.ts
backend/src/ee/services/license/__mocks__/licence-fns.ts
backend/src/ee/services/license/licence-fns.ts
backend/src/ee/services/license/license-dal.ts
backend/src/ee/services/license/license-service.ts
backend/src/ee/services/license/license-types.ts
backend/src/ee/services/saml-config/saml-config-service.ts
backend/src/server/routes/index.ts
backend/src/services/identity/identity-service.ts
backend/src/services/org/org-service.ts
frontend/src/hooks/api/subscriptions/types.ts
frontend/src/views/Org/MembersPage/components/OrgIdentityTab/components/IdentitySection/IdentitySection.tsx
frontend/src/views/Org/MembersPage/components/OrgMembersTab/components/OrgMembersSection/OrgMembersSection.tsx

Reverts Infisical/infisical#1995

Revert "Add support for Identity-Based Pricing"

---

backend/src/services/integration-auth/integration-sync-secret.ts
frontend/src/pages/integrations/azure-key-vault/create.tsx

- This PR adds the option to set initial sync behavior for Azure Key Vault integrations
```sh
```
---

feat: added initial sync behavior for azure key integration

---

docs/integrations/cicd/gitlab.mdx
docs/mint.json
docs/self-hosting/guides/custom-certificates.mdx

- Adds documentation for configuring Infisical trust with self-signed certs
```sh
```
---

doc: added guide for configuring certs

---

backend/src/db/migrations/20240627115024_add-oidc-updated-at-trigger.ts

- This PR adds an onUpdateTrigger to oidcConfig table
```sh
```
---

misc: add onUpdate trigger to oidc config

---

.infisicalignore
backend/src/ee/services/ldap-config/ldap-config-service.ts
backend/src/ee/services/license/__mocks__/licence-fns.ts
backend/src/ee/services/license/licence-fns.ts
backend/src/ee/services/license/license-dal.ts
backend/src/ee/services/license/license-service.ts
backend/src/ee/services/license/license-types.ts
backend/src/ee/services/saml-config/saml-config-service.ts
backend/src/server/routes/index.ts
backend/src/services/identity/identity-service.ts
backend/src/services/org/org-service.ts
frontend/src/hooks/api/subscriptions/types.ts
frontend/src/views/Org/MembersPage/components/OrgIdentityTab/components/IdentitySection/IdentitySection.tsx
frontend/src/views/Org/MembersPage/components/OrgMembersTab/components/OrgMembersSection/OrgMembersSection.tsx

Reverts Infisical/infisical#2023

Add support for Identity-Based Pricing"

---

cli/packages/util/secrets.go
frontend/src/views/SecretMainPage/components/CreateSecretForm/CreateSecretForm.tsx
frontend/src/views/SecretOverviewPage/components/CreateSecretForm/CreateSecretForm.tsx

- This PR ensures that leading and trailing spaces are trimmed before being saved
```sh
```
---

misc: added secret name trimming

---

.github/workflows/check-migration-file-edited.yml
.github/workflows/update-be-new-migration-latest-timestamp.yml
backend/scripts/create-migration.ts

1. PR add a new check via Github Action to ensure in PRs migration files are not edited. 
2. Additionally added slugifying the input of migration file creator name so that it standardized
```sh
```
---

feat: added slugify migration file creater name and additional check to ensure migration files are not editied in PR

---

backend/src/ee/services/ldap-config/ldap-config-service.ts
frontend/src/views/Settings/OrgSettingsPage/components/OrgAuthTab/LDAPGroupMapModal.tsx

- This PR ensures that the ldap group being referred to in the LDAP group mapping can be found in the LDAP directory and is valid.
- Added the following display view when organization does not have any groups
```sh
```
---

misc: added backend check for ldap group config

---

backend/src/lib/logger/logger.ts

- ensures that sensitive request information is not logged on error
```sh
```
---

misc: add config to redacted keys

---

frontend/src/views/SecretMainPage/SecretMainPage.tsx
frontend/src/views/SecretMainPage/components/ActionBar/ActionBar.tsx
frontend/src/views/SecretMainPage/components/SecretListView/SecretItem.tsx
frontend/src/views/SecretOverviewPage/SecretOverviewPage.tsx

- Rename "Commits" to something more intuitive
- If searching for a secret in overview page, if you click explore then the search term should persist upon navigating to the secret main page
- fix grid alignment issue in main page
- resolve safari secret settings concern in secret main page
Fix alignment issue
```sh
```
---

fix: addressed main page ui/ux concerns

---

backend/src/ee/services/audit-log/audit-log-types.ts
backend/src/server/routes/v1/webhook-router.ts
frontend/src/hooks/api/auditLogs/types.tsx
frontend/src/views/Project/AuditLogsPage/components/LogsTableRow.tsx

- This PR addresses undefined or blank values showing up on webhook URL metadata
```sh
```
---

misc: removed webhook url from audit logs table

---

frontend/src/views/ShareSecretPage/components/AddShareSecretForm.tsx
frontend/src/views/ShareSecretPublicPage/components/SecretTable.tsx

fix ui secret sharing

---

frontend/src/views/ShareSecretPage/components/AddShareSecretForm.tsx
frontend/src/views/ShareSecretPublicPage/ShareSecretPublicPage.tsx
frontend/src/views/ShareSecretPublicPage/components/SecretTable.tsx

Secret sharing UI update

---

frontend/src/hooks/api/ldapConfig/queries.tsx
frontend/src/hooks/api/oidcConfig/queries.tsx
frontend/src/hooks/api/ssoConfig/queries.tsx
frontend/src/views/Settings/OrgSettingsPage/components/OrgAuthTab/LDAPModal.tsx
frontend/src/views/Settings/OrgSettingsPage/components/OrgAuthTab/OIDCModal.tsx
frontend/src/views/Settings/OrgSettingsPage/components/OrgAuthTab/OrgAuthTab.tsx
frontend/src/views/Settings/OrgSettingsPage/components/OrgAuthTab/OrgGeneralAuthSection.tsx
frontend/src/views/Settings/OrgSettingsPage/components/OrgAuthTab/OrgLDAPSection.tsx
frontend/src/views/Settings/OrgSettingsPage/components/OrgAuthTab/OrgOIDCSection.tsx
frontend/src/views/Settings/OrgSettingsPage/components/OrgAuthTab/OrgSCIMSection.tsx
frontend/src/views/Settings/OrgSettingsPage/components/OrgAuthTab/OrgSSOSection.tsx
frontend/src/views/Settings/OrgSettingsPage/components/OrgAuthTab/SSOModal.tsx

- This PR redesigns the org security settings page (Identity provider)
Before:
After:
```sh
```
---

misc: redesigned org security settings page

---

backend/src/ee/services/audit-log/audit-log-types.ts
backend/src/server/routes/index.ts
backend/src/server/routes/v3/secret-router.ts
backend/src/services/secret/secret-service.ts
backend/src/services/secret/secret-types.ts
frontend/src/hooks/api/secrets/index.ts
frontend/src/hooks/api/secrets/mutations.tsx
frontend/src/hooks/api/secrets/types.ts
frontend/src/views/SecretMainPage/components/ActionBar/ActionBar.tsx
frontend/src/views/SecretMainPage/components/ActionBar/MoveSecretsModal.tsx

- This PR will allow users to move secrets from one folder to another directly via web UI
```sh
```
---

feat: move secrets

---

frontend/src/views/Org/IdentityPage/components/IdentityProjectsSection/IdentityAddToProjectModal.tsx
frontend/src/views/Org/IdentityPage/components/IdentityProjectsSection/IdentityProjectRow.tsx
frontend/src/views/Org/MembersPage/components/OrgIdentityTab/components/IdentitySection/IdentitySection.tsx
frontend/src/views/Org/MembersPage/components/OrgIdentityTab/components/IdentitySection/IdentityTable.tsx

This PR includes a few improvements to the latest identity UX:
- Added menu options for the Identity Table (Edit identity, Delete Identity).
- Updated Identity Projects Table to not redirect user to projects that they don't have access to.
---

Identity Workflow Improvements (Table Menu Opts, Error Handling)

---

backend/src/services/identity-access-token/identity-access-token-dal.ts

This PR fixes a Token Auth reference in `identityAccessTokenDALFactory`.
---

Fix Token Auth Ref in Access Token DAL

---

backend/src/server/routes/v1/identity-aws-iam-auth-router.ts
backend/src/server/routes/v1/identity-azure-auth-router.ts
backend/src/server/routes/v1/identity-gcp-auth-router.ts
backend/src/server/routes/v1/identity-kubernetes-auth-router.ts
backend/src/server/routes/v1/identity-oidc-auth-router.ts
backend/src/server/routes/v1/identity-token-auth-router.ts
backend/src/server/routes/v1/identity-universal-auth-router.ts
frontend/src/views/Org/IdentityPage/components/IdentityClientSecretModal.tsx
frontend/src/views/Org/MembersPage/components/OrgIdentityTab/components/IdentitySection/IdentityAwsAuthForm.tsx
frontend/src/views/Org/MembersPage/components/OrgIdentityTab/components/IdentitySection/IdentityAzureAuthForm.tsx
frontend/src/views/Org/MembersPage/components/OrgIdentityTab/components/IdentitySection/IdentityGcpAuthForm.tsx
frontend/src/views/Org/MembersPage/components/OrgIdentityTab/components/IdentitySection/IdentityKubernetesAuthForm.tsx
frontend/src/views/Org/MembersPage/components/OrgIdentityTab/components/IdentitySection/IdentityOidcAuthForm.tsx
frontend/src/views/Org/MembersPage/components/OrgIdentityTab/components/IdentitySection/IdentityTokenAuthForm.tsx
frontend/src/views/Org/MembersPage/components/OrgIdentityTab/components/IdentitySection/IdentityUniversalAuthClientSecretModal.tsx
frontend/src/views/Org/MembersPage/components/OrgIdentityTab/components/IdentitySection/IdentityUniversalAuthForm.tsx

- This PR adds validation for TTL values so that int overflow won't occur like in the issue reported here https://github.com/Infisical/infisical/issues/2098
```sh
```
---

misc: add max checks for TTL values of identities

---

backend/src/ee/services/license/licence-fns.ts
backend/src/ee/services/license/license-types.ts
backend/src/server/routes/index.ts
backend/src/services/super-admin/super-admin-service.ts
frontend/src/hooks/api/subscriptions/types.ts
frontend/src/views/admin/DashboardPage/UserPanel.tsx

- This PR will make admin user deletion a part of the pro/enterprise plan
Dependent on the following PR:
https://github.com/Infisical/license-server/pull/15
```sh
```
---

misc: moved admin user deletion to pro plan

---

docs/documentation/platform/identities/oidc-auth/general.mdx
docs/documentation/platform/identities/oidc-auth/github.mdx
docs/mint.json

- This PR adds documentation for connecting Github workflows to Infisical via OIDC Auth
```sh
```
---

doc: added docs for connecting github to infisical via oidc auth

---

frontend/src/views/ShareSecretPublicPage/components/SecretTable.tsx

- This PR will enable users to hide and unhide secret values upon viewing a shared secret
Before 
After
```sh
```
---

feat: add share-secret hide and unhide

---

frontend/package-lock.json
frontend/package.json

- This PR updates the storybook package in the frontend application in order to resolve dependabot security report
**Snippets of resolution**:
**Additional notes**:
At some point, we will have to upgrade our next version because some of the latest versions of packages like storybook no longer support next 12. We might miss out on patches.
```sh
```
---

misc: addressed ws vulnerability via package update

---

frontend/src/pages/org/[id]/overview/index.tsx

There is a bug on the feature cards on the overview page, that overflowed on smaller screen sizes.
Before:
After:
---

Fix: Features card overflow

---

backend/src/ee/routes/v1/scim-router.ts
backend/src/ee/services/scim/scim-service.ts
backend/src/ee/services/scim/scim-types.ts

This PR fixes part of the `PATCH /Groups` endpoint part of SCIM. It fixes the type on a field and implements the `add` operation as part of this endpoint.
---

Fix SCIM PATCH /Groups Fn

---

backend/src/server/routes/index.ts
backend/src/services/secret/secret-queue.ts
backend/src/services/webhook/webhook-fns.ts
backend/src/services/webhook/webhook-service.ts

- This PR will modify slack webhook to display project name instead of workspace ID
Before:
After:
```sh
```
---

misc: displayed project name in slack webhook

---

backend/src/services/integration-auth/integration-auth-service.ts

- This PR ensures that instance AWS credential is not globally updated/set
```sh
```
---

misc: moved aws creds to constructor

---

company/handbook/hiring.mdx
company/mint.json

updated hiring handbook

---

backend/src/lib/api-docs/constants.ts
backend/src/server/routes/v1/secret-folder-router.ts
backend/src/services/secret-folder/secret-folder-dal.ts
backend/src/services/secret-folder/secret-folder-service.ts
backend/src/services/secret-folder/secret-folder-types.ts
docs/api-reference/endpoints/folders/get-by-id.mdx
docs/mint.json

This PR adds endpoint for folder to get one folder by id. This is used in terraform secret_folder
```sh
```
---

New folder endpoints for terraform

---

backend/src/services/identity-azure-auth/identity-azure-auth-fns.ts

After a lot of debugging, I figured out the "issue" with Azure. The Azure JWT may sometimes contain a "/" at the end, and sometimes not. It depends on the user, and the user really shouldn't have to think about this. I myself was having a lot of issues due to exactly this.
This PR addresses the formatting issue by doing an arbitrary check on the audience and removing the trailing slash if necessary. 
```sh
```
---

fix(auth): Azure audience formatting bug

---

backend/src/ee/routes/v1/external-kms-router.ts
backend/src/ee/services/external-kms/external-kms-service.ts
backend/src/services/kms/kms-service.ts

This PR fixes a bug in cert manager that got into due to kms re-architecture. 
```sh
```
---

fix: slug too big for project fixed

---

backend/src/db/migrations/20240717114407_add-project-data-key.ts
backend/src/db/schemas/projects.ts
backend/src/keystore/keystore.ts
backend/src/services/kms/kms-service.ts

- This PR adds the generation of project data key for secret encryption/decryption
```sh
```
---

feat: added project data key

---

docs/self-hosting/ee.mdx

This will allow people to white list out going connections from Infisical only to Infisical servers (license servers, etc)

add ips for whitelisting

---

docs/self-hosting/configuration/envars.mdx

Followed the documentation on SMTP2GO , Here's a screenshot showing the exact credentials :

Add SMTP2GO credentials for email configuration

---

frontend/src/views/SecretApprovalPage/components/AccessApprovalRequest/components/ReviewAccessModal.tsx
frontend/src/views/SecretApprovalPage/components/SecretApprovalRequest/components/SecretApprovalRequestAction.tsx

Typo recovery: `by pass` must be `bypass`
N/A
---

style(frontend): typo bypass

---

frontend/src/pages/integrations/aws-parameter-store/create.tsx
frontend/src/pages/integrations/aws-secret-manager/create.tsx
frontend/src/pages/integrations/circleci/create.tsx
frontend/src/pages/integrations/flyio/create.tsx
frontend/src/pages/integrations/github/create.tsx
frontend/src/pages/integrations/gitlab/create.tsx
frontend/src/pages/integrations/hashicorp-vault/create.tsx
frontend/src/pages/integrations/heroku/create.tsx
frontend/src/pages/integrations/qovery/create.tsx
frontend/src/pages/integrations/render/create.tsx
frontend/src/pages/integrations/vercel/create.tsx

chore(ui): Grammar fix

---

backend/src/ee/services/audit-log/audit-log-types.ts
backend/src/lib/api-docs/constants.ts
backend/src/server/routes/v1/project-env-router.ts
backend/src/services/project-env/project-env-dal.ts
backend/src/services/project-env/project-env-service.ts
backend/src/services/project-env/project-env-types.ts

- This PR adds the missing GetByID endpoint for project environments as a prerequisite for the "environment" terraform resource
Required by the following PR:
https://github.com/Infisical/terraform-provider-infisical/pull/47
```sh
```
---

misc: add endpoint for environment terraform resource

---

docs/self-hosting/deployment-options/native/standalone-binary.mdx

Removed leftover code from when I was initially writing the docs. 
---

chore(docs): remove redundant doc

---

docs/self-hosting/deployment-options/native/standalone-binary.mdx

chore(docs): typo in url

---

docs/mint.json
docs/sdks/languages/ruby.mdx
docs/sdks/overview.mdx
docs/self-hosting/deployment-options/native/standalone-binary.mdx

This PR introduces a comprehensive documentation page on the Ruby SDK and how to use it, with full examples included, which is inline with the rest of our SDK docs.
---

feat(docs): Ruby sdk

---

cli/packages/cmd/login.go
frontend/src/views/Login/components/MFAStep/MFAStep.tsx
frontend/src/views/Login/components/PasswordStep/PasswordStep.tsx

PR addresses missing CLI login fallback strategy in some steps like Password flow for which org id already present in the token. 
This PR also fixes the CLI not showing the URL when override is enabled on domain.
```sh
```
---

Missing paste token option in CLI brower login flow

---

backend/src/server/routes/v2/project-router.ts
backend/src/services/certificate/certificate-dal.ts
backend/src/services/project/project-service.ts
backend/src/services/project/project-types.ts
docs/api-reference/endpoints/certificate-authorities/list.mdx
docs/api-reference/endpoints/certificates/list.mdx
docs/mint.json

This PR adds:
- List CA and certificates endpoints to the documentation.
- Filter options so you can filter CAs/certificates by `commonName` and `friendlyName`.
---

Add List CAs / Certificates to Documentation + Filter Options

---

backend/src/lib/api-docs/constants.ts
backend/src/server/routes/v2/project-router.ts

This PR improves the documentation for the LIST (GET) CAs / certificates endpoint parameters by adding descriptions to them.
---

Add descriptions for parameters for LIST (GET) CAs / certificates endpoints

---

backend/src/server/routes/v1/secret-sharing-router.ts
backend/src/services/secret-sharing/secret-sharing-service.ts
backend/src/services/secret-sharing/secret-sharing-types.ts
frontend/src/hooks/api/secretSharing/types.ts
frontend/src/views/ShareSecretPage/components/AddShareSecretForm.tsx
frontend/src/views/ShareSecretPage/components/AddShareSecretModal.tsx
frontend/src/views/ShareSecretPage/components/ShareSecretSection.tsx
frontend/src/views/ShareSecretPage/components/ShareSecretsRow.tsx
frontend/src/views/ShareSecretPage/components/ShareSecretsTable.tsx
frontend/src/views/ShareSecretPublicPage/ShareSecretPublicPage.tsx

This PR contains minor UI adjustments to the secret sharing functionality.
More specifically:
- Turned strange AND/OR conditional on expiration time / max views fields into dropdowns.
- Adjusted styling of secret sharing table.
There is likely a lot more optimization that can be done in general but this is a start.
---

Secret Sharing UI/UX Adjustment

---

backend/src/ee/services/group/group-fns.ts

This pull request optimizes the `removeUsersFromGroupByUserIds` function to improve performance when handling multiple users. The main change involves replacing a sequential for await loop with concurrent Promise-based operations using `Promise.all()`. This optimization allows for parallel processing of user removals, potentially reducing execution time for bulk operations. Additionally, the unnecessary for await syntax was removed as it was incorrectly used with a regular array.
---

perf(group-fns): optimize sequential delete to be concurrent

---

docs/documentation/guides/migrating-from-envkey.mdx

add envkey migration page

---

frontend/src/views/Org/MembersPage/MembersPage.tsx
frontend/src/views/Org/UserPage/components/UserProjectsSection/UserProjectRow.tsx
frontend/src/views/Project/MembersPage/MembersPage.tsx
frontend/src/views/Project/RolePage/RolePage.tsx
frontend/src/views/SecretOverviewPage/components/SelectionPanel/SelectionPanel.tsx

Lint fixes to unblock prod pipeline

Lint fixes to unblock prod pipeline 

---

frontend/src/views/ShareSecretPublicPage/ShareSecretPublicPage.tsx
frontend/src/views/ViewSecretPublicPage/ViewSecretPublicPage.tsx

This PR adds slightly more x-padding to the secret sharing page promo banner.
As requested by @vmatsiiako.
---

Add More Padding to Secret Sharing Banner

---

cli/packages/api/api.go
cli/packages/api/model.go
cli/packages/cmd/agent.go
cli/packages/models/cli.go
cli/packages/util/agent.go
cli/packages/util/secrets.go
docs/integrations/platforms/infisical-agent.mdx

Adds support for fetching secret by name. Before you could only list secrets in a env and path.

add single secret fetch for agent

---

docs/sdks/languages/csharp.mdx
docs/sdks/languages/java.mdx
docs/sdks/languages/node.mdx
docs/sdks/languages/python.mdx

Documented the use of custom TLS certificates.
---

docs(sdks): Custom TLS certificate support

---

frontend/src/components/v2/Input/Input.tsx
frontend/src/helpers/string.ts
frontend/src/pages/integrations/hashicorp-vault/authorize.tsx
frontend/src/pages/integrations/hashicorp-vault/create.tsx
frontend/src/views/IntegrationsPage/components/IntegrationsSection/IntegrationsSection.tsx

This pull request refactors the Hashicorp Vault integration UI to improve the user experience during the integration process. The changes make the setup smoother and more intuitive on the frontend side.
- Fixes the issue where Vault Namespace was incorrectly marked as a required field during setup.(#767)
- Addresses the incompatibility with OSS version of Vault that doesn't support namespaces.(#767)
The existing integration process for Hashicorp Vault had some usability issues and didn't properly account for differences between Vault versions. These changes aim to:
1. Streamline the integration process for users.
2. Improve clarity around required fields.
3. Ensure compatibility with both Enterprise and OSS versions of Vault.
- Refactored the UI components for a more intuitive flow.
- …

refactor(hashicorp-integration): make hashicorp vault integration easier to use

---

backend/src/ee/services/permission/project-permission.ts
backend/src/services/secret-folder/secret-folder-fns.ts
backend/src/services/secret-folder/secret-folder-service.ts
frontend/src/context/ProjectPermissionContext/types.ts
frontend/src/views/Project/RolePage/components/RolePermissionsSection/ProjectRoleModifySection.utils.ts
frontend/src/views/Project/RolePage/components/RolePermissionsSection/RolePermissionSecretFoldersRow.tsx
frontend/src/views/Project/RolePage/components/RolePermissionsSection/RolePermissionsSection.tsx
frontend/src/views/SecretMainPage/components/ActionBar/ActionBar.tsx
frontend/src/views/SecretMainPage/components/FolderListView/FolderListView.tsx

- This PR will enable custom roles to have different RBAC for secret folder resources. This is useful if you want to give users full access to secrets but read-only access to folders
```sh
```
---

feat: added secret folder permissions

---

.github/workflows/check-api-for-breaking-changes.yml
.github/workflows/run-backend-tests.yml

Github has changed their image so it no longer supports `docker-compose` command. I have updated to the new command.

Update docker-compose to docker compose in GHA

---

frontend/src/components/v2/DeleteActionModal/DeleteActionModal.tsx

- [✅] Bug fix
---
Closes #2214
- [✅] I have read the [contributing guide](https://infisical.com/docs/contributing/getting-started/overview), agreed and acknowledged the [code of conduct](https://infisical.com/docs/contributing/getting-started/code-of-conduct). 📝

Placeholder value is same as it's label

---

frontend/src/views/SecretMainPage/components/CreateSecretForm/CreateSecretForm.tsx
frontend/src/views/SecretOverviewPage/components/CreateSecretForm/CreateSecretForm.tsx

Fixes linting to unblock deployment pipeline. 
---

Fix: Linting

---

docs/documentation/platform/kms/aws-kms.mdx
docs/mint.json

update broken image in ksm docs

---

backend/src/services/project-bot/project-bot-fns.ts

fix: resolved auto bot create failing on update

---

company/handbook/meetings.mdx
company/mint.json

add meetings article to handbook
